### ISSUE TITLE
Missing transaction record fields for `AccountAllowanceAdjustmentTransaction`

### ISSUE THREAD

**Issue by SimiHunjan** [hashgraph/hedera-sdk-js#1003]
### Description

The transaction record for an AccountAllowanceAdjustmentTransaction() should return the corresponding adjustment that was made:
```
    /**
     * The current balances of any adjusted crypto allowances as a result of this
     * transaction. This field will only be populated for CryptoAdjustAllowanceTransaction.
     */

    repeated CryptoAllowance crypto_adjustments = 17;

    /**
     * The current balances of any adjusted non-fungible token allowances as a result of this
     * transaction. This field will only be populated for CryptoAdjustAllowanceTransaction.
     */
    repeated NftAllowance nft_adjustments = 18;

    /**
     * The current balances of any adjusted fungible token allowances as a result of this
     * transaction. This field will only be populated for CryptoAdjustAllowanceTransaction.
     */
    repeated TokenAllowance token_adjustments = 19;
```

This was included in the protobuf changes PR for this feature: 

https://github.com/hashgraph/hedera-protobufs/pull/152/files#diff-282b092daf92d72c0573a1e75fb80df9c68ce358c2fab955956a5f744878fd5aR130

### Steps to reproduce

Get the transaction record for an AccountAllowanceAdjustTransaction() and try to get the adjustment

### Hedera network

previewnet

### Version

v2.11.0-beta.1

**Comment by danielakhterov** [comment]
Implemented here: https://github.com/hashgraph/hedera-sdk-js/commit/64c26c80d81e0ae5344b540ffc23be5ed5d0b408
