### ISSUE TITLE
NFT allowance in Account Info is missing isApproveForAll flag

### ISSUE THREAD

**Issue by SimiHunjan** [hashgraph/hedera-sdk-js#1004]
### Description

GetAccountInfo is missing the isApproveForAll flag for the NFT allowances.

NFT Allowances : 
[TokenNftAllowance{tokenId=0.0.2165, ownerAccountId=null, spenderAccountId=0.0.2158, serials=null}]
here the spender 0.0.2158 has allowance for all serials on the owner for NFT 0.0.2165

But this information is missing the info.

### Steps to reproduce

Create a owner account, spender account and an NFT token.
grant allowance on NFT token of the owner to the spender with approveForAll set true.

get Account info on owner doest not show this flag.

### Hedera network

previewnet

### Version

v2.11.0-beta.1

**Comment by danielakhterov** [comment]
Just want to clarify that the original intention was to remove the use of `approvedForAll` and instead have a nullable `serials` field. When `serials` is `null` that implies **all** serials are approved, if `serials` is a list then this implies **only** these serials are approved. However, this `TokenNftAllowance` is being changed to have an `allSerials` field which would be equivalent to `approvedForAll`.
