### ISSUE TITLE
Populate the `ownerAccountID` in the allowances fields for owner account infos

### ISSUE THREAD

**Issue by SimiHunjan** [hashgraph/hedera-sdk-js#1006]
### Problem

`ownerAccountID` is left null for all allowance token types listed in the account info for an owner.
`hbarAllowances=[HbarAllowance{ownerAccountId=null, spenderAccountId=0.0.1948, amount=10 ℏ}], tokenAllowances=[], tokenNftAllowances=[]}`

### Solution

Populate this field with the owner account ID

**Comment by danielakhterov** [comment]
Implemented here: 5092b57b5a88126f84f62679e49c92384917d048
