### ISSUE TITLE
HIP-206: Add precompile call data to ContractFunctionResults

### ISSUE THREAD

**Issue by SimiHunjan** [hashgraph/hedera-sdk-js#1009]
### Problem

Add precompiled call data for `parameters`, `gas`, and `amount` to the `ContractFunctionResults`. These would be in the `TransactionBody` if it was a normal call but the body for precompiles is a
different type.

HIP: https://github.com/hashgraph/hedera-improvement-proposal/blob/master/HIP/hip-206.md#additional-protobuf-fields

HAPI Protobuf PR: https://github.com/hashgraph/hedera-protobufs/pull/163

### Solution

Support HAPI updates

**Comment by easpaas** [comment]
@SimiHunjan I can't assign myself to this issue. Could you verify if this is a permission issue for this repo?

**Comment by SimiHunjan** [comment]
should be fixed now
