### ISSUE TITLE
Review SonarCloud Issues 

### ISSUE THREAD

**Issue by SimiHunjan** [hashgraph/hedera-sdk-js#1019]
### Problem

The SonarCloud report for the SDK needs to be reviewed.

### Solution

Review and address findings in report.

**Comment by easpaas** [comment]
I have included comments within the SonarCloud issues for which issues can be ignored.

**Comment by danielakhterov** [comment]
@easpaas we need to determine if there is any work left for this issue, otherwise we can close it.
