### ISSUE TITLE
TransferTransaction substitutes FT id for NFT id during creation

### ISSUE THREAD

**Issue by rocketmay** [hashgraph/hedera-sdk-js#1027]
### Description

Issue:

When creating a TransferTransaction with NFT ID 0.0.34033784 and FT ID 0.0.34033787, the NFT ID is written to the TransferTransaction as the FT ID.

If the FT lines are commented out, the NFT transaction data is built correctly.

Further testing shows that using the same NFT ID 0.0.34033784, using a token ID of 0.0.2217988 doesn't cause the bug to happen but 0.0.34049803 does cause the bug to occur.

Expected result:

When creating a TransferTransaction with NFT ID specified as 0.0.34033784, expect the transfer to be created to transfer token 0.0.34033784 and not the Fungible Token in the other part of the trade.

### Steps to reproduce

Create a TransferTransaction with the specified token ID's

Freeze and parse the transaction and review that the NFT ID has been changed to the FT ID.

### Additional context

`export default class HashgraphService {

    public async BuildTradeTransaction(buyer_account_id: string, nftToken:tokenInfo, FTCost:number):Promise<Uint8Array> {

        let transferTransaction = new TransferTransaction()

        // buyer sends ft
         .addTokenTransfer("0.0.34033787",buyer_account_id,-FTCost)
         .addTokenTransfer("0.0.34033787",process.env.TREASURY_ID,FTCost)

         // treasury sends nft
          .addNftTransfer("0.0.34033784", 1, process.env.TREASURY_ID, buyer_account_id);
          
        let signedTransaction = await this.signAndMakeBytes(transferTransaction);
        return Promise.resolve(signedTransaction);

    }

    async signAndMakeBytes(trans: Transaction) {
        
        const privKey = PrivateKey.fromString(process.env.T_OP_KEY);
        const pubKey = privKey.publicKey;

        let nodeId = [new AccountId(3)];
        let transId = TransactionId.generate(process.env.T_OP_ID);
        
        trans.setNodeAccountIds(nodeId);
        trans.setTransactionId(transId);
        
        trans = await trans.freeze();

        let transBytes = trans.toBytes();

        const sig = await privKey.signTransaction(Transaction.fromBytes(transBytes) as any);

        const out = trans.addSignature(pubKey, sig);

        const outBytes = out.toBytes();
        
        console.log("Transaction bytes", outBytes);

       let parsedTransaction = Transaction.fromBytes(outBytes);
       console.log(JSON.stringify(parsedTransaction));
        return outBytes;
    }

...

}`

### Hedera network

testnet

### Version

v2.11.3

### Operating system

Windows

**Comment by bugbytesinc** [comment]
After looking at the TransferTransaction.js file from the hashgraph js sdk project, it appears from inspection that this line (and the ones that follow it) are the culprit:

https://github.com/hashgraph/hedera-sdk-js/blame/main/src/account/TransferTransaction.js#L771

**Comment by bugbytesinc** [comment]
In particular, it appears that the code splits on the relative order of NFT and FT addresses (which explains the differences in behavior between two different FT sets in the comments above)....in this particular code path around line 791 there appears to be an issue: the iTokenId is used instead of jTokenId to represent the NFT transfer being added to the nftTransfers list.  ITokenID is the FT in this example, not the NFT id.

**Comment by bugbytesinc** [comment]
It looks like the defect was introduced in this commit: https://github.com/hashgraph/hedera-sdk-js/commit/27bba08e597ddd0ea6f2464d67f833d882025720

**Comment by danielakhterov** [comment]
Fixed on `main`
