### ISSUE TITLE
Add or update queries to get nft serials in account balance

### ISSUE THREAD

**Issue by rocketmay** [hashgraph/hedera-sdk-js#1029]
### Problem

There is no SDK call which returns the serial numbers for NFTs owned by an account.

### Solution

Update one of the existing queries or add a new one which returns all non Fungible tokens owned by an account and the serial #'s. 

### Alternatives

There is a mirror node call but mirror node results can be up to fifteen minutes old.

**Comment by xin-hedera** [comment]
@rocketmay there is no HAPI to return all nfts with serial numbers owned by an account so SDK won’t be able to implement such a feature.

mirrornode’s up-to 15 min balance info is for crypto and fungible tokens. The nfts owned by an account returned from /api/v1/accounts/:accountId/nfts just adds 2-3 secs delay on top of consensus.

**Comment by rocketmay** [comment]
_The nfts owned by an account returned from /api/v1/accounts/:accountId/nfts just adds 2-3 secs delay on top of consensus._

This is very interesting and good to know! This is sufficient for my requirements. Perhaps it would be worth clarifying somewhere in the documentation.
