### ISSUE TITLE
Guide for using signature provider feature for wallet developers

### ISSUE THREAD

**Issue by SimiHunjan** [hashgraph/hedera-sdk-js#1032]
### Problem

We need a guide that outlines the basic steps of creating a provider.

### Solution

Create guide.

**Comment by easpaas** [comment]
@SimiHunjan @danielakhterov Are there other guides that I can reference for this? At the moment I think this ticket is too ambiguous to make any progress.

**Comment by SimiHunjan** [comment]
@easpaas this was to document a guide for wallet developers in how they would use or what steps they would take to take advantage of the signature provider feature in the SDK. This is the HIP for that feature https://hips.hedera.com/hip/hip-338. This can be a markdown file. We were planning to host it at docs.hedera.com. The markdown file can be shared with me to add to that site.
