### ISSUE TITLE
Add comments describing methods/functions

### ISSUE THREAD

**Issue by SimiHunjan** [hashgraph/hedera-sdk-js#1048]
### Problem

When new features are delivered it is sometimes not intuitive how the new function/method is supposed to work. Comments describing the function/method would make it easier to understand the behavior.

### Solution

Add comments to describe the functions/methods in the source code.

**Comment by easpaas** [comment]
@SimiHunjan might this issue date be flexible? Perhaps, a good use case for a `tech debt` label? For example, this issue should be kept in mind when devs are working within the files; rather, something to chip away at than spend time going through every file 😬 

Thoughts?

**Comment by mehcode** [comment]
For context, if the method relates to set/get in the protobuf – that should be copied from the protobuf documentation.
