### ISSUE TITLE
Not working in browser because 'process' is undefined

### ISSUE THREAD

**Issue by kylemantesso** [hashgraph/hedera-sdk-js#1049]
### Description

What happened?
SDK throws uncaught reference error when used in browser

Expected?
it does not throw error when used in browser

### Steps to reproduce

```
npx create-react-app my-app
 cd my-app
npm install --save @hashgraph/sdk
```

Use SDK, will result in error

### Additional context

Error:
```
exports.js:159 Uncaught ReferenceError: process is not defined
    at Module../node_modules/@hashgraph/sdk/src/exports.js 
```

 Exports.js:
```
...
if (
    process != null &&
    process.env != null &&
    process.env.HEDERA_SDK_LOG_LEVEL != null
) {
...
```

Suggest checking that `process` is defined 

### Hedera network

mainnet, testnet, previewnet

### Version

v2.12.0

### Operating system

macOS

**Comment by justin-m-lacy** [comment]
I'm getting the same error.

**Comment by danielakhterov** [comment]
This is a silly mistake. Moved the logger construction through environment variables into `index.js` which is only loaded in NodeJS. https://github.com/hashgraph/hedera-sdk-js/releases/tag/v2.12.1 Contains the fix
