### ISSUE TITLE
Look into preventing the user from calling constructors in JS

### ISSUE THREAD

**Issue by danielakhterov** [hashgraph/hedera-sdk-js#1052]
### Problem

This issue was created while I was in a call with a couple others discussing the Signature Providers feature in the SDK. This feature is supposed to make types in the SDK which other packages can extend. The logic in the constructors for these new types is supposed to be async, but async constructors aren't a thing in JS. So, to get around this we want to make sure users don't accidentally call the JS constructors for these types. This is easily solved if a user uses TypeScript because we already annotate the methods as private, but there are plenty of users who do not use TypeScript; how do we prevent them from calling the constructors, or at the very least indicate at runtime they are calling the wrong method. My answer to this is "just use TS" or read the documentation, but not everyone likes that answer :)

Title

### Solution

Title

**Comment by SimiHunjan** [comment]
Not relavent
