### ISSUE TITLE
SDK testing includes browser testing with Playwright or Puppeteer

### ISSUE THREAD

**Issue by SimiHunjan** [hashgraph/hedera-sdk-js#1059]
### Problem

The SDK currently does not include testing for this case.

### Solution

Add testing for this case.

**Comment by danielakhterov** [comment]
Not really following where  this issue stems from. Puppeteer shouldn't be required to test the SDK since it's not a UI application.

**Comment by bluemonad** [comment]
> Not really following where this issue stems from. Puppeteer shouldn't be required to test the SDK since it's not a UI application.

I think the point is to add tests in browser context, as opposed to only NodeJS context. The exact testing framework should not be critical. Having such tests should hopefully prevent issues like [this](https://github.com/hashgraph/hedera-sdk-js/issues/1049) from occurring.
