### ISSUE TITLE
Creating a token with maxSupply fails precheck 

### ISSUE THREAD

**Issue by KilianB** [hashgraph/hedera-sdk-js#1071]
### Description

Executing a token create transaction with max supply fails with a precheck error

`PrecheckStatusError: transaction 0.0.29648296@1649786758.670775896 failed precheck with status INVALID_TOKEN_MAX_SUPPLY`

### Steps to reproduce

Execute the following transaction 

````typescript
const createTx = new TokenCreateTransaction({
  tokenName: tokenName,
  tokenSymbol: tokenSymbol,
  supplyKey: privateKey,
  decimals: 8,

  initialSupply: 10_000_000,
  maxSupply: 10_000_000,
  treasuryAccountId: operatorAcc,
  tokenMemo: tokenMemo,
});
```

### Additional context

_No response_

### Hedera network

testnet

### Version

v2.12.1 

### Operating system

_No response_

**Comment by danielakhterov** [comment]
Closing as I don't think this is an SDK bug. You should create this issue here; https://github.com/hashgraph/hedera-services

Unless you're implying that this code worked in previous SDK versions, but no longer does in which case we should re-open this issue.
