### ISSUE TITLE
Account alias feature does not seem to work

### ISSUE THREAD

**Issue by SimiHunjan** [hashgraph/hedera-sdk-js#1086]
### Description

@gregscullard was trying to using the account alias feature in the SDK and returns INVALID_ACCOUNT_ID when trying to request the account info of the alias account. The example in the SDK errors as well. This is reported as working fine in the Java SDK. 

Please see steps below.

- Created a new account with 5 hbar (normal AccountCreateTransaction)
- Transferred 9 hbar from this account to an alias, no error raised (I’d expect insufficient balance)
- Created another new account with 20 hbar
- Transferred 9 hbar from this account to an alias, no error raised and I can’t find a transaction transferring hbar from the above account to the new one.
- The corresponding receipt has no children
- getInfo and getBalance using the alias fail with INVALID_ACCOUNT_ID
- I took the SDK example to try things out and it failed on getting balance near the end.

### Steps to reproduce

Reference example: https://github.com/hashgraph/hedera-sdk-js/blob/main/examples/account-alias.js

### Hedera network

testnet

### Version

v0.2.13

**Comment by danielakhterov** [comment]
Fixed and released: https://github.com/hashgraph/hedera-sdk-js/releases/tag/v2.13.1
