### ISSUE TITLE
Cannot find `setExpirationTime` in `TopicUpdateTransaction` 

### ISSUE THREAD

**Issue by uac-nhan-nguyen** [hashgraph/hedera-sdk-js#1087]
### Description

Hi,

I'm trying to extend the expiry time of a consensus topic. There seems to be a method called `setExpirationTime(<expirationTime>)` for that in documentation:

https://docs.hedera.com/guides/docs/sdks/consensus/update-a-topic

However I couldn't find it in this SDK version 2.13.0.

### Steps to reproduce

Expect snippet below to work:
```
const tx = await new TopicUpdateTransaction()
  .setTopicId(...)
  .setExpirationTime(...)
  .execute(client) 
```

### Hedera network

testnet

### Version

2.13.0

**Comment by danielakhterov** [comment]
I think this field may have been added inbetween features which is why it wasn't included in the SDK. Nonetheless, we'll get this resolved as soon as we can.
