### ISSUE TITLE
Enable the SDK to retrieve a record even if a transaction failed

### ISSUE THREAD

**Issue by SimiHunjan** [hashgraph/hedera-sdk-js#1090]
### Problem

Right now, getRecord does a getReceipt first and if the status isn’t SUCCESS, it throws an exception.

There are cases when being able to get a record for a failed transaction does make sense, and it would be desirable to be able to override the exception being thrown.

### Solution

Add support for this feature.

**Comment by SimiHunjan** [comment]
cc @gregscullard

**Comment by danielakhterov** [comment]
https://github.com/hashgraph/hedera-sdk/pull/26

**Comment by mehcode** [comment]
- [ ] Add `getReceiptQuery(): TransactionReceiptQuery`
- [ ] Add `getRecordQuery(): TransactionRecordQuery
- [ ]`


Expected usage:

```js
let badReceipt = transactionResponse.getReceiptQuery().execute(client);
```
