### ISSUE TITLE
Max attempts 10

### ISSUE THREAD

**Issue by teacoat** [hashgraph/hedera-sdk-js#1095]
### Description

Not too sure what this error is, but I've been seeing it in my logs

![image](https://user-images.githubusercontent.com/3913019/165311463-230bb54e-a245-4a5d-88f1-8284805db616.png)

### Steps to reproduce

Unable to reproduce, seems random

### Hedera network

mainnet

### Version

2.13.0

**Comment by danielakhterov** [comment]
This error is thrown when the SDK has tried to execute the request 10 times and is still receiving retrying status codes. To solve this you could increase the max attempts to for instance 20 or more if you really need the SDK to try as long as it can.
