### ISSUE TITLE
Mismatching chunk size unit with doc

### ISSUE THREAD

**Issue by voyager-gold** [hashgraph/hedera-sdk-js#1110]
### Description

According to the doc below, it says default chunk size is 2048 kb, while actual implementation is 2048 bytes
https://docs.hedera.com/guides/docs/sdks/file-storage/append-to-a-file

Implementation:
https://github.com/hashgraph/hedera-sdk-js/blob/main/src/file/FileAppendTransaction.js#L88
https://github.com/hashgraph/hedera-sdk-js/blob/main/src/file/FileAppendTransaction.js#L319-L321

As `this._contents.length` is in byte, not kb, it calculates chunk count incorrectly.

Is the chunk size 2048 kb or 2048 bytes?

### Steps to reproduce

See above

### Hedera network

testnet

### Version

v2.12.0

**Comment by danielakhterov** [comment]
I think this is a bug with the docs instead. The chunk size by default is 2KiB (2048 bytes) not 2048 KiB
Should create an issue under: https://github.com/hashgraph/hedera-docs/

**Comment by SimiHunjan** [comment]
updated docs thanks!
