### ISSUE TITLE
getNextMirrorNode returning undefined when used with Angular framework

### ISSUE THREAD

**Issue by ed-marquez** [hashgraph/hedera-sdk-js#1117]
### Description

A user is reporting an error coming from angular app when usingjs-sdk....
it all works good from node app, same hedera pkg version though.

### Steps to reproduce

Looks like the function getNextMirrorNode returns undefined. 

It even sends the message, but can't subscribe to it
```
     const cancel = client._mirrorNetwork
            .getNextMirrorNode()
            .getChannel()
            .makeServerStreamRequest(
                "ConsensusService",
                "subscribeTopic",
                request,
```

See error in screenshot in the next section.

### Additional context

The error in the attached image occurs:

<img width="550" alt="screenshotError" src="https://user-images.githubusercontent.com/72571340/166721250-644338c3-545d-48e4-8269-19a5c479625d.png">

### Hedera network

testnet, other

### Version

v2.11.3

**Comment by mehcode** [comment]
Please see https://github.com/hashgraph/hedera-sdk-js/issues/1114. The mirror nodes do not support use in a browser environment.

**Comment by ed-marquez** [comment]
Got it. Thanks for the quick response. Are we considering adding that in a future release? If so, happy to help find users to help define requirements.

**Comment by mehcode** [comment]
It couldn't be added here. It would need to be added to the mirror nodes themselves. They don't expose a grpc-web endpoint.
