### ISSUE TITLE
Getting tx confirmation using Provider requires manual creation tx ID - passing tx confirmation doesn't work 

### ISSUE THREAD

**Issue by ed-marquez** [hashgraph/hedera-sdk-js#1128]
### Description

I'm using the signer/provider provided by HashPack's HashConnect in my application. Version 2.13.1 of the hashgraph SDK and 0.1.6 of HashConnect.
HashConnect uses the signer/provider in the SDK (see imports in https://github.com/Hashpack/hashconnect/blob/main/lib/src/provider/signer.ts AND https://github.com/Hashpack/hashconnect/blob/main/lib/src/provider/provider.ts) 

I freeze a transaction with `.freezeWithSigner(signer)` and execute it with `.executeWithSigner(signer)`. That works as expected. 

However, getting a tx confirmation (receipt or record) is difficult. I should be able to just get and use the transaction id from the execution object, like:
```
const tokenCreateSubmit = await tokenCreateTx.executeWithSigner(signer);
const txId = tokenCreateSubmit.transactionId
const tokenCreateRx = await provider.getTransactionReceipt(txId)
```
But that doesn't work. I had to create the txId manually as follows:
```
const tokenCreateSubmit = await tokenCreateTx.executeWithSigner(signer);
const sec = tokenCreateSubmit.transactionId.validStart.seconds.low;
const nano = tokenCreateSubmit.transactionId.validStart.nanos.low;
const txId = `${accountId}@${sec}.${nano}`;
const tokenCreateRx = await provider.getTransactionReceipt(txId);
```
I also tried generating the tx id before freezing and executing the transaction with the signer using `TransactionId.generate()` (https://docs.hedera.com/guides/docs/sdks/transactions/transaction-id), but that approach doesn't work either to get the tx Id that enables retrieving a confirmation.

A user reported the exact same behavior and issue via Discord. This observation was shared with the internal team.

### Steps to reproduce

[tokenCreate.txt](https://github.com/hashgraph/hedera-sdk-js/files/8720820/tokenCreate.txt)
The file attached is a component in a larger application but can be used to reproduce/analyze the issue.

Can reproduce the whole application and see the code here; https://gitpod.io/#https://github.com/ed-marquez/hedera-dapp-days/tree/testing

### Additional context

N/A

### Hedera network

testnet

### Version

v0.25

### Operating system

Windows

**Comment by danielakhterov** [comment]
I'm going to close this issue as it doesn't seem to be an SDK issue. However, I did review hashconnects implementation and the odd thing I found is https://github.dev/Hashpack/hashconnect/blob/6e449504f89d0d1f421b457f3e7d6c7dcb2f0964/lib/src/message/message-handler.ts#L62-L63 which seems to simply parse the response from string into a JSON object. It doesn't construct a `TransactionResponse` so https://github.dev/Hashpack/hashconnect/blob/3175f7a7b1cc7ad18198dc0c347e05aaa402128a/lib/src/provider/provider.ts#L82-L83 doesn't seem right to me. The `res.response` is not a `TransactionResponse`, it's only an object that matches the _look_ of the response. All the methods that exist on `TransactionResponse` and hence the `.transactionId` field inside are not  there.
