### ISSUE TITLE
Add technology compatibility kit (TCK)

### ISSUE THREAD

**Issue by SimiHunjan** [hashgraph/hedera-sdk-js#1134]
### Problem

TCKs allows independent implementations to have a way to test for compatibility of the feature.

### Solution

Add TCK

Implement a TCK:

- [ ] TCK should require minimal work from the signature provider
- [ ] TCK should provide an itemized list of tests that failed or passed.
- [ ] TCK should provide a overall passed/failed checkmark.
- [ ] TCK should support headfull and headless signature providers.

**Comment by annamariyaivanova** [comment]
@SimiHunjan this is quite outdated and taking into account we are working on the TCK, I will close this issue.
