### ISSUE TITLE
SDK Queries (AccountBalanceQuery(), AccountInfoQuery(), ContractInfoQuery()) returning "undefined" when using .executeWithSigner()

### ISSUE THREAD

**Issue by ed-marquez** [hashgraph/hedera-sdk-js#1136]
### Description

This may be a HashConnect issue, but reporting here because it's worth double-checking the SDK first.

The following queries can be performed using `.executeWithSigner()`. However, they all return "undefined". They all work as expected when using the Hedera Client, but not working as expected with a signer (HashConnect's in this case):

```
const xCheck = await new AccountBalanceQuery().setAccountId(accountId).executeWithSigner(signer);
const zzCheck = await new AccountBalanceQuery()
	.setContractId(contractId)
	.executeWithSigner(signer);
const zCheck = await new AccountInfoQuery().setAccountId(accountId).executeWithSigner(signer);
const yCheck = await new ContractInfoQuery().setContractId(contractId).executeWithSigner(signer);
```

Fortunately, I'm able to use `await signer.getAccountBalance()` to get the balance of the account of interest because balance queries are not paid. 

Unfortunately, there's currently no way to query the balance for a contract because the info and balance queries above don't work. `await provider.getAccountBalance(contractId)` should work, but it returns `INVALID_ACCOUNT_ID`, so it's not working well with contracts. May be worth considering enabling the SDK to handle this case just like `AccountBalanceQuery().setContractId(contractId)` works.

 Mirror query could work for getting the contract balance, but the mirror delay for balances makes painful to use.

### Steps to reproduce

1. Run the queries above for any account and contract
2. Try with both client and signer and see difference

### Hedera network

testnet

### Version

v2.14.2

### Operating system

Windows

**Comment by danielakhterov** [comment]
From what I can tell, and from our discussions in Slack, these errors look like they're coming from `HashConnect` implementation of signature providers. At the moment I don't see how this is an SDK bug, so I'm closing this issue. However, if there is more info that indicates this is an SDK bug then we'll reopen. 

> May be worth considering enabling the SDK to handle this case just like `AccountBalanceQuery().setContractId(contractId)` works.

I don't know how the SDK can handle this case as it's not up to the SDK, it's up to the signature provider implementer. The SDK interfaces cannot have code in them by default, so there is nothing the SDK can really do here. If we were to provide an abstract class with a default implementation then we run into the issue where you need to require the entire SDK to create a signature provider which is something we wanted to avoid.
