### ISSUE TITLE
Hedera Java SDK protobuf-javalite dependency incompatible with important GCP libraries like secrets manager

### ISSUE THREAD

**Issue by robkainz** [hashgraph/hedera-sdk-js#1151]
### Description

I'm not able to start my spring boot server in a Google Cloud environment after upgrading to a recent Hedera SDK (2.14.0-beta.1 was used at the time, but I am quite sure the problem still exists with the latest SDK.) I first noticed the problem when some unit tests failed.

@gregscullard quickly determined that the reason was protobuf-javalite is incompatible with Google's google-cloud-secretmanager:2.0.2, which we heavily depend on, and I imagine others will as well.

According to this discussion Greg sent to me, protobuf-javalite was only meant to be used in an Android environment, though I don't think that is 100% confirmed. However, it is clear from Google's documentation according to the discussion that it is not usable with GCP libraries:

https://github.com/GoogleCloudPlatform/cloud-opensource-java/issues/587

Here is the specific exception I saw when starting up my server on Google Cloud:

```
nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [java.lang.String]: Factory method 'operatorMainnetPrivateKey' threw exception; nested exception is java.lang.NoClassDefFoundError: io/grpc/CallCredentials2
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:799)
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:228)
	at
  ...

```
Here is the exception I saw when running my unit tests, this specific one simply moves hbar from my testnet faucet account to the one I use for testing:

```
  java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    com/hedera/hashgraph/sdk/proto/TokenTransferList.mergeExpectedDecimals(Lcom/google/protobuf/UInt32Value;)V @31: invokevirtual
  Reason:
    Type 'com/google/protobuf/UInt32Value' (current frame, stack[2]) is not assignable to 'com/google/protobuf/GeneratedMessageLite'
  Current Frame:
    bci: @31
    flags: { }
    locals: { 'com/hedera/hashgraph/sdk/proto/TokenTransferList', 'com/google/protobuf/UInt32Value' }
    stack: { 'com/hedera/hashgraph/sdk/proto/TokenTransferList', 'com/google/protobuf/UInt32Value$Builder', 'com/google/protobuf/UInt32Value' }
```

Part of the stack trace showing that it is a protobuf dependency issue:

```
at java.base/java.lang.Class.forName0(Native Method)
    at java.base/java.lang.Class.forName(Class.java:398)
    at com.google.protobuf.GeneratedMessageLite.getDefaultInstance(GeneratedMessageLite.java:299)
    at com.google.protobuf.GeneratedMessageInfoFactory.messageInfoFor(GeneratedMessageInfoFactory.java:58)

```

I suspect that lite version of protobuf dependency for the Hedera sdk must be replaced with the full version.

### Steps to reproduce

1. Write a Junit test case that sends some hbar from one account to another in a simple spring boot application.
2. Add the following dependency to your build.gradle file: implementation 'com.google.cloud:google-cloud-secretmanager:2.0.2'
3. Compile and run the unit test.

### Hedera network

mainnet, testnet

### Version

2.14.0-beta.1

### Operating system

macOS

**Comment by steven-sheehy** [comment]
I believe this ticket should be on the hedera-sdk-java repo?

**Comment by robkainz** [comment]
@steven-sheehy Yes you are correct, mistakenly pulled up the wrong project.
