### ISSUE TITLE
AccountAllowanceDeleteTransaction unable to revoke NFT allowances

### ISSUE THREAD

**Issue by ah-7** [hashgraph/hedera-sdk-js#1162]
### Description

After approving a single NFT allowance using an AccountAllowanceApproveTransaction, it's not possible to remove that allowance using an AccountAllowanceDeleteTransaction.

### Steps to reproduce

`const transaction = new AccountAllowanceDeleteTransaction()`
            `.deleteAllTokenNftAllowances(new NftId(TokenId.fromString(tokenId), serialNo), operatorId, spenderId)`
           ` .freezeWith(client)`
        
`const signTx = await transaction.sign(spenderKey);`
`const txResponse = await signTx.execute(client);`
`const receipt = await txResponse.getReceipt(client);`
`const transactionStatus = receipt.status;`
`console.log("The transaction consensus status is " + transactionStatus.toString());`

### Additional context

The error message displayed is always as follows:

Error: max attempts of 10 was reached for request with last error being: BUSY

### Hedera network

testnet

### Version

2.16.0-beta.2

**Comment by danielakhterov** [comment]
This is not a bug; I believe what happened was that the network was in fact really busy when you submitted your request. Since the network was so busy it ended up exhausting all 10 attempts. What you can do is increase the max attempts via `setMaxAttempts()`.
