### ISSUE TITLE
sync needs to be requesting https for time.google.com

### ISSUE THREAD

**Issue by scalemaildev** [hashgraph/hedera-sdk-js#1163]
### Description

I have been getting 'mixed content' errors in my app and have tracked them down to line 9 of /src/sync.js

This should be requesting https or else it will be blocked on any https site.

### Steps to reproduce

Run the hedera js sdk in an https website and you should get a mixed content error pointing to time.google.com.

### Additional context

```
        const response = await axios.get("http://time.google.com", {
```

### Hedera network

testnet

### Version

v2.15

### Operating system

Linux

**Comment by danielakhterov** [comment]
Should be fixed and released in https://github.com/hashgraph/hedera-sdk-js/releases/tag/v2.16.1

**Comment by supermonkeybrainz** [comment]
> Should be fixed and released in https://github.com/hashgraph/hedera-sdk-js/releases/tag/v2.16.1

Oh no!  I just realized we now get CORS errors.  Ha!  It's always something.

**Comment by danielakhterov** [comment]
Heh, yea there is always something :stuck_out_tongue: I do think I've come up with a solution though https://github.com/hashgraph/hedera-sdk-js/commit/9beef303a62d80f575ee4ff995134263498ac3df

**Comment by danielakhterov** [comment]
@supermonkeybrainz Just released https://github.com/hashgraph/hedera-sdk-js/releases/tag/v2.16.4 today which I think solves this issue

**Comment by supermonkeybrainz** [comment]
It does, thanks!
