### ISSUE TITLE
nftApprovals not exposed by AccountAllowanceApproveTransaction

### ISSUE THREAD

**Issue by teacoat** [hashgraph/hedera-sdk-js#1167]
### Description

nftApprovals are not exposed the same as hbarApprovals or tokenApprovals in AccountAllowanceApproveTransaction, pretty straightforward!

### Steps to reproduce

N/A

### Hedera network

mainnet

### Version

2.14.2

**Comment by danielakhterov** [comment]
Fixed: https://github.com/hashgraph/hedera-sdk-js/commit/5beeca23a0fadbc0c3f90a824677b4b851fb8981
