### ISSUE TITLE
Comment out of date in regards to new url

### ISSUE THREAD

**Issue by mensfeld** [hashgraph/hedera-sdk-js#1176]
Here, the `time.google.com` is referenced but the end host for the request is `grpc-web.myhbarwallet.com`. I think it's confusing and wanted to let you guys know.

https://github.com/hashgraph/hedera-sdk-js/blob/c8623b029eaa873182e758f0809f902cb5b49886/src/sync.js#L6

**Comment by danielakhterov** [comment]
Fixed: https://github.com/hashgraph/hedera-sdk-js/commit/5f9fc0b4ad16fc69dd07348c995e4af34eb98167
