### ISSUE TITLE
Add ECDSA key support to Mnemonic logic

### ISSUE THREAD

**Issue by Nana-EC** [hashgraph/hedera-sdk-js#1177]
### Problem

Currently [Mnemonic logic](https://github.com/hashgraph/hedera-sdk-js/blob/main/packages/cryptography/src/Mnemonic.js) inherently supports Ed25519 key. 
Usage example [generate-key.js](https://github.com/hashgraph/hedera-sdk-js/blob/main/examples/generate-key.js)

With the expansion and need for great ECDSA support this becomes a limiting factor on wallets

### Solution

Add configuration to support ECDSA keys also
Expand `Mnemonic.toPrivateKey(passphrase)` to take in a keyType that is used to affect the hash algorithm used and key type returned

### Alternatives

Add `Mnemonic.toEcdsaPrivateKey(passphrase)` and `Mnemonic.toEd25519PrivateKey(passphrase)` with `Mnemonic.toPrivateKey(passphrase)` defaulting to the latter

**Comment by shemnon** [comment]
This line in particular needs review - https://github.com/hashgraph/hedera-sdk-js/blob/main/packages/cryptography/src/Mnemonic.js#L284

It may be correct for 
Hedera we just need to take it down an ECDSA path.  The queistion is we are using the same derivation point for two different algorithms.

**Comment by lbaird** [comment]
I agree that it's better to add a key type parameter to `Mnemonic.toPrivateKey(passphrase)`, rather than creating two new methods. It might also be good to keep the method without the parameter (which defaults to ed25519), for backward compatibility. 

I also think that the new implementation should be as close as possible to the old one. As many of the steps as possible should be identical. It's just that the last step should use a number generator to create an ECDSA key instead of an ed25519 key.

**Comment by mehcode** [comment]
@lbaird As we use a shared specification for SDKs, adding a default parameter to a function is not possible in all languages so we can't change `toPrivateKey` in a non-breaking fashion. Go for example does not support default parameters and in JavaScript its a breaking change to add a default parameter (if the function is ever used as a function pointer).

Our only reasonable non-breaking choice is:

- Deprecate `toPrivateKey` _or_ keep and continue to output ed25519 as a "default"
- Add `toEd25519PrivateKey`
- Add `toEcdsaPrivateKey`

This is similar to how we have `PrivateKey.generateEd25519()` and `PrivateKey.generateEcdsa()`

**Comment by lbaird** [comment]
@mehcode it sounds like you’re saying that in Nana’s original proposal,
you’d like to reject the “solution” and instead do the “alternatives”?  I
think that would be fine.

**Comment by lbaird** [comment]
And to be clear, I’m also fine with the original proposal (do “solution”
and not do “alternatives”).
