### ISSUE TITLE
Error in deploying contract with byecode generated with Truffle - Hardhat

### ISSUE THREAD

**Issue by damianlluch** [hashgraph/hedera-sdk-js#1178]
Hi, on the other blockchains where I have some contracts deployed (polygon, eth, binance, avalanche). The OZ plugins for Hardhat or Truffle are used for the use of proxies.
In the architecture we use (erc721 contract factory) we have a transparent proxy for the factory, and then a beacon proxy for the token contracts.
Question, I have done a test and I have been able to deploy the factoria contract in Hedera, I have only deployed the factoria contract by generating the bytecode with solc-js directly.
Now I have tried with the bytecode generated by Truffle as Hardhat.

And I get this message:

```
ReceiptStatusError: receipt for transaction 0.0.0@1656489717.954698316 contained error status CONTRACT_REVERT_EXECUTED
```

Is there any problem with the bytecodes generated by these frameworks?

**Comment by danielakhterov** [comment]
I don't know if the bytecodes generated by those frameworks is good or bad, but if you fetch the transaction record for the transaction ID you should be able to get the reason a `CONTRACT_REVERT_EXECUTED` was returned through `TransactionRecord.contractFunctionResult`
