### ISSUE TITLE
Error: Hedera returned response code: KEY_PREFIX_MISMATCH (68)

### ISSUE THREAD

**Issue by rahulasati** [hashgraph/hedera-sdk-js#118]
I am getting **Error: Hedera returned response code: KEY_PREFIX_MISMATCH (68)** when trying to run FileContentsQuery from the same account using which file is created

const fileIdLike = {
   shard: 0, realm: 0, file: fileId
}
let fileQueryResp = await new FileContentsQuery(client).setFileId(fileIdLike).execute()

**Comment by mehcode** [comment]
@rahulasati What version of the SDK are you using?

**Comment by mehcode** [comment]
@rahulasati We reproduced this and the fix is present in the upcoming 0.8.0 release. You can try it out with:

```
npm i --save @hashgraph/sdk@0.8.0-beta.3
```

**Comment by rahulasati** [comment]
Hi @mehcode thanks for fixing this, i will upgrade to latest version and verify.
