### ISSUE TITLE
`ContractId.fromEvmAddress()` does not produce a valid hedera contract address

### ISSUE THREAD

**Issue by mgarbs** [hashgraph/hedera-sdk-js#1188]
### Description

What happened
```
const contract = ContractId.fromEvmAddress(0, 0, "0x0000000000000000000000000000000002D6DEc3");
console.log(contract.toString());

> 0.0.0000000000000000000000000000000002d6dec3
```

What should happen
const contract = ContractId.fromEvmAddress(0, 0, "0x0000000000000000000000000000000002D6DEc3");
console.log(contract.toString());

> 0.0.1002 (Something like this. Exact value displayed)

### Steps to reproduce

1. Run the code snippet
2. Look at what it logs (not a proper hedera contract address)

### Additional context

It looks like it just takes the string and makes it a num after the realm number. No conversion is happening

### Hedera network

testnet

### Version

^2.14.2

### Operating system

macOS

**Comment by danielakhterov** [comment]
Use `ContractId.fromSolidityAddress()` instead here. It's deprecated because you should no longer be using solidity encoded contract IDs and instead should use proper CREATE2 contract IDs.

**Comment by mgarbs** [comment]
> Use `ContractId.fromSolidityAddress()` instead here. It's deprecated because you should no longer be using solidity encoded contract IDs and instead should use proper CREATE2 contract IDs.

When I deploy a smart contract using Remix and the JSON RPC Relay, I get a solidity address back. This path is one that many users could potentially take. Your suggestion to use `ContractId.fromSolidityAddress()` worked. Thank you for that. However, people taking a similar path may not know what to do if we remove this function.

**Comment by gregscullard** [comment]
@danielakhterov I don't understand your comment (I don't get the meaning of `proper` CREATE2 contract IDs), not all contracts are created with CREATE2 (in fact the majority aren't). Why remove deprecate the function ?

I see that `fromSolidityAddress` has not been deprecated on AccountId, I guess a developer could convert the address back to an AddressId and then over to a ContractId.

```
    const accountId = AccountId.fromSolidityAddress(solidityAddress);
    const recoveredContractId = new ContractId(accountId.shard, accountId.realm, accountId.num);
    console.log(recoveredContractId.toString());
```

(I understand that in the case of CREATE2, you can't work the entity id back from the contract's (EVM) address but this is not the most common use of addresses wrt contracts)

**Comment by gregscullard** [comment]
Re-opening - not satisfied with closure.

**Comment by danielakhterov** [comment]
@gregscullard From my understanding, when creating contracts going forward you'll always get a CREATE2 address. Old solidity addresses do still work for old contracts, but since that behavior is no longer the default I thought it would make sense deprecating that method in the SDKs as well.

**Comment by gregscullard** [comment]
That's incorrect, CREATE2 is one way of creating a contract with a deterministic EVM Address (this is used primarily in DEFI) but it is not the only way to create a contract, in fact, a contract deployed with the SDK will not used CREATE2 which is a solidity operation for creating a contract from within a contract.
Contracts created with the SDK will be known by their `contractId` or equivalent solidity address.
We should revert the deprecation imo.

**Comment by gregscullard** [comment]
https://github.com/hashgraph/hedera-protobufs/blob/main/services/transaction_receipt.proto doesn't include an EVM address, only a contractId.

**Comment by danielakhterov** [comment]
@gregscullard https://github.com/hashgraph/hedera-protobufs/blob/0941bd652174852cb87467b98de5565e6583582d/services/basic_types.proto#L168 The `ContractID` type is what contains the `evm_address`
