### ISSUE TITLE
ContractCreateFlow() can't use .freezeWith() and .sign() after setting an adminKey

### ISSUE THREAD

**Issue by cisc0f** [hashgraph/hedera-sdk-js#1189]
### Description

I know `ContractCreateFlow()` is not a transaction as I've seen in [this issue](https://github.com/hashgraph/hedera-sdk-js/issues/1135), but if I set an admin key and I need to pay the transactions that `ContractCreateFlow()` is executing using another account, I can't as  `.freezeWith()` and `.sign()` are not available. My workaround right now is changing the operator using `client.setOperator(adminId, adminKey)`. 

Error:
```
.freezeWith(client);
         ^
TypeError: (intermediate value).setGas(...).setBytecode(...).setAdminKey(...).freezeWith is not a function
```

### Steps to reproduce

1. Open this [codesandbox](https://codesandbox.io/s/issue-001-3mqi29)
2. Fork and add your testnet credentials in .env file
3. Run example to get the error (ContractCreateFlow() line 37 of index.js)

### Hedera network

testnet

### Version

v2.14.2

### Operating system

macOS

**Comment by ed-marquez** [comment]
+1 on this issue. Basically, the reasoning that `ContractCreateFlow()` is not a transaction and can't support `.freezeWith()` means that users cannot directly create contracts that have an admin key using `ContractCreateFlow`. 

The admin key for a contract must sign the creation operation. If `ContractCreateFlow()` doesn't have .freezeWith() or `.sign()`, that means we're forcing users of `ContractCreateFlow()` to change the operator to deploy contracts with admin keys.

**Comment by danielakhterov** [comment]
The addition of `freezeWith()` doesn't work here, but adding a `*Flow.sign[With|WithOperator]()` does make sense.
