### ISSUE TITLE
Matching requirements - NFT creation without supply key should error out

### ISSUE THREAD

**Issue by ed-marquez** [hashgraph/hedera-sdk-js#1191]
### Description

NFT collections (token IDs) on Hedera are **required to have an initial supply of zero**. The logic being that the user **mints the individual serial numbers under the NFT collection with the authorization (signature) of the supply key**. 

Today, it is possible to create an NFT collection without a supply key, which seems like a bad design... 
After checking with the Hedera team, there doesn't seem to be a valid use case for creating an NFT collection that can't have serials numbers added. 

**The creation of a token of type NFT without supply key should result in an error for the user.**
Leemon also suggested that this should be an error.
That would be a better design that aligns with the requirements listed in the first paragraph.

### Steps to reproduce

In the code below, the user doesn't find out that the tokenId doesn't have a supply key until they try to mint new NFTs. So , they're now stuck with an NFT collection that is empty forever, does not have use, and can't be deleted (if no admin key).

	let nftCreateTx = await new TokenCreateTransaction()
		.setTokenName("Fall Collection")
		.setTokenSymbol("LEAF")
		.setTokenType(TokenType.NonFungibleUnique)
		.setSupplyType(TokenSupplyType.Finite)
		.setDecimals(0)
		.setInitialSupply(0)
		.setMaxSupply(5)
		.setTreasuryAccountId(client.operatorAccountId)
		// .setSupplyKey(client.operatorPublicKey)
		// .setTokenMemo("my Non-fungible token using NFT Storage.")
		.freezeWith(client);
	let nftCreateSubmit = await nftCreateTx.execute(client);
	let nftCreateRx = await nftCreateSubmit.getReceipt(client);
	let tokenId = nftCreateRx.tokenId;

let tokenMintTx = new TokenMintTransaction()
			.setTokenId(tokenId)
			.setMetadata([Buffer.from(metadataURI)])
			.freezeWith(client);
		let tokenMintSubmit = await tokenMintTx.execute(client);
		let tokenMintRx = await tokenMintSubmit.getReceipt(client);

### Hedera network

mainnet

### Version

v2.17

### Operating system

Windows

**Comment by mehcode** [comment]
I would think that errors should be introduced at the network level. 

We've historically never errored at the client level for an operation that would succeed at the network level. If we want to do this here, there would be a high barrier to merge given the precedent.

**Comment by SimiHunjan** [comment]
cc: @tinker-michaelj @Neeharika-Sompalli

**Comment by Neeharika-Sompalli** [comment]
> cc: @tinker-michaelj @Neeharika-Sompalli

Opened [this](https://github.com/hashgraph/hedera-services/issues/3698) issue on services

**Comment by danielakhterov** [comment]
Closing this issue as it's been moved into services.
