### ISSUE TITLE
Hou could I get accountID list from publickey?

### ISSUE THREAD

**Issue by lijixy** [hashgraph/hedera-sdk-js#1195]
### Description

When I generate a privateKey and create a new accountID, but how could I get the accountID which has created?

### Steps to reproduce

1、generate a private
2、create a new accountID

### Hedera network

mainnet

### Version

v1.0.0

**Comment by danielakhterov** [comment]
I'm not really sure what you mean. When you say "create a new account ID", what exactly did you do? Did you submit an `AccountCreateTransaction` or did you do `privateKey.publicKey.toAccountId(0, 0)`?

**Comment by lijixy** [comment]
AccountCreateTransaction

**Comment by danielakhterov** [comment]
Ah, once you create an account using `AccountCreateTransaction` you should fetch the receipt using `getReceipt()`. We have an example that uses a `Wallet`, but the code would be very similar if you're using `Client` directly. https://github.com/hashgraph/hedera-sdk-js/blob/main/examples/create-account.js 
Hope that helps. If you're still having trouble please post a code snippet on what you've been doing so far.
