### ISSUE TITLE
AccountAllowanceApproveTransaction() sucessful, but getting SPENDER_DOES_NOT_HAVE_ALLOWANCE

### ISSUE THREAD

**Issue by ed-marquez** [hashgraph/hedera-sdk-js#1202]
### Description

After successfully setting an AccountAllowanceApproveTransaction(), when it's time to perform the transfer, I get the error SPENDER_DOES_NOT_HAVE_ALLOWANCE.

A user also reported this issue on Discord (https://discord.com/channels/373889138199494658/768621337865486347/998722341372698694). I tried following the examples on documentation and GitHub examples for the allowance transfer, but still not getting the expected result. 

Started investigating this because a user was having difficulties with allowance via precompiles for a fungible token. 
I'm trying just HBAR with the SDK for simplification.

See repro step for details... 

Not sure if I'm coding the allowance and/or approvedHbarTransfer incorrectly, or if there's a different issue here. 
It's possible that we may need to get more specific with documentation, but looking forward to your response. 

@SimiHunjan @danielakhterov 

Mirror node query for the owner account shows the allowance:
https://testnet.mirrornode.hedera.com/api/v1/accounts/0.0.2917624/allowances/crypto
An AccountInfoQuery for the same account via the SDK does not show the allowance information. Will create a separate issue.

### Steps to reproduce

- Go to:
https://codesandbox.io/s/hedera-example-contract-allowance-sdk2-onzzik?file=/index.js:5209-5219

- Open new terminal and run: node index.js

- See error SPENDER_DOES_NOT_HAVE_ALLOWANCE

- See lines 109 and 126 - where the allowance and transfer are being done.

### Hedera network

testnet

### Version

v2.17

### Operating system

Windows

**Comment by bugbytesinc** [comment]
Line 130 might be the issue, do you need to add the "spender" flag on the receiving account?

**Comment by danielakhterov** [comment]
@ed-marquez I'm not really what is the issue with your code to be honest. It seems like it should work and we do have some unit tests that confirm we're setting the `approved` flag. https://github.com/hashgraph/hedera-sdk-js/blob/52423d4a71c783e33fa9e35412f328a92589e630/test/unit/TransferTransaction.js#L180 https://github.com/hashgraph/hedera-sdk-js/blob/52423d4a71c783e33fa9e35412f328a92589e630/test/unit/TransferTransaction.js#L202

**Comment by ed-marquez** [comment]
@danielakhterov thanks for looking into it. Could you please take a quick look at the code for `AccountAllowanceApproveTransaction()`? 
That transaction is successful. However, I went back and did account info queries for treasury (owner) and alice (spender) after setting the allowance, expecting that at least one should come back with info on hbar allowances.  
**Both queries come back with no info on hbar allowances, which tells me this module may not be working as expected**

**Comment by hashaxis** [comment]
Just wanted to add that we are experiencing the same issue with non-fungible token allowance transfers. (Also struggling to remove allowances once set; but may be unrelated.)

**Comment by ed-marquez** [comment]
@danielakhterov @SimiHunjan @hashaxis 

Found the issue and a workaround!

Daniel, I believe the SDK is requiring the spender to pay for the transaction fee. So if there's a different client paying for that fee, that transaction errors out with SPENDER_DOES_NOT_HAVE_ALLOWANCE

As you mentioned, the code I had shared before in the code sandbox (https://codesandbox.io/s/hedera-example-contract-allowance-sdk2-onzzik?file=/index.js) was correct. 

- I simply changed the client operator to be the spender in line 132, which should not be required: client.setOperator(aliceId, aliceyKey);
- and now the allowance transfer goes through
- see updated code for reference

**Comment by danielakhterov** [comment]
@ed-marquez @hashaxis Re: `AccountInfo.*allowances` being empty https://github.com/hashgraph/hedera-sdk-js/issues/1211 

> Daniel, I believe the SDK is requiring the spender to pay for the transaction fee - which shouldn't happen.
So if there's a different client paying for that tx fee, that transaction errors out with SPENDER_DOES_NOT_HAVE_ALLOWANCE

The thing is the SDK doesn't require anything here. The SDK simply serializes the data into a protobuf and sends it over to the services which is why I linked the serialization test above.

**Comment by danielakhterov** [comment]
Closing as this doesn't seem to be an SDK issue.
