### ISSUE TITLE
Receipt for ContractCreateFlow() returns an empty fileID field

### ISSUE THREAD

**Issue by ed-marquez** [hashgraph/hedera-sdk-js#1210]
### Description

A receipt for ContractCreateFlow should return information about the contract ID and file ID.
Contract ID works well. File ID does not, as it returns null. 

I do understand that ContractCreateFlow deletes the file, but the ID should be captured and made available to the user.

### Steps to reproduce

- See line 70 in index.js of this codesanbox https://codesandbox.io/s/hedera-example-contract-allowance-sdk2-onzzik?file=/index.js
- node index.js
- See null file ID

Code below for convenience.

const contractCreateTx = new ContractCreateFlow()
		.setBytecode(bytecode)
		.setAdminKey(operatorKey)
		.setGas(3000000);
	const contractCreateSubmit = await contractCreateTx.execute(client);
	const contractCreateRx = await contractCreateSubmit.getReceipt(client);
	const fileId = contractCreateRx.fileId;
	const contractId = contractCreateRx.contractId;
	const contractAddress = contractId.toSolidityAddress();
	console.log(`- The file ID is: ${fileId}`);
	console.log(`- The smart contract ID is: ${contractId}`);
	console.log(`- The smart contract ID in Solidity format is: ${contractAddress} \n`);

### Additional context
<img width="361" alt="bug" src="https://user-images.githubusercontent.com/72571340/181768562-c993048b-d8d0-4960-95fc-30cbfbb28d1d.png">

### Hedera network

testnet

### Version

v2.17

### Operating system

Windows

**Comment by mehcode** [comment]
Can you explain the use case for knowing the (deleted) file ID that was used? Know that if your bytecode is less than 6k, a file shouldn't be used to create the contract (this is a newer feature Hedera added to the ContractCreateTransaction).

**Comment by danielakhterov** [comment]
Closing since as of right now I don't see why the `fileId` should be returned in the receipt, and it'd also make me a bit concerned if the SDK were to change the receipt that is being returned.
