### ISSUE TITLE
FileAppend default chunk size is too small

### ISSUE THREAD

**Issue by gregscullard** [hashgraph/hedera-sdk-js#1212]
The current default size (2.17.0) is 2048, a transaction can be up to 6144 bytes in size, the chunk size can probably be increased to 4096 without issues. This would reduce the number of transactions needed to upload larger contract files.

**Comment by danielakhterov** [comment]
You're right, and I thought we already fixed this some time ago since Java defaults to 4096 bytes. Nonetheless, will fix.
