### ISSUE TITLE
Add code coverage 

### ISSUE THREAD

**Issue by SimiHunjan** [hashgraph/hedera-sdk-js#1219]
### Problem

A code coverage tool will help identify where tests need to be added in the code.

### Solution

Add code coverage tool

**Comment by danielakhterov** [comment]
Fixed by #1236 1236

**Comment by danielakhterov** [comment]
Re-opening to fix https://github.com/hashgraph/hedera-sdk-java/pull/1071#issuecomment-1215674608 but in JS

**Comment by danielakhterov** [comment]
Seems to already be fixed considering other PRs contain codecov reports.
