### ISSUE TITLE
passing a string to File[Create, Update]Transaction.setContents() won't do what the user expects

### ISSUE THREAD

**Issue by abonander** [hashgraph/hedera-sdk-js#122]
This passes it straight to the proto `setContents()` method which is expecting the string to be Base64 binary-encoded data (all `bytes` setters in JS have this overload which gives support on platforms without `Uint8Array`).

We should instead encode the string as UTF-8 or not allow passing strings.

**Comment by mehcode** [comment]
Going from UTF-8 string data to a byte array requires text encoding which is surprisingly not well supported in JavaScript. 

Until someone needs this and asks in the future, I'm just removing it for now.
