### ISSUE TITLE
`pauseKey` does not update with `TokenUpdateTransaction` because its missing from `_makeTransactionData`

### ISSUE THREAD

**Issue by mgarbs** [hashgraph/hedera-sdk-js#1221]
### Description

Sent `TokenUpdateTransaction` with `setPauseKey` to a newly created token. The tx was `SUCCESSFUL` but the `pauseKey` kept the old value and did not update as expected.

### Steps to reproduce

<img width="1032" alt="image" src="https://user-images.githubusercontent.com/101222532/182413793-6eac6a7d-3ccd-4025-9633-b60b33ea1116.png">

Looking at the SDK, the `pauseKey` is missing from `_makeTransactionData` [here](https://github.com/hashgraph/hedera-sdk-js/blob/main/src/token/TokenUpdateTransaction.js#L653)

### Hedera network

testnet

### Version

v2.17.1

### Operating system

macOS

**Comment by Topachi** [comment]
Bug discovered by HbarSuite Team

**Comment by mgarbs** [comment]
> Bug discovered by HbarSuite Team
That's correct. This bug was posted by @Topachi in the Hedera Discord. I confirmed/recorded the behavior and logged the issue. Thanks
