### ISSUE TITLE
Remove calculating time drift

### ISSUE THREAD

**Issue by danielakhterov** [hashgraph/hedera-sdk-js#1223]
### Problem

Calculating time drift in the SDK has lead to numerous issues. Although I do like the feature, it is problematic.

### Solution

Remove calculating the time drift ourselves, but expose a way for users to set the time drift value. Also provide an example.

**Comment by gregscullard** [comment]
is this timedrift calculation the automatic removal of a few seconds from system time in the transactionId's valid start ?

Would removing this not be a breaking change meaning all developers would have to update their setup to set the value as you suggest ? 
Existing code could stop working as a result no ?

**Comment by danielakhterov** [comment]
> Did this replace the removal of a few seconds from the transaction's valid_start_time ?

Yes

> If this the case, will that be re-instated ?

This is also correct, but hopefully the provided example will make this easier.

Unfortunately we do need to remove this code because
> Hey team, we've had a report that [this grpc-web endpoint in the JS SDK](https://github.com/hashgraph/hedera-sdk-js/blob/main/src/sync.js#L9-L13) is being flagged as malicious by Google, which is preventing a marketplace from listing ads with Google. Will CC you in Slack discussion.

**Comment by gregscullard** [comment]
I'm ok with removing the problematic code, not with setting the drift to 0 by default since it was approx 8s + random in the past, that should remain.
If you want to enable users to override, I'm fine with it, but let's keep the default where it was please.
The random nanos were also there to reduce the likelihood of duplicate transactions resulting from the same accountId creating many transactions in the same millisecond.

**Comment by danielakhterov** [comment]
> I'm ok with removing the problematic code, not with setting the drift to 0 by default since it was approx 8s + random in the past, that should remain.

Oh, sorry I should clarify this time drift code is unrelated to the time gitter. The gitter is still there. The time drift code was strictly to calculate the actual time drift of the users PC.
