### ISSUE TITLE
Fix `Query.[queryPayment|maxQueryPayment]` and `Client.maxQueryPayment` interactions

### ISSUE THREAD

**Issue by danielakhterov** [hashgraph/hedera-sdk-js#1230]
The current interactions of the aforementioned fields are a bit obscure and confusing. We should clean up the code around that and make sure we adequately test it so it's easier to understand.

**Comment by Kalina-Todorova** [comment]
Hi @danielakhterov we have a use-case in the relay while integrating with The Graph which is described here: https://github.com/hashgraph/hedera-json-rpc-relay/issues/437 It seems related to the change you are doing here, but for a more specific case, what is your take on the sdk being able configure how much to pay for contract local call?

**Comment by danielakhterov** [comment]
Hey, @Kalina-Todorova the SDK should definitely support configuring the payment amount for any query, and the fact that it was overwriting the value was an unfortunate bug. However, specifically in regards to `ContractCallQuery`, what is a bit disappointing is that this is the only query where the result of `ContractCallQuery.getCost()` does not guarantee success on `execute`. In our examples, we've had to add an explicit `setQueryPayment()` to get around this https://github.com/hashgraph/hedera-sdk-js/blob/2fdda753ffb231142443c0b11a248c84e69633ad/examples/create-stateful-contract.js#L96 unlike for any other query. An option I think _may_ work, but I don't know how to nicely implement it is supporting a way to tell the SDK to use N * `*Query.getCost()` as the payment. So if the consensus node returns 2 Hbar for the cost of a query and N is 1.1, we would actually use 2.2 Hbar instead of 2 Hbar; increasing the likeliness a query will succeed.

Also, after reading the issue I see the error message is backwards :facepalm: Will fix
