### ISSUE TITLE
Mnemonic inconsistency with Java and Go

### ISSUE THREAD

**Issue by izik1** [hashgraph/hedera-sdk-js#1242]
### Description

In Java and Go, when you call `PrivateKey.fromMnemonic(mnemonic, "secret sauce")` with a legacy mnemonic it will _succeed_, but on JS it fails.

However, if you call `mnemonic.toPrivateKey("secret sauce")` with that _same_ `mnemonic` it will fail in all SDKs.

This inconsistency indicates either a bug in _this_ SDK, or a bug in _those_ SDKs.

Another way to interpret this, is that in this SDK `PrivateKey.fromMnemonic` and `mnemonic.toPrivateKey` are the same, but in the other SDKs they aren't. Theoretically, that means in other SDKs legacy mnemonics _can_ use the "not legacy" conversion/derivation, but in JS they can't. That may or may not be desired.

### Steps to reproduce

(source code)

### Additional context

N/A

### Hedera network

other

### Version

main (e16f9100de2a7c683b3c39871a3bcf46d72f3b87)

**Comment by ochikov** [comment]
We are going to investigate it and sync with JAVA & GO Team.

**Comment by petreze** [comment]
@izik1 
Hey, as documented, both `PrivateKey.fromMnemonic()` and `Mnemonic.toPrivateKey()` are deprecated
There are several ways of achieving the same wanted results:

`Mnemonic.from[Words/String]().to[Ed25519/Ecdsa]PrivateKey()`

**Comment by ochikov** [comment]
@izik1 Can you please confirm the above comment? 
Also keep in mind this issue: #1350  which we are currently working on.

**Comment by ochikov** [comment]
@izik1 I am closing this issue.
