### ISSUE TITLE
PublicKey.equals incorrect result

### ISSUE THREAD

**Issue by rokn** [hashgraph/hedera-sdk-js#1245]
### Description

The PublicKey.equals method seems to not be working correctly. When called on keys that are the same it returns false.

### Steps to reproduce

```js
import {PrivateKey, PublicKey} from "@hashgraph/sdk";

const original = PrivateKey.generate().publicKey;

const copy = PublicKey.fromString(original.toStringRaw());

console.log(original.toStringRaw());
console.log(copy.toStringRaw());

console.log(original.equals(copy));
```
This seems to reproduce it. It should print `true`.

### Additional context

I suspect it's because in this method:
```js
  equals(other) {
    if (this._key instanceof _Ed25519PublicKey.default && other instanceof _Ed25519PublicKey.default) {
      return this._key.equals(other);
    } else if (this._key instanceof _EcdsaPublicKey.default && other instanceof _EcdsaPublicKey.default) {
      return this._key.equals(other);
    } else {
      return false;
    }
  }
```
`other` is used instead of `other._key`

### Hedera network

mainnet, testnet, previewnet

### Version

2.18.0

### Operating system

macOS

**Comment by danielakhterov** [comment]
Heh, that's a silly mistake. Thanks for looking into it, the PR linked above I believe fixed this issue. I added a regression test as well https://github.com/hashgraph/hedera-sdk-js/pull/1249/files#diff-f5f2987f068e348b7b58c33cc13c78101edbcc962611a05cb5f02380f228b3c9R28
