### ISSUE TITLE
Cannot run due to token error in NodeChannel.cjs

### ISSUE THREAD

**Issue by galipmedia** [hashgraph/hedera-sdk-js#1247]
### Description

... node_modules/@hashgraph/sdk/lib/channel/NodeChannel.cjs:112
      }, 10_000);
         ^^
SyntaxError: Invalid or unexpected token

It works if I change that to 10000.

### Steps to reproduce

run: node index

### Hedera network

mainnet

### Version

v2.18.0

### Operating system

Linux

**Comment by mehcode** [comment]
Please use the latest patch release of Node 12. I believe this was added in Node 12.5.
