### ISSUE TITLE
Error "Error: (BUG) unexpectedly received no response" is not able to be caught.

### ISSUE THREAD

**Issue by Sheng-Long** [hashgraph/hedera-sdk-js#1252]
### Description

When this error occurs, it does not seem to be possible to catch it:

```
Uncaught (in promise) Error: (BUG) unexpectedly received no response
    at decodeUnaryResponse (Channel.js:312:15)
    at e2.rpcImpl (WebChannel.js:68:35)
```

### Steps to reproduce

Intermittent issue.  Occurs on mainnet most frequently.  The best way I've found to reproduce it is to get a new transactionId from an explorer and run the following code:
```
    await new TransactionReceiptQuery()
      .setTransactionId(txId)
      .execute(client);
  ```
  until it occurs.

### Hedera network

mainnet

### Version

v2.17.1

### Operating system

macOS

**Comment by SimiHunjan** [comment]
@danielakhterov please review

**Comment by danielakhterov** [comment]
@Sheng-Long I'm having a real hard time reproducing this error. I created a draft PR to illustrate my testing, and I was able to catch this particular error. 
![image](https://user-images.githubusercontent.com/36461294/190259362-b061d53f-018b-4c21-ae6f-67ca97322384.png)

**Comment by danielakhterov** [comment]
I believe we've resolved this issue, but created another issue for a separate problem: #1266
