### ISSUE TITLE
Signer / LocalProvider not working as expected with ContractCreateFlow()

### ISSUE THREAD

**Issue by ed-marquez** [hashgraph/hedera-sdk-js#1256]
### Description

See repro steps

### Steps to reproduce

- "@hashgraph/sdk": "2.18"
- The code in the section below returns the error:

```
@hashgraph/sdk/src/transaction/TransactionReceiptQuery.js:126  
                : transactionId.clone();
TypeError: Cannot read properties of undefined (reading 'clone') at TransactionReceiptQuery.setTransactionId 
```

### Additional context

```
const myWallet = new Wallet(operatorId, operatorKey, new LocalProvider());

const bytecode = fs.readFileSync("./binaries/TokenCreateContract_sol_TokenCreator.bin");
const gasLimit = 100000;
const [contractId, contractAddress] = await contractDeployFcn(bytecode, gasLimit, myWallet);

async function contractDeployFcn(bytecode, gasLim, wallet) {
	// Create the smart contract
	const contractCreateTx = new ContractCreateFlow()
		.setBytecode(bytecode)
		.setGas(gasLim)
		.executeWithSigner(wallet);
	// const contractInstantiateSubmit = await contractInstantiateTx.executeWithSigner(wallet);
	// const contractCreateRx = await contractCreateTx.getReceiptWithSigner(wallet);
	const contractCreateRx = await wallet.getProvider().waitForReceipt(contractCreateTx);
	const contractId = contractCreateRx.contractId;
	const contractAddress = contractId.toSolidityAddress();

	return [contractId, contractAddress];
}
```

### Hedera network

testnet

### Version

2.18

### Operating system

Windows

**Comment by ed-marquez** [comment]
based on the response to the previous issue, it's possible that the missing `await` for `ContractCreateFlow` is introducing the error. 
If that's the case, 
- a more specific error may help
- the issue can be closed

**Comment by danielakhterov** [comment]
@ed-marquez which line of code threw that error? This error feels familiar, but I don't recall where I saw it :(

**Comment by ed-marquez** [comment]
Hi @danielakhterov - for repro: https://edmarquez-hederaexample-0apt3fxfhpi.ws-us65.gitpod.io/

It's thrown at this line:
`const contractCreateRx = await wallet.getProvider().waitForReceipt(contractCreateTx);`

If I add await to the `ContractCreateFlow` line, then the error pops up:
`Error: transactionId must be set or client must be provided with freezeWith`

**Comment by danielakhterov** [comment]
@ed-marquez I was able to reproduce :partying_face: and hence was able to quickly fix it in the PR above. Still need to add some automated form of testing for this feature before we merge, but a fix is _there_ that manually worked after updating `examples/create-simple-contract.js`

**Comment by ed-marquez** [comment]
Awesome. Great to hear and thank you for looking into this, Daniel!
