### ISSUE TITLE
.executeWithSigner() not present for ContractExecuteTransaction()

### ISSUE THREAD

**Issue by ed-marquez** [hashgraph/hedera-sdk-js#1257]
### Description

	const contractExecTx = new ContractExecuteTransaction()
		.setContractId(contractId)
		.setGas(gasLim)
		.setPayableAmount(payableAmt)
		.setFunction(fcnName, paramsObj)
		.freezeWithSigner(wallet);
	const contractExecSubmit = await contractExecTx.executeWithSigner(wallet);

Results in `TypeError: contractExecTx.executeWithSigner is not a function`

Note that this transaction does not need to be signed and is working as expected when using `Client`

### Steps to reproduce

-"@hashgraph/sdk": "2.18",
- See code in the next section. Generates the error below:

```
const contractExecSubmit = await contractExecTx.executeWithSigner(wallet);         
TypeError: contractExecTx.executeWithSigner is not a function
```

### Additional context

```
const myWallet = new Wallet(operatorId, operatorKey, new LocalProvider());
async function main() {

	//Execute a contract function
	const gasLimHi = 4000000;
	const payAmt = new Hbar(90);
	const fcnName = "createNonFungible";
	const fcnParams = new ContractFunctionParameters()
		.addString("myToken")
		.addString("MTK")
		.addString("No Memo")
		.addUint32(250)
		.addUint32(7700000);
	const rec = await contractExecuteFcn(contractId, gasLimHi, payAmt, fcnName, fcnParams, myWallet);
}

async function contractExecuteFcn(contractId, gasLim, payableAmt, fcnName, paramsObj, wallet) {
	//Execute a contract function (create NFT)
	const contractExecTx = new ContractExecuteTransaction()
		.setContractId(contractId)
		.setGas(gasLim)
		.setPayableAmount(payableAmt)
		.setFunction(fcnName, paramsObj)
		.freezeWithSigner(wallet);
	const contractExecSubmit = await contractExecTx.executeWithSigner(wallet);
	// const contractExecRec = await contractExecSubmit.getRecordWithSigner(wallet);

	// return contractExecRec;
	return 1;
}

```

### Hedera network

testnet

### Version

2.18

### Operating system

Windows

**Comment by danielakhterov** [comment]
`freezeWithSigner()` returns a promise, so you must `await` it before calling `executeWithSigner` which does exist: https://github.com/hashgraph/hedera-sdk-js/blob/cae04e57bdffc2dedff1f3b05aefe32d5c32e8a1/src/Executable.js#L482

**Comment by ed-marquez** [comment]
Hey @danielakhterov - just for clarity, the line
	`const contractExecTx = new ContractExecuteTransaction()`
does not require `await` and as you mention, it returns a promise.

The line  
	`const contractExecSubmit = await contractExecTx.executeWithSigner(wallet);`
does include `await` as suggested, but the error still occurs. 

Does the `Executable.js` src file you linked apply `.executeWithSigner` even to the `ContractExecuteTransaction` class? 
I know it applies for other classes I've tried before, but odd that the error occur when executing a contract function.

**Comment by danielakhterov** [comment]
`Executable` applies to all transactions and queries, but does not apply to flows. `new ContractExecuteTransaction` does not require an `await`, but what you have above has a `new ContractExecuteTransaction()...freezeWithSigner()`, that last call `freezeWithSigner()` returns a promise and hence must be awaited before you can call `executeWithSigner()` on it. Hope that clears it up.
