### ISSUE TITLE
Providing a .getReceiptWithSigner() and .getRecordWithSigner() for execution objects

### ISSUE THREAD

**Issue by ed-marquez** [hashgraph/hedera-sdk-js#1258]
### Problem

When working with `Signer`/`Provider` instead of `Client`, users have to obtain a transaction receipt through the `Provider`, like: 

`const contractCreateRx = await wallet.getProvider().waitForReceipt(contractCreateTx);` OR
`const contractCreateRx = await wallet.getProvider().getTransactionReceipt(contractCreateTx);`

This is an unfamiliar process for existing users that have been using `Client`, and for new users it would be confusing having a lack of consistency in the experience using Client vs Signer/Provider.

### Solution

For new users and existing users coming from using `Client`, it would be a much more intuitive and simple experience to have the methods propose, so that transaction confirmations can be obtained in a similar way, as in:
```
const contractCreateRx = await contractCreateTx.getReceiptWithSigner(wallet);
const contractCreateRec = await contractCreateTx.getRecordWithSigner(wallet);
```

Also if a user starts developing their application with Client, and then needs to update to signer/provider, this would make that migration much easier for developers and the styles would be very similar.

**Comment by danielakhterov** [comment]
We already have this, but it exists on `TransactionResponse` not `Transaction` (same as `getReceipt`), and we use it in _some_ of our examples: https://github.com/hashgraph/hedera-sdk-js/blob/d7de9d4877c8ff06a429f5d2735a306f50bbf0b7/examples/account-alias.js#L94
