### ISSUE TITLE
Typo inside Wallet class

### ISSUE THREAD

**Issue by JulissaDantes** [hashgraph/hedera-sdk-js#1259]
### Description

The message parameter for the signer has an extra 's', [see this line](https://github.com/hashgraph/hedera-sdk-js/blob/ea0bd993ed1dd6440f79889aaf509e7d278ad358/src/Wallet.js#L72). More instances of the typo [here.](https://github.com/hashgraph/hedera-sdk-js/search?q=messasge)

### Steps to reproduce

Check the code

### Hedera network

testnet

### Version

current

### Operating system

macOS

**Comment by danielakhterov** [comment]
Haha, thanks for pointing this out, seems like I've made this mistake more than once :laughing:   Anyways, fixed with a quick commit to `main`: https://github.com/hashgraph/hedera-sdk-js/commit/cae04e57bdffc2dedff1f3b05aefe32d5c32e8a1
