### ISSUE TITLE
[question] support for custom key types

### ISSUE THREAD

**Issue by Cooper-Kunz** [hashgraph/hedera-sdk-js#126]
Does this SDK support [threshold](https://docs.hedera.com/docs/keys-and-signatures) or other key schemas yet? 

If so, can I get an example of how to use? If not, any ideas on when that may be added?

**Comment by mehcode** [comment]
@Cooper-Kunz Should be the same API from the Java SDK.

https://github.com/hashgraph/hedera-sdk-java/blob/master/examples/src/main/java/com/hedera/hashgraph/sdk/examples/advanced/CreateAccountThresholdKey.java#L55

An example in JavaScript:

```js
const key = new ThresholdKey(2);
key.add(publicKeyOne);
key.add(new KeyList().addAll(keyA, keyB, keyC));
key.add(publicKeyTwo);
```

**Comment by Cooper-Kunz** [comment]
Thanks for this @mehcode!

I've tested out the following and it seems to be working 🎊  

---

**Create Account with Threshold Key**

```
require("dotenv").config();

const {
  Client,
  Ed25519PrivateKey,
  AccountCreateTransaction,
  ThresholdKey
} = require("@hashgraph/sdk");

async function main() {
  const operatorPrivateKey = process.env.OPERATOR_KEY;
  const operatorAccount = process.env.OPERATOR_ID;

  if (operatorPrivateKey == null || operatorAccount == null) {
    throw new Error(
      "environment variables OPERATOR_KEY and OPERATOR_ID must be present"
    );
  }

  const client = new Client({
    network: { "0.testnet.hedera.com:50211": "0.0.3" },
    operator: {
      account: operatorAccount,
      privateKey: operatorPrivateKey
    }
  });

  const privateKeyList = [];
  const publicKeyList = [];
  await generateKeys(privateKeyList, publicKeyList, 4);
  const thresholdKey = await createThresholdKey(3, publicKeyList);
  const newAccountTransaction = await buildNewAccountTx(thresholdKey, 100, client);
  console.log(await newAccountTransaction.execute(client));
}

async function generateKeys(priv, pub, size) {
  for (var i = 0; i < size; i++) {
    var privateKey = await Ed25519PrivateKey.generate();
    var publicKey = privateKey.publicKey;
    priv.push(privateKey);
    pub.push(publicKey);
  }
}

async function createThresholdKey(sizeOfThreshold, keys) {
  const thresholdKey = new ThresholdKey(sizeOfThreshold);
  for (var i = 0; i < keys.length; i++) {
    thresholdKey.add(keys[i]);
  }
  return thresholdKey;
}

async function buildNewAccountTx(key, initialBalance, operator) {
  const accountCreateTransaction = new AccountCreateTransaction()
    .setKey(key)
    .setInitialBalance(initialBalance)
    .build(operator);
  return accountCreateTransaction;
}

main();
```

Transaction confirmation - https://testnet.dragonglass.me/hedera/transactions/0012491577149684263000000

---

**Testing a CryptoTransfer with Threshold Key**

```
require("dotenv").config();

const {
  Client,
  CryptoTransferTransaction,
  Ed25519PrivateKey
} = require("@hashgraph/sdk");

async function main() {
  const operatorPrivateKey = process.env.THRESHOLD_KEY_ONE;
  const operatorAccount = process.env.THRESHOLD_ID;

  if (operatorPrivateKey == null || operatorAccount == null) {
    throw new Error(
      "environment variables OPERATOR_KEY (THRESHOLD_KEY_ONE) and OPERATOR_ID must be present"
    );
  }

  const client = new Client({
    network: { "0.testnet.hedera.com:50211": "0.0.3" },
    operator: {
      account: operatorAccount,
      privateKey: operatorPrivateKey
    }
  });

  // there must be a transaction built, before it can be signed
  const transaction = new CryptoTransferTransaction()
    .addSender(operatorAccount, 0)
    .addRecipient("0.0.1249", 0)
    .setMemo("testing threshold account")
    .build(client); // implicitly signs from operator, i.e. process.env.THRESHOLD_KEY_ONE

  // Grab another of our threshold keys
  const threshold2 = await Ed25519PrivateKey.fromString(
    process.env.THRESHOLD_KEY_TWO
  );

  // this account is a 2 of 3 threshold key,
  // we can sign with this explicitly, and the other signature is the operator
  transaction.sign(threshold2);

  console.log(await transaction.execute(client));
}

main();
```

Transaction confirmation - 
https://testnet.dragonglass.me/hedera/transactions/001404601577154745603000000

---

Do you mind if I submit a pull request including an example like the above?

I can also include updated or new examples for other issues I've created, i.e. #103, #105, #125,

**Comment by mehcode** [comment]
More examples are definitely good.

---
```
    .build(client); // implicitly signs from operator, i.e. process.env.THRESHOLD_KEY_ONE
```

This is a great time to ask @Cooper-Kunz - Does this behavior make sense? We've been discussing it among ourselves. I'm in favor of removing it as it feels odd. If you are explicitly building, that means you should expect explicit signing.

**Comment by Cooper-Kunz** [comment]
Great, @mehcode - I'll open an issue outlining the scope, or to ask any questions I might have.

--- 

Wrt to implicit signing from the client who builds the tx - 

In the example I ran above, I have a 2:3 threshold key. The first time I attempted to sign with keys 2 & 3, with key 1 as the operator. I'm sure this is a strange scenario to exist in the wild, but unexpectedly this resulted in all 3 keys signing the transaction, and so I'd agree it's odd behavior. 

What is being proposed as the alternative(s)?

**Comment by mehcode** [comment]
@Cooper-Kunz The alternative would be just

```js
// [...]
  .build(client)
  .sign(operatorKey)
  .sign(key2)
  .execute(client) // implicitly signs with operatorKey if not already
```

instead of

```js

// [...]
  .build(client) // implicitly signs with operatorKey
  .sign(key2)
  .execute(client)
```

Note that implicit signature of operator would not go away, it would just move to `.execute`. Further, if you want "full" control you can just not set the operator on the client ( which would require you to make and set your own transaction IDs and sign everything manually ).

**Comment by Cooper-Kunz** [comment]
Hmm. Your concern doesn't seem resolved if `.execute(client)` implicitly signs the tx too, right?

> If you are explicitly building, that means you should expect explicit signing.

Plus the example outlined still seems like it'd result in my scenario's unexpected behavior. 
Are there any other options being considered?  Potentially `.build()` vs `.buildAndSign()`?

**Comment by mehcode** [comment]
Honestly I wanted the change mainly because signing with the operator is potentially asynchronous (due to hardware wallet support) so it has to be done in an async context and I don't want `.build` to return a Promise.

Signing with the operator should be idempotent and I can't imagine a scenario where you don't want to sign by the operator on execution.

However we are adding ( in the newest PR ) a variant of the constructor that allows you to omit the operator and thus any of the "magic" that comes from that ( automatic transaction IDs and implicit signatures ).
