### ISSUE TITLE
Deleting NFT allowance with AccountAllowanceDeleteTransaction() reports success, but the allowance remains available for the spender

### ISSUE THREAD

**Issue by ed-marquez** [hashgraph/hedera-sdk-js#1267]
### Description

Delegated transfer of NFT serial still goes through, despite the allowance being removed.

Accounts: Treasury, Alice, Bob. 

In this scenario, 
- Treasury give Alice an allowance for **all** NFT serials under a specific token ID
- Alice performs a delegated transfer (serial 5) from the Treasury to Bob
- The treasury removes the NFT allowance for Alice for serials 3 and 4
- **[BUG]** Alice is still able to send serial 4 to Bob, even after the allowance has been removed. 

### Steps to reproduce

1. Open the following GitPod: https://gitpod.io/#https://github.com/ed-marquez/hedera-example-allowances-sdk
2. Add a .env file with your own credentials
3. Open the file: `index_nft.js` and add the following code between lines 69 and 71:

```
console.log(`- Alice performing allowance transfer from Treasury to Bob...\n`);
nft2Send = new NftId(tokenId, 4);
const allowanceSendHbarRx1 = await transfers.nftAllowanceFcn(treasuryId, bobId, nft2Send, aliceId, aliceKey, client);
console.log(`- Allowance transfer status: ${allowanceSendHbarRx1.status} \n`);

await queries.balanceCheckerFcn(treasuryId, tokenId, client);
await queries.balanceCheckerFcn(aliceId, tokenId, client);
await queries.balanceCheckerFcn(bobId, tokenId, client);
```
4. Run  `index_nft.js` 
5. Notice how the delegated transfer of NFT serial 4 still goes through, despite the allowance being removed in line 68

### Hedera network

mainnet, testnet

### Version

2.18.1

### Operating system

Windows

**Comment by SimiHunjan** [comment]
Tagging to review @tinker-michaelj

**Comment by danielakhterov** [comment]
Closing as this doesn't seem to be a JS SDK issue, and instead seems to be a hedera-services issue.
