### ISSUE TITLE
HIP-573: Blanket exemptions for custom fee collectors

### ISSUE THREAD

**Issue by SimiHunjan** [hashgraph/hedera-sdk-js#1270]
### Problem

Add support for a [HIP-573](https://hips.hedera.com/hip/hip-573)
- [ ]  https://github.com/hashgraph/hedera-protobufs/pull/229

### Solution

Add support for a [HIP-573](https://hips.hedera.com/hip/hip-573)

**Comment by danielakhterov** [comment]
Resolved: https://github.com/hashgraph/hedera-sdk-js/commit/fe01ef0a54c8884f71577a5f3557ac2fad34244e
