### ISSUE TITLE
Implement `TransactionReceiptQuery.validateStatus` and `TransactionRecordQuery.validateReceiptStatus`

### ISSUE THREAD

**Issue by danielakhterov** [hashgraph/hedera-sdk-js#1273]
https://github.com/hashgraph/hedera-sdk-js/issues/1270

**Comment by Sean-Tedrow-LB** [comment]
This should actually be on `TransactionResponse`, not on `TransactionReceiptQuery` or `TransactionRecordQuery`

**Comment by danielakhterov** [comment]
Resolved: https://github.com/hashgraph/hedera-sdk-js/commit/65d98dd73ab3f691caefa5f6d99977ca27dfa62b
