### ISSUE TITLE
GrpcServiceError permanently renders a network node as unhealthy

### ISSUE THREAD

**Issue by Ivo-Yankov** [hashgraph/hedera-sdk-js#1275]
### Description

When a `GrpcServiceError: gRPC service failed with status: UNAVAILABLE` error is thrown, it permanently marks the network node as `unhealthy`.

The issue was discovered when testing for this [bug in the json-rpc-relay](https://github.com/hashgraph/hedera-json-rpc-relay/issues/533). 

### Steps to reproduce

- Start a local hedera node
- Initialise an sdk client and connect it to the local network
- Deploy the contract from the linked issue
- Execute `getLotsOfData` with `gasLimit = 15_000_000` and `count=1000`. The method should resolve normally.
- Execute it again, but with `count=20000`. The network node takes longer than 10s to execute the transaction and the SDK throws the following error: `GrpcServiceError: gRPC service failed with status: UNAVAILABLE`
- Now any further transactions initiated from the same sdk client instance will result in:
```
Error: failed to find a healthy working node
    at Network.getNode (.../@hashgraph/sdk/lib/client/ManagedNetwork.cjs:503:15)
    at CostQuery.execute (.../@hashgraph/sdk/lib/Executable.cjs:587:32)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async ContractByteCodeQuery._beforeExecute (.../@hashgraph/sdk/lib/query/Query.cjs:330:26)
    at async ContractByteCodeQuery.execute (.../@hashgraph/sdk/lib/Executable.cjs:549:5)
```

### Hedera network

other

### Version

v2.18.2

**Comment by ochikov** [comment]
Hello @Ivo-Yankov 
I was able to reproduce the issue. However, when I correct the input param of the function, my transaction is successful and I am not getting the error for the unhealthy node. 

For example, this is the response with input param (Uint24) 20000:
```
ognyanchikov@Ognyans-MacBook-Pro hello-hedera-js-sdk % node issue1275.js
- The bytecode file ID is: 0.0.1069 

Status of file append is SUCCESS
The smart contract ID is 0.0.1070
/Users/ognyanchikov/Projects/HEDERA_SDKs/hedera-sdk-js/lib/client/ManagedNetwork.cjs:503
        throw new Error("failed to find a healthy working node");
              ^

Error: failed to find a healthy working node
    at Network.getNode (/Users/ognyanchikov/Projects/HEDERA_SDKs/hedera-sdk-js/lib/client/ManagedNetwork.cjs:503:15)
    at ContractCallQuery.execute (/Users/ognyanchikov/Projects/HEDERA_SDKs/hedera-sdk-js/lib/Executable.cjs:586:32)
    at async main (/Users/ognyanchikov/Projects/hedera-js/hello-hedera-js-sdk/issue1275.js:127:23)
```

And then when I pass a smaller input number (Uint24) 1000:
```
ognyanchikov@Ognyans-MacBook-Pro hello-hedera-js-sdk % node issue1275.js
- The bytecode file ID is: 0.0.1071 

Status of file append is SUCCESS
The smart contract ID is 0.0.1072
Res3: 32
ognyanchikov@Ognyans-MacBook-Pro hello-hedera-js-sdk % 
```

So I am thinking about how I can handle it. Should I make the response time configurable, as per #1276? Or I can handle the error and make additional checks?

**Comment by Ivo-Yankov** [comment]
Hello @ochikov 
After the initial timeout error are you able to successfully send more transactions without creating a new instance of the sdk client?

When I last tested this issue in the json rpc relay after a single transaction timeout that made the whole relay unusable until it was restarted or a new sdk instance was created. I think that timeouts are sure to happen from time to time and that's normal. So changing the hardcoded value wouldn't neccessarily fix this issue.

**Comment by ochikov** [comment]
> Hello @ochikov After the initial timeout error are you able to successfully send more transactions without creating a new instance of the sdk client?
> 
> When I last tested this issue in the json rpc relay after a single transaction timeout that made the whole relay unusable until it was restarted or a new sdk instance was created. I think that timeouts are expected to happen from time to time, so changing the hardcoded value wouldn't necessarily fix this issue.

I need to test it with the same instance, because I use node and just execute the file with the logic, so every time I am calling the file, the new instance is created, that's why actually I can do it immediately after the error is thrown, but with the smaller number passed as input param.

**Comment by ochikov** [comment]
It's tested and the bug is not fixed. A new PR is prepared for fix.
