### ISSUE TITLE
TopicMessage does not expose the transactionId of the message

### ISSUE THREAD

**Issue by amandaluniz** [hashgraph/hedera-sdk-js#1277]
### Description

The `TopicMessage` object resulting from the `TopicMessageQuery` does not expose the transaction ID of the said message. The Java SDK has a transactionId property in it, whilst the JS SDK does not, it has a `initialTransactionId` but it comes as `undefined`

### Steps to reproduce

Using version `2.18.2` of the JS SDK listen for messages in any given topic.
```
new TopicMessageQuery()
      .setTopicId(topicId)
      .setStartTime(0)
      .subscribe(
        client,
        null,
        async (message: TopicMessage) => {
          logger.info(`Message received: ${message.initialTransactionId}`);
        }
      )
```

I would expect to be able to access the `transactionId` of every message, but there's no such property and the `initialTransactionId` is always undefined

### Hedera network

testnet

### Version

v2.18.2

**Comment by mehcode** [comment]
The transaction ID is _only_ set by the official hedera mirror node on the `TopicMessage` if you are sending a chunked message. Java calls this property `transactionId` and JS calls the property `initialTransactionId`. That's an inconsistency but from reviewing the code, both should work the same way.

I would recommend opening up an issue https://github.com/hashgraph/hedera-mirror-node to ask to _always_ pass the transaction ID back, even for non-chunked messages.
