### ISSUE TITLE
Make `words` in `Mnemonic` a publicly visible field

### ISSUE THREAD

**Issue by jackthta** [hashgraph/hedera-sdk-js#1288]
### Description

I used to be able to `Mnemonic.generate()` and access the mnemonic words directly like so ...
```
Mnemonic.generate().then((mnemonic) => {
  const mnemonicPhrase = mnemonic.words; // 👈
  // do stuff with `mnemonicPhrase`
})
```
... but it seems that the `words` property is now wrapped inside a `_mnemonic` property, so to have the above example work, I would have to do this:
```
Mnemonic.generate().then((mnemonic) => {
  const mnemonicPhrase = mnemonic._mnemonic.words; // 👈
  // do stuff with `mnemonicPhrase`
})
```
I don't think it's in best practice to access `_`-prefixed properties like that, so my temporary workaround has been to do ...
```
Mnemonic.generate().then((mnemonic) => {
  const mnemonicPhrase = mnemonic.toString().split(' '); // 👈
  // do stuff with `mnemonicPhrase`
})
```
... but that's pretty verbose and I think it would be very helpful and convenient to just be able to access the `words` property like in the first example.

### Steps to reproduce

1)
```
Mnemonic.generate().then((mnemonic) => {
  // follow steps #2 and #3 in here
})
```

2) Trying to access `mnemonic.words` shouldn't work.
3) Trying to see what's inside `mnemonic` via `console.log(mnemonic)` and there should be a `_mnemonic` property that contains the desired `words` property.

### Hedera network

mainnet

### Version

2.18.0

**Comment by ochikov** [comment]
Hello @jackthta,
You can get the mnemonic directly performing `toString()` on the returned mnemonic. For example:
```
mnemonic.toString()
```

Or here is the example with full implementation:
```
 const mnemonic = await Mnemonic.generate();
 console.log(`mnemonic = ${mnemonic.toString()}`);
```
There is also example located in `examples/generate-keys.js`

**Comment by Kalina-Todorova** [comment]
Hi @jackthta please try out the recommended example above and let us know if this works. Closing this issue for now.
