### ISSUE TITLE
Contract Create - timed out waiting for consensus on transaction ID

### ISSUE THREAD

**Issue by rahulasati** [hashgraph/hedera-sdk-js#131]
Hi,
i am using version **@hashgraph/sdk@0.8.0-beta.3**
getting following error while contract create 

**timed out waiting for consensus on transaction ID: 1577371342,655000000,,,17210**

Sample Code
let transactionId = await new ContractCreateTransaction()
        .setBytecodeFile(fileId)
        .setGas(10000000)
        .setAutoRenewPeriod(autoRenewPeriod)
        .setAdminkey(client._getOperatorKey())
        .setConstructorParams(encodedConstructorParams)
        .setInitialBalance(0)
        .setMemo('memo')
        .execute(client);

**Comment by mehcode** [comment]
@rahulasati Any chance you have a small smart contract you can share that reproduces this and the complete example code?

**Comment by mehcode** [comment]
Please re-open if you're still having the issue
