### ISSUE TITLE
No response after executing transaction

### ISSUE THREAD

**Issue by AdriMsM91** [hashgraph/hedera-sdk-js#1318]
### Description

Good morning,

Whenever we're executing a Transactions, sometimes we don't have any response for the next (**10-20min**) It keeps in executing and after **10-20 min**, we got this error `Error: max attempts of 10 was reached for request with last error being: TRANSACTION_EXPIRED`, so It means, the user will be Stuck without seeing any progress between 10-20min and after that he will receive an **ERROR MESSAGE**. 

After getting this error, we checked If the transaction was executed and It was executed **SUCCESFULLY** but we didn't receive any response about this.

 When we were at **v2.17.0** , we were getting `(Bug) unexpectedly received no response` , but since we upgrade to **v2.18.5** , we don't get the error anymore but instead we're getting many others.

First of all, we would like to understand from where is coming this error **(has something to do envoy server on it?**), since as we have following the traces is not anything related to our end. In Testnet, this never happens, we have made  over 100k operations consecutives as tests and we never got the error, but as soon as we test the same flow on Mainnet, we got the errors sometimes in the first 100 operations and other times in the operation number 800... so its totally ramdom.

Also another BUG we found is.... some times while we're executing the transactions we're receiving `max attempts of 10 was reached for request with last error being: BUSY` and other times we're receiving `Error: failed to find a healthy working node` 

At least these last errors are tractable, but in the case of the first ones, we can't do anything to recover from the error.

![image](https://user-images.githubusercontent.com/59306428/199472102-9d38a280-daae-4238-8df0-28a9410302ab.png)
![image](https://user-images.githubusercontent.com/59306428/199472165-ec68a369-68c2-444a-bb90-6571544851db.png)
The next error was happening in the same flow but in **v2.17.0**
![1](https://user-images.githubusercontent.com/59306428/199467814-7a80cfb2-0d3b-4c7c-be3b-c56cdf864dee.jpg)
![2](https://user-images.githubusercontent.com/59306428/199467844-379d2129-270b-453a-83ee-772a3eff4af6.jpg)

```js
    const txResponse = new TransferTransaction()
      .setMaxTransactionFee(new Hbar(maxFee))
      .addHbarTransfer(senderAccount, amount.negated()) 
      .addHbarTransfer(targetAccountId, amount); 
    console.log('executing transaction...');
    const txSubmit = await txResponse.execute(client);
    console.log('getting transaction receipt...'); // The code can't reach this line due to the previus error in the execute.
    return await handleReceipt(txSubmit, client);
    


### Steps to reproduce

1. Generate a Transaction (Usually `new TransferTransaction()`) 
2. Execute transaction with `.execute()`

### Additional context

### Hedera network

mainnet

### Version

v2.18.5

### Operating system

Windows

**Comment by AdriMsM91** [comment]
Hello @Kalina-Todorova 

Yes I'd say only in Mainnet , we have never these errors in Testnet or at least we didn't find.

About `(Bug) unexpectedly received no response` , yes as far as we checked it, every Transaction was executed **Successfully** and only in Mainnet.

**Comment by Kalina-Todorova** [comment]
Got it, alright, thank you for the additional info, we will keep you updated on our progress when we dig deeper.

**Comment by ochikov** [comment]
I am going to start to debug it. I will keep you updated.

**Comment by ochikov** [comment]
I still cannot reproduce it on LocalNode/Testnet/Previewnet and even on LocalNode with Mainnet configuration. I am continuing to dig into it and will try to reproduce it on the Mainnet. Will keep you updated.

**Comment by AdriMsM91** [comment]
Good morning,

Thanks @ochikov , this is very critical, for Kabila and the entire Hedera ecosystem, now we are having a lot of problems with all our users in Production, since they get stuck in the middle of the processes and do not get answers after at least 15-20min... and then after that time they need to do again what's missing from the process.

I have seen more people talking about this in Hedera Discord #feedback channel , people from HbarSuite (Topachi) and also Bugbytes.

I hope we can find a solution soon.

**Comment by AdriMsM91** [comment]
Hello @ochikov , I've been talking with @gregscullard and I need to specify we're having this problems in Client side, It means executing directly in the browser, we're not executing any action in Node.js

So It may be the problem is in the envoy (grpcWeb proxy)? Talking with Greg, he told me in Client side only Node 0.0.3 is working, and we have only one proxy.

I hope this info helps.

**Comment by ochikov** [comment]
Thank you very much for the clarification. I will discuss it with the team. Meanwhile, can you provide me with some sample configuration so I can reproduce it? We are now using your example provided above on the mainnet to try to reproduce it. Thank you in advance.

**Comment by AdriMsM91** [comment]
Sure,

```js
let client;
client = Client.forNetwork(network);
client.setOperator(AccountId.fromString(accountId), operatorKey);
 ```
 
 We are executing the next query each 10 secs and each 15-20min we get the error: `Error: failed to find a healthy working node`
 
 ```js
 await new AccountBalanceQuery()
      .setAccountId(accountId)
      .execute(client);
 ```
 Also in the next query for example, when It fails we get **Stuck** for like **15-20 min** and after that we get the error 
 `(Bug) unexpectedly received no response`
  but the Transaction went thru and It was executed **SUCCESFULLY** but we **didn't receive** any response about this.
 
 ```js  const txResponse = new TransferTransaction()
      .setMaxTransactionFee(new Hbar(maxFee))
      .addHbarTransfer(senderAccount, amount.negated()) 
      .addHbarTransfer(targetAccountId, amount); 
    console.log('executing transaction...');
    const txSubmit = await txResponse.execute(client);
    console.log('getting transaction receipt...'); // The code can't reach this line due to the previus error in the execute.
    return await handleReceipt(txSubmit, client);

**Comment by ochikov** [comment]
Thank you. I am going to keep you updated.

**Comment by AdriMsM91** [comment]
Good night @ochikov 

A little more feedback....

After the talks with @gregscullard and his help, **Kabila** has decided to create our own Proxy (Envoy). Right now, we have setup **8 Proxys** pointing to **8 Nodes in Mainnet**.

The first test minting 2k NFTs in Mainnet has been executed **SUCCESFULLY** . Not a single mistake. Even the errors which we were getting from `AccountBalanceQuery()` we're not getting anymore.

We will keep doing tests in the next days and we will keep you posted.

**Comment by ochikov** [comment]
Thank you very much for the update. 🙏

**Comment by ochikov** [comment]
> I

Can you here elabore more on `It means executing directly in the browser, we're not executing any action in Node.js`
Because if you even install the SDK and execute something through the browser, it again goes through the SDK.

**Comment by ochikov** [comment]
> Hello @ochikov , I've been talking with @gregscullard and I need to specify we're having this problems in Client side, It means executing directly in the browser, we're not executing any action in Node.js
> 
> So It may be the problem is in the envoy (grpcWeb proxy)? Talking with Greg, he told me in Client side only Node 0.0.3 is working, and we have only one proxy.
> 
> I hope this info helps.

Can you here elaborate more on `It means executing directly in the browser, we're not executing any action in Node.js`
Because if you even install the SDK and execute something through the browser, it again goes through the SDK.

**Comment by AdriMsM91** [comment]
Good morning @ochikov , sure.

Executing in the browser means, we're **not** generating the Transaction + Freezing + Transforming to Bytes + Sending to our BackEnd (Node.js) + Transforming to Trx + Executing there. We're just generating the transaction and executing it directly in the **Browser (Client side)** and It has byg differences between doing this in BackEnd and doing this in FrontEnd. 

As you know, web clients **can't speak gRPC** ,  they can only speak **grpcWeb** which means we need a translator (a proxy) between the web client and nodes. Currently, all web client transactions are going to node **0.0.3**

**Comment by ochikov** [comment]
Yes I got it. Keep in mind that we are using gRPC in the SDKs for the different languages (for JS -> grpc-js) and this can input extra bugs into the product. I've browsed their github and I can see a lot of issues as well.

**Comment by AdriMsM91** [comment]
Good night @ochikov 

What is the actual state of this issue right now? In local we have been trying with our own Proxy and every Error we had (In Mainnet), was fixed. Main problem right now is... when we are trying to use it (Our Proxy) in our Release / Production Environment as It is https instead http , we're having too many troubles & errors... 

When do you think this could be fixed?

**Comment by ochikov** [comment]
Hello @AdriMsM91,
The state is as follows:

1. We have released v2.18.6, so the problem with the unhealthy node was that once the transaction takes more than 10s, it is rejected and the node is put as unhealthy. We managed to solve that.
2. I am currently making 1000 AccountBalanceQuery requests each per 10 seconds on Mainnet to try to reproduce it. On node.js it is not happening for now. I am currently setting up React App to try from the web client. 

We are going to keep you updated as soon as we have any news.

**Comment by AdriMsM91** [comment]
Thanks for the update @ochikov 

That won't fix our main problem I guess, which was:

Whenever we're **executing a Transactions**, sometimes we don't have any response for the next **(10-20min)** It keeps in executing and after 10-20 min, we got this error `Error: max attempts of 10 was reached for request with last error being: TRANSACTION_EXPIRED`, so It means, the user will be Stuck without seeing any progress between **10-20min** and after that he will receive an **ERROR MESSAGE**.

After getting this error, we checked If the transaction was executed and It was executed **SUCCESFULLY** but we didn't receive any response about this.

**Comment by ochikov** [comment]
@AdriMsM91 Yes, That's true. We are trying also to reproduce it and dig into the case where the error is: 

`Error: max attempts of 10 was reached for request with last error being: TRANSACTION_EXPIRED`

I will keep you updated.

**Comment by ochikov** [comment]
@AdriMsM91  Meanwhile, can you show me how you are generating the transaction and executing it directly in the **Browser (Client side)**? I want to try to reproduce it as well.

**Comment by AdriMsM91** [comment]
Sure. This is just an example of one of the Transactions where we received the BUG

```js
 let mintTx = new TokenMintTransaction()
      .setMaxTransactionFee(new Hbar(maxFee))
      .setTokenId(tokenId);
      setMetadata(metadata);
    freezeWith(client);
    const mintTxSign = await mintTx.sign(supplyKey);
   let  mintTxResponse = await mintTxSign.execute(client);
```
    

```js
    const txResponse = new TransferTransaction()
      .setMaxTransactionFee(new Hbar(maxFee))
      .addHbarTransfer(senderAccount, amount.negated()) 
      .addHbarTransfer(targetAccountId, amount); 
    console.log('executing transaction...');
    const txSubmit = await txResponse.execute(client);
    console.log('getting transaction receipt...'); // The code can't reach this line due to the previus error in the execute (It happens ramdomly).
    return await handleReceipt(txSubmit, client);
    ``
    
 If you need something else let me know, also If you want I'm dropping to you my Discord ID , in case you need more code.
 
 **AdrianMsM91{KBL}#9999**

**Comment by teacoat** [comment]
We have also been experiencing this issue in HashPack, I have been pushing to get this fixed for at least 6 months now.

It happens on mainnet when the network is under load from client side executions, as the MHW proxy can not keep up with the load.

I believe there is work being done to make this proxy system more resiliant, maybe @SimiHunjan could link any relevant tickets?

**Comment by ochikov** [comment]
We've added two proxies for the Mainnet (one of the MHW and one of the Swirlds). We are going to release a new version with the fix. I am going to keep you updated.

**Comment by AdriMsM91** [comment]
Hello @ochikov Thanks for the answer although I'm not sure If 2 Proxies will be enough for our use case where we can have 500 people sending Trx non stop (Minting, Sending NFTs...etc) For the moment we deployed our 8 Proxies and overall are working good but we have a byg problem, I hope you can help us. We opened this Issue in **[hedera-json-rpc-relay]** , but they told us is a problem with the **SDK**.

One of the problems is this one: https://github.com/hashgraph/hedera-json-rpc-relay/issues/712

And other is... since we're using our own Proxies, instead of getting just 1 Receipt for example for each Transaction, in Network is appearing a lot of them.... And It is increasing the timers a lot. If we use MYH Proxy, It doesn't happens...

![image](https://user-images.githubusercontent.com/59306428/203734198-467d0cb1-86fd-433f-b827-66594af25dee.png)

**Comment by ochikov** [comment]
We are investigating https://github.com/hashgraph/hedera-json-rpc-relay/issues/712 issue. I will keep you updated in the issue itself.
