### ISSUE TITLE
ScheduleNetworkUpdate continues to trigger even when the client.close() is called.

### ISSUE THREAD

**Issue by ochikov** [hashgraph/hedera-sdk-js#1320]
### Description

ScheduleNetworkUpdate continues to trigger even when the `client.close()` is called. `ScheduleNetworkUpdate` is triggering AddressBookQuery and the query for updating the address book is throwing `Error getting nodes from the mirror for file 0.0.102`. The logic is trying to update the address book `10 times` by default waiting random milliseconds between each try. The integration tests stuck based on that behavior. 

### Steps to reproduce

Run the integration tests with the command: `task test:integration:node`

### Hedera network

mainnet, testnet, previewnet, other

### Version

v2.18.5

**Comment by topshef** [comment]
related reports tbc
https://discord.com/channels/373889138199494658/616725732650909710/1040785961744863323

https://discord.com/channels/373889138199494658/616725732650909710/1038929499091386510

https://discord.com/channels/373889138199494658/616725732650909710/1038928478122287104

https://discord.com/channels/373889138199494658/373889138199494660/1040736823095337000
