### ISSUE TITLE
Get transaction value functions mentioned in docs not available

### ISSUE THREAD

**Issue by mgarbs** [hashgraph/hedera-sdk-js#1323]
### Description

What happened: errors are thrown when calling "get transaction value" functions for [TopicCreateTransaction](https://docs.hedera.com/guides/docs/sdks/consensus/create-a-topic#get-transaction-values)

Ex `getAdminKey`
<img width="583" alt="image" src="https://user-images.githubusercontent.com/101222532/202727898-6893e911-ec30-4665-be63-7b5f4ab5ac8f.png">

Expected: functions to not throw and return appropriate values

### Steps to reproduce

This is the code snippet
```javascript
    const transaction = new TopicCreateTransaction()
        .setSubmitKey(thresholdKey);

    console.log(`The submit key is: ${transaction.getSubmitKey()}`);
```

### Hedera network

testnet

### Version

"@hashgraph/sdk": "^2.18.6"

### Operating system

macOS

**Comment by petreze** [comment]
Greetings @mgarbs :wave:

For all property getters we provide native getters instead of `getX` methods
Therefore, for your specific case you should use `transaction.submitKey` or `transaction.adminKey`

**Comment by mgarbs** [comment]
Okay, I will update the docs to reflect this. Thank you! :)

**Comment by ochikov** [comment]
We've synced with the team and decided to deprecate `. submitKey` and provide `. getSubmitKey()`. It will be changed into the next release.
