### ISSUE TITLE
calling `getMessage()` from submit topic message docs results in `TypeError: not a function`

### ISSUE THREAD

**Issue by mgarbs** [hashgraph/hedera-sdk-js#1324]
### Description

Called `getMessage()` to get the message but a `TypeError` was thrown instead

Here are the docs [submit-a-message#get-transaction-values](https://docs.hedera.com/guides/docs/sdks/consensus/submit-a-message#get-transaction-values)

### Steps to reproduce

1. run this snippet
```javascript
    console.log('Create submit message tx');
    const submitMsgTransaction = await new TopicMessageSubmitTransaction()
        .setTopicId(newTopicId)
        .setMessage('{"myNameIs": "json"}');

    
    const getMessage = submitMsgTransaction.getMessage(); // throws TypeError: submitMsgTransaction.getMessage is not a function
```

### Additional context

<img width="1152" alt="image" src="https://user-images.githubusercontent.com/101222532/202740792-89009e16-d1e3-4efb-87aa-8b4fbc5bf42f.png">

### Hedera network

testnet

### Version

"@hashgraph/sdk": "^2.18.6"

### Operating system

macOS

**Comment by ochikov** [comment]
Hello @mgarbs 👋

For all property getters, we provide native getters instead of getX methods

/**
     * @returns {?Uint8Array}
     */
    get message() {
        return this._message;
    }
Therefore, for your specific case, you should use submitMsgTransaction.message

We are going to fix that into the documentation as well.

**Comment by mgarbs** [comment]
Awe

> Hello @mgarbs 👋
> 
> For all property getters, we provide native getters instead of getX methods
> 
> ```
> /**
>      * @returns {?Uint8Array}
>      */
>     get message() {
>         return this._message;
>     }
> ```
> 
> Therefore, for your specific case, you should use submitMsgTransaction.message
> 
> We are going to fix that into the documentation as well.

Awesome! Thanks :)
Do you want me to close this when we merge the PR for the docs on this?

**Comment by ochikov** [comment]
@mgarbs We are going to handle them. Thank you.

**Comment by ochikov** [comment]
We've synced with the team and decided to deprecate `.message` and provide `.getMessage()`. It will be changed into the next release.
