### ISSUE TITLE
Module parse failed: Unexpected token (109:43) `const transactionRange = body.utilPrng?.range`

### ISSUE THREAD

**Issue by SarjuHansaliya** [hashgraph/hedera-sdk-js#1338]
### Description

After version [2.18.5](https://github.com/hashgraph/hedera-sdk-js/releases/tag/v2.18.5), I have started getting issue
```
./node_modules/@hethers/wallet/node_modules/@hashgraph/sdk/src/PrngTransaction.js 109:43
Module parse failed: Unexpected token (109:43)
File was processed with these loaders:
 * ./node_modules/react-scripts/node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
|     const body = /** @type {HashgraphProto.proto.ITransactionBody} */
|     bodies[0];
>     const transactionRange = body.utilPrng?.range;
|     return Transaction._fromProtobufTransactions(new PrngTransaction({
|       range: transactionRange
```

I think due to `?.` Javascript is throwing this error while starting app. When I looked into it more, it looks like introduced in this PR #1302

### Steps to reproduce

1. clone https://github.com/SarjuHansaliya/testing_hedera_sdk
2. do `yarn`
3. run `yarn start`

### Hedera network

testnet

### Version

2.18.5

**Comment by ochikov** [comment]
Hello @SarjuHansaliya. We are going to investigate it. We will keep you updated.

**Comment by ochikov** [comment]
You can test the new version v2.19.0.

**Comment by SarjuHansaliya** [comment]
Thank you @ochikov for quick response.
