### ISSUE TITLE
Improve examples structure and coverage

### ISSUE THREAD

**Issue by Cooper-Kunz** [hashgraph/hedera-sdk-js#134]
**Description** 

Currently, if you visited the examples, you wouldn't know what's supported given that there's nothing for smart contracts, files, threshold keys (e.g. #126), etc. 

Screenshot below of the current `/examples` folder:

<img width="1011" alt="Screen Shot 2019-12-26 at 12 48 39 PM" src="https://user-images.githubusercontent.com/11776938/71488506-237f7500-27de-11ea-81f7-22df5e67010b.png"> 

Based on #103 & #125 I think there are a few examples that need to be updated, also.

---

**Suggestion**

Create the following structure within `/examples`: 

- hello-hedera.js <- contains a "Hello World" example
- /cryptocurrency
- /files
- /smart-contracts
- /miscellaneous

Short term goal (scope of this issue): Implement popular / required APIs for each service.
Long term goal: implement each API in priority, based on usage and availability within the SDK.

---

I'm happy to work on this in my free time.

I've been using [v0.8.0-beta.0](https://github.com/hashgraph/hedera-sdk-js/tree/v0.8.0-beta.0) but can target `beta.3`, if it's further updated & stable.

**Comment by mehcode** [comment]
@Cooper-Kunz On "Supported" I think we should adopt a matrix of sorts for SDK support in the Readme. I'm not sure how that would look. Perhaps just:

- [x] Crypto-Currency
   - [x] Create Account
   - [x] Update Account

... etc.

---

On examples, I agree that we need a good deal more of them. Java has a good amount and we could transfer those over here to showcase more of the SDK as low hanging fruit.

**Comment by Cooper-Kunz** [comment]
A 'supported features' matrix makes sense to me - perhaps even a consistent one across each SDK.

How do you feel about the following structure, breaking it out by service? (fake content, obviously)

| Cryptocurrency | Support | References |
| --- | --- | --- |
| Create Account | ✅ | [docs](), [1]()
| Delete Account | 🚫 | [docs](), [1](), [2]()
| Get Account Balance | ✅ | [docs](), [1]()
| Get Stakers | 🚫 | [docs]()

e.g...

| File Service | Support | References |
| --- | --- | --- |
| Create File | ✅ | [docs]()
| Delete File | ✅  | [docs](), [1](), [2]()
| Get File Contents | ✅ | [docs](), [1]()

---

Wrt examples - I agree porting [those available in Java](https://github.com/hashgraph/hedera-sdk-java/tree/master/examples/src/main/java/com/hedera/hashgraph/sdk/examples) is a solid first step, and I can submit a pr.

**Comment by mehcode** [comment]
Yes and yes to me :100:

**Comment by Cooper-Kunz** [comment]
Updated examples were merged in #176 

Everyone should feel free to let me know if they have issues or need new examples!

I'll close this issue for now, and reopen another if there's value vs. effort in the supported matrix.

Thanks for all your help @mehcode and other maintainers!! 😄 🎊 👍
