### ISSUE TITLE
`generateEd25519Async()` should be referenced in the depredated note of `PrivateKey.generate()`

### ISSUE THREAD

**Issue by mgarbs** [hashgraph/hedera-sdk-js#1341]
### Problem

The suggested note for the depredated function PrivateKey.generate() does not suggest a valid function. I think its supposed to suggest `PrivateKey.generateEd25519Async()` instead of `PrivateKey.generateEd25519()`

<img width="800" alt="image" src="https://user-images.githubusercontent.com/101222532/204831974-139c36af-baff-4f45-af46-8961689f3e6e.png">

```bash 
TypeError: PrivateKey.generateEd25519 is not a function
    at createThresholdTopicAndUpdateThresholdKey (/Users/michaelgarber/playground/threshold_signatures/service/threshold.js:36:31)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async main (/Users/michaelgarber/playground/threshold_signatures/index.js:24:5)
```

### Solution

Change the suggestion for PrivateKey.generate to be `PrivateKey.generateEd25519Async()`

**Comment by ochikov** [comment]
Hello @mgarbs, I cannot reproduce it. Which version do you use?

**Comment by mgarbs** [comment]
> Which version do you use?

"@hashgraph/sdk": "^2.18.6"
