### ISSUE TITLE
Passing single public key to instantiate `new KeyList(publicKey, 1)` results in invalid `KeyList`

### ISSUE THREAD

**Issue by mgarbs** [hashgraph/hedera-sdk-js#1343]
### Description

When a `KeyList` is created like this, other functions fail to parse it

```js
const privKey = PrivateKey.generate();
const thresholdKey = new KeyList(privKey.publicKey, 1);
console.log(thresholdKey)

//Create the transaction
console.log('create a new topic and set submit key as threshold key');
const topicCreateTx = await new TopicCreateTransaction()
    .setAdminKey(operatorKey.publicKey)
    .setSubmitKey(thresholdKey)
    .execute(client);
```
results in

```bash
➜  threshold_signatures node index.js
KeyList {
  _keys: PublicKey { _key: PublicKey { _key: [Ed25519PublicKey] } },
  _threshold: 1
}
create a new topic and set submit key as threshold key
TypeError: this._keys.map is not a function
    at KeyList._toProtobufKey (/Users/michaelgarber/playground/threshold_signatures/node_modules/@hashgraph/sdk/lib/KeyList.cjs:169:29)
    at TopicCreateTransaction._makeTransactionData (/Users/michaelgarber/playground/threshold_signatures/node_modules/@hashgraph/sdk/lib/topic/TopicCreateTransaction.cjs:291:60)
```

### Steps to reproduce

1. run the code snippet
2. profit ??

### Hedera network

testnet

### Version

"@hashgraph/sdk": "^2.18.6"

### Operating system

macOS

**Comment by petreze** [comment]
Hey @mgarbs :wave:

The constructor of `KeyList` accepts a list of public key(s) as the first argument. Meaning that even if you are going to provide just one key, you would have to pass it as a list containing only that key

**Comment by mgarbs** [comment]
> you would have to pass it as a list containing only that key

I know that but shouldn't the code just take care of that in case I pass a single key?

**Comment by mgarbs** [comment]
The sdk shouldn't let you create a bad `KeyList` like the code above is what I'm trying to say.

**Comment by petreze** [comment]
@mgarbs 
Got it, `KeyList` is adjusted to handle a single key as a first argument. Will be present from next release
