### ISSUE TITLE
Refactor crypto objects to fit new standard [EPIC]

### ISSUE THREAD

**Issue by ochikov** [hashgraph/hedera-sdk-js#1357]
### Description

Once all decisions to do with this [reference](https://github.com/hashgraph/hedera-sdk-reference/issues/73) have been made, the code in this SDK will need to be changed to match.

Linked Issues:
#1356 
#1334 
#1242 

### Steps to reproduce

Refactor crypto objects

### Hedera network

mainnet, testnet, previewnet

### Version

Current Version

### Operating system

None

**Comment by petreze** [comment]
Fixed with [PR](https://github.com/hashgraph/hedera-sdk-js/pull/1550)
