### ISSUE TITLE
GRPC-WEB Proxies needs to be monitored and put as healthy/unhealthy

### ISSUE THREAD

**Issue by ochikov** [hashgraph/hedera-sdk-js#1363]
### Description

If we get some kind of an HTTP ERROR CODE from the grpc-web-proxy, currently the SDK is design to watch only for headers labeled: `grpc-status` and `grpc-message` and thus we cannot catch the empty headers with the empty response but with HTTP ERROR CODE errors, so we cannot mark this web-proxy as unhealthy.

### Steps to reproduce

1. Create react-app
2. Connect the client to MHW web-proxy
3. Try to execute transaction
4. Get 503

### Additional context

Here are the only two headers that we are currently watching:
https://github.com/hashgraph/hedera-sdk-js/blob/develop/src/channel/WebChannel.js#L71

### Hedera network

mainnet, testnet, previewnet

### Version

v2.19.1

### Operating system

macOS

**Comment by petreze** [comment]
Fixed with the following [PR](https://github.com/hashgraph/hedera-sdk-js/pull/1395). Closed
