### ISSUE TITLE
Bug TransferTransaction Executing after 50 Iterations

### ISSUE THREAD

**Issue by AdriMsM91** [hashgraph/hedera-sdk-js#1398]
### Description

Good morning,

We have been testing the new version of the SDK **v2.19.2** on **Mainnet**, in which we have found 2 problems:

**1.** After 49 iterations working correctly, at iteration 50, when doing the .execute the a TransferTransaction , we have returned the error:

``
Error: transaction must have been frozen before calculating the hash will be stable, try calling freeze
    at Ni._requireFrozen (url/_next/static/chunks/pages/_app-5a956b80bccd7cb3.js:1:1512695)
    at Ni.signWith (url/_next/static/chunks/pages/_app-5a956b80bccd7cb3.js:1:1503987)
    at Ni._beforeExecute (url/_next/static/chunks/pages/_app-5a956b80bccd7cb3.js:1:1508826)
    at Ni.execute (url/_next/static/chunks/pages/_app-5a956b80bccd7cb3.js:1:1451982)
    at url/_next/static/chunks/1227-44d2777179fbbe75.js:1:297810
    at l (url/_next/static/chunks/main-528d4c536870c533.js:1:109502)
    at Generator._invoke (url/_next/static/chunks/main-528d4c536870c533.js:1:109290)
    at P.forEach.e.<computed> [as next] (url/_next/static/chunks/main-528d4c536870c533.js:1:109925)
    at g (url/_next/static/chunks/1227-44d2777179fbbe75.js:1:296186)
    at i (url/_next/static/chunks/1227-44d2777179fbbe75.js:1:296389)
    ``
**Looking at SDK, I think the logic is backward -->**

 **__requireFrozen() basically throws an error if its not frozen, but that should come after the if (!frozen) { freeze;}_**
 
 What I don't really understand is why is failing after 49 executes correctly. We changed back the version of the SDK to v2.18.6 with our own Proxies and we don't get the error, although some times ramdomly we got other (1 of each 40-50 executions).
 
**2.** The Proxies of SwirldsLabs are working fine, but 2 of them (3 and 4) are down, so If we're using FreezeTransactions and we Freeze in BackEnd with the Node 3 or 4 , the execute in FrontEnd will fail.

![image](https://user-images.githubusercontent.com/59306428/213150118-d5b7857f-3f04-405a-a250-fbb30240e263.png)

### Steps to reproduce

```js
const hbarAmount = validHbar(amount);
    const txResponse = new TransferTransaction()
      .setMaxTransactionFee(new Hbar(maxFee))
      .addHbarTransfer(originAccountId, hbarAmount.negated()) 
      .addHbarTransfer(targetAccountId, hbarAmount); 
    console.log('executing transaction...');
    const txSubmit = await txResponse.execute(client);
    console.log('getting transaction receipt...');
   ```

### Hedera network

mainnet

### Version

2.19.2

### Operating system

Windows

**Comment by ochikov** [comment]
@AdriMsM91 Yes you are right, if you freeze and sign a transaction for specific nodes and if those nodes are not available, your transaction will fail. You need to resign for another node and then try to execute it. The reason for that is that you are specifying to which nodes you want to execute the transaction, but they are not Healthy nodes and the algorithm cannot find any other healthy nodes from those that you are specifying.

**Comment by AdriMsM91** [comment]
@ochikov That should be done by the SDK itself. It seems to me a huge problem, that we have to implement this logic due to network failures, the **SDK should rebalance** if there is a node that has not responded or is not healthy.

Btw, do we know anything about the first issue?

Thanks.

**Comment by petreze** [comment]
@AdriMsM91 
Just to clarify, is the posted code piece from the backend or the frontend of your application? And also are you specifying the nodes against which you want to submit the transaction for execution?

In regards to the first issue, to sum up your case:
- when you are with the `2.19.2` version of the you are getting the mentioned error at the exact 50th iteration
- and with version `2.18.6` you are getting an error at a random iteration on each ~40-50 executions? Also is it the same error as the one with `2.19.2` version or not?

**Comment by petreze** [comment]
Hello @AdriMsM91 
As far as I understood, you are generating each transaction in your BE (freezing and signing it there) and after that, executing those transactions from your FE? This is how I paraphrase your case from your words but the code piece you have provided (which you said is from your front-end) shows that you are generating and executing the TX on your FE part

_(one note: whenever you are calling `.execute(client)`, the SDK automatically freezes the transaction and signs it with the private key of the `client`_

**Comment by AdriMsM91** [comment]
Hello @petreze As I said at the beginning, I'm not using my BackEnd for anything. All this code is executed ONLY in FrontEnd in https://kabila.app , the second point (2.) was about the problems with Swirlds Proxies, but in the first point, where I got the error, everthing is executed in FrontEnd and is only the code I just sent what is failing, there isn't anything else.

**Comment by petreze** [comment]
@AdriMsM91 
Hey, I was not able to reproduce the issue up until now..
I've tried with the latest version of the SDK (2.19.2) on mainnet, iterate and perform 100 times the `TransferTransaction` you described, then return the recipe. On each recipe returned the status code is `SUCCESS`
Will further investigate. Just wanted to update you on this one

**Comment by AdriMsM91** [comment]
The only difference is that we execute a **Batch of x10 mints with Metadata** + **1 Transfer Transaction** , but Mint is one Transaction (Which was good) and the Transfer Transaction (Which failed in the Iteration 50) is the code I put above. I guess the way to test this is Mint 10k NFTs and in each batch of 10 NFTs execute a transferTransaction.

**Comment by petreze** [comment]
@AdriMsM91 
One clarification, by `batch` do you mean that you are adding those transaction in a list of promises and then awaiting them at once with `Promise.all() / allSettled()` or you are executing the one by one?

**Comment by AdriMsM91** [comment]
Im executing them one by one, I can't do in your way with Promise.all or allSettled , since some Metadatas are attach to specific SerialNumber... :(

**Comment by ochikov** [comment]
@AdriMsM91 can you try with the latest beta version of the SDK ?

**Comment by AdriMsM91** [comment]
Hello @ochikov the same as I answered you in the other Issue..... I can't be doing again the tests and less when this has never happened to us on Testnet. The network should work equal in Testnet and in Mainnet and we have seen many scenarios where It doesn't. It means I would need to spend a lot of Hbars to test in Mainnet since It doesn't happen in the iteration 500 ot 1000, can be in the 8,000 or might in the 15,000 is totally ramdom. In Testnet with more than I don't know... 250k Transactions never happened to us.

**Comment by AdriMsM91** [comment]
Yes. I think with your fix, It should be fixed. If It happens again, I'll reopen. Thanks.
