### ISSUE TITLE
Client.ping() doesn't work

### ISSUE THREAD

**Issue by AdriMsM91** [hashgraph/hedera-sdk-js#1412]
### Description

Hello,

The method Client.ping() doesn't work, in the documentation It sais:

```
To validate the network is up and the client can connect to it you can call the `Client.ping()` method. If the network is up nothing will happen, if the network is down, or the client failed to connect to the network for some other reason then this call would 
throw an error.
```
Even If you put an invalid IP Address  & Node , it returns data (An empty array without any Node Valid) and never throws an error. Even If the Node is wrong or doesn't exist, doesn't throw an error either.

### Steps to reproduce

Client.ping()

### Hedera network

mainnet

### Version

2.19.1

### Operating system

Windows

**Comment by ochikov** [comment]
[v2.20.0-beta.4](https://github.com/hashgraph/hedera-sdk-js/releases/tag/v2.20.0-beta.4) Should fix it.

**Comment by ochikov** [comment]
https://github.com/hashgraph/hedera-sdk-js/releases/tag/v2.20.0
