### ISSUE TITLE
PublicKey.fromStringECDSA is not a function

### ISSUE THREAD

**Issue by mshakeg** [hashgraph/hedera-sdk-js#1433]
### Description

I'm trying to construct a PublicKey instance from the ECDSA public key string as follows:
```ts
import {
  PublicKey,
} from "@hashgraph/sdk";

const eoaAddress = '0xe15A8699a85558E570a0d0d5DE533bd23cE64d4A';
const publicKey = PublicKey.fromStringECDSA(eoaAddress);
```
But I get the following TypeError:
```
TypeError: PublicKey.fromStringECDSA is not a function
```

### Steps to reproduce

I can create an example, but I think the above is sufficient.

### Hedera network

testnet

### Version

@hashgraph/sdk@2.19.2

### Operating system

None

**Comment by mshakeg** [comment]
If I attempt to use `PublicKey.fromString(eoaAddress)` I get the following public key length error:
```
/Users/usr/project/node_modules/@hashgraph/cryptography/lib/PublicKey.cjs:74
    throw new _BadKeyError.default(`invalid public key length: ${data.length} bytes`);
          ^

BadKeyError: invalid public key length: 20 bytes
    at Function.fromBytes (/Users/usr/project/node_modules/@hashgraph/cryptography/lib/PublicKey.cjs:74:11)
    at Function.fromString (/Users/usr/project/node_modules/@hashgraph/cryptography/lib/PublicKey.cjs:106:22)
    at Function.fromString (/Users/usr/project/node_modules/@hashgraph/sdk/lib/PublicKey.cjs:83:49)
    at /Users/usr/project/dist/transfer-to-ecdsa.js:35:43
    at Generator.next (<anonymous>)
    at /Users/usr/project/dist/transfer-to-ecdsa.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/usr/project/dist/transfer-to-ecdsa.js:4:12)
    at main (/Users/usr/project/dist/transfer-to-ecdsa.js:20:12)
    at Object.<anonymous> (/Users/usr/project/dist/transfer-to-ecdsa.js:65:6)
```

**Comment by ochikov** [comment]
@mshakeg Hello,
There is no such functionality to create a public key from the address. 
This functionality is to create a `PublicKe`y from a string of the format of the `PublicKey`, it is not to create it from evm address.

You can create `AccountId` from the evm address.

**Comment by mshakeg** [comment]
Hi @ochikov , I see, but when I try `AccountId.fromSolidityAddress(eoaAddress)` on the EOA EVM address I get the following address, I think `AccountId.fromSolidityAddress` only works on long zero addresses that are essentially an entity id e.g.
`0x0000000000000000000000000000000000332d91` evaluates to the decimal number `3354001` hence account id `0.0.3354001`

```
/Users/usr/project/node_modules/@hashgraph/sdk/lib/EntityIdHelper.cjs:93
    throw new Error("negative numbers are not allowed in IDs");
          ^

Error: negative numbers are not allowed in IDs
    at Object.constructor (/Users/usr/project/node_modules/@hashgraph/sdk/lib/EntityIdHelper.cjs:93:11)
    at new AccountId (/Users/usr/project/node_modules/@hashgraph/sdk/lib/account/AccountId.cjs:41:30)
    at Function.fromSolidityAddress (/Users/usr/project/node_modules/@hashgraph/sdk/lib/account/AccountId.cjs:132:12)
    at /Users/usr/project/dist/transfer-to-ecdsa.js:38:48
    at Generator.next (<anonymous>)
    at /Users/usr/project/dist/transfer-to-ecdsa.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/usr/project/dist/transfer-to-ecdsa.js:4:12)
    at main (/Users/usr/project/dist/transfer-to-ecdsa.js:20:12)
    at Object.<anonymous> (/Users/usr/project/dist/transfer-to-ecdsa.js:66:6)
```

**Comment by Neurone** [comment]
Hi @mshakeg , the EVM address is actually the last 20 bytes of the hashed (keccak-256) public key. It's not a matter of the correct function to use, you simply cannot retrieve the public key starting from the EVM address.

What exactly are you trying to achieve? Maybe we can find another solution.

**Comment by mshakeg** [comment]
Hi @Neurone ah I see, basically, I'd like to transfer HBAR to an EVM address that hasn't yet been instantiated on the Hedera network similarly to [this example](https://github.com/hashgraph/hedera-json-rpc-relay/blob/c6b5d1ceac1fbdf56287060ca8653ccc4c726aff/docs/examples/account-alias-ecdsa.js#L62), however instead of generating a new ECDSA key pair and deriving the public key from it, I'd like to use the associated EVM address instead.

**Comment by ochikov** [comment]
@mshakeg you can use [this](https://github.com/hashgraph/hedera-sdk-js/blob/develop/examples/lazy-create-transfer-tx.js) example.

This is `hollow account` creation. You've got the evm address without the key. Then you need to create a transaction with this account and sign it. This is needed in order for your account to be transformed from `hollow account` to a full hedera account.

**Comment by mshakeg** [comment]
@ochikov hmm, I'm getting the following type error on `PublicKey.toEvmAddress()`:
```ts
const evmAddress = publicKey.toEvmAddress();
```
Gives the following type error:
```
Property 'toEvmAddress' does not exist on type 'PublicKey'.
```

I've got sdk@2.19.2 installed.

**Comment by ochikov** [comment]
You need to switch to version 2.20.0-beta.4. This functionality is presented there.

**Comment by mshakeg** [comment]
@ochikov ah ok, I just tested the example script you linked against testnet and it fails with **status code: 13** `NOT_SUPPORTED`, is that expected? And if so do you know when the testnet update with support for this is?

**Comment by ochikov** [comment]
@mshakeg I think yes because the functionality is only on previewnet now. Can you test on previewnet?

**Comment by mshakeg** [comment]
@ochikov yes, I just confirmed, it works in `previewnet`, but still not `testnet`, I guess I'll have to wait for the next testnet network upgrade.

**Comment by ochikov** [comment]
Yes, as well as when it is available there, we are going to release the 2.20.0 stable version.

**Comment by ochikov** [comment]
Hello @mshakeg There is a slight change and we are not releasing this functionality in https://github.com/hashgraph/hedera-sdk-js/releases/tag/v2.20.0
I will keep you updated about the release of HIP-583, but I think that this functionality will not be presented at all!

**Comment by ochikov** [comment]
@mshakeg you can test the new v2.22.0 version of the SDK.

**Comment by mshakeg** [comment]
@ochikov thanks, just confirmed that it works on testnet!
