### ISSUE TITLE
Add CodeClimate and Codacy to automate code quality review and standardize lint

### ISSUE THREAD

**Issue by calvinchengx** [hashgraph/hedera-sdk-js#144]
To maintain consistent coding standards, I propose that we hook `hedera-sdk-js` to CodeClimate and Codacy.

This ensures that we maintain a high code quality standard and focus our energy on code patterns/design and functionality, while offloading mundane code quality checks to standard best practices.

**Comment by mehcode** [comment]
Personally, I disagree. This is already happening through our very extensive eslint configuration. See: https://github.com/launchbadge/eslint-config and https://github.com/hashgraph/hedera-sdk-js/blob/master/.eslintrc.js#L1 and https://github.com/hashgraph/hedera-sdk-js/commit/8df1e37a8347b1baa41e9ee1e5e1bbd3ffb9e5f4/checks?check_suite_id=379299567#step:8:7.

We could stand to clean up some of the lint warnings however. :smile:

**Comment by calvinchengx** [comment]
Well, linting is a very minor part of what constitutes good code.

Bigger issues usually relate to code duplication, cyclomatic complexity and the like.

**Comment by mehcode** [comment]
@calvinchengx Sorry for not fully explaining that. The term "linting" these days does mean **all** of that. All codacy does is run eslint with a hyper minimal configuration.

**Comment by calvinchengx** [comment]
That's why it makes sense to use CodeClimate (as well). Which does a great job with detecting code smells and cyclomatic complexity.

Codacy also does a little more than lint checks.
