### ISSUE TITLE
Client.close() is not closing all background servies/jobs and console hangs

### ISSUE THREAD

**Issue by a-ridley** [hashgraph/hedera-sdk-js#1441]
### Description

When specifying client.close() and running a script like an account balance query, the console hangs and stays active. It seems like client.close() is not closing all background jobs/services.

I expect the client to close and not cause the console to hang.

I noticed that If you set `scheduleNetworkUpdate: false` like this, `const client = Client.forTestnet({scheduleNetworkUpdate: false}).setOperator(operatorAccountId, operatorPrivateKey)`; and wait a couple of seconds (7-10 seconds); then it allows the client to close, and the console no longer hangs.

### Steps to reproduce

1. open the below vscode project
[account-balance-query.zip](https://github.com/hashgraph/hedera-sdk-js/files/10574268/account-balance-query.zip)
3. set up your .env
4. node index.js
5. Notice the client never closes and the console hangs (i waited like 10 minutes)
6. Go and set `{scheduleNetworkUpdate: false}`
7. Re-run & notice the client will successfully close and not keep the console hanging

### Hedera network

testnet

### Version

2.19.2

### Operating system

macOS

**Comment by ochikov** [comment]
Hello @a-ridley,
Thank you for your issue. It's a known problem and you can use the version 2.20.0-beta.4 where this issue is resolved. Soon it will be released to 2.20.0 stable.

**Comment by a-ridley** [comment]
Great! Thanks @ochikov :)

**Comment by ochikov** [comment]
https://github.com/hashgraph/hedera-sdk-js/releases/tag/v2.20.0
