### ISSUE TITLE
Add API docs

### ISSUE THREAD

**Issue by SimiHunjan** [hashgraph/hedera-sdk-js#1484]
### Problem

As a developer, I want use to reference the API docs whens building applications using my IDE.

- The Hedera JavaScript SDK API docs can automatically be generated from the comments in the source files
- This allows documentation to be accessible in the IDE as the developer is writing code
- https://hashgraph.github.io/hedera-sdk-js/classes/_token_tokencreatetransaction_.tokencreatetransaction.html#setautorenewaccount

### Solution

Add comments to document APIs.

**Comment by ochikov** [comment]
The following website https://hashgraph.github.io/hedera-sdk-js is generated from a branch called `gh-pages`. The information is lastly generated 3 years ago. The v2 of the SDK supports `typedoc` and the format of generated docs are different. We are going to continue to dig into it to find the best way and format of generation the docs.
