### ISSUE TITLE
Issues in ContractFunctionParams 

### ISSUE THREAD

**Issue by rahulasati** [hashgraph/hedera-sdk-js#153]
Following type of params is not working with checked on version 1.0.0-beta.4 
1. functonParams.addInt256(<BigNumber {s: 1, e: 3, c: Array(1)}>) - Call get succeeded but get always return 0 
2. functonParams.addInt32Array() - Call get succeeded but get always return empty array 
3. functonParams.addInt64Array() - Call get succeeded but get always return empty array
4. functonParams.addInt256Array() - Call get succeeded but get always return empty array
5. functonParams.addAddressArray() - ["00000000000000000000000000000000000004ba", "00000000000000000000000000000000000004bc”]
Err while Contract call:  Error: Reduce of empty array with no initial value
6. functonParams.addBytesArray()
7. can't see support for uint32, uint64 and uint256

**Comment by rahulasati** [comment]
Attached Test Smart Contract for testing purpose:

[TestContract.sol.zip](https://github.com/hashgraph/hedera-sdk-js/files/4019523/TestContract.sol.zip)

**Comment by danielakhterov** [comment]
@rahulasati 
Array encoding and implementing unsigned integer types should be resolved with #154

**Comment by rahulasati** [comment]
Thanks @danielakhterov when i can expect a release with these fixes ?

**Comment by mehcode** [comment]
All fixed and out with v1.0.0-beta.5
