### ISSUE TITLE
Bare React Native no longer supported

### ISSUE THREAD

**Issue by robkainz** [hashgraph/hedera-sdk-js#1546]
### Description

The Hedera JS SDK used to work with a bare React Native project years ago, before we switched to the golang SDK to overcome very long JS SDK init times in our React Native project. My understanding is those initialization issues have been fixed and we would like to begin adding support for the community-developed wallet connect library, built using the Wallet Connect V2 protocol, so far only written in Javascript and under review by the Hedera wallet community. But Wallawallet relies on audited native code that protects user's security utilizing the secure enclave/element for IOS and Android devices and the native code is likely not compatible with a React Native expo project. So we need to keep the React Native project bare and want to switch back to the Hedera JS SDK.

Currently when trying to fetch balance on IOS, we get the error: 

> undefined is not an object (evaluating '_sdk.LocalProvider.fromClient')

The same code was tried in a simple node project and worked just fine. 

Can you please support bare React Native applications again for the Hedera JS SDK?

### Steps to reproduce

1. Using v2.23.0 of @hashgraph/sdk, create a bare react native project that attempts to fetch balance from the Hedera mainnet.

### Hedera network

mainnet

### Version

v2.23.0

### Operating system

Other

**Comment by ochikov** [comment]
Hello @robkainz,
Thank you for your issue.
Can you include a repo or example of a code snippet?

**Comment by robkainz** [comment]
@ochikov I can provide this code snippet. If you need a RN project, would probably take me a while to create one that resembles Wallawallet regarding it's configuration, native code, etc., without sharing the repo, which we don't want to do. 

Your readme does state that bare react native is not currently supported, so it sounds like you are aware of this issue. In my case, the failure occurs from trying to create a LocalProvider from the Client as in the snippet below.


```
const getClient = async (jsonConfig:any, selectedNetwork:any) =>
{
    const network = await getNetworkConfig(selectedNetwork);
    const operator = ENV.defaultClientConfig;
    operator.accountId = jsonConfig.accountId;
    operator.privateKey = jsonConfig.privateKey;
    let cfg = { network: network.network, operator: operator };
    const client:Client = Client.fromConfig(JSON.stringify(cfg));
    const maxQueryFee:BigNumber = new BigNumber(jsonConfig.maxQueryFee);
    const maxTransactionFee:BigNumber = new BigNumber(jsonConfig.maxTransactionFee);
    client.setMaxQueryPayment(Hbar.fromTinybars(maxQueryFee.toNumber()));
    client.setMaxTransactionFee(Hbar.fromTinybars(maxTransactionFee.toNumber()));
    return client;
}

const client = await getClient(jsonConfig, network);
const accountId = jsonConfig.accountId;
const localProvider:LocalProvider = LocalProvider.fromClient(client);
```

**Comment by robkainz** [comment]
Thanks @ochikov Would be extremely helpful as wallet connect support is becoming our top priority.

**Comment by AdriMsM91** [comment]
It is critical for Kabila App also, since we're developing our Apps for iOs & Android with React Native.

**Comment by AdriMsM91** [comment]
Good night,

This is a critical issue for Kabila App, since we're developing our iOs & Android Apps with React Native. We're currently developing with Expo, but we just saw this message:

![image](https://user-images.githubusercontent.com/59306428/229638652-f5df48df-31e1-4bef-bdcc-61e4ffba8a62.png)

So... really JS SDK doesn't work for iOs using React Native???

**Comment by ochikov** [comment]
@AdriMsM91 This statement does not mean that it does not work! It means that it supports Expo Kit and not Bare Kit.

**Comment by AdriMsM91** [comment]
But @ochikov as you can see in that message, It says: `React Native with Expo on Android devices and Android emulators.` If it's supported by iOs devices and iOs emulatores also, why are you guys specifying Android? 

We haven't done any tests in iOs yet, so I trust in your word that works in iOs with Expo.

Thanks for your answer.

**Comment by ochikov** [comment]
@AdriMsM91 I've created React Native app with Expo. I was able to include and test the SDK both on IOS and Android simulators. I am applying screenshots from the Emulators (I've used a button to trigger transfer transactions) as well as logs:
![Screenshot 2023-04-07 at 17 25 00](https://user-images.githubusercontent.com/13587218/230625511-8f56da7c-c9fd-4b73-a339-9e92c5052c7b.png)
![Screenshot 2023-04-07 at 17 24 45](https://user-images.githubusercontent.com/13587218/230625512-b029363b-d8a4-449b-972c-52fd27f94371.png)
![Screenshot 2023-04-07 at 17 21 13](https://user-images.githubusercontent.com/13587218/230625514-9890594c-1795-4b32-aadd-d3fa695b5f79.png)
![Screenshot 2023-04-07 at 17 21 09](https://user-images.githubusercontent.com/13587218/230625516-4a6600bf-f2ca-4a2a-b91b-928441dc674c.png)

**Comment by AdriMsM91** [comment]
Thanks you @ochikov ! Might worth updating the Text I posted above, to make it clear that we support iOs and Android with Expo.

**Comment by ochikov** [comment]
Further research and tests with `react-native-cli` without Expo, show that it is not supported. The reason is that we are using a package `expo-random` in the cryptography package. I will further research and try to use another not expo-based library in order to test and eventually provide support for a React project setup with `react-native-cli`.

**Comment by robkainz** [comment]
Ok, thanks for looking into this. We will investigate adding Expo to enable us to use the Hedera JS-SDK over the native Hedera golang SDK we currently use, which will require a new security audit and depending on Expo's biometrics API for Android/IOS it may require our users to completely uninstall/reinstall the app to upgrade.
