### ISSUE TITLE
When upgrading from 2.20.0 to 2.22.0 export 'hexZeroPadded' not found

### ISSUE THREAD

**Issue by teacoat** [hashgraph/hedera-sdk-js#1548]
### Description

Did a simple update of the sdk, now I am unable to compile because it is throwing an error.

### Steps to reproduce

1. add the sdk to a project
2. observe error

### Additional context

I am currently using this in an angular project, have had another developer mention this error as well so I don't believe its to do with my stack.

Confirmed this error exists up to 2.24.0

![image](https://user-images.githubusercontent.com/3913019/229815428-9efa00f9-f579-443e-8ce6-01ea47eebd05.png)

### Hedera network

mainnet

### Version

2.22.0

### Operating system

None

**Comment by teacoat** [comment]
After downgrading back to 2.19.2 I seem to continue getting this error... not sure whats up

**Comment by ochikov** [comment]
@teacoat the problem is with the latest version of the subpackage cryptography. I will provide a fix ASAP and notify you.

**Comment by teacoat** [comment]
thank you @ochikov :pray:

**Comment by ochikov** [comment]
@teacoat We've released a new stable version of the cryptography subpackage. Now when you reinstall the SDK, it should fetch the newer version and get rid of the error. Can you confirm?

**Comment by teacoat** [comment]
Fixed - note, need to delete package.lock if error persists
