### ISSUE TITLE
Add Multi-Node Execution for Client Requests and Transactions

### ISSUE THREAD

**Issue by mshakeg** [hashgraph/hedera-sdk-js#1562]
### Problem

Currently, the Hedera SDK for JavaScript does not support executing client requests or transactions to multiple consensus nodes simultaneously. This functionality is desired for the following reasons:
1. To submit query requests (e.g., `ContractCallQuery`) to multiple nodes and allow users to estimate the most likely correct response based on all responses.
2. To submit transactions (e.g., `ContractExecuteTransaction`) to multiple nodes to mitigate MEV or front running, as it's possible for nodes to change the ordering of transactions within their blocks/events or even delay a transaction to a node's later block/event and carry out sandwich attacks for example. By submitting a transaction to N nodes, a transaction's consensus timestamp (based on the median timestamp of the earliest transaction of the N duplicate transactions) is more likely to be sooner than the consensus timestamp if the transaction was submitted to a single node especially one that attempts MEV.

### Solution

To address this problem, a new feature can be added in the SDK to support executing client requests and transactions to multiple consensus nodes (specified explicitly or randomly selected). This can be achieved by implementing the following steps:

1. Extend the SDK's client configuration to allow specifying multiple consensus nodes or a flag to randomly select nodes(while also allowing the number of randomly selected nodes to be specified).
2. Modify the SDK's request and transaction execution logic(located in `client.execute()`) to support broadcasting the request/transaction to the specified or selected nodes.
3. In the case of query requests, return all responses and allow the user to aggregate the responses from all nodes and provide an estimation of the most likely correct response.
4. In the case of transactions, submit the transaction to multiple nodes. When getting the transaction record using `TransactionRecordQuery` it should return the earliest transaction of the N duplicate transactions(since only the earliest is processed while the later duplicate transactions are effectively ignored).

### Alternatives

Users can implement this functionality themselves, by creating multiple instances of the SDK client, each configured with a different node, and then manually broadcasting the requests/transactions. However, this approach can be cumbersome and repetitive for developers, and having built-in support in the SDK would be more convenient and promote best practices.

**Comment by petreze** [comment]
@mshakeg 
Currently, how the SDK works is that, whether or not you are setting the `nodeAccountIds` explicitly, the transaction will be passed randomly to a node from this list. Both points you mentioned are handled in hedera core network part. Furthermore, if you try to process the same transaction to more than one node simultaneously, you will get `DUPLICATE_TRANSACTION` error from the consensus algorithm, so basically your request cannot be done

**Comment by mshakeg** [comment]
@petreze, sorry, forget to get back to you. Your comment has brought up an important clarification I'd like to understand better. When a transaction is submitted to multiple nodes, could you confirm if:

1. All instances of that transaction fail with the error DUPLICATE_TRANSACTION.

or -

2. Only the transaction/s beyond the first instance of the transaction to be processed(i.e. ordered by consensus timestamp) fail with this error.

My current understanding aligns with (2.), in which case my proposal should not encounter any issues. However, if the current behaviour is (1.), have there been any considerations to update the Hedera core consensus logic to reflect the behaviour described in (2.)? This adjustment could align with the concerns and solutions outlined in my original request.

**Comment by mshakeg** [comment]
@petreze a user could effectively submit a "transaction" to multiple nodes with all being processed by the network but only the first instance(i.e. by consensus ordering) of the duplicates would be successful with the rest reverting as described in [point 2.](https://github.com/hashgraph/hedera-sdk-js/issues/1562#issuecomment-1681909679)

This can be achieved by a user signing an intent and then wrapping that intent in multiple unique transactions each distributed to a node. Since the duplicate intents have identical nonces on the level of the intent(e.g if the intent is to be processed by a smart contract wallet then this wallet tracks its own nonce internally which is different from the EOA's nonce), the EVM will revert for all intents beyond the first.

Since multi-node execution can be achieved as described above, there should technically be no issue submitting a transaction to multiple nodes.

**Comment by Nana-EC** [comment]
> 2\. Only the transaction/s beyond the first instance of the transaction to be processed(i.e. ordered by consensus timestamp) fail with this error.

@mshakeg this is correct. Later instances of the transaction will fail with the duplicate error

**Comment by Nana-EC** [comment]
@petreze you're right that for transactions duplicates will result in an error.
For queries there will be errors when querying multiple nodes.

**Comment by mshakeg** [comment]
> @mshakeg this is correct. Later instances of the transaction will fail with the duplicate error

@Nana-EC thanks for the confirmation, if that is correct is this ask not reasonable for users who want to minimise the possibility of MEV. Though this will only work if the first tx instance(by consensus order) is by a node not engaging/facilitating MEV.

**Comment by mshakeg** [comment]
Hey @Nana-EC there's been much discussion about MEV on CT recently and I wanted to revisit this discussion. While I don't think there's much if any MEV activity on Hedera at this point in time as I don't think council members are allowed to engage or facilitate such activity, I do think that this will become a concern with the transition to permissionless nodes as nodes can control the ordering of transactions within `blocks` they produce (or `events` if that's the more correct nomenclature for the hashgraph algorithm) and hence can engage in MEV within their `events`. There's been a few ideas on how to reduce MEV, but below is an idea that I think could work well for hashgraph implementations such as Hedera:

- **Transaction Duplication**: A user can submit an identical transaction to multiple nodes, indicating a request for priority handling to reduce MEV risks.
- **Priority Queue Allocation**: If a transaction is found to be duplicated in an `event` produced on at least one other node then the first instance of that transaction(i.e. present in the `event` with the earliest median timestamp) is pushed on to the priority queue for that `event`.
- **Execution and Duplicate Management**: This model processes transactions in a priority queue for any given `event` before the rest of the non-priority transactions for that `event`, aiming to counteract MEV tactics like front-running. For an MEV agent to guarantee a front-run of a priority non-MEV transaction `T` with their transaction `TF` within an influenced event `E1`, they must not only place `TF` earlier than `T` in `E1` but also ensure that it's duplicated across multiple nodes — matching the priority criteria of `T`. This requirement significantly increases the complexity, cost, and risk for MEV agents. They must correctly predict which transactions will be prioritized (or risk wasting fees on unnecessary duplications) and even then face the uncertainty of their front-run transaction `TF` being outpaced by `T`'s duplicates in earlier events (say `E2`, ...). To me it seems like the only way to consistently guarantee txs like `TF` successfully front-run txs like `T` is to have a supermajority of the network collude to have `TF` frontrun `T`.

Keen to hear your take on this or any ideas you might have to further mitigate MEV.
