### ISSUE TITLE
Expose checksum helper methods

### ISSUE THREAD

**Issue by teacoat** [hashgraph/hedera-sdk-js#1568]
### Problem

I am attempting to use the sdk for checksum generation/validation rather than relying on copied code, it seems entity id helper is not exported thus I cannot use the helper functions contained in it.

This is the error message I get:

`Error: Module not found: Error: Package path ./lib/EntityIdHelper is not exported from package /node_modules/@hashgraph/sdk`

### Solution

Export or create a relevant class to enable checksum generation/validation

### Alternatives

Perhaps I am importing it wrong, if so how would I do it correctly?

**Comment by ochikov** [comment]
Hello @teacoat, can you give me a more detailed example of what you are trying to achieve? `EntityIdHelper` is a file with helper methods for internal class use. Maybe based on your example, I will help you with the right way of doing it.

**Comment by teacoat** [comment]
@ochikov getting this strange error now, any ideas?
![image](https://user-images.githubusercontent.com/3913019/236322992-cfc19a32-478c-4254-9591-6c13210d7789.png)

**Comment by ochikov** [comment]
Hello @teacoat,
I am able to use the `EntityIdHelper` both in Node.js project as well as React FE project. What is your setup? Did you reinstall your node_modules?

**Comment by ochikov** [comment]
Hello @teacoat,
I am able to use the EntityIdHelper both in Node.js project as well as React FE project. What is your setup? Did you reinstall your node_modules?

**Comment by ochikov** [comment]
Hello @teacoat, did you manage to resolve the issue?

**Comment by ochikov** [comment]
@teacoat I am closing the issue.

**Comment by ochikov** [comment]
@teacoat Can you test `2.27.0-beta.3` ?
