### ISSUE TITLE
Passing negative argument value to Contract's function call using Hedera SDK fails

### ISSUE THREAD

**Issue by amandeeprehal-lab49** [hashgraph/hedera-sdk-js#1571]
### Description

If one call below `testFunction` using Hedera' s SDK with negative `val`,  it fails with an exception. Is there any Hedera's SDK API to get negative values from smart contract either by Events or function return values. 

Expectations - Smart contract should accept and return negativ values when the datatype is int.

### Steps to reproduce

```
contract Pair  {
 
    event NegativeNumber(int32 number);

    function testFunction(int32 val) external returns(int32) {
        emit NegativeNumber(200);
        emit NegativeNumber(val);
        emit NegativeNumber(-20);
        return val;
    }
}
```

```
const args = new ContractFunctionParameters()
      .addInt32(-12);

const txn = new ContractExecuteTransaction()
      .setContractId(this.contractId)
      .setGas(gas)
      .setFunction("testFunction", args)
      .setPayableAmount(0);

const txnResponse = await txn.execute(client);
```

### Hedera network

testnet

### Version

hashgraph-sdk version 2.19.0

### Operating system

macOS

**Comment by ochikov** [comment]
Hello @amandeeprehal-lab49 and thank you for your issue. We are familiar with the bug. We've got reported it already: https://github.com/hashgraph/hedera-sdk-js/issues/1284
We are going to schedule fixing it for some of our next releases.

**Comment by amandeeprehal-lab49** [comment]
thanks @ochikov!
