### ISSUE TITLE
Bug executing in Front End Transactions AGAIN

### ISSUE THREAD

**Issue by AdriMsM91** [hashgraph/hedera-sdk-js#1606]
### Description

Good evening,

Again (Yes I've reported this 2 times already), we get each 300 - 500 NFTs minted executing transactions in Front End different errors. Same as the others times when I reported.

x1 Mint Transactions with 10 NFTs
x1 Hbar Transfer Transaction
Loop

I'm getting this 2 different errors. It's need to be fixed ASAP, all our customers are having problems with it and they can't even mint their collections.

![image](https://github.com/hashgraph/hedera-sdk-js/assets/59306428/01cbf771-0e55-419a-80b0-7c63a266fd82)
![image](https://github.com/hashgraph/hedera-sdk-js/assets/59306428/df6c1f13-dfc8-4081-900b-7619434b2673)
![image](https://github.com/hashgraph/hedera-sdk-js/assets/59306428/73283dcb-376f-45fd-99df-ea08ca7aa041)
![image](https://github.com/hashgraph/hedera-sdk-js/assets/59306428/8117bf23-75f1-456a-8ab0-857b5fe282bb)

### Steps to reproduce

x1 Mint Transactions with 10 NFTs
x1 Hbar Transfer Transaction
Loop

### Hedera network

mainnet

### Version

2.20.0

### Operating system

macOS

**Comment by ochikov** [comment]
Hello @AdriMsM91,
As you can see, you are getting errors from executing transactions from Node 3 and Node 4. They are down:
![Screenshot 2023-05-15 at 11 24 16](https://github.com/hashgraph/hedera-sdk-js/assets/13587218/d0be7dc3-26f7-4179-a036-57ee08623e5f)

Also, I don't know your exact configuration, but if you explicitly defined to use those nodes, you cannot get through them, because they are not functioning. Did you use the `setNodeAccountIds` functionality? 

Also, you can update to the latest version, because the latest version support looping through different proxies of a down node to try to proceed the transaction through another proxy.

**Comment by ochikov** [comment]
@AdriMsM91 
I've performed ~5000 transactions last few days and with the newest version, I cannot reproduce the bug that the SDK cannot switch to another Node. Please update to the latest version. We've fixed also the freezing issue.

**Comment by petreze** [comment]
@AdriMsM91 
Also on the `Transaction must been frozen before calculating the hash will be stable, try calling freeze.` topic. First and foremost - the error message can come from several places from the SDK, so we cannot guess what triggers this on your side. Secondly, the message is self-explanatory - the transaction has to be frozen in order to achieve what you are trying to accomplish.

On the other issue - I will also try to reproduce it
`x1 Mint Transactions with 10 NFTs and then x1 Hbar Transfer Transaction repeatedly in a loop`
I will write you if there is any progress

**Comment by ochikov** [comment]
@AdriMsM91 do we have any updates from the updating to the newest version?

**Comment by AdriMsM91** [comment]
We will be updating tomorrow. Today we have our big mint and we don't want to risky anything.

**Comment by AdriMsM91** [comment]
Good night,

We upgraded today, so we will let you know If any of our customers reports again. Btw I saw in different Discords from wallets, people having the same Error than I'm reporting, as you can see, today in HashPack this has been reported also.

So I guess obviously there is a problem with this, since If It fails ramdomly is nothing to be about freezing it or not, is more, we do the .execute() directly and It works 90% of the time, 10% fails.

![image](https://github.com/hashgraph/hedera-sdk-js/assets/59306428/bbb15925-abd2-47c3-8ee5-39643df37427)

**Comment by ochikov** [comment]
@AdriMsM91 We were able to reproduce the error when we did not have any healthy nodes left. We are going to investigate it. Thank you for the report.

**Comment by AdriMsM91** [comment]
Yeah @ochikov also with the last version 2.25.0 , today in production we have the same problem. 
![image](https://github.com/hashgraph/hedera-sdk-js/assets/59306428/5d9ad59a-0ae5-44e5-8913-9197e128944f)

**Comment by petreze** [comment]
@AdriMsM91 
Just to clarify, how exactly are you setting up the client for mainnet?

**Comment by AdriMsM91** [comment]
Hello @petreze and @ochikov 

Since long time ago, we don't use our setup for proxies, basically since Swirlds Labs deployed every proxy for every node, we are not using that anymore.

This is how I'm creating the client for Mainnet. Also talking the the wallet-ecosystem-channel this weekend, looks like it is happening to many people.

```js
let client = Client.forNetwork(network);
```

**Comment by petreze** [comment]
@AdriMsM91 
Good but the important thing is the `network` object. What exactly are you passing to `forNetwork()`?

**Comment by AdriMsM91** [comment]
> @AdriMsM91 Good but the important thing is the `network` object. What exactly are you passing to `forNetwork()`?

'mainnet'

**Comment by AdriMsM91** [comment]
Hello @petreze @ochikov 

Actually is impossible to test anything in Mainnet, we just keep getting different errors each time. Each 300-400 NFTs, now I'm getting this error.  It's really frustrating tbh.

```js
max attempts of 10 was reached for request with last error being: HttpError: failed with error code: 503
```
![image](https://github.com/hashgraph/hedera-sdk-js/assets/59306428/0d8df58c-156e-4013-ba6a-50ccc8aed947)

**Comment by petreze** [comment]
Newest official `v2.25.0` or the one I mentioned - `v2.26.0-beta.2`?

**Comment by AdriMsM91** [comment]
@petreze 

`v2.26.0-beta.2`

**Comment by SimiHunjan** [comment]
@AdriMsM91 do you encounter the same issue on testnet or is this on mainnet only?

**Comment by SimiHunjan** [comment]
Thanks going to check in with the devops team as well. Appreciate your patience.

**Comment by nickpoorman** [comment]
@AdriMsM91 can you try the following?

~x1 Mint Transactions with 10 NFTs~

Instead do:

x1 Mint Transactions with 1 NFTs

I suspect, during high network usage, you have a greater chance of hitting a throttle due to the 10x amount of work required when minting 10x NFTs in a single transaction.

**Comment by AdriMsM91** [comment]
Hello Nick,

I just finished the test 1 by 1 instead of batches of 10 and I got the same error in my 37 NFT minted.

![image](https://github.com/hashgraph/hedera-sdk-js/assets/59306428/2ba93ccf-9286-455f-94d7-09485949302c)
![image](https://github.com/hashgraph/hedera-sdk-js/assets/59306428/d49e6e6b-0035-4deb-9cd8-85e6332c3c32)

**Comment by AdriMsM91** [comment]
Hello, good morning.

Any advances on this? We have all our customers opening tickets daily about this problem. They can't even mint more than 200-300 NFTs without getting this error.

Thanks.

**Comment by SimiHunjan** [comment]
@AdriMsM91 we are still investigating the issue. It is not reproducible on testate at the moment. In the meantime, is the app able to retry when it receives the 503 unavailable errors? To confirm, you are now only receiving 503 errors?

**Comment by ochikov** [comment]
Hey @AdriMsM91 I can reproduce the error, but when this error occurs, we are switching to another proxy so there aren't failing transactions because of this error on my side. We are working to investigate why we are receiving this error. It's only reproducible on mainnet.

**Comment by AdriMsM91** [comment]
I would need to do an incredible work around to be able to retry. Right now we're only getting 503 errors since last updated.

**Comment by ochikov** [comment]
It's not connected with the update and the new version I think. On test net is not reproducible. I think that the proxies has high load. Why you need to implement work around? The SDK is retrying itself. Also you can set the max retries to different number from the default value (10).

**Comment by SimiHunjan** [comment]
@AdriMsM91 have you tried to remove node3 and node4 from the client node list? Something like:

```
const client = Client.forNetwork({
    "https://node02.swirldslabs.com:443": new AccountId(5),
    // remove "https://node03.swirldslabs.com:443": new AccountId(6),
    // remove "https://node04.swirldslabs.com:443": new AccountId(7),
    "https://node05.swirldslabs.com:443": new AccountId(8),
    "https://node06.swirldslabs.com:443": new AccountId(9),
    "https://node07.swirldslabs.com:443": new AccountId(10),
    "https://node08.swirldslabs.com:443": new AccountId(11),
    "https://node09.swirldslabs.com:443": new AccountId(12),
    "https://node10.swirldslabs.com:443": new AccountId(13),
    "https://node11.swirldslabs.com:443": new AccountId(14),
    "https://node12.swirldslabs.com:443": new AccountId(15),
    "https://node13.swirldslabs.com:443": new AccountId(16),
    "https://node14.swirldslabs.com:443": new AccountId(17),
    "https://node16.swirldslabs.com:443": new AccountId(19),
    "https://node17.swirldslabs.com:443": new AccountId(20),
    "https://node18.swirldslabs.com:443": new AccountId(21),
    "https://node19.swirldslabs.com:443": new AccountId(22),
    "https://node20.swirldslabs.com:443": new AccountId(23),
    "https://node21.swirldslabs.com:443": new AccountId(24),
    "https://node22.swirldslabs.com:443": new AccountId(25),
    "https://node23.swirldslabs.com:443": new AccountId(26),
    "https://node24.swirldslabs.com:443": new AccountId(27),
    "https://node25.swirldslabs.com:443": new AccountId(28),
    "https://node26.swirldslabs.com:443": new AccountId(29),
    });
```

Both those nodes are down and are not receiving requests https://status.hedera.com/. In the image you shared above it looks like it is also highlighting those two nodes.

**Comment by SimiHunjan** [comment]
hey @AdriMsM91 ! I tried to mint an NFT collection using the app for testnet, but seems I need to buy a pass or own a specific NFT. 

When users sign the transaction to mint NFTs do they sign a single transaction that goes to one node that is randomly selected by the SDK or do they sign multiple transactions with different node IDs set and then the app will try submitting transactions to each of those nodes until one is successful?

**Comment by AdriMsM91** [comment]
@petreze Thanks, seems like it's fixed! Minted 2,000 NFTs in Mainnet without any problem. 
![image](https://github.com/hashgraph/hedera-sdk-js/assets/59306428/94789992-8590-44c7-88c8-0e5c1641cf8f)

**Comment by petreze** [comment]
@AdriMsM91 
So glad to hear that !
