### ISSUE TITLE
INVALID_TRANSACTION_BODY is thrown when the SDK is used with fixed single node (When the node become unhealthy)

### ISSUE THREAD

**Issue by ochikov** [hashgraph/hedera-sdk-js#1610]
### Description

The [hedera-json-rpc-relay](https://github.com/hashgraph/hedera-json-rpc-relay) is using the JS SDK for executing `AccountInfoQuery` with fixed (locked) node on mainnet using Node 0.0.4. Sometimes the node is becoming unhealthy and the SDK is returning `INVALID_TRANSACTION_BODY` error, for example:
```
 err: {
      "type": "SDKClientError",
      "message": "transaction 0.0.2@1684417478.596685656 failed precheck with status INVALID_TRANSACTION_BODY",
      "stack":
          Error: transaction 0.0.2@1684417478.596685656 failed precheck with status INVALID_TRANSACTION_BODY
              at SDKClient.<anonymous> (/Users/ognyanchikov/Projects/HEDERA_SDKs/hedera-json-rpc-relay/packages/relay/dist/lib/clients/sdkClient.js:86:40)
              at Generator.throw (<anonymous>)
              at rejected (/Users/ognyanchikov/Projects/HEDERA_SDKs/hedera-json-rpc-relay/packages/relay/dist/lib/clients/sdkClient.js:25:65)
              at processTicksAndRejections (node:internal/process/task_queues:96:5)
      "status": {
        "_code": 50
      },
      "validNetworkError": true
    }
```

What is the workflow:
When we are doing Query, we are sending two requests, in this case `cryptoGetInfo` request. 
- The first one is of type `COST_ANSWER` (2) and in it's header the `payment` object is created with `transactionId` for `AccoundId(0)` (hardcoded).
- The second one is of type `ANSWER_ONLY` (0) and in it's header the `payment` object needs to be created with the `paymentTransactions` based on the `NodeAccountId`. Since we don't have any healthy node, the object is `undefined` and this then leads to: `INVALID_TRANSACTION_BODY` error. 

We need to do the following actions:
- Try to understand why the node 4 (hardcoded by the hedera-json-rpc-relay) is unhealthy
- In case the node is not unhealthy, what causes the SDK to mark it as unhealthy
- Create another node that we can use for that kind of operations (like Node 0.0.4).

### Steps to reproduce

1. Clone the https://github.com/hashgraph/hedera-json-rpc-relay repo
2. Clone the https://github.com/hashgraph/hedera-local-node
3. Create configuration for the Local Node to work with the local relay
4. Manually edit the ManagedNetwork.js file in the SDK instance used in the relay and set the variable `this._unhealthyNodesCount` equal to 1. 
5. Run `npx hardhat test` in the smoke folder of the Hedera Local Node

### Hedera network

mainnet

### Version

v.2.25.0

### Operating system

Other

**Comment by ochikov** [comment]
@Nana-EC I think that with the latest release (v2.29.0) this error is fixed as well.

**Comment by ochikov** [comment]
@Nana-EC  @SimiHunjan We are going to close this issue.

**Comment by Nana-EC** [comment]
Thanks @ochikov 
We updated previously and I believe it reduced the observation counts.
@AlfredoG87 can you confirm post v2.29.0 of the SDK this error is either removed or heavily reduced.

Notably, the relay took steps to reinstatiate an SDK instance for various reasons so the reduced observations may be skewed.
