### ISSUE TITLE
Research about EthereumTransactionData.fromBytes

### ISSUE THREAD

**Issue by petreze** [hashgraph/hedera-sdk-js#1615]
### Description

EthereumTransactionData cannot be generated `fromBytes()` from a signed transaction generated previously with the usage of ethers.js (6.4.0)
Signing a transaction with `await wallet.signTransaction(tx);` from ethers
Error: `reason: 'invalid rlp data', code: 'INVALID_ARGUMENT', argument: 'data'`
EthereumTransactionData uses `"@ethersproject/rlp": "5.7.0"` for encoding/decoding ethereum transaction data

**Notes:** The entire workflow works if using previous ethers.js version - (5.7.2)

### Steps to reproduce

```
const tx = {
    value: ,
    gasPrice:,
    gasLimit: ,
    chainId: ,
    to: ,
    nonce:
};

const wallet = new ethers.Wallet('private_key');
const signed = await wallet.signTransaction(tx);
    
const transactionBuffer = Buffer.from(signed.substring(2), 'hex');

const ethereumTransactionData = EthereumTransactionData.fromBytes(transactionBuffer);
```

### Additional context
Note that while ethers.js has newer stable v6 (6.4.0) version, the @ethersproject/rlp library is still with the most recent stable version v5 (5.7.0). And since everything works properly with ethers v5 (5.7.2), my assumption is that it comes from the difference between those versions

Furthermore, the bytes length generated from `await wallet.signTransaction(tx);` differs between the versions, hence the newer representation cannot be decoded by the previous decoding approach

### Hedera network

other

### Version

v25.0.0

### Operating system

macOS

**Comment by ochikov** [comment]
@petreze What will be the solution here? We are just going to downgrade to Ethers Legacy 5.7?
