### ISSUE TITLE
ScheduleCreateTransaction _scheduledTransaction is null after serialization

### ISSUE THREAD

**Issue by ArthHashPack** [hashgraph/hedera-sdk-js#1636]
### Description

When creating a ScheduleCreateTransaction, I am setting a TransferTransaction as the tx to schedule.  When I serialize the ScheduleCreateTransaction instance into bytes and deserialize it back into an instance of ScheduleCreateTransaction, the _scheduledTransaction is now null.  

When I try to access the tx info with _getScheduledTransactionBody(), the deserialized transaction instance doesn't have a scheduledTransactionBody where the original instance of the tx does have that info.  Is this the intended behavior?  If so, is there another way to access the scheduled transaction info after serialization?

### Steps to reproduce

The following code demonstrates the issue.  scheduledTx has a non null _scheduledTransaction and tx2 has a null _scheduledTransaction.  
```
    const tx =  new TransferTransaction()
        .addHbarTransfer(sender, -amount)
        .addHbarTransfer(recipient, amount)

    const scheduledTx = new ScheduleCreateTransaction()
        .setScheduledTransaction(tx)
        .freezeWith(client);

    const sch = scheduledTx._getScheduledTransactionBody()
    
    const bytes = scheduledTx.toBytes()
    const tx2 = ScheduleCreateTransaction.fromBytes(bytes)
    const sch2 = tx2._getScheduledTransactionBody()
```

### Additional context

This is an image of the debugger state after stopping execution at the end the above code sample.
![final_stroke](https://github.com/hashgraph/hedera-sdk-js/assets/40450705/37b242f9-50a3-4ebf-baa9-f6b1a759ab0c)

### Hedera network

testnet

### Version

2.24.2

### Operating system

Linux

**Comment by ochikov** [comment]
@ArthHashPack thank you for your issue. The fix will be released in the next version.
