### ISSUE TITLE
`Module parse failed in: Unexpected token` in export.js

### ISSUE THREAD

**Issue by ericleponner** [hashgraph/hedera-sdk-js#1641]
### Description

I'm trying to upgrade @hashgraph/sdk from 2.18.0 to 2.26.0 in [mirror-node-explorer](https://github.com/hashgraph/hedera-mirror-node-explorer).
When I build, I get the following error from webpack:

```
in ./node_modules/@hashgraph/sdk/src/exports.js

Module parse failed: Unexpected token (172:9)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| export { default as Logger } from "./logger/Logger.js";
| export { default as LogLevel } from "./logger/LogLevel.js";
> export * as EntityIdHelper from "./EntityIdHelper.js";
| 
| export { default as StatusError } from "./StatusError.js";

 @ ./node_modules/@hashgraph/sdk/src/browser.js 25:0-29 25:0-29
 @ ./src/utils/wallet/WalletManager.ts
 @ ./src/router.ts
 @ ./src/main.ts
 @ multi ./src/main.ts

 error  in ./node_modules/@hashgraph/sdk/src/client/Client.js

Module parse failed: Unexpected token (726:29)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|                 }
|             } catch (error) {
>                 this._logger?.trace(
|                     `failed to update client address book: ${
|                         /** @type {Error} */ (error).toString()

 @ ./node_modules/@hashgraph/sdk/src/client/WebClient.js 21:0-33 65:39-45
 @ ./node_modules/@hashgraph/sdk/src/browser.js
 @ ./src/utils/wallet/WalletManager.ts
 @ ./src/router.ts
 @ ./src/main.ts
 @ multi ./src/main.ts



 WAIT  Compiling...                                                                                                                                                                              9:40:14 AM



 ERROR  Failed to compile with 2 errors                                                                                                                                                          9:40:25 AM

 error  in ./node_modules/@hashgraph/sdk/src/exports.js

Module parse failed: Unexpected token (172:9)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| export { default as Logger } from "./logger/Logger.js";
| export { default as LogLevel } from "./logger/LogLevel.js";
> export * as EntityIdHelper from "./EntityIdHelper.js";
| 
| export { default as StatusError } from "./StatusError.js";

 @ ./node_modules/@hashgraph/sdk/src/browser.js 25:0-29 25:0-29
 @ ./src/utils/wallet/WalletManager.ts
 @ ./src/router.ts
 @ ./src/main.ts
 @ multi ./src/main.ts

 error  in ./node_modules/@hashgraph/sdk/src/client/Client.js

Module parse failed: Unexpected token (726:29)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|                 }
|             } catch (error) {
>                 this._logger?.trace(
|                     `failed to update client address book: ${
|                         /** @type {Error} */ (error).toString()

 @ ./node_modules/@hashgraph/sdk/src/client/WebClient.js 21:0-33 65:39-45
 @ ./node_modules/@hashgraph/sdk/src/browser.js
 @ ./src/utils/wallet/WalletManager.ts
 @ ./src/router.ts
 @ ./src/main.ts
 @ multi ./src/main.ts


```

### Steps to reproduce

1) Checkout  [mirror-node-explorer](https://github.com/hashgraph/hedera-mirror-node-explorer)
2) Change version of @hashgraph/sdk from 2.18.0 to 2.26.0 in package.json
3) npm run serve:prod

### Hedera network

mainnet

### Version

v2.26.0

### Operating system

macOS

**Comment by ochikov** [comment]
Hello, @ericleponner, and thank you for your issue.
I've created some modifications and released a new beta version for testing. Unfortunately, when I attach it to the mirror node explorer, it uses other packages as `@kabuto-sh`, `hashconnect` and their version is 2.26.0 which breaks the build again. I am continuing to investigate it. 

I've tried to use Babel plugins for Optional Chaining (?.) where the error was coming from. At the end, we rewrite this functionality. 

I've also created a React App with Typescript and tested it. It is running without any problems. 
I will test it with Vue and return to you ASAP.

**Comment by ochikov** [comment]
@ericleponner here is the update:
So I've created a Vue with Typescript and it is working. 
When we release the stable version 2.27.0, you will be able to change it to package.json and get it to work. 
Now if you put the current `2.27.0-beta.3` in package.json it will not work because `hashconnect` and `@kabuto-sh` are using versions with "^" and the last stable version is 2.26.0 which will lead to the same errors but from those two packages. I've removed them from your project, commented out some code, and left the `2.27.0-beta.3`. It's building successfully.

**Comment by ericleponner** [comment]
Hello @ochikov, thanks for investigating.
I will wait for 2.27.0 publication and redo my upgrade attempts.

**Comment by ochikov** [comment]
@ericleponner No worries. Will stay in touch for further updates/help if needed.

**Comment by ochikov** [comment]
@ericleponner can you test with the newest version?

**Comment by ericleponner** [comment]
@ochikov  It works :)
Thanks Ognyan.
