### ISSUE TITLE
Support Native gRPC Protocol for Backend node.js clients

### ISSUE THREAD

**Issue by nickpoorman** [hashgraph/hedera-sdk-js#1653]
### Problem

Frontend [web browsers cannot support the native gRPC protocol](https://grpc.io/blog/state-of-grpc-web/) due to the fact that gRPC uses HTTP2, and the grpc clients do not have the necessary access to the HTTP2 headers granted to them by the browsers. Due to this, [some nodes on the network](https://github.com/hashgraph/hedera-sdk-js/blob/d26bad11dab50c568ea2f380c4dfa841b2892f4c/src/constants/ClientConstants.js#L4) have a grpc-web proxy running in front of nodes.

This can cause problems in some scenarios.

### Solution

If a developer is using the hedera-sdk-js in the backend, they should be able to toggle the use of the native gRPC protocol directly, skipping the grpc-web proxy entirely and using the IPs reported from the address book from Mirror Node. It would appear this is done via the NodeClient, which is the default export for "Client" from index.js. However, this is rather confusing and with the lack of documentation, this is not immediately obvious.

### Alternatives

Update the documentation to include the different scenarios for the different types of clients.

_No response_

**Comment by gregscullard** [comment]
@nickpoorman the javascript SDK will instantiate a list of nodes that depends on the environment it's used in already.
* If the environment is a browser, it will use the grpc-web-proxies
* If the environment is node.js, it will use a direct connection (for node.js to make a grpc-web connection requires importing a specific library -see below- which the sdk doesn't import).

    "@improbable-eng/grpc-web": "^0.13.0",
    "@improbable-eng/grpc-web-node-http-transport": "^0.15.0",

**Comment by petreze** [comment]
@gregscullard 
Hey Greg, the SDK is set to use [grpc-js](https://www.npmjs.com/package/@grpc/grpc-js) library. I will take a closer look on these 2 that you pointed out

**Comment by nickpoorman** [comment]
@gregscullard I think it heavily relies on which "Client" the user imports/requires. Unless I'm mistaken, [this "browser" in package.json](https://github.com/hashgraph/hedera-sdk-js/blob/d26bad11dab50c568ea2f380c4dfa841b2892f4c/package.json#L15) is only a hint to bundlers like webpack.

If they import using the following method then they are going to get the [NodeClient via the index.js](https://github.com/hashgraph/hedera-sdk-js/blob/develop/src/index.js#L28).

```
const {
    Client,
} = require("@hashgraph/sdk");
```

**Comment by petreze** [comment]
Greetings @nickpoorman @gregscullard 
I was wondering if we can close this one, since for now we fixed the issues around the grpc calls and also the [grpc-js](https://www.npmjs.com/package/@grpc/grpc-js) library supports native gRPC communication?

**Comment by SimiHunjan** [comment]
Closing for now as resolved
