### ISSUE TITLE
[create-account.js]Receiving "undefined" for when the account ID is printed to the console

### ISSUE THREAD

**Issue by SimiHunjan** [hashgraph/hedera-sdk-js#167]
The create-account.js example prints "account = undefined" when it should print "account = <accountId>" 
![Screen Shot 2020-01-15 at 2 14 22 PM](https://user-images.githubusercontent.com/21989138/72476480-2ac4ed80-37a2-11ea-9385-62fd0c60f20e.png)

**Comment by Cooper-Kunz** [comment]
Hey @SimiHunjan which version of the SDK are you running?

I believe that it was renamed to `receipt._accountId` in v1 , instead of `receipt.accountId`

Although I'm not sure if that was intentional 😄 

If you print out the entire receipt, you should be able to see the ID and the new formatting.

**Comment by mehcode** [comment]
See: https://github.com/hashgraph/hedera-sdk-js/blob/master/CHANGELOG.md#changed-2

The fields were renamed to `getAccontId()` as opposed to `accountId`. 

The example does use `.getAccountId()` - https://github.com/hashgraph/hedera-sdk-js/blob/master/examples/create-account.js#L31

---

@Cooper-Kunz This is JavaScript and in JavaScript any `_` prefixed means the same as saying `private void method()` in Java. We should change the `.toString` to hide those.

**Comment by SimiHunjan** [comment]
Ok so the examples just need to be updated?

**Comment by mehcode** [comment]
I'm unsure where you are seeing the old example. It looks updated in master.

**Comment by Cooper-Kunz** [comment]
Hey @mehcode

**Comment by Cooper-Kunz** [comment]
> @Cooper-Kunz This is JavaScript and in JavaScript any _ prefixed means the same as saying private void method() in Java. We should change the .toString to hide those.

@mehcode helpful reminder. And thanks for the insight into the changelog.

**Comment by SimiHunjan** [comment]
Actually, you are right @mehcode  this was issue was logged 2 weeks ago so it was probably from an older version. Thanks!

**Comment by mehcode** [comment]
Apologies. I would have pointed it out but I didn't notice it was an older issue.
