### ISSUE TITLE
Issue with keys from Mnemonic

### ISSUE THREAD

**Issue by rahulasati** [hashgraph/hedera-sdk-js#168]
I am using following code to get private key from mnemonic

let mnemonicsResult = Mnemonic.fromString(mnemonics);
let privKey = await Ed25519PrivateKey.fromMnemonic(mnemonicsResult, "")
const privateKey = privKey.toString()
const publicKey = privKey.publicKey.toString()

above code works for one most of the mnemonics but not working some of the mnemonics  (account id : 0.0.1761)

SDK Version - 1.0.1

**Comment by mehcode** [comment]
Mnemonic phrases from before the "big mobile app update" will not work.

**Comment by rahulasati** [comment]
so how to handle that? is there any way we can identity such mnemonics or accountId's ?

**Comment by publu** [comment]
They work on myhbarwallet.com? but not on the new versions of the sdk

**Comment by mehcode** [comment]
> They work on myhbarwallet.com?

Is that a question? If the phrase in question works in MHW but not here, that is 100% a bug that needs investigating.

**Comment by rahulasati** [comment]
@mehcode yes it works on myhbarwallet.com

**Comment by mehcode** [comment]
I chatted with @publu on Discord. It seems there is some confusion about mnemonics in the community which is causing this.

```js
rootKey = Ed25519PrivateKey.fromMnemonic(PHRASE, PASSWORD)
actualKey = rootKey.derive(0)
```

`rootKey` should **never** be used directly. MHW assumes the above process and never looks at `rootKey` when accessing the account.

**Comment by rahulasati** [comment]
Case 1. if we use privatekey by derive(0) on Ed25519PrivateKey it works for older accounts but it wont works with mnemonics generated later.
Case 2. if we use privatekey as a rootKey without derive(0) it works with mnemonics generated after  "big mobile app update"  but it wont works with Older generated mnemonics.

So my question here is is there any other way to solve this apart from the hack if 1 fails try with the other approach @mehcode

**Comment by mehcode** [comment]
There is not. This just happens to be how HD keys work. It's unfortunate that we have two kinds of keys floating around.
