### ISSUE TITLE
Losing transaction signatures after transaction bytes encoding and decoding

### ISSUE THREAD

**Issue by pathornteng** [hashgraph/hedera-sdk-js#1705]
### Problem

Currently if we call `toBytes` to encode  the transaction into bytes and then call `fromBytes` to decode the transaction bytes into the transaction object, we lose the signatures. I am not sure if this is by design. Let me know if there is a way to preserve the signature while encoding and decoding.

### Solution

The following code can demonstrate the problem.

```
const transferTransaction = new TransferTransaction()
    .addHbarTransfer(myAccountId, -amount)
    .addHbarTransfer("0.0.3", amount)
    .freezeWith(client);
  const newPrivateKey = PrivateKey.generateED25519();
  const signedTx = await transferTransaction.sign(newPrivateKey);
  console.log("SignatureMap before", signedTx.getSignatures());

  const bytes = await signedTx.toBytesAsync();
  const tx = Transaction.fromBytes(bytes);
  console.log("SignaturesMap after " + tx.getSignatures());
```

**Comment by jaycoolslm** [comment]
@pathornteng thanks for creating this issue. I am looking to use this functionality.

I do want to note that in the tooltip for this method it reads:
```
Get the current signatures on the request

NOTE: Does NOT support sign on demand
```

Perhaps the .toBytes() method is considered sign on demand. Might this be the reason why the method is not working?

**Comment by petreze** [comment]
Hello, I tried also with `await getSignaturesAsync()` where there is a note: `Supports sign on demand` but the result is the same, so the issue is not there.
Will have a deeper look into this issue and keep you posted!

**Comment by petreze** [comment]
@pathornteng @jaycoolslm 
Hmm, I just noticed that in the provided example the second time you log the signatures you do it like this: `console.log("SignaturesMap after " + tx.getSignatures());`. Using the `"+"` operator will cast `toString()` to the `SignatureMap` object and a string representation will be returned in the end. However in the first logging statement you use `","` which passes the object as a separate argument to the log method and this is why it displays the data.

Try the second log like this: `console.log("SignaturesMap after ", tx.getSignatures());` and it should work as expected..

**Comment by jaycoolslm** [comment]
@petreze 

Even still, the mapping only contains one signature. It's not showing the other parties:

![Screenshot 2023-07-06 at 15 20 11](https://github.com/hashgraph/hedera-sdk-js/assets/86686746/3dc09f8d-2e03-4306-9e7d-6402cf49bb64)

**Comment by jaycoolslm** [comment]
Hi, yes I am specifically setting in to node account 3. This is because it is a prerequisite in order to convert it to bytes, right?

will i be able to view all the correct signatures if I setNodeAccounts to another account? Or am I mistaken in thinking nodeAccounts need to be set?

**Comment by petreze** [comment]
Hey @jaycoolslm 
Not exactly, you either have to set it explicitly or freeze the transaction before calling `toBytes()`. By freezing the transaction, the `nodeAccountIds` list gets populated with nodes from the specified network to which you are trying to connect. In a sense it is mandatory for `nodeAccountIds` to be set, the thing is that by freezing, the SDK does that under the hood

**Comment by jaycoolslm** [comment]
![Screenshot 2023-07-08 at 15 45 53](https://github.com/hashgraph/hedera-sdk-js/assets/86686746/b75e53db-4998-46bf-b853-0be3c5468511)
![Screenshot 2023-07-08 at 15 46 14](https://github.com/hashgraph/hedera-sdk-js/assets/86686746/0321443e-441d-4996-b0e2-d90f53516232)

**Comment by jaycoolslm** [comment]
Doesn't do it under the hood for me

**Comment by jaycoolslm** [comment]
Note:

The above error was caused because I was trying to sign the tx like this:

```
const signature = clientKey.signTransaction(associateTx);
associateTx.addSignature(clientKey.publicKey, signature);
```

When I did it like this:

`await associateTx.sign(clientKey);`

The one node Id set error doesn't arise

**Comment by jaycoolslm** [comment]
Right, so Ive resolved the issue:

Turns out, it's not because of the .setNodeAccounts() method.

Its because the signatures are found buried inside the node account signature map

Can be accessed like this

```
const nodeAccounts = tx.getSignatures();
	nodeAccounts._map.forEach((value, key) => {
		value._map.forEach((value, key) => {
			console.log('key', key);
		});
	});
```

**Comment by petreze** [comment]
@jaycoolslm 
Yes, thats what I meant exactly. It is a nested mapping
