### ISSUE TITLE
CONTRACT_REVERT_EXECUTED

### ISSUE THREAD

**Issue by amrierscuo** [hashgraph/hedera-sdk-js#1707]
### **1° case)**
I followed this tutorial https://docs.hedera.com/hedera/tutorials/smart-contracts/send-and-receive-hbar-using-solidity-smart-contracts, I setup correctly .env and all the modules then I've got the same problem unanswered from stackoverflow:
https://stackoverflow.com/questions/76125491/unkown-error-receipt-status-error-for-a-smart-contract-deployed-on-hedera
Here the problem is:
**How can I get more details about what causes this error to occur? And how can I fix it?** 

_I tried to answer partially this question in case 2 with an example_
--------------------------------------------------------------------------------------
### **2° Case)** I **want to interact with this contract with node js scripts and sdk**:
We have 2 account, an **owner** that can deposit hbar in the contract and a **recipient** that can withdraw.

```
_// SPDX-License-Identifier: GPL-3.0
pragma solidity ^0.8.1;

contract SimpleTransfer {

    address payable recipient;
    address owner;

    constructor(address payable _recipient) {
        recipient = _recipient;
        owner = msg.sender;
    }

    function deposit() public payable {
        require(msg.sender == owner, "only the owner can deposit");
    }

    function withdraw(uint256 amount) public {
        require(msg.sender == recipient, "only the recipient can withdraw");
        require(amount <= address(this).balance, "the contract balance is less then required amount");

        (bool success, ) = recipient.call{value: amount}("");
        require(success, "Transfer failed.");
    }

    function getRecipient() public view returns (address payable) {
        return recipient;
    }

    function getContractBalance() public view returns (uint256) {
        return address(this).balance;
    }
}_
```

First to start I notice Solidity has his own "address" and "address payable" referred standardly at Ethereum address or generally the EVM that we get from https://portal.hedera.com/ by creating an **ECDSA account , but if we use this we can not get signature for interact with the hedera testnet using node js, since INVALID_SIGNATURE** comes up, for some reason **ED25519 account with id and privk can handle the signature** on hedera so i opted for work with those account, 
in the .env we have MY_ACCOUNT_ID,MY_PRIVATE_KEY for owner and MY_ACCOUNT_ID2, MY_PRIVATE_KEY2 for the recipient. So create  your own for test it, remember that the priv key is HEX Encoded Private Key.

First we can deposit the contract bytecode id with store.js.
we get an id to copy and paste inside the deploy.js that take also the process.env.MY_ACCOUNT_ADDRESS2 which is supposed to insert in the contract his address for verify if it's the same of the signature from the withdraw.js, once executed it print the address of the recipient and the contract id

use balance.js for get the hbar balance of yours account

paste the contract id in deposit.js with the owner signature for execute.

it works, then the problem start with getRecipientAndContractBalance.js, we use it for retrieve the balance inside the contract(it works) and the address of the recipient (it doesn't work)

paste the contract id in the withdraw.js and you get the CONTRACT_REVERT_EXECUTED, it because we have that in the solidity contract:
 require(msg.sender == recipient, "only the recipient can withdraw"); 
 so in hashscan we will see "only the recipient can withdraw", it because we are not properly passing msg.sender == recipient in the right formats.
 
 **Ok so the problem is, how can i interact with the solidity contract address in the proper way?** 

### Steps to reproduce

unzip [simple-transfer.zip](https://github.com/hashgraph/hedera-sdk-js/files/11957394/simple-transfer.zip)

if modules are not installed: 
cd ..\simple-transfer

npm install
npm install --save @hashgraph/sdk
npm install dotenv

populate the .env with your credentials

node store.js
get the id  and put it in the appropriate place inside deploy.js, inside it be sure to pass also the recipient address

node deploy.js
get the id of the contract and put it inside, deposit.js,getRecipientAndContractBalance.js and withdraw.js

node balance.js
for see the balance of your accounts

node deposit.js
deposit tot hbar, 10 standard

node getRecipientAndContractBalance.js
part broken, we do not have stored properly the recipient address during deploy

node withdraw.js
CONTRACT_REVERT_EXECUTED

### Hedera network

testnet

### Version

v2.29.0

### Operating system

Windows

**Comment by amrierscuo** [comment]
I have found an idea that actually works for 2 ° case, maybe it the issue, working with byte32 instead, using hedera id and padding until 32 characters are reached 
Here what i changed:
SimpleTransfer.sol
`// SPDX-License-Identifier: GPL-3.0
pragma solidity ^0.8.1;

contract SimpleTransfer {
    bytes32 public recipient;
    address payable owner;

    constructor(bytes32 _recipient) {
        recipient = _recipient;
        owner = payable(msg.sender);
    }

    function deposit() public payable {
        require(msg.sender == owner, "only the owner can deposit");
    }

    function withdraw(uint256 amount, bytes32 withdrawerId) public {
        require(recipient == withdrawerId, "only the recipient can withdraw");
        require(amount <= address(this).balance, "the contract balance is less then required amount");

        (bool success, ) = owner.call{value: amount}("");
        require(success, "Transfer failed.");
    }

    function getRecipient() public view returns (bytes32) {
        return recipient;
    }

    function getContractBalance() public view returns (uint256) {
        return address(this).balance;
    }
}
`
store.js , .env , balance.js, and deposit.js still stay the same but:
deploy.js:
`const {
  Client,
  ContractCreateTransaction,
  ContractFunctionParameters,
  PrivateKey,
  Hbar,
} = require("@hashgraph/sdk");

require("dotenv").config();

const operatorPrivateKey = PrivateKey.fromString(process.env.MY_PRIVATE_KEY);
const operatorId = process.env.MY_ACCOUNT_ID;

let client = Client.forTestnet();
client.setOperator(operatorId, operatorPrivateKey);

client.setDefaultMaxTransactionFee(new Hbar(100));
client.setMaxQueryPayment(new Hbar(50));

function toBytes32(accountId) {
  const buffer = Buffer.from(accountId, 'utf8');
  if (buffer.length > 32) {
    throw new Error('Account ID is too long to fit in bytes32');
  }
  const bytes32 = Buffer.alloc(32);
  buffer.copy(bytes32);
  return bytes32;
}

async function deployContract(bytecodeFileId, recipientAddress) {
  const contractTx = new ContractCreateTransaction()
    .setBytecodeFileId(bytecodeFileId)
    .setGas(5000000) 
    .setConstructorParameters(new ContractFunctionParameters().addBytes32(toBytes32(recipientAddress))); 
  const contractResponse = await contractTx.execute(client);
  const contractReceipt = await contractResponse.getReceipt(client);

  const newContractId = contractReceipt.contractId;
  console.log("The smart contract ID is " + newContractId);
}

const recipientAddress = process.env.MY_ACCOUNT_ID2;
console.log("recipientAddress:", recipientAddress);
deployContract("0.0.15053099", recipientAddress).catch(console.error);
`
withdraw.js:
`const {
  Client,
  ContractExecuteTransaction,
  ContractFunctionParameters,
  PrivateKey,
  Hbar,
} = require("@hashgraph/sdk");

require("dotenv").config();

const operatorPrivateKey = PrivateKey.fromString(process.env.MY_PRIVATE_KEY2);
const operatorId = process.env.MY_ACCOUNT_ID2;
const recipientId = process.env.MY_ACCOUNT_ID2;

let client = Client.forTestnet();
client.setOperator(operatorId, operatorPrivateKey);

// Conversion function to turn a Hedera account ID into a bytes32 value
function toBytes32(accountId) {
  const buffer = Buffer.from(accountId, 'utf8');
  if (buffer.length > 32) {
    throw new Error('Account ID is too long to fit in bytes32');
  }
  const bytes32 = Buffer.alloc(32);
  buffer.copy(bytes32);
  return bytes32;
}

async function withdraw(contractId, amount, withdrawerId) {
  const withdrawTx = new ContractExecuteTransaction()
    .setContractId(contractId)
    .setGas(1000000)
    .setFunction("withdraw", new ContractFunctionParameters().addUint256(amount).addBytes32(toBytes32(withdrawerId)));

  const response = await withdrawTx.execute(client);
  const receipt = await response.getReceipt(client);

  console.log("Withdraw status: " + receipt.status.toString());
}

const hbarAmount = 5;
const tinybarAmount = hbarAmount * 100000000;


// Call the function, replace '0.0.15053101' and '5' with your own values
withdraw("0.0.15053101", tinybarAmount, recipientId).catch(console.error);

//withdraw("0.0.15053101", tinybarAmount, withdrawerId).catch(console.error);
`
Now th require works because of the paddle handling in bytes32.

I still can not resolve the case 1, but I hope it can be useful for someone.

**Comment by ochikov** [comment]
Hello @amrierscuo, thank you for your issue. We are going to investigate and return to you when we are ready.

**Comment by ochikov** [comment]
@amrierscuo 
You can use the token with Id (I've deployed it for you on testnet): 0.0.15337603
The result is as follows:
```
- Creating accounts...
- Created Treasury account 0.0.15341837 that has a balance of 100 ℏ
- Created Alice's account 0.0.15341861 that has a balance of 100 ℏ

- Deploying contract...
- The smart contract ID is: 0.0.15341871
- The smart contract ID in Solidity format is: 0000000000000000000000000000000000ea192f

- Token ID (for association with contract later): 0.0.15337603

====================================================
GETTING HBAR TO THE CONTRACT
====================================================
- Caller (Operator) PAYS 20 ℏ to contract (fallback/receive)...
- Contract balance (getBalance fcn): 20 ℏ

- Caller (Operator) PAYS 1000 ℏ to contract (payable function)...
0000000000000000000000000000000000ea192f
0000000000000000000000000000000000ea0883
contractId ContractId {
  shard: Long { low: 0, high: 0, unsigned: false },
  realm: Long { low: 0, high: 0, unsigned: false },
  num: Long { low: 15341871, high: 0, unsigned: false },
  evmAddress: null,
  _checksum: null
}
gasLimit 15000000
Params ContractFunctionParameters {
  _selector: ContractFunctionSelector {
    name: null,
    _params: 'address,address',
    _paramTypes: [ [Object], [Object] ]
  },
  _arguments: [
    { dynamic: false, value: [Uint8Array] },
    { dynamic: false, value: [Uint8Array] }
  ]
}
payableAmt 1000
- Contract balance (getBalance fcn): 1020 ℏ

```

Do you need other assistance, or I can close the issue as resolved?

**Comment by amrierscuo** [comment]
Yes, thank you!
