### ISSUE TITLE
Inconsistency with class name for submitting messages (consensus service)

### ISSUE THREAD

**Issue by SimiHunjan** [hashgraph/hedera-sdk-js#171]
Consensus Service - submit a message to a topic

Java SDK - ConsensusMessageSubmitTransaction
https://github.com/hashgraph/hedera-sdk-java/blob/master/src/main/java/com/hedera/hashgraph/sdk/consensus/ConsensusMessageSubmitTransaction.java

JS SDK - ConsensusSubmitMessageTransaction
https://github.com/hashgraph/hedera-sdk-js/blob/hcs/src/consensus/ConsensusSubmitMessageTransaction.ts

The spreadsheet has ConsensusMessageSubmitTransaction, but ConsensusSubmitMessageTransaction seems more intuitive.

**Comment by mehcode** [comment]
The convention established in Java is `<Noun><Verb>` like `TopicCreate` or `MessageSubmit`. Thanks for opening an issue before I released. I did forget to fix that.
