### ISSUE TITLE
client._mirrorNetwork.getNextMirrorNode() returns undefined in client side

### ISSUE THREAD

**Issue by wasinnimlaor** [hashgraph/hedera-sdk-js#1710]
### Description

My purpose is to [getTopiceMessage](https://docs.hedera.com/hedera/sdks-and-apis/sdks/consensus-service/get-topic-message) but got the error

![image (1)](https://github.com/hashgraph/hedera-sdk-js/assets/62790229/b0963fd2-03c8-4bb4-af92-1ddaf234a945)

The root cause is `client._mirrorNetwork.getNextMirrorNode()` returns `undefined` in client side, but has value in server side 

![image](https://github.com/hashgraph/hedera-sdk-js/assets/62790229/ee47a81c-b31f-4686-b9f2-fc1e5e01ec29)

### Steps to reproduce

1. create a Hedera client
2. try to call `getTopiceMessage` or `client._mirrorNetwork.getNextMirrorNode()`

### Hedera network

testnet

### Version

v2.0.0

### Operating system

macOS

**Comment by derek-meeco** [comment]
duplicate 
https://github.com/hashgraph/hedera-sdk-js/issues/1114
