### ISSUE TITLE
error status INSUFFICIENT_TX_FEE when creating a token.

### ISSUE THREAD

**Issue by shierve** [hashgraph/hedera-sdk-js#1714]
### Description

When trying to create a token using `TokenCreateTransaction()` I keep getting `INSUFFICIENT_TX_FEE` error even though I have enough hbar. It is happening while running unchanged scripts that previously worked correctly. If I set manually the max fee with `.setMaxTransactionFee(new Hbar(100))` then it works properly. There must be some error in fee estimation.

For the record the same error is shown when trying to create a token in Hashpack's 'Demo dApp' which is likely using this SDK, and has no option to set the max fee manually.
![image](https://github.com/hashgraph/hedera-sdk-js/assets/10463860/7843a607-ab87-4805-b0aa-bee12a9ba7c2)

### Steps to reproduce

Here is an example transaction that fails:
```
let transaction = await new TokenCreateTransaction()
        .setTokenType(TokenType.FungibleCommon)
        .setTokenName("metacoken")
        .setTokenSymbol("MTC-A")
        .setTokenMemo("Metaco token for guaranteed profits")
        .setDecimals(3)
        .setInitialSupply(1000)
        .setTreasuryAccountId(wallet.getAccountId())
        .setFeeScheduleKey(wallet.getAccountKey())
        .setFreezeDefault(false)
        .freezeWithSigner(wallet);
    transaction = await transaction.signWithSigner(wallet);
    let resp = await transaction.executeWithSigner(wallet);
```
Where wallet is a wallet with more than enough hbar. When adding `.setMaxTransactionFee(new Hbar(100))` it works properly.

### Hedera network

testnet

### Version

2.29.0

### Operating system

None

**Comment by petreze** [comment]
@shierve 
This happens because of the pricing in Hedera. As it is fixed for any given transaction and the price fluctuation of the HBAR token, you would have to adjust the `transactionFee` via `setMaxTransactionFee()` method whenever there is volatility in the price of the token. In regards to the `TokenCreateTransaction`, the default value is 30 hbars, so you can start incrementing from there
