### ISSUE TITLE
Cannot use @hashgraph/proto with sample vue app

### ISSUE THREAD

**Issue by ericleponner** [hashgraph/hedera-sdk-js#1718]
### Description

I created a sample app using `vuejs` [quick start guide](https://vuejs.org/guide/quick-start.html#creating-a-vue-application) (I selected `typescript`) and added a call to `Key.decode()` in it.
`Key.decode()` crashes and it looks like javascript vm is unable to resolve module `hashgraph.proto`.

I tried various compiler options without luck.
I wonder if `hashgraph.proto` module is correctly setup (?).

### Steps to reproduce

1) clone https://github.com/ericleponner/sample-vue-app
2) npm install
3) npm run dev
4) browse http://localhost:5173

=> page displays message "Key not decoded"
=> browser console displays:
`HelloWorld.vue:20 Failed to decode key: TypeError: Cannot read properties of undefined (reading 'proto') (anonymous) @ HelloWorld.vue:20 `

### Hedera network

testnet

### Version

2.12.0

### Operating system

macOS

**Comment by ericleponner** [comment]
I found a workaround.

 I replaced:
`import hashgraph from "@hashgraph/proto";`
by 
`import * as hashgraph from "@hashgraph/proto";`

Now `Key.decode()` works correctly…

**Comment by ochikov** [comment]
@ericleponner It's used in the same manner in the JS SDK. This is the right way of the import.

**Comment by ericleponner** [comment]
@ochikov
It's unfortunate because IntelliJ completion logic proposes the **wrong** way and `typescript 5` happily compiles it. 
It's only at runtime that everything breaks mysteriously.

In fact, I thought this two forms of import were syntactically equivalent. 
Wouldn't it be possible for `hedera-sdk-js `to support both forms ? 
It could save hours in some cases…

**Comment by ochikov** [comment]
To be honest, I thought the same. I will research and keep you updated about the imports and the support.

**Comment by ochikov** [comment]
Hello @ericleponner,
I dig a little bit into it. The proto package does not export "hashgraph". The package exports:
```
Reader
Writer
proto
com
google
```
Based on that exports, when you have the line: 
```
import hashgraph from "@hashgraph/proto";
```
it is actually `undefined`. That's why it is compiled, but on runtime, it fails. 
The correct way (based on the exports of the package) is to use some of the following imports:

```
import * as `something` from "@hashgraph/proto";
```
or
```
import { proto } from "@hashgraph/proto";
```

I am not sure if the proto package is exported as `hashgraph`, that it will introduce a breaking change.
I am still digging the IntelliJ wrong completion logic.

**Comment by ericleponner** [comment]
Hello @ochikov 

It tested with the following statement:
`import { proto } from "@hashgraph/proto"`
it compiles and runs fine (after I renamed `hashgraph.proto.Key` as `proto.Key` obviously).
I guess I will keep this form in HashScan code.

Why IntelliJ is not proposing this automatically ? Strange … 
During my debugging, I read about `default export` in js package: may be something to verify in `proto` package.

Thanks for investigating Ognyan.

**Comment by ochikov** [comment]
Hello @ericleponner, I wasn't able to discover why your setup is suggesting the wrong import format. I will close the issue.

**Comment by ericleponner** [comment]
Ok. Thanks for investigating.
