### ISSUE TITLE
Invalid default renewal period for HCS

### ISSUE THREAD

**Issue by Cooper-Kunz** [hashgraph/hedera-sdk-js#174]
I'm attempting to run a `ConsensusTopicCreateTransaction()` on `testnet` 🎊  

Unfortunately, I get this error:

```
HederaError: Hedera returned response code: INVALID_RENEWAL_PERIOD (70)
```

Here's the code I'm attempting to run against `0.testnet.hedera.com:50211`

```
const HederaClient = require("../hedera-client");

const { ConsensusTopicCreateTransaction } = require("@hashgraph/sdk");

async function main() {
  const transaction = await new ConsensusTopicCreateTransaction()
    .execute(HederaClient);

  const record = await transaction.getRecord(HederaClient);
  console.log("record:", record);

  const newTopicId = record.receipt._topicId;
  console.log("new HCS topic ID:", newTopicId);
}

main();
```

What's the default renewal period, or valid range for an HCS topic? 
Will the SDK default to this, similarly to Files/Contracts? 

Separately, it'd be nice if `INVALID_RENEWAL_PERIOD` could display which tx triggered the error.

**Comment by mike-burrage-hedera** [comment]
This appears to have been fixed in #172 - can you confirm?

**Comment by mehcode** [comment]
Pretty sure this is fixed on master now. We just need to cut a release. This will happen very soon.

**Comment by Cooper-Kunz** [comment]
Seems working on master 💯 

```
require("dotenv").config();

const HederaClient = require("./hedera-client");
const { ConsensusTopicCreateTransaction } = require("@hashgraph/sdk");

async function main() {
  const tx = await new ConsensusTopicCreateTransaction().execute(HederaClient);
  console.log("tx:", tx);

  const record = await tx.getRecord(HederaClient);
  console.log("record:", record);

  const newTopicId = record.receipt._topicId;
  console.log("new HCS topic ID:", newTopicId);
}

main();
```

`
new HCS topic ID: ConsensusTopicId { shard: 0, realm: 0, topic: 155262 }
`

Thanks for the help!
