### ISSUE TITLE
`AccountId.fromSolidityAddress()` should result in a valid AccountId

### ISSUE THREAD

**Issue by mgarbs** [hashgraph/hedera-sdk-js#1740]
### Description

When I run this code with a valid ECDSA public key(`0xdfc61db3604e254611827ecf0d42e6f4b2e256ac`):
```js   
const operatorId = AccountId.fromSolidityAddress(process.env.ECDSA_PUBLIC_KEY_TEST as string);
console.log(operatorId.toString())
````

My result is not correct: `3754302899.6939525058696216271.955580009603552940`

I would expect it to be: `0.0.1367`

### Steps to reproduce

1. Run the code snippet
2. Observe the result

### Hedera network

testnet

### Version

^2.30.0

### Operating system

macOS

**Comment by petreze** [comment]
Hey @mgarbs 
We are aware of this and I created a more generic issue inside the [reference repo](https://github.com/hashgraph/hedera-sdk-reference/issues/128) in order to see the entire reasoning and discuss approaches

**Comment by petreze** [comment]
Closing this one as it is addressed inside the [generalized issue](https://github.com/hashgraph/hedera-sdk-reference/issues/128) and it will be fixed after we make a decision and implement the call to the mirror node to get the actual `num` field of the `AccountId`. A new ticket will be open in all SDKs in regards to that
