### ISSUE TITLE
Failed to fetch Error --> (.execute()) (FrontEnd Execution)

### ISSUE THREAD

**Issue by AdrianKBL** [hashgraph/hedera-sdk-js#1744]
### Description

Good afternoon,

Lately we are having a lot of reports from different customers about having problems when minting. Remember that our Minting Platform execute the transactions in FrontEnd directly. I have been debugging it in Mainnet and looks like it is"totally ramdom". Sometimes happens when you have minted 100 NFTs, sometimes when you minted 300 and sometimes when you minted 4k. Today I tested with 4k NFTs and I got the same error 3 times. Also remember that our flow is:

10 NFTs minted at once (In the same transaction) + x1 Hbar Transfer 
![image](https://github.com/hashgraph/hedera-sdk-js/assets/59306428/540dec59-2a4e-42c0-a64c-205fbf5ea23e)

 

### Steps to reproduce

 ```js
  let mintTx = new TokenMintTransaction()
      .setMaxTransactionFee(new Hbar(maxFee))
      .setTokenId(tokenId);
    if (amount) mintTx.setAmount(amount);
    if (metadata) mintTx.setMetadata(metadata);
    mintTx.freezeWith(client);
    const mintTxSign = await mintTx.sign(supplyKey);
  const mintTxResponse = await mintTxSign.execute(client);
  const transactionId = mintTxResponse.transactionId
  return handleReceiptV2(transactionId, client);
  ```

```js
const handleReceiptV2 = async (transactionId, client) => {
  let receiptQuery = new TransactionReceiptQuery().setTransactionId(
    transactionId
  );

  let receipt = {
    data: null,
    error: null
  };

  try {
    receipt.data = await receiptQuery.execute(client);
    receipt.error = null;
  } catch (error) {
    console.log('Receipt fails, retrying...error:' + error);
    receipt.error = error;
  }
  ```
 We also can see the same error in this execution: 
 
 ```js
  new AccountBalanceQuery()
      .setAccountId(accountId)
      .execute(client);
```

Both of them due to: 
```js
 TypeError: Failed to fetch\n' +
     'at e.eval [as rpcImpl] (webpack-internal:///./node_modules/@hashgraph/sdk/src/channel/WebChannel.js:68:40)\n' +
     'at e.rpcCall (webpack-internal:///./node_modules/protobufjs/src/rpc/service.js:94:21)\n'




### Additional context

_No response_

### Hedera network

mainnet

### Version

2.29.0

### Operating system

Windows

**Comment by petreze** [comment]
@AdrianKBL 
Yesterday I was able to reproduce it but as you said, totally randomly. Could not find any dependence for now. Will update you if I find anything!

**Comment by AdrianKBL** [comment]
Thanks you @petreze as always! We have more customers with this problem each day :(

**Comment by SimiHunjan** [comment]
hey @AdrianKBL ! We are continuing to invest with internal teams.

**Comment by AdrianKBL** [comment]
Hello @petreze I've updated and I ran 3 tests. Now I get the error way way faster than before, usually always before I hit the 100 NFTs minted.

![image](https://github.com/hashgraph/hedera-sdk-js/assets/59306428/3ff9cc36-dace-4003-80a5-59d683d13fb1)

**Comment by petreze** [comment]
@AdrianKBL 
Did you try by increasing the `maxAttempts` value?

**Comment by AdrianKBL** [comment]
That doesn't change anything @petreze , in thousands of tests we setup to more and when fails more than 5 times, doesn't matter what you put that never recover from that, that's why we even decreased it.

**Comment by petreze** [comment]
@AdrianKBL Still cannot reproduce it, will update you ASAP
Is this happening on testnet as well?

**Comment by petreze** [comment]
@AdrianKBL 
Hello, we found that 2 of the web proxy nodes on mainnet are not available plus several others that are significantly more problematic. I released `2.32.0-beta.2` version for you to test without those nodes!

Also, just keep in mind that those 5** errors might come from your local network connection. It can be due to bad internet connection, firewall settings, browser settings, browser cache and so on. From an SDK side, I think we are good

**Comment by AdrianKBL** [comment]
Hello @petreze 

I can assure you that these errors can't be due to any of these reasons. My internet connection is 5 GB, I don't have firewall and all my tests are done with clear browser without cache & cookies.

I guess most of the errors arrive due to these 2 web proxies that weren't available on Mainnet, now looks like everything is good.

Thanks you!

**Comment by petreze** [comment]
Glad to hear that!
I'm just going to release a stable version today with all these fixes! If something additionally appears, re-open or open a new ticket!
