### ISSUE TITLE
Add retry logic on .getReceipt for network response "Unknown"

### ISSUE THREAD

**Issue by SimiHunjan** [hashgraph/hedera-sdk-js#1806]
### Problem

As a developer, I need to get the receipt of a transaction to validate the transaction was successful or to get data from the transaction that executed which is returned in the receipt.

If I ask for the receipt and the receipt returns a status of Success then do not retry to get the receipt of the transaction.
If I ask for the receipt and receipt returns "Unknown" retry attempting to get the receipt. Unknown means that the status of returning the receipt or not is unknown https://github.com/hashgraph/hedera-protobufs/blob/main/services/response_code.proto#L147.

### Solution

- Review the getReceipt logic that is implemented in the SDK
- Retry getting the receipt on an "Unknown" status
- Test the feature works as expected when "Unknown" is returned

**Comment by petreze** [comment]
@SimiHunjan 
Hey Simi, just tested it and it retries on encountering `Unkown`. This applies to `getRecord()` as well !
Keep in mind that although [here](https://github.com/hashgraph/hedera-sdk-js/blob/develop/src/transaction/TransactionResponse.js#L76-L92) we do not check, when we execute `this.getReceiptQuery().execute()`, we go through [this flow](https://github.com/hashgraph/hedera-sdk-js/blob/develop/src/transaction/TransactionReceiptQuery.js#L204) of execution and there are the checks for retrying on several statuses
