### ISSUE TITLE
Add HIP-745: Optionally send transaction data without required transaction fields 

### ISSUE THREAD

**Issue by SimiHunjan** [hashgraph/hedera-sdk-js#1807]
### Problem

HIP-745 is an application level HIP which introduces a way to create transactions without the notion of throwing errors if the transaction being created does not have all the required fields before signing. The required fields would need to be in place before the transaction is signed, but the dapp should be able to send, for example, an incomplete transaction to the wallet and allow the wallet to assign other transaction properties before it presents it to the user to sign.

HIP: https://hips.hedera.com/hip/hip-745

### Solution

- Design the feature for the SDK
- Review the design with the team
- Implement the feature
- Release the feature

```[tasklist]
### Tasks
- [ ] https://github.com/hashgraph/hedera-sdk-js/issues/1808
```

**Comment by petreze** [comment]
Left a comment inside the [reference repo](https://github.com/hashgraph/hedera-sdk-reference/issues/127#issuecomment-1706057436)
