### ISSUE TITLE
Missing "_logger"

### ISSUE THREAD

**Issue by flomar12** [hashgraph/hedera-sdk-js#1809]
### Description

Im using the Hedera SDK v2.31.0 on NestJS and i get the following error on "transaction.execute()": 

TypeError: Cannot read properties of undefined (reading '_logger')

I tried to set the logger through "client.setLogger" but the error remains.

### Steps to reproduce

1. Create NestJs Project (ng new test-project) 
2. Install Hedera SDK  (npm install --save @hashgraph/sdk)
3. Setup a client 
4. Execute any type of transaction (AccountCreate, TopicCreate,...) 
5.Error occurs
"TypeError: Cannot read properties of undefined (reading '_logger')
at AccountCreateTransaction.execute (/Users/xyz/WebstormProjects/xyz-backend/node_modules/@hashgraph/sdk/lib/Executable.cjs:516:50)"

### Hedera network

other

### Version

2.31.0

### Operating system

None

**Comment by chihabhajji** [comment]
@flomar12 , can you provide any instructions on how you were able to resolve this issue since you closed it (it still persists on 2.40.0)
