### ISSUE TITLE
fix: ContractFunctionParameters#addAddress(param) should accept param type of EvmAddress

### ISSUE THREAD

**Issue by bguiz** [hashgraph/hedera-sdk-js#1816]
### Problem

`ContractFunctionParameters#addAddress(param)`:

* currently errors when you pass in `param` value of `TransactionRecord#children[0]?.evmAddress` (type `@hashgraph/sdk/lib/EvmAddress.d.ts`)
    * `Error: `address` type requires parameter to be 40 or 42 characters`
* but it is OK with `TransactionRecord#children[0]?.evmAddress.toString()` (type `string`)

### Solution

 * This method should accept *both* `string` and `EvmAddress` types as parameters
 * This is not a bug per se, rather I'd consider it a potential developer friction point

### Alternatives

* Nil

**Comment by petreze** [comment]
@bguiz 
Thank you for your suggestion. I've added this possibility and also enhanced the `ContractFunctionParameters.addAddressArray()` method to also be able to handle `EvmAddress` as an input parameters!
