### ISSUE TITLE
Parity BaseClient.ts methods

### ISSUE THREAD

**Issue by SimiHunjan** [hashgraph/hedera-sdk-js#184]
Java SDK:

```
getMaxQueryPayment()
getMaxTransactionFee()
```
https://github.com/hashgraph/hedera-sdk-java/blob/master/src/main/java/com/hedera/hashgraph/sdk/Client.java

JS SDK:

```
maxQueryPayment
maxTransactionFee
```
https://github.com/hashgraph/hedera-sdk-js/blob/master/src/BaseClient.ts

**Comment by cacampbell** [comment]
Private fields are accessible in JS, yes

**Comment by mehcode** [comment]
@SimiHunjan Short answer. Those methods were never _supposed_ to exist.

---

I don't personally think they're useful acessers and I'm fine with deprecating (forever) the methods from both SDKs unless you have an objection there.

**Comment by mehcode** [comment]
We've added deprecation warnings for those methods. If anyone thinks they are useful, please feel free to re-open for discussion.
