### ISSUE TITLE
Random 403 errors

### ISSUE THREAD

**Issue by teacoat** [hashgraph/hedera-sdk-js#1858]
### Description

We have had various users come to us with 403 errors when doing transactions - the error being "max attempts of 10 was reached with last error being: HttpError: failed with code 403"

This has happened since we updated from v2.24.x to v2.32.x

### Steps to reproduce

We are unable to reproduce it

### Hedera network

mainnet

### Version

2.32.0

### Operating system

https://github.com/hashgraph/hedera-sdk-js/assets/3913019/ebc82497-273d-498c-bb86-20440ff17ee4

None

**Comment by SimiHunjan** [comment]
User is based in Macedonia, which is currently part of the OFAC block list on mainnet. 

When the block list was updated, it included countries and areas which are subject to OFAC sanctions based on the information contained here: https://ofac.treasury.gov/sanctions-programs-and-country-information . Balkans related sanctions (which includes parts of Macedonia) were updated on July 31st, 2023, and as part of that update some parts of Macedonia were added to the IP block list of the third party provider we were using to provide IP blocking compliance services. However, we believe that those IP blocks provided to us were over-inclusive, and we plan to shortly re-deploy the blocklist to only block these comprehensively sanctioned regions: Cuba, Iran, Syria, the Democratic Republic of North Korea, the Crimea, and the So-called Republic of Luhansk and the So-called Republic of Donetsk.

**Comment by SimiHunjan** [comment]
The OFAC block list was updated and Macedonia was removed from the list. The user will be asked to try again.

**Comment by SimiHunjan** [comment]
@teacoat is the user still experiencing this error?

**Comment by teacoat** [comment]
User is now able to complete transactions
