### ISSUE TITLE
What could cause this error

### ISSUE THREAD

**Issue by teacoat** [hashgraph/hedera-sdk-js#1861]
### Description

We see this error quite often and I have been unable to nail down the root cause:

![image](https://github.com/hashgraph/hedera-sdk-js/assets/3913019/c4386f3c-3a64-454b-95b6-62e254e165bf)

### Steps to reproduce

Unknown

### Hedera network

mainnet

### Version

2.32.0

### Operating system

None

**Comment by petreze** [comment]
As it suggests, you should either freeze the transaction via `tx.freezeWith(client)` or set the `transactionId` explicitly before submitting
