### ISSUE TITLE
2.34.0 breaking change

### ISSUE THREAD

**Issue by teacoat** [hashgraph/hedera-sdk-js#1884]
### Description

Something in the new version is incompatible with older versions, it seems to have to do with transaction ID not being a string or something? A bunch of dapps seem to be trying to run string manipulation functions on transaction id to format it for mirrornode calls and updating hashpack to 2.34.0 breaks as it seems to be returning transactionId as an object now

### Steps to reproduce

N/A

### Additional context

![image](https://github.com/hashgraph/hedera-sdk-js/assets/3913019/00637971-d2e7-47be-aab7-fd3ba14767e8)

![image](https://github.com/hashgraph/hedera-sdk-js/assets/3913019/6472ae0e-c7f6-4147-9630-7b6a777599e6)

### Hedera network

mainnet

### Version

2.34.0

### Operating system

None

**Comment by teacoat** [comment]
Off the top of my head, could this have to do with converting a response .toBytes() then rebuilding it using .fromBytes()?

**Comment by petreze** [comment]
@teacoat 
How do you get the transactionId here on these occurrences?

**Comment by petreze** [comment]
Ah I think I found the issue - is it after you use `TransactionResponse.toJSON()`?

**Comment by teacoat** [comment]
@petreze yes i tested it with 2.33.0 and it introduced no issues - however the dapps that are recieving the data are likely using an older version of the sdk. I am not using .toJson on my side of the code, not sure about the dapps.

**Comment by teacoat** [comment]
However they are likely using .fromBytes on the receipt 
![image](https://github.com/hashgraph/hedera-sdk-js/assets/3913019/86320c00-057d-4b53-92ad-e1b3987ba96c)

The flow looks like:
Dapp creates transactions in older version > sends bytes to hashpack > hashpack executes using new version > hashpack gets receipt > hashpack converts receipt toBytes using new version > sends back to dapp > dapp does .fromBytes using old version > dapp throws error trying to run string manipulation on transactionId that previously worked

**Comment by petreze** [comment]
@teacoat shortly releasing v2.34.1 and would suggest to test with it again!

**Comment by petreze** [comment]
@teacoat 
Done, can you try please with it?

**Comment by petreze** [comment]
@teacoat 
Sweet, happy to hear that!
