### ISSUE TITLE
FileContentsQuery().executeWithSigner(signer) return undefined

### ISSUE THREAD

**Issue by wasinnimlaor** [hashgraph/hedera-sdk-js#1951]
### Description

`FileContentsQuery().executeWithSigner(signer)` returns `undefined` but `FileContentsQuery().execute(client)` return file contents.

`executeWithSigner` method is working fine with transactions but return `undefined` when using with `FileContentsQuery`.

![image](https://github.com/hashgraph/hedera-sdk-js/assets/62790229/4d629865-854a-4d82-bfa5-d5fd14871719)

![image](https://github.com/hashgraph/hedera-sdk-js/assets/62790229/0412bb5c-c107-4d61-b5b6-e8c9ca0d1276)

### Steps to reproduce

1. call `FileContentsQuery().executeWithSigner(signer)` with HashConnect Signer, then view result
2. call `FileContentsQuery().execute(client)` with client instance, then view result

### Hedera network

testnet

### Version

2.34.1

### Operating system

macOS

**Comment by ochikov** [comment]
Hello @wasinnimlaor and thanks for the bug. I've used the following code:

```
 const wallet = new Wallet(
        process.env.OPERATOR_ID,
        process.env.OPERATOR_KEY,
        new LocalProvider()
    );

    const resp = await new FileContentsQuery()
        .setFileId("0.0.112")
        .executeWithSigner(wallet);
    console.log("Responce", resp);
    
```
and the response is as follows:
```ognyanchikov@Ogis-MacBook-Pro hedera-sdk-js % node examples/get-exchangerates.js
Responce <Buffer 0a 0c 08 01 10 0c 1a 06 08 80 ae 99 a4 0f 12 0c 08 01 10 0f 1a 06 08 80 ae 99 a4 0f>
```
You can find it in the examples folder:
examples/get-exchangerates.js

You can also copy your non-working code here in order to test it.

**Comment by wasinnimlaor** [comment]
Hi @ochikov , thank you for your response. I think the way you and I use `executeWithSigner` is the same, but how we create signer or provider are different. Mine use Hashconnect's `getProvider` and `getSigner`, yours is `new Wallet`.

Could this possible to be the root cause, like there's a bug from Hashconnect library?

https://github.com/Hashpack/hashconnect#providersigner

![image](https://github.com/hashgraph/hedera-sdk-js/assets/62790229/e4413cc1-0716-4ad6-b1f9-ebad549b252f)

**Comment by ochikov** [comment]
Hello @wasinnimlaor,
I was able to reproduce it using hashconnect. 
Indeed the return is undefined. I will try to understand whether the problem is in the hash-connect or in the SDK.

![Screenshot 2023-10-09 at 16 39 59](https://github.com/hashgraph/hedera-sdk-js/assets/13587218/064d26f1-daef-4700-a113-dfefa3694bb1)

I will continue to dig into it.

**Comment by ochikov** [comment]
I think all the Querries are returning undefined:
```
 const balance = await new AccountBalanceQuery()
      .setAccountId(accountId.innerHTML)
      .executeWithSigner(signer);

    console.log(balance);
   
I've tested with `AccountBalanceQuery` as well. The result is `undefined`

**Comment by ochikov** [comment]
Hey @wasinnimlaor, as I promised, I've spent some time and performed the following actions as for you, maybe point 3 is the most interesting:

1. Tried to do the `Query` transaction in the scope of the hashconnect:
```
 const tx = new AccountBalanceQuery().setAccountId(accountId.innerHTML);

    const transactionBytes = await makeBytes(tx, accountId.innerHTML);

    const transaction = {
      topic: pairingData.topic,
      byteArray: transactionBytes,

      metadata: {
        accountToSign: accountId.innerHTML,
        returnTransaction: true,
      },
    };
    const response = await hashconnect?.sendTransaction(
      pairingData.topic,
      transaction
    );

    console.log("responce:", response);
    
but I am getting the following error:
<img width="726" alt="Screenshot 2023-10-11 at 13 46 14" src="https://github.com/hashgraph/hedera-sdk-js/assets/13587218/c0426183-f030-4103-a951-ed8b759945f2">
```
2. Then tried with `transaction`:

```
 function makeBytes(trans, signingAcctId) {
      let transId = TransactionId.generate(signingAcctId);
      trans.setTransactionId(transId);

      let nodeId = 5;

      trans.setNodeAccountIds([new AccountId(nodeId)]);

      trans.freeze();

      let transBytes = trans.toBytes();

      return transBytes;
    }

    const tx = new TokenAssociateTransaction();
    tx.setTokenIds(["0.0.4520159"]);
    tx.setAccountId(accountId.innerHTML);

    const transactionBytes = await makeBytes(tx, accountId.innerHTML);

    const transaction = {
      topic: pairingData.topic,
      byteArray: transactionBytes,

      metadata: {
        accountToSign: accountId.innerHTML,
        returnTransaction: true,
      },
    };
    const response = await hashconnect?.sendTransaction(
      pairingData.topic,
      transaction
    );

    console.log("responce:", response);
```
and I am getting response:
<img width="717" alt="Screenshot 2023-10-11 at 13 38 30" src="https://github.com/hashgraph/hedera-sdk-js/assets/13587218/16e7c59a-53da-45aa-a14a-5861cf202787">

3. After that I remembered that for Query, we can do it directly with client/provider and no signature is required, so the code:

```
  const balance = await new AccountBalanceQuery()
      .setAccountId(accountId.innerHTML)
      .execute(provider.client  );

    console.log(balance);
    ```
Is working and return result is as follows:

![Screenshot 2023-10-11 at 14 32 41](https://github.com/hashgraph/hedera-sdk-js/assets/13587218/a9152a95-e13b-4179-b0b9-c9fb62bb795b)

**Comment by wasinnimlaor** [comment]
Hi @ochikov , thank you for the follow up. I've tried to use client from `HashConnectProvider` before but I got this error.

![image](https://github.com/hashgraph/hedera-sdk-js/assets/62790229/6d65d6b3-317b-4497-b323-9901f61a79d5)

![image](https://github.com/hashgraph/hedera-sdk-js/assets/62790229/0b26edc2-de85-4be0-9d09-d7a78cc6e875)

<img width="639" alt="image" src="https://github.com/hashgraph/hedera-sdk-js/assets/62790229/73b7adf3-6be4-4888-b63c-8510aadedb43">


So maybe both `executeWithSigner` and `client.provider` issues came from Hashconnect side?

**Comment by wasinnimlaor** [comment]
For me `executeWithSigner` is working fine with any `transaction`, but it returns `undefined` when using with `query`

**Comment by wasinnimlaor** [comment]
The interesting thing is client form `Client.forTestnet()`(@hashgraph/sdk) has `operator` property but `provider.client`(hashconnect)'s `operator` is null


_client form `Client.forTestnet()`(@hashgraph/sdk)_
<img width="914" alt="image" src="https://github.com/hashgraph/hedera-sdk-js/assets/62790229/32056baf-27be-4b0f-b891-c7465bc36830">

![image](https://github.com/hashgraph/hedera-sdk-js/assets/62790229/4fabbfc4-010d-4c7a-8484-4231657094af)


_`provider.client`(hashconnect)_
![image](https://github.com/hashgraph/hedera-sdk-js/assets/62790229/8e3eef36-02f0-4cf1-93d1-1207aa5ee1e2)

so that's explain why I got this error when I as trying to use `execute` with provider.client`(hashconnect)

![image](https://github.com/hashgraph/hedera-sdk-js/assets/62790229/a5535d84-3e8e-46cd-978e-3e666cd03423)

**Comment by wasinnimlaor** [comment]
Yeah, looks like they're not planning to support `query` with their `provider.client`

https://github.com/Hashpack/hashconnect/issues/111

![image](https://github.com/hashgraph/hedera-sdk-js/assets/62790229/055e8e97-a78b-4146-9f85-13b086e7b384)

**Comment by ochikov** [comment]
Hello @wasinnimlaor, @teacoat answered me, that they are not supporting `query`, because nobody uses them cause it costs money and it's a bad pattern

**Comment by wasinnimlaor** [comment]
Hi @ochikov, thank you so much for effort and response. We've agreed to not do this query and find the new solution for this issue.
