### ISSUE TITLE
How to use this repo to deploy a simple smart contract (solidity)

### ISSUE THREAD

**Issue by zydjohnHotmail** [hashgraph/hedera-sdk-js#1965]
### Description

How to deploy smart contract on Hedera testnet blockchain?

Hello:
I am new to this blockchain, but I have quite some experience with other blockchains. I have applied for an acocunt with Hedera blockchain and have some testnet tokens.
Here I can use the following JavaScript code to get my account balance:

import { Wallet, LocalProvider, AccountBalanceQuery } from "@hashgraph/sdk";
import dotenv from "dotenv";

dotenv.config();

async function main() {
  if (process.env.ACCOUNT_ID == null || process.env.PRIVATE_KEY == null) {
    throw new Error(
      "Environment variables ACCOUNT_ID, and PRIVATE_KEY are required."
    );
  }

  const wallet = new Wallet(
    process.env.ACCOUNT_ID,
    process.env.PRIVATE_KEY,
    new LocalProvider()
  );

  const balance = await new AccountBalanceQuery()
    .setAccountId(wallet.getAccountId())
    .executeWithSigner(wallet);

  console.log(
    `${wallet
      .getAccountId()
      .toString()} balance = ${balance.hbars.toString()}`
  );
}

void main();

setTimeout(() => {
  process.exit(0);
}, 3000);

D:\nodejs\hedra-project>node AccountBalance.js
0.0.4470974 balance = 10000 ℏ

D:\nodejs\hedra-project>
So I have 1000 testnet tokens, it is enough to deploy some smart contract.

I have the following HelloWorld.sol file:
// SPDX-License-Identifier: MIT
pragma solidity ^0.8.0;

contract HelloWorld {
  function sayHello() public pure returns (string memory) {
    return "Hello World";
  }
}

Using Remix, I can complie and get its bytecode, so I write the following JavaScript, trying to deploy this simple smart contract on the Hedrea testnet, since I have 10K tokens balance, it is enough to deploy one simple smart contract.  The following is the deploy.js code:
import { Client, Wallet, LocalProvider, FileCreateTransaction, Hbar } from "@hashgraph/sdk";
import dotenv from "dotenv";
dotenv.config();

const client = Client.forTestnet();
client.setOperator(process.env.ACCOUNT_ID, process.env.PRIVATE_KEY);

const wallet = new Wallet(
  process.env.ACCOUNT_ID,
  process.env.PRIVATE_KEY,
  new LocalProvider()
);

const byteCode = "0x608060405234801561001057600080fd5b5061017c806100206000396000f3fe608060405234801561001057600080fd5b506004361061002b5760003560e01c8063ef5fb05b14610030575b600080fd5b61003861004e565b60405161004591906100c4565b60405180910390f35b60606040518060400160405280600b81526020017f48656c6c6f20576f726c64000000000000000000000000000000000000000000815250905090565b6000610096826100e6565b6100a081856100f1565b93506100b0818560208601610102565b6100b981610135565b840191505092915050565b600060208201905081810360008301526100de818461008b565b905092915050565b600081519050919050565b600082825260208201905092915050565b60005b83811015610120578082015181840152602081019050610105565b8381111561012f576000848401525b50505050565b6000601f19601f830116905091905056fea2646970667358221220f41697157301e5b711ae91d093f64cf70f00a8128efd896c0e39f46cefe9c0e064736f6c63430008000033";

async function createFile() {
  const transactionId = await new FileCreateTransaction()
    .setContents(byteCode)
    .setMaxTransactionFee(new Hbar(15))
    .execute(client);

  const receipt = await transactionId.getReceipt(client);
  const newFileId = receipt.fileId;

  console.log("The new file ID is: " + newFileId);
}

createFile();

=> When I run this code, I got errors:
D:\nodejs\hedra-project>node deploy.js
file:///D:/nodejs/hedra-project/node_modules/@hashgraph/sdk/src/PrecheckStatusError.js:46
        super(
        ^

PrecheckStatusError: transaction 0.0.4470974@1696532147.727485011 failed precheck with status INVALID_SIGNATURE
    at new PrecheckStatusError (file:///D:/nodejs/hedra-project/node_modules/@hashgraph/sdk/src/PrecheckStatusError.js:46:9)
    at FileCreateTransaction._mapStatusError (file:///D:/nodejs/hedra-project/node_modules/@hashgraph/sdk/src/transaction/Transaction.js:1441:16)
    at FileCreateTransaction.execute (file:///D:/nodejs/hedra-project/node_modules/@hashgraph/sdk/src/Executable.js:728:32)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async createFile (file:///D:/nodejs/hedra-project/deploy.js:17:27) {
  status: Status { _code: 7 },
  transactionId: TransactionId {
    accountId: AccountId {
      shard: Long { low: 0, high: 0, unsigned: false },
      realm: Long { low: 0, high: 0, unsigned: false },
      num: Long { low: 4470974, high: 0, unsigned: false },
      aliasKey: null,
      evmAddress: null,
      _checksum: null
    },
    validStart: Timestamp {
      seconds: Long { low: 1696532147, high: 0, unsigned: false },
      nanos: Long { low: 727485011, high: 0, unsigned: false }
    },
    scheduled: false,
    nonce: null
  },
  contractFunctionResult: null
}

Node.js v20.5.0

D:\nodejs\hedra-project> 
=> How to fix this issue, I am using Node.js (v20.5.0) for Windows 10. The following is package.json:
{
 "name": "hedra-project",
 "version": "1.0.0",
 "description": "",
 "main": "index.js",
 "type": "module",
 "scripts": {
  "test": "echo \"Error: no test specified\" && exit 1"
 },
 "keywords": [],
 "author": "",
 "license": "ISC",
 "dependencies": {
  "@hashgraph/sdk": "^2.35.0",
  "dotenv": "^16.3.1"
 }
}
Thanks!

### Steps to reproduce

1. npm init -y
2. npm install @hashgraph/sdk dotenv
3. create .env file with content like this: 
ACCOUNT_ID=0.0.4470974
PRIVATE_KEY=0x...(My account private key)
HEDERA_NETWORK=testnet
4. Write one HelloWorld.sol
5. Use Remix to compile to get the bytecode from the HelloWorld.sol
6. Write one deploy.js to deploy the bytecode compiled from HelloWorld.sol
7. Run this command: node deploy.js to get the errors.

### Additional context

![HederaDeploySmartContractNOK](https://github.com/hashgraph/hedera-sdk-js/assets/45263518/fa296f66-1c64-49bc-8cd8-133aa0681b05)

### Hedera network

testnet

### Version

2.35.0

### Operating system

Windows

**Comment by ochikov** [comment]
Hello @zydjohnHotmail,
I've fixed your code. 
In order to deploy a smart contract, you need to:
- Create File on Hedera to store the bytecode
- Append the content to the file
- Instantiate the contract instance

```
async function main() {
  //Grab your Hedera testnet account ID and private key from your .env file
  const myAccountId = AccountId.fromString(process.env.OPERATOR_ID);
  const myPrivateKey = PrivateKey.fromString(process.env.OPERATOR_KEY);

  // If we weren't able to grab it, we should throw a new error
  if (myAccountId == null || myPrivateKey == null) {
    throw new Error(
      "Environment variables myAccountId and myPrivateKey must be present"
    );
  }

  // Create Hedera Testnet Client

  //The client has a default max transaction fee of 100,000,000 tinybars (1 hbar) and default max query payment of 100,000,000 tinybars (1 hbar).
  // If you need to change these values, you can use.setMaxDefaultTransactionFee() for a transaction and .setDefaultMaxQueryPayment() for queries.
  // So the max transaction fee is 1 hbar and the max query fee is 1 hbar, but those values can be changed
  const client = Client.forTestnet();

  // The operator is the account that will pay for the transaction query fees in HBAR
  client.setOperator(myAccountId, myPrivateKey);

  // Create a file on Hedera and store the bytecode
  const fileCreateTx = new FileCreateTransaction()
    .setKeys([myPrivateKey])
    .freezeWith(client);
  const fileCreateSign = await fileCreateTx.sign(myPrivateKey);
  const fileCreateSubmit = await fileCreateSign.execute(client);
  const fileCreateRx = await fileCreateSubmit.getReceipt(client);
  const bytecodeFileId = fileCreateRx.fileId;
  console.log(`- The bytecode file ID is: ${bytecodeFileId} \n`);

  //Append contents to the file
  const fileAppendTx = new FileAppendTransaction()
    .setFileId(bytecodeFileId)
    .setContents(bytecode)
    .freezeWith(client);
  const fileAppendSign = await fileAppendTx.sign(myPrivateKey);
  const fileAppendSubmit = await fileAppendSign.execute(client);
  const fileAppendRx = await fileAppendSubmit.getReceipt(client);
  console.log("Status of file append is", fileAppendRx.status.toString());

  // Instantiate the contract instance
  const contractTx = await new ContractCreateTransaction()
    //Set the file ID of the Hedera file storing the bytecode
    .setBytecodeFileId(bytecodeFileId)
    //Set the gas to instantiate the contract
    .setGas(100000)
    //Provide the constructor parameters for the contract
    .setConstructorParameters();

  //Submit the transaction to the Hedera test network
  const contractResponse = await contractTx.execute(client);

  //Get the receipt of the file create transaction
  const contractReceipt = await contractResponse.getReceipt(client);

  //Get the smart contract ID
  const newContractId = contractReceipt.contractId;

  //Log the smart contract ID
  console.log("The smart contract ID is " + newContractId);
}
main();
```

You can find the deployed contract [here](https://hashscan.io/testnet/contract/0.0.4519848).

**Comment by zydjohnHotmail** [comment]
Hi,
Thanks for your help.  But your code is not easy to understand, for these 2 statements:   const myAccountId = AccountId.fromString(process.env.OPERATOR_ID);
  const myPrivateKey = PrivateKey.fromString(process.env.OPERATOR_KEY);
Where is AccountId is defined? Where is PrivateKey is defined?

**Comment by ochikov** [comment]
Hey @zydjohnHotmail,
They are defined in the .env file of the project. The format is as follows:
```
OPERATOR_ID = YOUR_ID
OPERATOR_KEY = YOUR_KEY
```
You can read them from whatever you want. You can also paste them directly in the code.

**Comment by zydjohnHotmail** [comment]
const myAccountId = AccountId.fromString(process.env.OPERATOR_ID);
    const myPrivateKey = PrivateKey.fromString(process.env.OPERATOR_KEY);    
=> I changed my .env to use your name:
OPERATOR_ID = YOUR_ID
OPERATOR_KEY = YOUR_KEY
=> But in VSCode, I can see those variables are not defined: 
Could not find name 'AccountId'. Did you mean 'myAccountId'?ts(2570)
Could not find name 'PrivateKey'. Did you mean 'myPrivateKey'?ts(2570)
I suspect that maybe  the SDK has some built-in global variables defined?
At least from your previous long code, I can't see AccountId & PrivateKey are defined.

**Comment by ochikov** [comment]
Hey @zydjohnHotmail, the errors that you've got:
```
Could not find name 'AccountId'. Did you mean 'myAccountId'?ts(2570)
Could not find name 'PrivateKey'. Did you mean 'myPrivateKey'?ts(2570)
```
are because you need to import those methods from the SDK as follows:

```
const {
  AccountId,
  PrivateKey,
  Client,
  FileCreateTransaction,
  ContractCreateTransaction,
  FileAppendTransaction,
} = require("@hashgraph/sdk");
require("dotenv").config();
```

Keep in mind that I am using `require`. You can use `import` as well.
Those are things related to JS, not to the SDK at all. 

Also you can use our JSON RPC URL in order to deploy directly your contract from the Remix as follows:

1. You need to add the Hedera network to your metamask, for example the Hedera Testnet:

<img width="428" alt="Screenshot 2023-10-09 at 13 00 49" src="https://github.com/hashgraph/hedera-sdk-js/assets/13587218/eb08e470-9155-4fbf-8120-38de9577803e">

2. You need to switch Metamask to that network.
3. You need to add your account. Use the Hedera Portal and copy your ECDSA HEX Encoded Private Key in the Metamask flow for adding an account.
4. You need to connect the selected account.
5. You need to select in the remix to use Injected Provider. 
<img width="343" alt="Screenshot 2023-10-09 at 13 04 08" src="https://github.com/hashgraph/hedera-sdk-js/assets/13587218/93d85484-64cc-4a95-8a04-69567c39d903">
6. Then when you try to deploy the contract, similar window will appear:
<img width="567" alt="Screenshot 2023-10-09 at 13 04 41" src="https://github.com/hashgraph/hedera-sdk-js/assets/13587218/528b296b-a645-4d89-ad3f-c7eddbbf8437">
7. Then yo
<img width="347" alt="Screenshot 2023-10-09 at 13 13 27" src="https://github.com/hashgraph/hedera-sdk-js/assets/13587218/6e7053e8-bacc-43a2-9ba6-20c27f5da1f3">
u need to sign your transaction as follows:

**Comment by zydjohnHotmail** [comment]
Hi, I changed my code, according to your example, but it is not working: PS D:\nodejs\hedra-project> node .\main_deploy.js
D:\nodejs\hedra-project\node_modules\@hashgraph\sdk\lib\account\AccountId.cjs:83
    if (text.startsWith("0x") && text.length == 42 || text.length == 40) {
             ^

TypeError: Cannot read properties of undefined (reading 'startsWith')
    at AccountId.fromString (D:\nodejs\hedra-project\node_modules\@hashgraph\sdk\lib\account\AccountId.cjs:83:14)
    at main (D:\nodejs\hedra-project\main_deploy.js:9:35)
    at Object.<anonymous> (D:\nodejs\hedra-project\main_deploy.js:55:3)
    at Module._compile (node:internal/modules/cjs/loader:1233:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1287:10)
    at Module.load (node:internal/modules/cjs/loader:1091:32)
    at Module._load (node:internal/modules/cjs/loader:938:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:83:12)
    at node:internal/main/run_main_module:23:47

Node.js v20.5.0
PS D:\nodejs\hedra-project>  => The current code: const { AccountId, PrivateKey, Client, FileCreateTransaction, ContractCreateTransaction, FileAppendTransaction } = require("@hashgraph/sdk");
const dotenv = require("dotenv");
  
dotenv.config();

const byteCode = "0x608060405234801561001057600080fd5b5061017c806100206000396000f3fe608060405234801561001057600080fd5b506004361061002b5760003560e01c8063ef5fb05b14610030575b600080fd5b61003861004e565b60405161004591906100c4565b60405180910390f35b60606040518060400160405280600b81526020017f48656c6c6f20576f726c64000000000000000000000000000000000000000000815250905090565b6000610096826100e6565b6100a081856100f1565b93506100b0818560208601610102565b6100b981610135565b840191505092915050565b600060208201905081810360008301526100de818461008b565b905092915050565b600081519050919050565b600082825260208201905092915050565b60005b83811015610120578082015181840152602081019050610105565b8381111561012f576000848401525b50505050565b6000601f19601f830116905091905056fea2646970667358221220f41697157301e5b711ae91d093f64cf70f00a8128efd896c0e39f46cefe9c0e064736f6c63430008000033";

async function main() {
    const myAccountId = AccountId.fromString(process.env.ACCOUNT_ID);
    const myPrivateKey = PrivateKey.fromString(process.env.PRIVATE_KEY);  
    const client = Client.forTestnet();
    client.setOperator(myAccountId, myPrivateKey);
  
    // Create a file on Hedera and store the bytecode
    const fileCreateTx = new FileCreateTransaction()
      .setKeys([myPrivateKey])
      .freezeWith(client);
    const fileCreateSign = await fileCreateTx.sign(myPrivateKey);
    const fileCreateSubmit = await fileCreateSign.execute(client);
    const fileCreateRx = await fileCreateSubmit.getReceipt(client);
    const bytecodeFileId = fileCreateRx.fileId;
    console.log(`- The bytecode file ID is: ${bytecodeFileId} \n`);
  
    //Append contents to the file
    const fileAppendTx = new FileAppendTransaction()
      .setFileId(bytecodeFileId)
      .setContents(byteCode)
      .freezeWith(client);
    const fileAppendSign = await fileAppendTx.sign(myPrivateKey);
    const fileAppendSubmit = await fileAppendSign.execute(client);
    const fileAppendRx = await fileAppendSubmit.getReceipt(client);
    console.log("Status of file append is", fileAppendRx.status.toString());
  
    // Instantiate the contract instance
    const contractTx = await new ContractCreateTransaction()
      //Set the file ID of the Hedera file storing the bytecode
      .setBytecodeFileId(bytecodeFileId)
      //Set the gas to instantiate the contract
      .setGas(100000)
      //Provide the constructor parameters for the contract
      .setConstructorParameters();
  
    //Submit the transaction to the Hedera test network
    const contractResponse = await contractTx.execute(client);
  
    //Get the receipt of the file create transaction
    const contractReceipt = await contractResponse.getReceipt(client);
  
    //Get the smart contract ID
    const newContractId = contractReceipt.contractId;
  
    //Log the smart contract ID
    console.log("The smart contract ID is " + newContractId);
  }
  main();
=> But the following AccountBalance.js code works: const {  AccountBalanceQuery, LocalProvider, Wallet } = require("@hashgraph/sdk");
const dotenv = require("dotenv");
  
dotenv.config();

async function main() {
    if (process.env.OPERATOR_ID == null || process.env.OPERATOR_KEY == null) {
        throw new Error(
            "Environment variables OPERATOR_ID, and OPERATOR_KEY are required."
        );
    }

    const wallet = new Wallet(
        process.env.OPERATOR_ID,
        process.env.OPERATOR_KEY,
        new LocalProvider()
    );

    const balance = await new AccountBalanceQuery()
        .setAccountId(wallet.getAccountId())
        .executeWithSigner(wallet);

    console.log(
        `${wallet
            .getAccountId()
            .toString()} balance = ${balance.hbars.toString()}`
    );
}

void main();

setTimeout(() => {
    process.exit(0);
}, 3000);
=> PS D:\nodejs\hedra-project> node .\AccountBalance.js
0.0.4470974 balance = 10000 ℏ
PS D:\nodejs\hedra-project> By the way, I can add Hedrea testnet to my Metamask wallet, but since my Metamask wallet doesn't have the testnet account, the account address format is totally different from EVM compitable address.  Anyway, this is not important, let me know if you can find issue with my current code to deply a simple smart contract! Thanks

**Comment by ochikov** [comment]
Can you upload your code to a github repo? It's really difficult to read it without the formatting and to test it to see where is the issue.

**Comment by ochikov** [comment]
This is the full code example:

```
const {
  AccountId,
  PrivateKey,
  Client,
  FileCreateTransaction,
  ContractCreateTransaction,
  ContractCallQuery,
  Hbar,
  ContractFunctionParameters,
  FileAppendTransaction,
} = require("@hashgraph/sdk");
require("dotenv").config();

const bytecode =
  "0x608060405234801561001057600080fd5b5061017c806100206000396000f3fe608060405234801561001057600080fd5b506004361061002b5760003560e01c8063ef5fb05b14610030575b600080fd5b61003861004e565b60405161004591906100c4565b60405180910390f35b60606040518060400160405280600b81526020017f48656c6c6f20576f726c64000000000000000000000000000000000000000000815250905090565b6000610096826100e6565b6100a081856100f1565b93506100b0818560208601610102565b6100b981610135565b840191505092915050565b600060208201905081810360008301526100de818461008b565b905092915050565b600081519050919050565b600082825260208201905092915050565b60005b83811015610120578082015181840152602081019050610105565b8381111561012f576000848401525b50505050565b6000601f19601f830116905091905056fea2646970667358221220f41697157301e5b711ae91d093f64cf70f00a8128efd896c0e39f46cefe9c0e064736f6c63430008000033";

async function main() {
  //Grab your Hedera testnet account ID and private key from your .env file
  const myAccountId = AccountId.fromString(process.env.OPERATOR_ID);
  const myPrivateKey = PrivateKey.fromString(process.env.OPERATOR_KEY);

  // If we weren't able to grab it, we should throw a new error
  if (myAccountId == null || myPrivateKey == null) {
    throw new Error(
      "Environment variables myAccountId and myPrivateKey must be present"
    );
  }

  // Create Hedera Testnet Client

  //The client has a default max transaction fee of 100,000,000 tinybars (1 hbar) and default max query payment of 100,000,000 tinybars (1 hbar).
  // If you need to change these values, you can use.setMaxDefaultTransactionFee() for a transaction and .setDefaultMaxQueryPayment() for queries.
  // So the max transaction fee is 1 hbar and the max query fee is 1 hbar, but those values can be changed
  const client = Client.forTestnet();

  // The operator is the account that will pay for the transaction query fees in HBAR
  client.setOperator(myAccountId, myPrivateKey);

  // Create a file on Hedera and store the bytecode
  const fileCreateTx = new FileCreateTransaction()
    .setKeys([myPrivateKey])
    .freezeWith(client);
  const fileCreateSign = await fileCreateTx.sign(myPrivateKey);
  const fileCreateSubmit = await fileCreateSign.execute(client);
  const fileCreateRx = await fileCreateSubmit.getReceipt(client);
  const bytecodeFileId = fileCreateRx.fileId;
  console.log(`- The bytecode file ID is: ${bytecodeFileId} \n`);

  //Append contents to the file
  const fileAppendTx = new FileAppendTransaction()
    .setFileId(bytecodeFileId)
    .setContents(bytecode)
    .freezeWith(client);
  const fileAppendSign = await fileAppendTx.sign(myPrivateKey);
  const fileAppendSubmit = await fileAppendSign.execute(client);
  const fileAppendRx = await fileAppendSubmit.getReceipt(client);
  console.log("Status of file append is", fileAppendRx.status.toString());

  // Instantiate the contract instance
  const contractTx = await new ContractCreateTransaction()
    //Set the file ID of the Hedera file storing the bytecode
    .setBytecodeFileId(bytecodeFileId)
    //Set the gas to instantiate the contract
    .setGas(100000)
    //Provide the constructor parameters for the contract
    .setConstructorParameters();

  //Submit the transaction to the Hedera test network
  const contractResponse = await contractTx.execute(client);

  //Get the receipt of the file create transaction
  const contractReceipt = await contractResponse.getReceipt(client);

  //Get the smart contract ID
  const newContractId = contractReceipt.contractId;

  //Log the smart contract ID
  console.log("The smart contract ID is " + newContractId);
}
main();
```

You need to pass just the OPERATOR_ID & OPERATOR_KEY.
With this code, this can be done by installing `dotenv` or adding it to the `package.json` and running `npm install`.
My package.json looks like:
```
{
  "name": "hello-hedera-js-sdk",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "ochikov",
  "license": "ISC",
  "dependencies": {
    "@hashgraph/sdk": "2.35.0",
    "dotenv": "^16.0.1",
    "ethers": "^5.7.2",
    "hashconnect": "^0.2.4",
    "node-fetch": "^2.6.13"
  },
  "devDependencies": {
    "@types/cors": "^2.8.13",
    "@types/express": "^4.17.17",
    "ts-node": "^10.9.1",
    "typescript": "^4.9.5"
  }
}


For OPERATOR_ID , I am using ED25519:
![Screenshot 2023-10-09 at 17 23 51](https://github.com/hashgraph/hedera-sdk-js/assets/13587218/c0634b74-4f57-4019-b09f-896c39c69f02)

For OPERATOR_KEY, I am using the DER Encoded Private Key:
![Screenshot 2023-10-09 at 17 23 57](https://github.com/hashgraph/hedera-sdk-js/assets/13587218/31b5c4de-b222-4c35-8512-61276e4d8a81)

**Comment by zydjohnHotmail** [comment]
https://github.com/zydjohnHotmail/test-Hedrea-JS-SDK => Can you use my code, but replace with your private key and test and let me know if you find any issue with my code.
Thanks!

**Comment by ochikov** [comment]
The problem is that in the file `main_deploy.js` you are looking for `myAccountId` from `process.env.ACCOUNT_ID` but in the env it is named `OPERATOR_ID` **NOT** `ACCOUNT_ID`

The same is with the `myPrivateKey`. You are looking for `process.env.PRIVATE_KEY` but in the env file it is named `OPERATOR_KEY` **NOT** `PRIVATE_KEY`

**Comment by zydjohnHotmail** [comment]
PS D:\nodejs\hedra-project> node .\main_deploy.js
D:\nodejs\hedra-project\node_modules\@hashgraph\sdk\lib\PrecheckStatusError.cjs:50
    super(props, `transaction ${props.transactionId.toString()} failed precheck with status ${props.status.toString()}`);
    ^

PrecheckStatusError: transaction 0.0.4470974@1697012727.401888449 failed precheck with status INVALID_SIGNATURE
    at new PrecheckStatusError (D:\nodejs\hedra-project\node_modules\@hashgraph\sdk\lib\PrecheckStatusError.cjs:50:5)
    at FileCreateTransaction._mapStatusError (D:\nodejs\hedra-project\node_modules\@hashgraph\sdk\lib\transaction\Transaction.cjs:1259:12)
    at FileCreateTransaction.execute (D:\nodejs\hedra-project\node_modules\@hashgraph\sdk\lib\Executable.cjs:671:22)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async main (D:\nodejs\hedra-project\main_deploy.js:19:30) {
  status: Status { _code: 7 },
  transactionId: TransactionId {
    accountId: AccountId {
      shard: Long { low: 0, high: 0, unsigned: false },
      realm: Long { low: 0, high: 0, unsigned: false },
      num: Long { low: 4470974, high: 0, unsigned: false },
      aliasKey: null,
      evmAddress: null,
      _checksum: null
    },
    validStart: Timestamp {
      seconds: Long { low: 1697012727, high: 0, unsigned: false },
      nanos: Long { low: 401888449, high: 0, unsigned: false }
    },
    scheduled: false,
    nonce: null
  },
  contractFunctionResult: null
}

Node.js v20.5.0
PS D:\nodejs\hedra-project> => No, I don't think this is  the reason, since I tried both OPERATOR_ID and ACCOUNT_ID; both OPERATOR_KEY & PRIVATE_KEY.  But for AccountBalance.js; as long as the variables in .env file and AccountBalance.js are the same, the code works.  But for main_deploy.js no matter what the variables are set, I always got the same errors.
