### ISSUE TITLE
Error : TypeError: receipt.hasTopicid is not a function

### ISSUE THREAD

**Issue by rahulasati** [hashgraph/hedera-sdk-js#197]
Hi,
i am using latest version 1.1.5 while calling getReceipt on contract execute transaction getting error
TypeError: receipt.hasTopicid is not a function

**Comment by mehcode** [comment]
Can you show the whole stack trace and the line of code where you're calling `getReceipt`? That's bizarre as we've been using it pretty regularly.

**Comment by rahulasati** [comment]
following is the code where line on bold i got issue
let transactionId = await new ContractExecuteTransaction()
            .setContractId(contractIdLike)
            .setFunction(abi[0].name, functionParams)
            .setMaxTransactionFee(parseInt(txFee))
            .setGas(gas)
            .setTransactionMemo(memo)
            .setPayableAmount(amount)
            .execute(client);
        log('contractCallResult transactionId : ', transactionId);
        **let contractCallReceipt = await transactionId.getReceipt(client);**
        log('contractCallReceipt : ', JSON.stringify(contractCallReceipt));

**Logs**
all:viewcontroller:grpc:contractcall contractCallResult transactionId :  +527ms TransactionId {accountId: AccountId, validStart: Time}accountId: AccountId {shard: 0, realm: 0, account: 140076}validStart: Time {seconds: 1581945554, nanos: 351000000}__proto__: Object
smart-contract-details.js:64239 all:viewcontroller:grpc:contractcall Err while Contract call:  +2s TypeError: receipt.hasTopicid is not a function
    at Function._fromProto (smart-contract-details.js:2813)
    at TransactionReceiptQuery._mapResponse (smart-contract-details.js:2905)
    at TransactionReceiptQuery.<anonymous> (smart-contract-details.js:1056)
    at Generator.next (<anonymous>)
    at fulfilled (smart-contract-details.js:927)

**Comment by mehcode** [comment]
This doesn't make sense. I cannot reproduce the issue in our [`create-stateful-contract.js`](https://github.com/hashgraph/hedera-sdk-js/blob/master/examples/create-stateful-contract.js) example. That one runs fine. Can you confirm you are on the latest version of the SDK from npm?

**Comment by mehcode** [comment]
From discussion on Discord/call, we discovered the proto classes we're being overwritten by local copies.
