### ISSUE TITLE
Add Long support for ContractFunctionParameters parameters

### ISSUE THREAD

**Issue by iron4548** [hashgraph/hedera-sdk-js#1972]
### Description

I have this code:

```typescript
  const params = new ContractFunctionParameters();
  params.addAddress(demoToken1.toSolidityAddress()); //address token
  params.addUint256(liquidityAmountDemo1Tiny); //uint amountTokenDesired
  params.addUint256(liquidityAmountDemo1Tiny); //uint amountTokenMin
  params.addUint256(liquidityAmountHbar.toTinybars()); //uint amountETHMin
  params.addAddress(client.operatorAccountId!.toSolidityAddress()); //address to
  params.addUint256(Math.floor(Date.now() / 1000) + 20); //uint deadline - 20s from now
```

uint amountETHMin expects the amount in tinyhbar. So naturally I tried with `liquidityAmountHbar.toTinybars()` but I got an error: 'Argument of type 'Long' is not assignable to parameter of type 'number | BigNumber'. 

So naturally what I did was changed liquidityAmountHbar.toBigNumber() to resolve the error. I also thought toBigNumber() would give me a tinybar in terms of BigNumber but that wasn't the case. It was hbar expressed as a BigNumber()

From Hbar.js

```
    /**
     * @returns {BigNumber}
     */
    toBigNumber() {
        return this.to(HbarUnit.Hbar);
    }
 ```

To avoid the mistake of using toBigNumber() in this context, which would have given incorrect results, for future developers, please add Long support for ContractFunctionParameters parameters such as params.addUint256 so developers can use `Hbar.toTinybars()`

### Steps to reproduce

N/A

### Hedera network

testnet

### Version

2.35.0

### Operating system

None

**Comment by iron4548** [comment]
Just realized I incorrectly reported this as a bug. I can't figure out how to change it to enhancement.

**Comment by svetoslav-nikol0v** [comment]
Hey [iron4548](https://github.com/iron4548),
We're working on that in order to be implemented in the next version.
