### ISSUE TITLE
Uint256Array on contract function arguments expecting number[] instead of BigNumber[]

### ISSUE THREAD

**Issue by AnBapDan** [hashgraph/hedera-sdk-js#1976]
### Description
Note: This was tested using Typescript.
I am trying to pass an array of BigNumber[] as a function argument, because the numbers that I am passing overflow the max capacity of number. However, this function is expecting a number[] instead of BigNumber[].

Looking through the SDK it seems the problem may be related to this part of the code

` /**
     * @param {number[]} value << should be Long[] | BigNumber[] | string[] | number[]
     * @returns {ContractFunctionParameters}
     */
    addUint256Array(value) {
        this._selector.addUint256Array();
        return this._addParam(util.convertToBigNumberArray(value), true);

  Can anyone verify this?

### Steps to reproduce

1. Create a function contract expecting a uint256,uint256 array or higher
2. Execute a snippet code like this ` const prompt = new ContractExecuteTransaction() .setContractId(contractId) .setFunction('method', new ContractFunctionParameters().addUint256Array(array) .setGas(100000)`

### Hedera network

testnet

### Version

v2.35.0

### Operating system

Linux

**Comment by rokn** [comment]
Hey @AnBapDan, we are currently working on a fix for that as part of #1972
