### ISSUE TITLE
Reducing empty arrays on ContractFunctionParameters() causes error

### ISSUE THREAD

**Issue by AnBapDan** [hashgraph/hedera-sdk-js#1990]
### Description

Note: This was tested using Typescript.
I have an API that tries to pass two arrays, accepted[] and denied[] into the smart contract. 
However, sometimes, denied is just [].
When passing to 
`  const prompt = new ContractExecuteTransaction()
    .setContractId(contractId)
    .setFunction('confirmPayment',
      new ContractFunctionParameters()
        .addUint256Array(accepted)
        .addUint256Array(denied))
    .setGas(1000000)`

The SDK fails to reduce, because no default initial value was passed on 
`const totalLengthOfValues = values.map(a => a.length).reduce((total, current) => total + current);` 
I have overwritten this line on ContractFunctionParameters.cjs and added `const totalLengthOfValues = values.map(a => a.length).reduce((total, current) => total + current, 0);`  and it worked as intended

### Steps to reproduce

1. Pass an empty array to ContractFunctionParameters().addUint256Array([])

### Hedera network

testnet

### Version

v2.35.0

### Operating system

Linux

**Comment by pathornteng** [comment]
The problem here is that the SDK should accept empty array instead of throwing an error.

**Comment by Petyo-Lukanov** [comment]
Issue is addressed in this PR - https://github.com/hashgraph/hedera-sdk-js/pull/2016 
and it will be available with the next SDK Release.
