### ISSUE TITLE
[v1.1.7] No way to sign in case of HCS submit message transaction with submitKey set

### ISSUE THREAD

**Issue by rahulasati** [hashgraph/hedera-sdk-js#200]
Hi,
I am using ConsensusSubmitMessageTransaction but can't find method to sign required in case topic has submitKey set.

Also, it says ConsensusSubmitMessageTransaction is deprecated use `ConsensusMessageSubmitTransaction` instead but ConsensusMessageSubmitTransaction is not exposed.
**version : 1.1.7**

**Comment by rahulasati** [comment]
is it like by default is sign with caller account's private key?

**Comment by mehcode** [comment]
The Transaction will sign by the operator private key which is generally required as the payer (or the operator) must always sign the transaction.

If you have an additional key, currently you must build and then continue signing the transaction.

```js
const transactionId = await new ConsensusMessageSubmitTransaction()
  .setTopicId(topicId)
  .setMessage("Hello, World")
  .build(client) // finalizes the transaction so it may not be mutated
  .sign(submitKey) // additional signature
  .execute(client);
```

**Comment by rahulasati** [comment]
Thanks @mehcode
