### ISSUE TITLE
Add new CI pipeline for release automation

### ISSUE THREAD

**Issue by nathanklick** [hashgraph/hedera-sdk-js#2006]
### Problem

The current release process is manual and should be converted to a CI driven workflow. 

### Solution

- Add a new CI pipeline which is triggered by a properly formatted version tag
- The CI pipeline should take the following actions:
   - Update the version specified in the `package.json` file to match the version in the tag.
   - ~~Execute `task test:unit:node` and validate results.~~
   - ~~Execute `task test:publish` and validate results.~~
   - Execute `task publish` and verify success. 
   - Create a Github release with autogenerated release notes.

### Alternatives

None

**Comment by rokn** [comment]
Hey @nathanklick, I think we can skip the `task test:unit:node` step as the publish step should run all the tests. Also we don't have `task test:publish` would that be something that we need to add and what would it do?

**Comment by nathanklick** [comment]
> Hey @nathanklick, I think we can skip the `task test:unit:node` step as the publish step should run all the tests. Also we don't have `task test:publish` would that be something that we need to add and what would it do?

The `task test:publish` came from here in the `RELEASE.md` file: https://github.com/hashgraph/hedera-sdk-js/blob/4ecdcfda314669d130bac3571263d6ed8ba1b8fd/RELEASE.md?plain=1#L7

If it doesn't exist, then we can omit it. The above write up was based on the `RELEASE.md` file and I'm sure I would have discovered the absence of the task here shortly.

**Comment by nathanklick** [comment]
@rokn The pipeline will update the `package.json` file to ensure it always publishes with the correct version; however, the engineers are still responsible for updating the `package.json` version prior to tagging. This is one of the minor pitfalls of triggering the pipeline based on the tag.

**Comment by nathanklick** [comment]
@rokn Another option could be to simply validate the `package.json` version against the tag version and fail the pipeline on mismatch. This would force the engineer to fix the problem and retag.

Which method would you prefer?

**Comment by rokn** [comment]
It would be best if there is a check for discrepancies between the tag and `package.json` version

**Comment by ochikov** [comment]
@nathanklick Hey, keep in mind that sometimes we are pushing also a beta releases for the community.
