### ISSUE TITLE
getRecord > ContractFunctionResult > asBytes() is empty

### ISSUE THREAD

**Issue by rahulasati** [hashgraph/hedera-sdk-js#201]
Hi,

let transactionId = await new ContractExecuteTransaction()
            .setContractId(contractIdLike)
            .setFunction(abi[0].name, functionParams)
            .setMaxTransactionFee(parseInt(txFee))
            .setGas(gas)
            .setTransactionMemo(memo)
            .setPayableAmount(amount)
            .execute(client);
        log('contractCallResult transactionId : ', transactionId);
        let contractCallReceipt = await transactionId.getReceipt(client);
        log('contractCallReceipt : ', JSON.stringify(contractCallReceipt));
        let contractCallRecord = await transactionId.getRecord(client);
        log('contractCallRecord : ', JSON.stringify(contractCallRecord));

I am getting ContractFunctionResult bytes is undefined even though contract call returns result.

how to get record result?

**Comment by mehcode** [comment]
Looks like getting the result of contract executions does not work in the current version. This is fixed in v1.1.8
