### ISSUE TITLE
Facing Transcation Oversize Issue

### ISSUE THREAD

**Issue by Tamizhselvantamizh** [hashgraph/hedera-sdk-js#202]
Getting TRANSACTION_OVERSIZE Error

//code
`const smartContract = require("./stateful.json");`
   `const smartContractByteCode = smartContract.contracts[ "stateful.sol:StatefulContract" ].bin;`
    `let buffer = Buffer.from(smartContractByteCode,"utf-8")`
    `var chunks = new Uint8Array(buffer)`
   ` console.log("contract bytecode size:", smartContractByteCode.length, "bytes");`
   ` // First we must upload a file containing the byte code`
    `const byteCodeFileId = (await (await new FileCreateTransaction()`
       ` .setMaxTransactionFee(new Hbar(3))`
        `.addKey(operatorPrivateKey.publicKey)`
        `.setContents(chunks)`
        `.execute(hederaClient))`
        `.getReceipt(hederaClient))`
       ` .getFileId();`

can you please suggest sample code

**Comment by Cooper-Kunz** [comment]
@Tamizhselvantamizh sorry to hear that you were having issues. It looks like they have been resolved?
