### ISSUE TITLE
HTS or the SDK treat Ed25519 private keys preferentially over ECDSA private keys

### ISSUE THREAD

**Issue by SimiHunjan** [hashgraph/hedera-sdk-js#2027]
### Description

I've tried all 4 combinations, and 3 of them work, but one of them does not: when the account is an ECDSA account and a HEX ecnoded priate key is used
```
# # Does not work: ECDSA account ID, HEX encoded private key
# ACCOUNT_ID=0.0.1201
# ACCOUNT_PRIVATE_KEY=0x2a965c3a<...redacted...>

# # Works: ECDSA account ID, DER encoded private key
# ACCOUNT_ID=0.0.1201
# ACCOUNT_PRIVATE_KEY=30300201<...redacted...>

# # Works: Ed25519 account ID, HEX encoded private key
# ACCOUNT_ID=0.0.1186
# ACCOUNT_PRIVATE_KEY=0x1c893adf<...redacted...>

# # Works: Ed25519 account ID, DER encoded private key
# ACCOUNT_ID=0.0.1186
# ACCOUNT_PRIVATE_KEY=302e0201<...redacted...>
```

I'm running a TokenCreateTransaction like this:
```
    let tokenCreateTx = await new TokenCreateTransaction()
        .setTokenType(TokenType.FungibleCommon)
        .setTokenName("MyCoin")
        .setTokenSymbol("MYC")
        .setDecimals(2)
        .setInitialSupply(1_000_000)
        .setTreasuryAccountId(accountId)
        .setAdminKey(accountKey)
        .setFreezeDefault(false)
        .freezeWith(client);
    const tokenCreateTxSigned = await tokenCreateTx.sign(accountKey);
    const tokenCreateTxSubmitted = await tokenCreateTxSigned.execute(client);
    const tokenCreateTxReceipt = await tokenCreateTxSubmitted.getReceipt(client);
    const tokenId = tokenCreateTxReceipt.tokenId;
```

The error that I get, only when using an ECDSA HEX encoded private key , is:
```
file:///Users/user/code/hedera/hello-future-world/04-hts-ft-sdk/node_modules/@hashgraph/sdk/src/PrecheckStatusError.js:46
        super(
        ^

PrecheckStatusError: transaction 0.0.1201@1699611549.547465403 failed precheck with status INVALID_SIGNATURE
    at new PrecheckStatusError (file:///Users/user/code/hedera/hello-future-world/04-hts-ft-sdk/node_modules/@hashgraph/sdk/src/PrecheckStatusError.js:46:9)
    at TokenCreateTransaction._mapStatusError (file:///Users/user/code/hedera/hello-future-world/04-hts-ft-sdk/node_modules/@hashgraph/sdk/src/transaction/Transaction.js:1440:16)
    at TokenCreateTransaction.execute (file:///Users/user/code/hedera/hello-future-world/04-hts-ft-sdk/node_modules/@hashgraph/sdk/src/Executable.js:727:32)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async main (file:///Users/user/code/hedera/hello-future-world/04-hts-ft-sdk/script-hts-ft.js:37:36) {
  status: Status { _code: 7 },
  transactionId: TransactionId {
    accountId: AccountId {
      shard: Long { low: 0, high: 0, unsigned: false },
      realm: Long { low: 0, high: 0, unsigned: false },
      num: Long { low: 1201, high: 0, unsigned: false },
      aliasKey: null,
      evmAddress: null,
      _checksum: null
    },
    validStart: Timestamp {
      seconds: Long { low: 1699611549, high: 0, unsigned: false },
      nanos: Long { low: 547465403, high: 0, unsigned: false }
    },
    scheduled: false,
    nonce: null

  },
  contractFunctionResult: null
}

Node.js v20.6.1
```

[hts-ft.js.zip](https://github.com/hashgraph/hedera-sdk-js/files/13338320/hts-ft.js.zip)

This issue was raised by @bguiz . 

### Steps to reproduce

See above

### Hedera network

testnet

### Version

na

### Operating system

None

**Comment by SimiHunjan** [comment]
Hey 
[@brendan](https://swirldslabs.slack.com/team/U04UCD8F3D1)
, we’ve investigated the issue and it’s most likely because we have no way of differentiating between an ECDSA key and ED25519 key when they are in the raw format. I believe that’s the reason we are using DER headers, because they allow differentiating between the two with some additional metadata. I’m not sure on what’s your use case, but some other guys have been doing some prechecks with the mirrornode to detect existing accounts when parsing keys. Like:
const pk1 = PrivateKey.fromStringECDSA(pkString);
//Query mirror node for account with pk1.publicKey
const pk2 = PrivateKey.fromStringED25519(pkString);
//Query mirror node for account with pk2.publicKey

// and whichever gets a hit is the correct format


Brendan Graetz
:flag-sg:  [13 hours ago](https://swirldslabs.slack.com/archives/C01BT9CM1EJ/p1700125496629869?thread_ts=1699611840.949469&cid=C01BT9CM1EJ)
My use case is what's in the code sbippet above. Just initialising a Client object with an account ID and private key copied from portal.


Brendan Graetz
:flag-sg:  [13 hours ago](https://swirldslabs.slack.com/archives/C01BT9CM1EJ/p1700125571569749?thread_ts=1699611840.949469&cid=C01BT9CM1EJ)
In terms of differentiating them, is there anything else that might be a clue, such as length/ num characters?


Antonio Mindov
  [13 hours ago](https://swirldslabs.slack.com/archives/C01BT9CM1EJ/p1700125593917029?thread_ts=1699611840.949469&cid=C01BT9CM1EJ)
That’s the problem, they are both 32 bytes/64 chars


Antonio Mindov
  [13 hours ago](https://swirldslabs.slack.com/archives/C01BT9CM1EJ/p1700125620340279?thread_ts=1699611840.949469&cid=C01BT9CM1EJ)
And both of them are parseable with both algorithms


Brendan Graetz
:flag-sg:  [13 hours ago](https://swirldslabs.slack.com/archives/C01BT9CM1EJ/p1700125712924439?thread_ts=1699611840.949469&cid=C01BT9CM1EJ)
If there is no way to tell them apart without making a network query (which isn't ideal) then I suggest that we add an optional param that is a flag which allows the script to specify which type of account to initialise for the client.
(And if unspecified, it uses the current logic)


Antonio Mindov
  [13 hours ago](https://swirldslabs.slack.com/archives/C01BT9CM1EJ/p1700125796244799?thread_ts=1699611840.949469&cid=C01BT9CM1EJ)
That’s why we have the different methods fromECDSA and fromED25519


Brendan Graetz
:flag-sg:  [13 hours ago](https://swirldslabs.slack.com/archives/C01BT9CM1EJ/p1700125841534379?thread_ts=1699611840.949469&cid=C01BT9CM1EJ)
And if current logic is employed, I suggest adding a console.warn to notify the dev that this has occurred.
Otherwise it end up in a silent failure.


Antonio Mindov
  [13 hours ago](https://swirldslabs.slack.com/archives/C01BT9CM1EJ/p1700125940278149?thread_ts=1699611840.949469&cid=C01BT9CM1EJ)
By the way we have the requirement of DER headers as part of the docs on that function:
image.png
 
image.png


:white_check_mark:
1



Brendan Graetz
:flag-sg:  [13 hours ago](https://swirldslabs.slack.com/archives/C01BT9CM1EJ/p1700125955494539?thread_ts=1699611840.949469&cid=C01BT9CM1EJ)
Ah, so there are already methods for this!
Great. Will explore and see if these work for me.
https://swirldslabs.slack.com/archives/C01BT9CM1EJ/p1700125796244799?thread_ts=1699611840.949469&cid=C01BT9CM1EJ



Antonio Mindov
That’s why we have the different methods fromECDSA and fromED25519
[From a thread in sdk-v2](https://swirldslabs.slack.com/archives/C01BT9CM1EJ/p1700125796244799?thread_ts=1699611840.949469&amp;cid=C01BT9CM1EJ) | [Today at 1:09 AM](https://swirldslabs.slack.com/archives/C01BT9CM1EJ/p1700125796244799?thread_ts=1699611840.949469&amp;cid=C01BT9CM1EJ) | [View reply](https://swirldslabs.slack.com/archives/C01BT9CM1EJ/p1700125796244799?thread_ts=1699611840.949469&amp;cid=C01BT9CM1EJ)


Antonio Mindov
  [13 hours ago](https://swirldslabs.slack.com/archives/C01BT9CM1EJ/p1700125991452799?thread_ts=1699611840.949469&cid=C01BT9CM1EJ)
Oh sorry, the names are fromStringECDSA and fromStringED25519
:white_check_mark:
1



Brendan Graetz
:flag-sg:  [12 hours ago](https://swirldslabs.slack.com/archives/C01BT9CM1EJ/p1700128046231739?thread_ts=1699611840.949469&cid=C01BT9CM1EJ)
ok, just verified that PrivateKey.fromStringECDSA() solves my problem


Brendan Graetz
:flag-sg:  [12 hours ago](https://swirldslabs.slack.com/archives/C01BT9CM1EJ/p1700128314544469?thread_ts=1699611840.949469&cid=C01BT9CM1EJ)
OK so I now don't think that this is a bug in the SDK anymore...
Instead, I'd reclassify this as a developer friction point.
My recommendation to resolve this is simply to prevent this from becoming a silent failure.
So I'd modify this such that whenever PrivateKey.fromString() is called,
and the param passed in is detected as HEX format,
that there is a console.warn() output that suggests to the developer:
"... consider using the fromStringECDSA or fromStringED25519 methods instead."

**Comment by bguiz** [comment]
@SimiHunjan thanks for adding the context above - just to summarise:
(1) This is a developer friction point, and not a bug as originally thought, but still needs to be handled as it results in a silent failure
(2) The developer friction point can be minimised by doing a `console.warn()` when the situation that leads this particular silent failure occurs

I suggest that the message used should be something along the lines of:

`WARNING: PrivateKey: You have used fromString on a HEX-encoded string. Consider using either fromStringECDSA or fromStringED2551 instead.`

**Comment by svetoslav-nikol0v** [comment]
Briefly what we did:
- deprecated `fromString()` method to prevent future confusion
- regardless of the method being deprecated, a warning message was added that suggests the developer use one of the other methods
- added a new `fromStringDer()` method that is used for a HEX-encoded string with a DER prefix for developer convenience

**Comment by bguiz** [comment]
Great!
