### ISSUE TITLE
License question

### ISSUE THREAD

**Issue by roccomuso** [hashgraph/hedera-sdk-js#203]
Any reason why LICENSE is Apache-2.0?

Switching to MIT would allow easy spreading and adoption.

**Comment by gakz** [comment]
@roccomuso, while Apache certainly has more legalese, in terms of outcome MIT and Apache are very similar. They should have no impact on your use of technology, modifications to it, contributions required, etc. You are free to do whatever you want to the code, commercial or otherwise.

**Comment by Cooper-Kunz** [comment]
Hi @roccomuso does that answer your question, or is there anything else we can do for you? 😄

**Comment by roccomuso** [comment]
ok thanks
