### ISSUE TITLE
Invalid Public Key Length

### ISSUE THREAD

**Issue by teacoat** [hashgraph/hedera-sdk-js#2071]
### Description

I occasionally get a 'invalid public key length' error from keys generated from the SDK, about 1 in 3000 keys seem to throw it.

### Steps to reproduce

1. Generate a bunch of keys
2. Do PublicKey.toStringRaw()
3. Do PublicKey.fromStringED25519()
4. Eventually you should get this error

### Additional context

![image](https://github.com/hashgraph/hedera-sdk-js/assets/3913019/24c1a38e-b4a8-4c43-8015-e652a2781655)

### Hedera network

mainnet

### Version

2.37.0

### Operating system

None

**Comment by ochikov** [comment]
Hey @teacoat, thanks for the issue. Can you provide us with a sample code that we can run and reproduce the issue?

**Comment by svetoslav-nikol0v** [comment]
Hey @teacoat , maybe you missed the last comment on this issue. Can you provide us a code snippet that we can use to reproduce the issue, please?

**Comment by svetoslav-nikol0v** [comment]
After testing this functionality, we did not encounter the error mentioned above. This error only occurs if the key is generated with the `generateECDSA()` method and then parsed with the `fromStringED25519()` method.
