### ISSUE TITLE
Rxjs Error when deploy to vercel

### ISSUE THREAD

**Issue by harisalkarni** [hashgraph/hedera-sdk-js#2101]
### Description

Halo,

i try to deploy my project to vercel but i got this rxjs error from @hashgraph/sdk npm package, do you know why this happen?

### Steps to reproduce

run vercel in my project
got this error in vercel log

<img width="1512" alt="Screenshot 2024-01-24 at 15 25 38" src="https://github.com/hashgraph/hedera-sdk-js/assets/49621897/a3570d66-2a6a-4f6e-85a7-8ded5742e66b">

### Hedera network

testnet

### Version

2.29.0

### Operating system

macOS

**Comment by svetoslav-nikol0v** [comment]
Hello [harisalkarni](https://github.com/harisalkarni), I see you're using an old version of 2.29.0 of the SDK. Have you tried deploying your project with the latest version of 2.40.0 of the SDK and checking if the problem still exists?

**Comment by harisalkarni** [comment]
yes i already tried using 2.40.0 version but the error still the same
the rxjs error

**Comment by harisalkarni** [comment]
i already fix it, i install rxjs package and the error is gone

**Comment by svetoslav-nikol0v** [comment]
Hello [harisalkarni](https://github.com/harisalkarni), we're going to close this ticket if there are no any other problems?
