### ISSUE TITLE
Transaction expiration issues 

### ISSUE THREAD

**Issue by Cooper-Kunz** [hashgraph/hedera-sdk-js#212]
Attempting to create new account results in a TRANSACTION_EXPIRED error. 

Here's the response. 

```
transactionID failed with status: TRANSACTION_EXPIRED
```

I'm attempting to run version `v1.1.8`

**Comment by mubarakcolan** [comment]
the issue with local system time. it is not match with current time.

**Comment by mehcode** [comment]
Yeah. That almost certainly isn't an issue in the SDK but an issue in time synchronization. Try making sure you have NTP or the equivalent enabled.

**Comment by Cooper-Kunz** [comment]
Interesting. Thanks for the clarity @mubarakcolan & @mehcode! 😄 

Am I able to manually configure or specify a transaction expiration time?

**Comment by mehcode** [comment]
@Cooper-Kunz By default, we send a transaction that is set to start 10 seconds in the past in case you are ahead of the server but we also set a default duration of 120 seconds in case you are behind. It sounds like you are more than a couple minutes off the time on the node. 

You can do `.setValidDuration` but it only goes up to ~ 180 I believe. 

A much better solution is to just make sure you're on the proper network time where you run your code. If you share the OS I can find some guides on it. It's a pretty common thing.

**Comment by Cooper-Kunz** [comment]
Thanks for the clarity! I was using a macbook, but I am sure I can fix myself or bug you next time 😉 

Just to confirm - is it supposed to be `.setValidDuration()` or `.setTransactionValidDuration()`? 

The latter is mentioned in the SDK [docs](https://docs.hedera.com/guides/docs/sdks/transactions). cc @SimiHunjan
