### ISSUE TITLE
Inability to create and execute Freeze Transaction

### ISSUE THREAD

**Issue by SvetBorislavov** [hashgraph/hedera-sdk-js#2135]
### Description

The Freeze transaction has a property FreezeType, which should be set with the 'setFreezeType' method. This method accepts the FreezeType class. 
The problem is that the FreezeType class is not exported from the SDK. This causes an inability to see the freeze type of the transaction.

If you skip the freeze type or manually export it for test purposes another problem occurs.
Invoking the execute method of this transaction throws an Error with the message 'not implemented'

### Steps to reproduce

1. Run the following snippet:

```
const { Client, FreezeType, FreezeTransaction } = require('@hashgraph/sdk');

async function run() {
  const client = Client.forTestnet();
  client.setOperator();

  const freezeTransaction = await new FreezeTransaction()
    .setFreezeType(FreezeType._fromCode(2))
    .freezeWith(client)
    .execute(client);
}
```

### Hedera network

testnet

### Version

2.40.0

### Operating system

None

**Comment by svetoslav-nikol0v** [comment]
After the necessary changes ware added the execution of `FreezeTransaction` returns status code `13` which means `The API is not currently supported` (NOT_SUPPORTED = 13).
