### ISSUE TITLE
HCS with submit key throws Error 13

### ISSUE THREAD

**Issue by Cooper-Kunz** [hashgraph/hedera-sdk-js#214]
When attempting to run a HCS create consensus service topic with a submit key, we're currently getting the following error. 

```
Error: 13 INTERNAL: Unexpected null for non-null column 
```

Which according to the protobufs means that it's not supported.

**Comment by mehcode** [comment]
@Cooper-Kunz This happened to be a problem in the Kabuto mirror node. Invalid submissions broke the API for get messages on topic. 

---

This is now fixed.
