### ISSUE TITLE
Unable to set autoRenewAccountId in TokenCreateTransaction

### ISSUE THREAD

**Issue by BartoszSolkaArianelabs** [hashgraph/hedera-sdk-js#2140]
### Description

I'm unable to set the autoRenewAccountId in TokenCreateTransaction.

The value in the setter is ignored. 
There is no difference in the behavior when the transaction is signed by `secondPrivateKey` vs when it's just signed by the operator.

The expected behavior is that setting autoRenewAccountId will work similarly to setting a different treasury account.

### Steps to reproduce

1. Rum the following code
``` typescript
const {
  AccountUpdateTransaction,
  Client,
  TransactionId,
  Timestamp,
  AccountId,
  Transaction,
  TokenCreateTransaction,
  TokenType,
  PrivateKey
} = require('@hashgraph/sdk');

async function run() {
  const operatorAccountId = '...';
  const operatorPrivateKey = '...';
  const secondAccountId = '...';
  const secondPrivateKey = '...';

  const client = Client.forTestnet().setOperator(operatorAccountId, operatorPrivateKey);

  const transaction = await new TokenCreateTransaction()
    .setTokenName("test_name")
    .setTokenSymbol("test_symbol")
    .setTokenType(TokenType.NonFungibleUnique)
    .setSupplyKey(PrivateKey.fromString(operatorPrivateKey))
    .setAutoRenewAccountId(secondAccountId)
    .setTreasuryAccountId(operatorAccountId)
    .freezeWith(client)
    .sign(PrivateKey.fromString(secondPrivateKey));

  await transaction.execute(client);

  console.log('operatorAccountId', operatorAccountId);
  console.log('secondAccountId', secondAccountId);

  client.close();
}
run();
```
2. Check autoRenewAccount.

### Additional context

console output:
```
operatorAccountId 0.0.2660798
secondAccountId 0.0.2184822
```
Created collection: https://hashscan.io/testnet/token/0.0.3550167

### Hedera network

testnet

### Version

v2.41.0

### Operating system

macOS

**Comment by agadzhalov** [comment]
Hi @BartoszSolkaArianelabs, thanks for submitting this issue. We will prioritise it soon and stat investigating it.
