### ISSUE TITLE
Long User Name on the new UI is not displayed correctly

### ISSUE THREAD

**Issue by armarik** [hashgraph/hedera-sdk-js#2146]
### Description

Users with long names on Guardian (latest version with new UI) are bot displayed correctly.

### Steps to reproduce

1. Create a user with a long name such as "cee - c23a7dd4-7384-4504-9d3f-8be4e36cd319"
2. Go to the initial Login page
3. Click the Demo Admin button on the login page and check the list of users and SRs (print included) where the name is not readable
4. After signing into guardian, the name of the user in the side panel is cut and the logout icon is not visible (print included)

### Additional context

![image (4)](https://github.com/hashgraph/hedera-sdk-js/assets/59831623/614cf8c2-7ab4-42c3-99f7-448c10f70578)
![image (3)](https://github.com/hashgraph/hedera-sdk-js/assets/59831623/0ae2b306-0d73-4b07-9bf7-38ba640ba610)

### Hedera network

mainnet, testnet, previewnet

### Version

v2.41.0

### Operating system

Linux

**Comment by agadzhalov** [comment]
Hi @armarik I think you've mistaken the repository since in `hedera-js-sdk` no frontend is involved . Most likely you've wanted to open to it in https://github.com/hashgraph/guardian

**Comment by armarik** [comment]
You are absolutely right 🤦  my bad,  I'll close this issue and open it in the right place. Apologies!
