### ISSUE TITLE
question - ContractCallQuery naming convention

### ISSUE THREAD

**Issue by Cooper-Kunz** [hashgraph/hedera-sdk-js#215]
The convention for getting a contract query results seems somewhat inconsistent vs other services.

```
const queryResult = await new ContractCallQuery()
  .setContractId("0.0.123456789")
  .setGas(1000)
  .setFunction("getMessage", null)
  .execute(client);

console.log("queryResult : ",queryResult.getString(0));
```

Versus 

```
fileReceipt.getFileId()

or

consensusTopicReceipt.getTopicId()
```

Is this intentional, or could we potentially rename it?

**Comment by mehcode** [comment]
In what way is it inconsistent? Perhaps I'm not seeing something.

`queryResult.getString(0)` returns the 0th result as a `string`

**Comment by Cooper-Kunz** [comment]
Sorry for the lack of clarity. I thought we typically override `.toString(`)

But even so, currently calling `.getString()` instead of `getString(0)` returns 

> RangeError: Start offset 443746866 is outside the bounds of the buffer
 
So if `.getString()` or `.toString()` by itself is the convention, and works, I'd be all set! Alternatively, because the responses for file create, topic create, etc., have specific accessors, I was thinking something more specific, like `.getResponseContents()`

**Comment by abonander** [comment]
@Cooper-Kunz the result can contain multiple strings, however. It depends entirely on the return type of the contract function you're calling. 

`.getString()` without a number is an invalid method call that Javascript unfortunately allows anyway, we'll have to add errors for that.
