### ISSUE TITLE
Incorrect handling of token type TokenType.NonFungibleUnique if it passed as enum ordinal (1)

### ISSUE THREAD

**Issue by sergedynevo** [hashgraph/hedera-sdk-js#2162]
### Description

I create nonfungible token, when I mint token. 
Expected:
 Token minted
Actual:
 No tokens minted

### Steps to reproduce

```
async function main() {
    const client = Client.forTestnet();
    const myPrivateKey = PrivateKey.fromStringDer(myPrivateKeyDer);
    const adminPrivateKey = PrivateKey.fromStringDer(adminPrivateKeyDer);
    client.setOperator(myAccountId, myPrivateKey);
    const tx = new TokenCreateTransaction()
        .setTokenName("The nft")
        .setTokenSymbol("TN")
        .setTokenType(1)
        .setTreasuryAccountId(myAccountId)
        .setSupplyKey(myPrivateKey.publicKey)
        .setAdminKey(myPrivateKey.publicKey)
    const resp = await tx.execute(client);
    const receipt = await resp.getReceipt(client);
    console.log(`${receipt}`);
    process.exit();
}
```
to mint a token
```
async function main() {
    const adminPrivateKey = PrivateKey.fromStringDer(adminPrivateKeyDer);
    const client = Client.forTestnet();
    client.setOperator(myAccountId, myPrivateKeyDer);
    const tx = new TokenMintTransaction()
        .setTokenId(tokenId)
        .setMetadata([Buffer.from("test")])
    const resp = await tx.execute(client);
    const receipt = await resp.getReceipt(client);
    console.log(`${receipt}`);
    process.exit();
}
```

### Additional context

successful transaction:
https://hashscan.io/testnet/transaction/1708581840.729569003

### Hedera network

testnet

### Version

2.42.0-beta.1

### Operating system

Windows

**Comment by agadzhalov** [comment]
Hi @sergedynevo, according to the [documentation](https://docs.hedera.com/hedera/sdks-and-apis/sdks/readme-1/define-a-token) the proper way of setting a type is by passing a `TokenType` which in your case is easily achievable by `.setTokenType(TokenType.NonFungibleUnique)`. 

![image](https://github.com/hashgraph/hedera-sdk-js/assets/77534278/43964d84-8932-4a39-bf6d-947f05906fff)


What is the specific reason you would like to pass enum? Can you give us more context?

Also if you want to set the token type from just passing a `number` this is not possible. You will have to create a `TokenType` object to which you would need to pass the enum type like this `.setTokenType(new TokenType(1))`

**Comment by sergedynevo** [comment]
Hi @agadzhalov 
> What is the specific reason you would like to pass enum? Can you give us more context?

Engaged in testing the Token Service to uncover any potential bugs.

> Also if you want to set the token type from just passing a `number` this is not possible. You will have to create a `TokenType` object to which you would need to pass the enum like this `.setTokenType(new TokenType(1))`

 was initially confused by the fact that passing a number was possible, as I successfully transferred Hbars using this:

``` JavaScript
    const transaction = new TransferTransaction()
    .addHbarTransfer(myAccountId, new Hbar(-10))
    .addHbarTransfer(otherAccountId, new Hbar(10));
```
and using this:
``` JavaScript
    const transaction = new TransferTransaction()
    .addHbarTransfer(myAccountId, -10)
    .addHbarTransfer(otherAccountId, 10);
```
But now I see that documentation clearly states that this is possible for [TransferTransaction](https://docs.hedera.com/hedera/sdks-and-apis/sdks/readme-1/transfer-tokens#methods), and is not possible for [TokenCreateTransaction](https://docs.hedera.com/hedera/sdks-and-apis/sdks/readme-1/define-a-token#methods).
