### ISSUE TITLE
TokenMintTransaction: Amount not validated before transaction

### ISSUE THREAD

**Issue by sergedynevo** [hashgraph/hedera-sdk-js#2163]
### Description

I create a fungible token. I mint a token specifying only tokenId.
Expected:
 Error, as token amount is 0
Actual:
 Transaction succeeded, spending HBars.

### Steps to reproduce

to create a token
```
async function main() {
    const client = Client.forTestnet();
    const myPrivateKey = PrivateKey.fromStringDer(myPrivateKeyDer);
    const adminPrivateKey = PrivateKey.fromStringDer(adminPrivateKeyDer);
    client.setOperator(myAccountId, myPrivateKey);
    const tx = new TokenCreateTransaction()
        .setTokenName("The token")
        .setTokenSymbol("TT")
        .setTreasuryAccountId(myAccountId)
        .setSupplyKey(myPrivateKey.publicKey)
        .setAdminKey(myPrivateKey.publicKey)
    const resp = await tx.execute(client);
    const receipt = await resp.getReceipt(client);
    console.log(`${receipt}`);
    process.exit();
}
```
to mint a token:
```
async function main() {
    const adminPrivateKey = PrivateKey.fromStringDer(adminPrivateKeyDer);
    const client = Client.forTestnet();
    client.setOperator(myAccountId, myPrivateKeyDer);
    const tx = new TokenMintTransaction()
        .setTokenId(tokenId)
    const resp = await tx.execute(client);
    const receipt = await resp.getReceipt(client);
    console.log(`${receipt}`);
    process.exit();
}
```

### Additional context

https://hashscan.io/testnet/transaction/1708583003.421824003

### Hedera network

testnet

### Version

2.42.0-beta.1

### Operating system

Windows

**Comment by sergedynevo** [comment]
Hi @agadzhalov, why was [the token mint transaction](https://docs.hedera.com/hedera/sdks-and-apis/sdks/readme-1/mint-a-token#methods) successful? I did not specify an amount or metadata. As a result, I only spent HBars and received nothing in return. 
Perhaps the default value of 'amount' for token mint transactions should be set to 1. This way, executing a mint transaction would automatically increase the token supply.

**Comment by agadzhalov** [comment]
Hi @sergedynevo as you can see in the docs
> This transaction accepts zero unit minting operations for fungible tokens ([HIP-564](https://hips.hedera.com/hip/hip-564))

You may wonder why, the simple answer is Hedera should stay consistent with most other networks. But I highly recommend you to read the whole [HIP-564](https://hips.hedera.com/hip/hip-564) for more details.

Let's take these two examples:
**Example 1**
`new TokenMintTransaction().setTokenId(tokenId)`

**Example 2**
`new TokenMintTransaction().setTokenId(tokenId).setAmount(0)`

The results of these two examples are the same. They both behave the same way. So basically when you don't pass `setAmount()` to your mint transaction is equivalent to passing `setAmount(0)`.

**Comment by sergedynevo** [comment]
Thanks!
