### ISSUE TITLE
Contract nonce field is missing in the getContractInfo() query and we have no way to get the nonce of a contract 

### ISSUE THREAD

**Issue by anastasiya-kovaliova** [hashgraph/hedera-sdk-js#2192]
### Description

In the Smart Contracts repo we need to get the nonce of a contract. We cannot track every transaction and search for the last nonce in it. We need to use the getContractInfo() query and get the contract nonce from it in the same way we are getting the account nonce field - EthereumNonce from the getAccountInfo() query.
Relevant documentations: 
- getAccountInfo() - has nonce field - Ethereum Nonce https://docs.hedera.com/hedera/sdks-and-apis/deprecated/sdks/cryptocurrency/get-account-info
- getContractInfo() -has no nonce field - https://docs.hedera.com/hedera/sdks-and-apis/sdks/smart-contracts/get-smart-contract-info

**NOTE**: this field is important for completing the tests for the account nonce discrepancies fiexs. Tests task: https://github.com/hashgraph/hedera-smart-contracts/issues/677

### Steps to reproduce

From the Smart Contracts project execute the getContractInfo() query and check the results returned.

Expected Result:
Contract nonce field should be present .

Actual Result:
No contract nonce field present.

### Hedera network

mainnet

### Version

2.42.0

### Operating system

None

**Comment by SimiHunjan** [comment]
The contract nonce field is not returned in contract get info query. Please see https://github.com/hashgraph/hedera-protobufs/blob/main/services/contract_get_info.proto.
