### ISSUE TITLE
TransactionReceipt.js is missing transactionId

### ISSUE THREAD

**Issue by HashGateApp** [hashgraph/hedera-sdk-js#2204]
### Description

I noticed that when sending a transaction and calling the transaction response as outlined in the [documentation](https://docs.hedera.com/hedera/sdks-and-apis/sdks/transactions/get-a-transaction-receipt). It's missing the .transactionId

### Steps to reproduce

```
TransactionReceipt receipt = txResponse.getReceipt(client);

receipt.transactionId <--- Doesn't exist
```

Screenshot of console.log(receipt)
![Screenshot 2024-03-15 113940](https://github.com/hashgraph/hedera-sdk-js/assets/149125380/127d21b9-0519-4592-9726-95230e449134)

### Hedera network

mainnet

### Version

2.41.0

### Operating system

Windows

**Comment by svetoslav-nikol0v** [comment]
Hello [HashGateApp](https://github.com/HashGateApp),

Yes, the `transactionId` is not included in `TransactionReceipt` object. It's included in `TransactionResponse` object. You You can check the documentation [here](https://docs.hedera.com/hedera/sdks-and-apis/sdks/transactions/submit-a-transaction).

```
Once you submit the transaction, the response will include the following:

- The transaction ID of the transaction
- The node ID of the node the transaction was submitted to
- The transaction hash

```

**Comment by svetoslav-nikol0v** [comment]
Hey [HashGateApp](https://github.com/HashGateApp),
Have you had a chance to check the documentation? Is there anything else we can help with?

**Comment by HashGateApp** [comment]
@svetoslav-nikol0v Thank you for sharing the Transaction Response documentation page, I was able to review it there.

My concern is that on the page dedicated to [Get A Transaction Receipt"](https://docs.hedera.com/hedera/sdks-and-apis/sdks/transactions/get-a-transaction-receipt) "transactionId" is highlighted in the Helper Methods under <TransactionReceipt>.transactionId

![image](https://github.com/hashgraph/hedera-sdk-js/assets/149125380/7359c5f6-a3ad-4b25-a8f3-a36baeaa0f85)

It appears that the Go and Java libraries have the transactionId under TransactionReceipt where as the JavaScript one does not

**Comment by SimiHunjan** [comment]
hey @HashGateApp ! Thanks for catch. We have updated the documentation here https://docs.hedera.com/hedera/sdks-and-apis/sdks/transactions/get-a-transaction-receipt.
