### ISSUE TITLE
Smart contract ContractCallQuery function cost

### ISSUE THREAD

**Issue by MaxiCredit** [hashgraph/hedera-sdk-js#221]
When I call the same script - which contains 3 ContractCallQuery functions - sometimes I need to pay nearly 5 hbars, sometimes only 0,06 hbars. I test my app on 0.testnet.hedera.com:50211. What cause this?

**Comment by mehcode** [comment]
What version of the SDK are you using? What version of Node?

**Comment by MaxiCredit** [comment]
@hashgraph/sdk@1.1.8
Node 10.16.0

**Comment by mehcode** [comment]
Can you set an explicit query payment to rule out the SDK making a mistake here @MaxiCredit ? 

---

```js
// on ContractCallQuery
.setQueryPayment(new Hbar("0.06")) 
```

The idea is to set it low, and bump it up if you need. It's possible there is an issue with automatically determining the payment amount. This will rule that out. 

In other words, if this works, there is an issue in determining the payment amount (either from the SDK or the network). If this doesn't, then the actual cost of the query calls is rapidly fluctuating.

**Comment by MaxiCredit** [comment]
It works that way. 
I set it to 0.015Hbar, below I get 'insufficient tx fee' error

**Comment by paulmadsenhed** [comment]
hi @MaxiCredit have you tried using the https://www.hedera.com/fees#estimator to predict the fees?

**Comment by MaxiCredit** [comment]
Yes, based on that calculator thought I that the higher fees are not correct.
Also, I am thinking of calculating dynamically the fee for .setQueryPayment. Is the estimator's algorithm somewhere available?

**Comment by paulmadsenhed** [comment]
what are the parameters of your call? 

The predicted query payment is determined by a) how much of various resources (bandwidth, gas, etc) your call consumes multiplied by b) specified hbar/resource unit prices - we currently only surface that result

**Comment by MaxiCredit** [comment]
Now I use it in this general way:
exports.callContract = async (contractId, functionName, params, hederaClient) => {
    let callResult = await new ContractCallQuery()
    .setContractId(contractId)
    .setQueryPayment(new Hbar("0.015"))  
    .setGas(10000) 
    .setFunction(functionName, params)
    .execute(hederaClient);

    console.log("call gas used:", callResult.gasUsed);
    return callResult;
}

So the parameter number differs on the scripts which use it. Some of them have only 1 parameter
while others have 6-7 parameters and return values. That why I am thinking of set the fee dynamically.
Here you can see examples:
https://github.com/MaxiCredit/Hedera-js

**Comment by paulmadsenhed** [comment]
the estimator indicates that that much gas can push the fee beyond your stipulated 0.015. For a ContractCallLocalQuery (as opposed to a ContractCall tx), the node to which  you are sending will take all the gas you provide in determining whether or not the payment is sufficient.

![Screenshot_2020-03-28 Fees Hedera Hashgraph](https://user-images.githubusercontent.com/50834364/77824749-57b74a00-70db-11ea-9ef6-d5b425f814bf.png)

**Comment by mehcode** [comment]
Given the numerous issues here we should probably push users towards setting an explicit payment amount for contract calls.

**Comment by donaldthibeau** [comment]
@paulmadsenhed to open issue on services code.
