### ISSUE TITLE
TokenCreateTransaction fails with INVALID_EXPIRATION_TIME when freezing with a client without operator

### ISSUE THREAD

**Issue by seromenho** [hashgraph/hedera-sdk-js#2216]
### Description

I am creating a TokenCreateTransaction transaction to be signed and broadcasted later (in less than the validity time window), but there's an error when executing the query

```console
transaction xxx failed precheck with status INVALID_EXPIRATION_TIME
```

### Steps to reproduce

```ts
const client = Client.forTestnet()
const payerAccountId = AccountId.fromString(payerAccountIdString)
const transactionId = TransactionId.generate(payerAccountId)
const treasuryPublicKey = PublicKey.fromStringED25519(publicKey)

const tx = new TokenCreateTransaction()
    .setTokenName(name)
    .setTokenSymbol(symbol)
    .setTreasuryAccountId(tresuryAccountId)
    .setInitialSupply(Long.fromString(initialSupply))
    .setTokenType(type)
    .setDecimals(decimals)
    .setPauseKey(treasuryPublicKey)
    .setSupplyKey(treasuryPublicKey)
    .setAdminKey(treasuryPublicKey)
    .setWipeKey(treasuryPublicKey)
    .setKycKey(treasuryPublicKey)
    .setTransactionId(transactionId)
    .setNodeAccountIds(nodeAccountIds)
    .freezeWith(client)
```

After signing, on broadcasting the error happens.
```ts
const client = Client.forTestnet()
const signedTransaction = Transaction.fromBytes(Buffer.from(signedRawTx, 'hex'))
const txResponse = await signedTransaction.execute(client)
```
  

### Additional context

Maybe a related issue: https://github.com/hashgraph/hedera-sdk-js/issues/991

### Hedera network

testnet

### Version

2.37.0

### Operating system

Linux

**Comment by seromenho** [comment]
I've found the problem right after creating this issue 🙃 

The documentation mentions that the default expiration time is 90 days by default but If I freeze the transaction without an operator the default value for expiration time is not set correctly.
I've fixed this manually setting the expiration time. 

```ts
const expirationTime = new Date()
expirationTime.setSeconds(expirationTime.getSeconds() + 7890000)
...
.setExpirationTime(expirationTime)
...
```

Closing the issue

**Comment by svetoslav-nikol0v** [comment]
Hi [seromenho](https://github.com/seromenho),

Setting the expiration time will do the job. In the newest version `2.44.0` the expiration time is set to `90 days` (as mentioned in the documentation) so it's not necessary to set it explicitly. 
Regarding the issue you mentioned above, the logic that was implemented then is removed now because overrides the `auto-renew account` if is different from the `operator account`.

We'll close the ticket if you have no further questions.

**Comment by svetoslav-nikol0v** [comment]
Hi @SimiHunjan ,
I think we can close this ticket.
