### ISSUE TITLE
ContractFunctionParams AddBytes32Array

### ISSUE THREAD

**Issue by RyoungHo** [hashgraph/hedera-sdk-js#225]
simple issue.

`public addBytes32Array(value: Uint8Array[]): this` function has bug.

current => this._selector.addBytes32();
chage => this._selector.addBytes32Array();

thanks.

**Comment by RyoungHo** [comment]
[https://github.com/hashgraph/hedera-sdk-js/blob/de1173277c38bc861c73ae35131f9b2614d5f5a0/src/contract/ContractFunctionParams.ts#L61](url)

**Comment by RyoungHo** [comment]
https://github.com/hashgraph/hedera-sdk-js/blob/de1173277c38bc861c73ae35131f9b2614d5f5a0/src/contract/ContractFunctionParams.ts#L61

**Comment by mehcode** [comment]
Resolved in #230
