### ISSUE TITLE
addTokenTransferWithDecimals() method not working

### ISSUE THREAD

**Issue by jaycoolslm** [hashgraph/hedera-sdk-js#2302]
### Description

Trying to use the addTokenTransferWithDecimals() to handle increasing the order of magnitude of a token but not making a difference.

Am on SDK "@hashgraph/sdk": "^2.45.0",

### Steps to reproduce

e.g. this token has 4 decimals. would expect this to send 1 of tokenId but it sends 0.0001

const tx = await new TransferTransaction()
    .addHbarTransfer(clientAccountId, -1)
    .addHbarTransfer(secondId, 1)
    .addTokenTransferWithDecimals(tokenId, secondId, 1, 4)
    .addTokenTransferWithDecimals(tokenId, clientAccountId, -1, 4)
    .setTransactionId(transactionId)
    .setNodeAccountIds([new AccountId(3)])
    .freeze()
    .sign(PrivateKey.fromStringED25519(secondKey));

### Hedera network

mainnet

### Version

latest

### Operating system

macOS

**Comment by ivaylonikolov7** [comment]
Hello @jaycoolslm

We tried to reproduce your issue by using the snippet you have provided. We made a transaction that transfers a token with decimals by executing `addTokenTransferWithDecimals` function.

After thoroughly done research, me and the team have concluded that `addTokenTransferWithDecimals` works as expected. Both `addTokenTransferWithDecimals` and `addTokenTransfer` both work the same way. They use the smallest part of a token similar to how hbar uses tiny bar when you transfer tokens and don't do any change to the amount like you expect. 

The difference between the two functions is that `addTokenTransfer` skips the decimals validity check. `addTokenTransferWithDecimals` function checks if you've used the correct amount of decimals and it throws an `INVALID_TOKEN_DECIMALS` error if not. Other than that this function doesn't do any transformation like increasing the order of magnitude of a token you expected in your issue. 

So given a token with 4 decimals and initial balance of receiver of 0 after the execution of this code snippet: 

```javascript
  const transferToken2 = await new TransferTransaction()
    .addTokenTransferWithDecimals(tokenId, receiverId, 1, 4)
    .addTokenTransferWithDecimals(tokenId, OPERATOR_ID, -1, 4)
    .addTokenTransfer(tokenId, receiverId, 4)
    .addTokenTransfer(tokenId, OPERATOR_ID, -4)
    .execute(client);
```

Receiver should have 5 of the smallest parts of a token or 0,0005.

**Comment by jaycoolslm** [comment]
Okay, so it's working as expected - but can't just be me who thinks it sounds quite counter intuitive?

**Comment by ivaylonikolov7** [comment]
We think Hedera SDKs should behave the same way in every aspect so we follow the same approach as the other SDKs. If we see a bump of issues similar to this we might have to rethink our strategy and change this everywhere. As of right now I think the thing we could do is we might have to improve the documentation to help other users like you. 

Thank you for the feedback!
