### ISSUE TITLE
NO_REMAINING_AUTOMATIC_ASSOCIATIONS

### ISSUE THREAD

**Issue by AdrianKBL** [hashgraph/hedera-sdk-js#2356]
### Description

For the Account Id 0.0.1704837 , the MirrorNode is returning that has 2 remainingAutomaticAssociations left, however, whenever this account tries to get an NFT (Without having the Token Id associated) It ends with the error from the SDK **NO_REMAINING_AUTOMATIC_ASSOCIATIONS**

### Steps to reproduce

```js
const accountId = "1704837";
const baseUrl = "https://mainnet-public.mirrornode.hedera.com/";
const tokensUrl = `${baseUrl}/api/v1/accounts/${accountId}/tokens?limit=100&order=desc`;
const accountUrl = `${baseUrl}/api/v1/accounts/${accountId}`;

async function fetchTokens(url) {
  let tokenAccount = [];
  let nextUrl = url;

  while (nextUrl) {
    const response = await fetch(nextUrl);
    const data = await response.json();
    tokenAccount = tokenAccount.concat(data.tokens);
    nextUrl = data.links.next ? baseUrl + data.links.next : null;
  }

  return tokenAccount;
}

async function getAccountInfo(url) {
  const response = await fetch(url);
  const data = await response.json();
  return data;
}

async function main() {
  // Fetch tokens
  const tokens = await fetchTokens(tokensUrl);

  // Count tokens with automatic_association == true
  const automaticAssociationCount = tokens.filter(token => token.automatic_association).length;

  console.log(`Number of tokens with automatic association: ${automaticAssociationCount}`);

  // Fetch account information
  const accountInfo = await getAccountInfo(accountUrl);

  console.log(`Max automatic token associations: ${accountInfo.max_automatic_token_associations}`);
}

main();
```
Output:
Number of tokens with automatic association: **7**
Max automatic token associations: **9**

I should be able to automatically associate 2 more tokens, but the network does not allow it and transactions fail with an error. 
![image](https://github.com/hashgraph/hedera-sdk-js/assets/59306428/fe658c7c-0a67-48c4-b93c-a77aadba50d0)

### Hedera network

mainnet

### Version

v2.45.0

### Operating system

macOS

**Comment by SimiHunjan** [comment]
@AdrianKBL the mirror node team they don't track remaining automatic association accounts and linked this issue where they state that https://github.com/hashgraph/hedera-mirror-node/issues/7399

**Comment by SimiHunjan** [comment]
@AdrianKBL the next steps for the mirror node to support this in the future is for someone in the community to champion the HIP

**Comment by SimiHunjan** [comment]
Closing this issue as it is unrelated to the SDK.
