### ISSUE TITLE
Add unit tests for HIP-869

### ISSUE THREAD

**Issue by svetoslav-nikol0v** [hashgraph/hedera-sdk-js#2406]
### Problem

The HIP introduces the ability to manage the Address Book via HAPI endpoints within current Address Book implementation.

### Solution

Use the following [test plan](https://www.notion.so/swirldslabs/HIP-869-Dynamic-Address-Book-Stage-1-HAPI-Endpoints-eb0e9f31b6e247a9a452aa263eb8dc34?pvs=4#235d711b77404023982c6b908baeba0f) to verify the behavior of the function.

**Comment by ivaylonikolov7** [comment]
fixed in https://github.com/hashgraph/hedera-sdk-js/pull/2459

**Comment by annamariyaivanova** [comment]
This issue relates only to unit tests, which have been done as part of development. The integration tests will be resolved in https://github.com/hashgraph/hedera-sdk-js/issues/2480
