### ISSUE TITLE
INSUFFICIENT_TX_FEE exception in examples

### ISSUE THREAD

**Issue by Sangatdas** [hashgraph/hedera-sdk-js#241]
Getting INSUFFICIENT_TX_FEE issue when running create-stateful-contract.js on testnet.
Getting above Exception when trying to update message. 

    // Update the message
->    const getRecord = await (await new ContractExecuteTransaction()
        .setContractId(newContractId)
        .setGas(7000) // ~6016
        .setFunction("setMessage", new ContractFunctionParams()
            .addString("hello from hedera again!"))
        .execute(hederaClient))
        // [getReceipt] or [getRecord] waits for consensus before continuing
        //      and will throw an exception
        //      on an error received during that process like INSUFFICENT_GAS
        .getRecord(hederaClient);

**Comment by donaldthibeau** [comment]
Can you confirm this issue still exists when submitting with a large amount of hbar and a funded account?

**Comment by mehcode** [comment]
The transaction fee is checked against your balance using the "maximum" gas amount you set. Up your max transaction fee using `.setMaxTransactionFee`. The actual hbar amount needed fluctatues between around 1~ hbar. Default is 1 in the SDK. Try setting it to a few hbar.
