### ISSUE TITLE
loop of messages without reading the receipt

### ISSUE THREAD

**Issue by ronete** [hashgraph/hedera-sdk-js#243]
Hi,

Could you please let me know if the following code is valid:
     for (let i = 0; i < 50; i += 1) {
         await new ConsensusSubmitMessageTransaction()
              .setTopicId(topicId)
              .setMessage(`${i}`)
              .execute(client);
     }

Please note that there is not receipt reading in the loop.

Thank you,
Ronete

**Comment by Cooper-Kunz** [comment]
Hi @ronete - it seems like you have a pretty small error in `.setMessage()`. 

You need to use a template literal in JS if you want to do things that way, e.g. `.setMessage(`${i}`)`

Also note that you don't have to get the receipt, if you don't want it 😄 But they can provide helpful insights into why your transaction may have failed, e.g. an `INVALID_TOPIC_MESSAGE`

Let us know if you have any other questions!

**Comment by ronete** [comment]
Hi Cooper, 

Yes, as you guessed, GitHub translated the markdown. The code generated transactions, it is OK syntactically. 

The reason why I sent this note is the observation that the transactions reached the mirror node (used Kabuto) out of order. The same order of transactions as Kabuto was reported by Hedera mirror (MIRROR_NODE_ADDRESS="hcs.testnet.mirrornode.hedera.com:5600").

I expected the transactions to be ordered by the HCS in the same order as they were sent. 
Could you please explain why the order is not preserved?

Thank you,
Ronete

**Comment by ronete** [comment]
Hi Cooper,

Thank you for your explanations. 
This is a good link that explains in details the Fair Ordering of Transactions, I added for my own reference:
https://www.hedera.com/blog/fair-timestamping-and-fair-ordering-of-transactions

Waiting for receipts decreases a lot the throughput of transactions. Is there anything else we can do to preserve the order of transactions without waiting for each receipt?

Thank you,
Ronete

**Comment by mehcode** [comment]
> Waiting for receipts decreases a lot the throughput of transactions. Is there anything else we can do to preserve the order of transactions without waiting for each receipt?

Nope. You can order by "transaction ID" at a later date as that will be sequential and in-insertion-order from the scope of only your client. 

---

I'm going to close this as there is nothing actionable on the SDK, but feel free to continue the conversation.
