### ISSUE TITLE
Incorrect validation for Bytes32 cast

### ISSUE THREAD

**Issue by JaimeSilver** [hashgraph/hedera-sdk-js#248]
There is an incorrect validation for Bytes32 and Bytes32 arrays. The following link addresses the issue: https://github.com/JaimeSilver/hedera-sdk-js/tree/Bytes32-Cast

**Comment by danielakhterov** [comment]
Can you elaborate on what you mean by "incorrect validation". I looked your last commit in the link your referenced and all you did was remove error handling. I'm wondering why you did that. `addBytes32()` and its array counterpart `addBytes32Array()` expect the input to be exactly 32 bytes long because the Solidity type being encoded is `bytes32`, not `bytes${param.length}`.

**Comment by JaimeSilver** [comment]
Hello Daniel,

In Solidiy (and Remix) a Bytes32 is submitted in Hex, so at the point of validation the string is not 32 in length, but 66 (64 plus the 2 of the 0x prefix). We were using Composer with Pablo and the validation was stopping the conversion from our input variable.

 

Example: “TESTNET-OA-TEST002” 0x544553544e45542d4f412d544553543030320000000000000000000000000000

 

I suspect the 8 arrays you have now might work since every variable is managed as byte string. But that is the next thing to check. Pablo is testing that repo and we will let you know if it solved the problem.

 

Jaime Plata
Co-founder, All Over Chain

jp@aochain.net <mailto:jp@aochain.net> 


WhatsApp/Mobile : +1 (704) 3073702 

 

This email may contain material that is confidential, privileged and/or attorney work product for the sole use of the intended recipient.  Any review, reliance or distribution by others or forwarding without express permission is strictly prohibited.  If you are not the intended recipient, please contact the sender and delete all copies.

**Comment by danielakhterov** [comment]
@JaimeSilver The parameter to `addBytes32` is not a `string`, but instead an `Uint8Array` meaning you should decode your string before you pass it to the method.

**Comment by JaimeSilver** [comment]
Alright then it should happen in Composer, I guess.
