### ISSUE TITLE
Difficulty Using Hashgraph SDK Directly in Browser Environments

### ISSUE THREAD

**Issue by ankurzeroic** [hashgraph/hedera-sdk-js#2482]
### Description

**Issue Description**

There is currently no straightforward way to use the Hashgraph SDK directly in a browser environment without a build step. This creates a significant barrier for developers who want to create quick prototypes, demos, or simple browser-based applications using the Hedera network. 

**Attempted Solutions and Their Outcomes**

1. Direct CDN Link to NPM Package:

Attempted URL: https://cdn.jsdelivr.net/npm/@hashgraph/sdk@2.50.0/dist/browser-bundle.min.js
Outcome: Failed with error "Couldn't find the requested file /dist/browser-bundle.min.js in @hashgraph/sdk."

2. Using Skypack CDN:

Attempted Code:
htmlCopy<script type="module">
  import * as HashgraphSDK from 'https://cdn.skypack.dev/@hashgraph/sdk';
  window.HashgraphSDK = HashgraphSDK;
</script>

Outcome: Failed with error "Package Error: 'node-forge@v1.3.1' could not be built. (Imported by '@hashgraph/cryptography')"

3. Using jsDelivr with ESM:

Attempted Code:
htmlCopy<script type="module">
  import { Client, AccountId, PrivateKey, TransferTransaction, Hbar, TransactionId } from 'https://cdn.jsdelivr.net/npm/@hashgraph/sdk@2.50.0/src/index.js';
</script>

Outcome: Failed with error "Uncaught TypeError: Failed to resolve module specifier '@hashgraph/cryptography'. Relative references must start with either '/', './', or '../'."

4. Pre-built Bundle Approach:

Attempted URL: https://cdn.jsdelivr.net/npm/@hashgraph/sdk@2.24.0/dist/ui-utils.min.js
Outcome: File not found at the specified location.

### Steps to reproduce

**Steps to Reproduce**

1. Create a simple HTML file.
2. Attempt to include the Hashgraph SDK using a script tag.
3. Try to use the SDK functions in JavaScript.

### Hedera network

mainnet

### Version

v2.50.0

### Operating system

macOS

**Comment by SimiHunjan** [comment]
Please re-open if you are having issues.
