### ISSUE TITLE
bytes 32 input parameter

### ISSUE THREAD

**Issue by JaimeSilver** [hashgraph/hedera-sdk-js#250]
https://github.com/hashgraph/hedera-sdk-js/blob/master/src/contract/ContractFunctionParams.ts

Please adjust function for bytes32 as it is incorrectly mapping as a Dynamic parameter:

    addBytes32(value) {
        if (value.length !== 32) {
            throw new Error(`addBytes32 expected array to be of length 32, but received ${value.length}`);
        }
        this._selector.addBytes32();
        return this._addParam(value, false);
    }

**Comment by danielakhterov** [comment]
Thank your mentioning this. This should now be fixed on master https://github.com/hashgraph/hedera-sdk-js/commit/5a599683d440b0d5a0300f1a0ce5079305097530
