### ISSUE TITLE
FileCreate/FileUpdate automatic chunking

### ISSUE THREAD

**Issue by jbair06** [hashgraph/hedera-sdk-js#2500]
### Problem

When creating or updating a file using the FileCreate or FileUpdate, if the contents are too large for a single transaction, a FileAppend is required to be created in addition to the FileCreate/Update.

FileAppend, on the other hand, can handle a large content because it does chunking of that content internally. It would be good to have FileCreate and FileUpdate to have this same functionality.

### Solution

Refactor FileCreate, FileUpdate, and FileAppend to all share a base class. This base class will have the shared components, including the chunking logic currently located in FileAppend.

**Comment by ivaylonikolov7** [comment]
After some syncs with the transaction tool team they managed to fix this issue without the need of automatic chunking for FileCreate/FileUpdateTransaction.
