### ISSUE TITLE
Topic subscription keepalive

### ISSUE THREAD

**Issue by gregscullard** [hashgraph/hedera-sdk-js#251]
Been noticing dropouts in mirror subscriptions if no transactions are sent for a few minutes, restarting the client fixes the issue.

The error handler in the JS client wasn't triggered when the connection was lost (mirror logs show the connection was cancelled suggesting it was closed by the client).

The Java SDK has a keep-alive, should/is the JS sdk doing the same ?

**Comment by mehcode** [comment]
It's not. It should be.

**Comment by qtbeee** [comment]
This is fixed on master (6b1150c395a259378247313a5a4a5c08398a5e15)
