### ISSUE TITLE
[QUESTION] Library + Contract

### ISSUE THREAD

**Issue by bakasura980** [hashgraph/hedera-sdk-js#252]
Hello, 

In my scenario, I have a contract that uses a library(Solidity). Is there a way to deploy such kind of contract and it would be great if you provide some examples

Thanks in advance

**Comment by christianholman** [comment]
https://github.com/hashgraph/hedera-sdk-js/blob/master/examples/create-stateful-contract.js Is this what you're looking for?

**Comment by donaldthibeau** [comment]
You can find documentation on how to use the smart contract service here: https://docs.hedera.com/guides/docs/hedera-api/smart-contracts
