### ISSUE TITLE
Duplicate transaction IDs

### ISSUE THREAD

**Issue by gregscullard** [hashgraph/hedera-sdk-js#253]
At high throughput, I encountered frequent duplicate transaction IDs.

Suggest a random element is added to the nanoseconds part of the transaction ID to lessen the risk of collisions. 

I see the code adds 1 to every nano second, but using the same account ID in a horizontally scaled solution with high throughput still results in duplicates since each instance of the SDK is independent.

**Comment by mehcode** [comment]
cc @xin-hedera 

---

Perhaps we should stop trying to do anything here and just provide a method on the client that sets a callback that gets invoked to return a new transaction ID. That way users can figure out their own solution as this is not an easy problem and can have different solutions depending on their constraints. 

```js
client.setNewTransactionId((account) => /* ... */);
```

I can't think of a good name for the method though:

 * `setMakeNewTransactionId`
 * `setOnNewTransactionId`

**Comment by mehcode** [comment]
Fixed on `develop` by doing as suggesting:

> Suggest a random element is added to the nanoseconds part of the transaction ID to lessen the risk of collisions.

**Comment by Steven-Yulong-Yan** [comment]
Hey, we are still experiencing this
