### ISSUE TITLE
removeAllSignatures return type should be map

### ISSUE THREAD

**Issue by jbair06** [hashgraph/hedera-sdk-js#2546]
### Problem

The removeAllSignatures function returns a dictionary of type {{ [publicKeyString: string]: Uint8Array[] }}. This is because JavaScript only deals with strings and numbers as keys in a dictionary. In order to maintain consistency with the other remove/add signature methods, this return type should be a map.

### Solution

Use a map instead of a dictionary as the return type, thus allowing the PublicKey to be used as the key, instead of a string.

**Comment by ivaylonikolov7** [comment]
resolved via #2559
