### ISSUE TITLE
forTestnet forMainnet is not a configurable interface

### ISSUE THREAD

**Issue by keithy** [hashgraph/hedera-sdk-js#255]
(caveat, my modern javascript experience is minimal having last coded in js over 10 years ago)

The lists of nodes appear to be hard coded internally but are not exported or usable for the sdk client-code.

As far as I can see the Client instanciation interface is requiring me either, to know the nodes already, or to use Client.forMainnet() and Client.forTestnet() forcing code like this...

```
switch(h_network) {
  case "main":
    client = Client.forMainnet()
    break;
  case "test":
    client = Client.forTestnet()
    break;
  default:
    console.log("Network is not set ", h_network);
}
```
Might I suggest this whole thing be re-thought, as this is the first piece of the hedera sdk that a new developer sees and it does not support a basic configurable usage scenario.

**Comment by mehcode** [comment]
> Might I suggest this whole thing be re-thought [...]

That comes off a bit harsh. We're definitely open to ideas. That's the spirit of open source. Do you have an idea of how it *should* work?

---

```js
switch(h_network) {
  case "main":
    client = Client.forMainnet()
    break;
  case "test":
    client = Client.forTestnet()
    break;
  default:
    // you have a subtle bug here where client won't be initialized, you should throw instead
    console.log("Network is not set ", h_network);
}
```

```js
// note that this does not work, its a simple matter of exporting a constant however
switch(h_network) {
  case "main":
    client = new Client(Mainnet)
    break;
  case "test":
    client = new Client(Testnet)
    break;
  default:
    console.log("Network is not set ", h_network);
}
```

I'm not seeing a huge difference between the above snippets. They both can be reduced to this pattern:

```js
let creator
switch (h_network) {
  case "main":
    creator = Client.forMainnet // require("hedera-sdk-js").Mainnet
    break

  case "test":
    creator = Client.forTestnet
    break

  // [...]
}

let client = creator();
```

```js
let network
switch (h_network) {
  case "main":
    network = Mainnet // require("hedera-sdk-js").Mainnet
    break

  case "test":
    network = Testnet
    break

  // [...]
}

let client = new Client(network);
```

**Comment by keithy** [comment]
Thanks for your prompt reply, took me a while to understand that you were suggesting I would have to submit a PR to add the export of the constants.

My own limitation is that I dont undersand javascript enough to start contributing to a project on day 2 of using javascript. I am sure that you wouldn't want my contributions (just yet) especially since at first glance exporting and Importing appears to be a non-trivial js topic.

Forgive me, by suggesting a rethink I was actually trying to be gentle...

My suggestion is that that having the words "mainnet" and "testnet" existing in the code at all stands out as being a candidate for configuration rather than code. When you consider that the future will have a betaNet and other sub-groups of my-favourite-nodes, or my-local-shard, I was surprised to see this amount of hardcoding.

A simple suggestion as to how it could work, is as follows.

configuration files: mainnet.conf, testnet.conf, betanet.conf // or supply your own
instanciation via client = Client.newFor('testnet') // reads the appropriate configuration file.

Alternatively have the networks defined in a hash, and pick one.
nodes['mainnet']={...}
nodes['testnet']={...}
nodes['betanet]={...}

**Comment by mehcode** [comment]
> Thanks for your prompt reply, took me a while to understand that you were suggesting I would have to submit a PR to add the export of the constants.

Definitely not saying you should submit a PR. You can. That's what open source is there for. However at a minimum, I do need to understand how you want it to work.

---

We do support configuration by file if that's what you're after. Look at `Client.fromFile` or `Client.fromJson`.

**Comment by keithy** [comment]
So I tried this...
```
const { Client } = require('@hashgraph/sdk');
 
module.exports = { 
    main: function(operator){
      return Client.forMainnet().setOperator( operator );
    },
    test: function(operator){
      return Client.forMainnet().setOperator( operator );
    }
}
```
used via
```
h_network="main";
clients[ h_network ]( operator )
```
I appear to have discovered that the operator arguement provided via the constructor and the operator argument provided via setOperator are not the same.

**Comment by keithy** [comment]
What I am after is simply to be able to select which network I am by changing a variable from "test" to "main", rather than by changing actual code. How can one publish some production code and run test cases against that code if it has to be hardcoded to use forMainnet()? Am I missing something?

**Comment by keithy** [comment]
something like 
```
export class NetworkNodes { ... }

export const Network = {
    map: {
        test: this
        main: this,
        file: NetworkNodes,
        nodes: NetworkNodes,
        random: NetworkNodes
    },
    use(name, ...args) {
        let cls = this.map[name]; /* || raise blue murder here*/;
        return cls[name](...args);
    }
    with( name, aClass) {
        self.map.push({ name, aClass} );
    }
    test() {
        return {
            "0.testnet.hedera.com:50211": "0.0.3",
            "1.testnet.hedera.com:50211": "0.0.4",
            "2.testnet.hedera.com:50211": "0.0.5",
            "3.testnet.hedera.com:50211": "0.0.6"
        };
    }
    main() {
        return {
            "35.237.200.180:50211": "0.0.3",
            "35.186.191.247:50211": "0.0.4",
            "35.192.2.25:50211": "0.0.5",
            "35.199.161.108:50211": "0.0.6",
            "35.203.82.240:50211": "0.0.7",
            "35.236.5.219:50211": "0.0.8",
            "35.197.192.225:50211": "0.0.9",
            "35.242.233.154:50211": "0.0.10",
            "35.240.118.96:50211": "0.0.11",
            "35.204.86.32:50211": "0.0.12"
        };
    }
};
```

**Comment by mehcode** [comment]
As I already suggested, from what you're suggesting, `Client.fromFile` is exactly what you are after. It enables you to do:

```js
// let networkFile = "networks/testnet.json";
let networkFile = "networks/mainnet.json";

let client = Client.fromFile(networkFile);
```

---

> The code below addresses the first issue, the title of this issue itself remains: "forTestnet forMainnet is not a configurable interface"

It is not designed to be. It is a method of convenience. There is the constructor that accepts a hashmap of the network as well as support for creating from JSON files.

If you simply want to toggle from main to test:

```js
let client = isTest ? Client.forTestnet() : Client.forMainnet();
``` 

---

I'm going to close this as there is not an actionable suggestion here. You've asked for configuration from files and we do indeed support that. If I'm misunderstanding something, please feel free to respond.
