### ISSUE TITLE
Invalid Transaction Start

### ISSUE THREAD

**Issue by ke389954** [hashgraph/hedera-sdk-js#256]
Hi,
I am trying to execute the fileService code  and create smart contract code. I am getting the error as
error { HederaPrecheckStatusError: Transaction 0.0.1@124124.151515 failed with status: TRANSACTION_EXPIRED
    at Function._throwIfError (/examples/node_modules/@hashgraph/sdk/lib/errors/HederaPrecheckStatusError.js:18:19)
    at Transaction.<anonymous> (examples/node_modules/@hashgraph/sdk/lib/Transaction.js:132:67)
    at Generator.next (<anonymous>)
    at fulfilled (/h
examples/node_modules/@hashgraph/sdk/lib/Transaction.js:5:58)
    at <anonymous>
  message: 'Transaction 0.0.1@124124.151515 failed with status: TRANSACTION_EXPIRED',
  status: TRANSACTION_EXPIRED,
  name: 'HederaPrecheckStatusError',
  transactionId: 0.0.1@124124.151515 }

Could you please guide me ?

**Comment by qtbeee** [comment]
The Transaction ID's timestamp is too far into the past. Are you setting the timestamp manually?

**Comment by ke389954** [comment]
I tried to run the example code which is given in the doc.

**Part of the code: without modifications** 

  const transactionId = await new FileCreateTransaction()
    .setContents("Hello, Hedera's file service!")
    .addKey(operatorPublicKey) // Defines the "admin" of this file
    .setMaxTransactionFee(new Hbar(15))
    .execute(client);

**ERROR:**
when I ran, got the error as " HederaPrecheckStatusError: Transaction 0.0.74581@1594188167.76000000 failed with status: INVALID_TRANSACTION_START"

**Part of the code:** 
Here I tried to set it manually. 

    const transactionId = await new FileCreateTransaction()
    .setContents("Hello, Hedera's file service!")
    .addKey(operatorPublicKey) // Defines the "admin" of this file
    .setMaxTransactionFee(new Hbar(15))
    .setTransactionId({
    account: { shard: 0, realm: 0, account: 1 }, //
    validStartSeconds: 1994187,
    validStartNanos: 256846
}).execute(client);
main();

**ERROR:**

  When I ran but  got the error as "HederaPrecheckStatusError: Transaction 0.0.1@124124.151515 failed with status: TRANSACTION_EXPIRED"

**Comment by ke389954** [comment]
Hi,
I got to know the problem. My system time was ahead by 10 mins.
But could you please tell me how to set these parameters
**validStartSeconds: 1994187,
validStartNanos: 256846.**
I mean the values.

**Comment by mehcode** [comment]
Use `withValidStart` to produce a new Transaction ID with manually setting the time: https://github.com/hashgraph/hedera-sdk-js/blob/master/src/TransactionId.ts#L76
