### ISSUE TITLE
Minimum required Node.js version

### ISSUE THREAD

**Issue by ChALkeR** [hashgraph/hedera-sdk-js#259]
`package.json` has:
https://github.com/hashgraph/hedera-sdk-js/blob/7a72ed9168d86a97be6ac371031582357f07d777/package.json#L47-L49

I'm relatively sure that's not correct, i.e. I doubt that dependencies work on that.
And anyway, is there any value in supporting unmaintained Node.js versions that can have known security issues?

CI seems to use 10.x,12.x,13.x (btw: should be updated to 14.x perhaps?):
https://github.com/hashgraph/hedera-sdk-js/blob/7a72ed9168d86a97be6ac371031582357f07d777/.github/workflows/node.yml#L17-L19

Perhaps the required version in `package.json` should be updated to what is actually being tested?

**Comment by mehcode** [comment]
> I'm relatively sure that's not correct, i.e. I doubt that dependencies work on that.
And anyway, is there any value in supporting unmaintained Node.js versions that can have known security issues?

When we first wrote the SDK, that was the target. You're right though, that it definitely doesn't work now.

**Comment by ChALkeR** [comment]
`gprc-js` has `"node": "^8.13.0 || >=10.10.0"` in `engines` but recommends 12.x.
Refs: #261.

**Comment by ChALkeR** [comment]
Seems to be fixed in `master`? Thanks.
I'll go ahead and close this unless this is needed for some reason.
