### ISSUE TITLE
Cannot get to work in Angular Framework using Webpack for bundling  

### ISSUE THREAD

**Issue by paullobo** [hashgraph/hedera-sdk-js#260]
Node v10.16.3
@hashgraph/sdk  v1.2.1
angular-cli  v9.1

Angular Code
`
import {Mnemonic} from '@hashgraph/sdk';
.
.
const result = Mnemonic.generate();
`

Issue while compiling
`ERROR in ./node_modules/@hashgraph/sdk/lib/crypto/Ed25519PrivateKey.js
Module not found: Error: Can't resolve 'crypto' in '/home/paul/Desktop/Projects/............/node_modules/@hashgraph/sdk/lib/crypto'
ERROR in ./node_modules/@hashgraph/sdk/lib/crypto/util.js
Module not found: Error: Can't resolve 'crypto' in '/home/paul/Desktop/Projects/............/node_modules/@hashgraph/sdk/lib/crypto'
ERROR in ./node_modules/@hashgraph/sdk/lib/crypto/Keystore.js
Module not found: Error: Can't resolve 'crypto' in '/home/paul/Desktop/Projects/Projects/............/node_modules/@hashgraph/sdk/lib/crypto'
ERROR in ./node_modules/cipher-base/index.js
Module not found: Error: Can't resolve 'stream' in '/home/paul/Desktop/Projects/Projects/............/node_modules/cipher-base'`

**Comment by mehcode** [comment]
You need to load the crypto-browserify polyfill. v2 will remove the need for that (and that piece is actually done and on `develop` )
