### ISSUE TITLE
Replacing grpc with grpc-js

### ISSUE THREAD

**Issue by feri42** [hashgraph/hedera-sdk-js#261]
The grpc package has deprecation pending. Can you consider replacing it with https://www.npmjs.com/package/@grpc/grpc-js ?

**Comment by ChALkeR** [comment]
One more thing to note: `grpc` is not just pending deprecation, it's also native module which limits the ability to use this sdk.
For example it has additional problems when used together with Electron.

https://www.npmjs.com/package/@grpc/grpc-js is the new upstream grpc implementation in clean js (actually, TypeScript), which doesn't require native modules and would solve several concerns.

It lives in the same repo as https://www.npmjs.com/package/grpc: https://github.com/grpc/grpc-node/tree/master/packages

[Supported engines](https://github.com/grpc/grpc-node/blob/master/packages/grpc-js/package.json#L9) are: `"node": "^8.13.0 || >=10.10.0"` (related: #259).

**Comment by danielakhterov** [comment]
Master should now be using the new grpc library and support node versions only above 10.0
