### ISSUE TITLE
Certain receipt queries are creating incompatible conversions using toBytes

### ISSUE THREAD

**Issue by kantorcodes** [hashgraph/hedera-sdk-js#2644]
### Description

When creating receipt queries on certain transaction types, for example an AccountCreateTransaction with a threshold key, the toBytes() method is incorrectly generated and causing an error. This particular bug is most obvious in the `hedera-wallet-connect` approach. We've received reports of other transaction types being impacted, but this has been the first I have been able to reproduce easily.

### Steps to reproduce

I've created some code to minimally reproduce this bug. You can run this in `src` - I created `checkUpdate.mjs` to reproduce easily. 

```
import {
    AccountCreateTransaction,
    Transaction,
    KeyList,
    PublicKey,
    Hbar,
    PrivateKey,
    TransactionReceiptQuery,
} from "./exports.js";
import { Client } from "./index.js";

const keys = [
    "74f5c2301727e5e62a212ff239ca9c4d58b318f3afcbe242ea06208c9e50defa",
    "340b42753071dfa75dea0d00b928c9d73301463cd1f9972240cd9dbf4a033a0d",
];

const PK = "Your PK"

const client = Client.forTestnet();

client.setOperator(
    "0.0.12345",
    PK
);

let publicKeys = [];

keys.forEach((key) => {
    publicKeys.push(PublicKey.fromString(key));
});

const thresholdKey = new KeyList(publicKeys, 2);

const transaction = new AccountCreateTransaction()
    .setKey(thresholdKey)
    .setInitialBalance(new Hbar(0))
    .setAccountMemo("test");

const frozenTransaction = transaction.freezeWith(client);
const signedTransaction = await frozenTransaction.sign(
    PrivateKey.fromStringED25519(PK),
);

const tx = await signedTransaction.execute(client);

const recieptQuery = new TransactionReceiptQuery().setTransactionId(tx.transactionId);

const receiptBytes = recieptQuery.toBytes();

console.log("query is", recieptQuery, receiptBytes);

const recieptTransaction = Transaction.fromBytes(receiptBytes)

console.log("receipt: ", recieptTransaction);
```

### Additional context

```
                    throw new Error(
                          ^

Error: (BUG) body.data was not set in the protobuf
    at Transaction.fromBytes (/hedera-sdk-js/src/transaction/Transaction.js:361:27)
    at /hedera-sdk-js/src/checkUpdate.mjs:55:40
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

### Hedera network

mainnet, testnet

### Version

2.53.0

### Operating system

None

**Comment by kantorcodes** [comment]
Note, the following issue in `hedera-wallet-connect` is related: https://github.com/hashgraph/hedera-wallet-connect/issues/337

I suspect this impacts other complex queries e.g. smart contract calls.

**Comment by ivaylonikolov7** [comment]
Hello @kantorcodes,

To utilize toBytes and fromBytes with a Query, please use Query.fromBytes(...) for deserialization and concreteQuery.toBytes() for serialization, where concreteQuery represents any specific query you intend to serialize. This approach allows you to store the serialized query as bytes in a database for later execution.

Please note, however, that this will only serialize the query’s body and will not include the parent transaction body, such as an AccountCreateTransaction in your case. Ensure this aligns with your expectations.

**Comment by kantorcodes** [comment]
> Hello @kantorcodes,
> 
> To utilize toBytes and fromBytes with a Query, please use Query.fromBytes(...) for deserialization and concreteQuery.toBytes() for serialization, where concreteQuery represents any specific query you intend to serialize. This approach allows you to store the serialized query as bytes in a database for later execution.
> 
> Please note, however, that this will only serialize the query’s body and will not include the parent transaction body, such as an AccountCreateTransaction in your case. Ensure this aligns with your expectations.
> 

Thanks, after tinkering we've realized this is likely an implementation issue and we can close this out. Sorry for the false alarm
