### ISSUE TITLE
Global scope pollution and CSP incompatibility

### ISSUE THREAD

**Issue by ChALkeR** [hashgraph/hedera-sdk-js#267]
_Filing as a single issue because there is a clear path forward, equivalent for both issues, see below._

There are two major related problems with the current protobuf usage:

### Currently, this library pollutes global scope

To reproduce:
```console
> Object.keys(global)
[
  'global', 'clearInterval', 'clearTimeout', 'setInterval', 'setTimeout', 'queueMicrotask',
  'clearImmediate', 'setImmediate', 'proto'
]
> Object.keys(global.proto)
[
  'google', 'proto', 'Timestamp', 'TimestampSeconds', 'AccountID',
  'ContractID', 'CurrentAndNextFeeSchedule', 'FeeComponents',
  'FeeData', 'FeeSchedule', 'FileID', 'HederaFunctionality', 'Key',
  ...
```

This is problematic for a number of reasons, including — what if other library or a fork uses the exact same names for their protocols? (`Timestamp`/`ContractID` don't seem specific).

Also, this makes things bad even _without_ any other libraries that do that, because once this gets in a project, it would be very hard to tell in the future if there is a problem or not. The best way to eliminate such conflicts would be to allow _no_ library to pollute global scope.

### Content Security Policy incompatibility

Currently, this library uses the `Function` constructor which allows generate JS code dynamically in runtime, which requires a `unsafe-eval` CSP rule, which basically makes CSP useless, and CSP is a crucial part of web security, i.e. a safeguard against XSS vulnerabilities.

Afaik, this library uses it _just_ to get the `global` variable as `Function('return this')()` for the above case (to pollute globals), hence this is basically the same issue.

### Solution

Protobuf has a `commonjs_strict` mode as opposed to `commonjs`:

```diff
diff --git a/gulpfile.js b/gulpfile.js
index e04a4300..5e79d197 100644
--- a/gulpfile.js
+++ b/gulpfile.js
@@ -43,7 +43,7 @@ gulp.task("build:proto", (cb) => {
     const cmd = "protoc " +
         `--plugin="protoc-gen-ts=${plugin}" ` +
         `--ts_out="service=grpc-web:${out}" ` +
-        `--js_out="import_style=commonjs,binary:${out}" ` +
+        `--js_out="import_style=commonjs_strict,binary:${out}" ` +
         `-I "${include}" ` +
         ` ${files}`;
```

Which brings the following differences in generated code (full diff on a single generated file, no need to apply manually):
```diff
diff -r lib.0/generated/ConsensusCreateTopic_pb.js lib.1/generated/ConsensusCreateTopic_pb.js
13c13
< var global = Function('return this')();
---
> var proto = {};
21c21
< goog.exportSymbol('proto.proto.ConsensusCreateTopicTransactionBody', null, global);
---
> goog.exportSymbol('proto.ConsensusCreateTopicTransactionBody', null, proto);
377c377
< goog.object.extend(exports, proto.proto);
---
> goog.object.extend(exports, proto);
```

### Additional changes

There is a problem though — not sure if intentional or not, but this seems to change the exported variable from `proto.proto` to `proto`.
The solution seems to be either
* To remove `package proto;` in all protocols and additionally fix `MirrorConsensusService.proto` (`s/ .proto//`, note the space).
  This makes unit tests pass in the `commonjs_strict` mode.
* To fix all the imports in js code.

### google/protobuf/wrappers usage

The `google/protobuf/wrappers` in `google-protobuf` is compiled in `commonjs` instead of `commonjs_strict` mode, but it seems easily fixable. I'll open another issue about that. _Upd: #268._

**Comment by ChALkeR** [comment]
I can file a PR to demonstrate the first mentioned approach, if you want me to.

**Comment by kenthejr** [comment]
That would be helpful @ChALkeR

**Comment by mehcode** [comment]
This sounds like a straightforward and good change. :+1: If you'd like to take the time to do the PR, that would be appreciated.

**Comment by ChALkeR** [comment]
#269.

**Comment by mehcode** [comment]
Done in `develop`
