### ISSUE TITLE
Consider removing usage of google/protobuf/wrappers and using an in-repo protocol for that

### ISSUE THREAD

**Issue by ChALkeR** [hashgraph/hedera-sdk-js#268]
Currently, this library uses one proto file not present in the repo itself: `google/protobuf/wrappers`.
That protocol is completely trivial: https://github.com/protocolbuffers/protobuf/blob/master/src/google/protobuf/wrappers.proto

It's used directly as `google-protobuf/google/protobuf/wrappers_pb.js` in a number of places here, but there is a problem with that -- that file has been compiled in `commonjs` mode instead of `commonjs_strict`, which brings the same issues with globals pollution and CSP incompatibility. https://github.com/protocolbuffers/protobuf/issues/7778 is related.

#267 is related, and even after the fixes mentioned in #267, it would be still blocked against this one if `wrappers.proto` is not also recompiled in `commonjs_strict` mode.

A possible solution would be to replace all direct usage of that compiled js file with a proto file inside this repo, compiled in the same mode as all the other proto files. Perhaps even a subset of that file if not all imports are used.

**Comment by mehcode** [comment]
It's a little unfortunate that the google provided library isn't compiled in `strict` mode but I agree a trivial fix is to inline the proto source.

**Comment by mehcode** [comment]
Done in `develop`
