### ISSUE TITLE
Add property to TransactionId which returns the hash of the transaction as sent to the network

### ISSUE THREAD

**Issue by gregscullard** [hashgraph/hedera-sdk-js#275]
Getting the hash of a transaction is the responsibility of a client using the SDK. It would be useful to integrate this capability in the SDK such that the SHA-384 hash of the bytes sent to the network are available as a property of the TransactionId entity returned after the call is executed.

**Comment by mehcode** [comment]
We decided to return a `TransactionResponse` from `execute()` that contains:

 - `nodeId`
 - `transactionId`
 - `transactionHash`

This is breaking so it's in the `develop` branch and will be available as v2
