### ISSUE TITLE
Bad code structure in TransactionRecordQuery/TransactionReceiptQuery

### ISSUE THREAD

**Issue by ChALkeR** [hashgraph/hedera-sdk-js#278]
Consider the following two files:
* https://github.com/hashgraph/hedera-sdk-js/blob/2d6ee9453bda5b582fe05e780e80aa0e7a36feb5/src/TransactionRecordQuery.ts#L70
* https://github.com/hashgraph/hedera-sdk-js/blob/2d6ee9453bda5b582fe05e780e80aa0e7a36feb5/src/TransactionReceiptQuery.ts#L100

The following is true for them:
1. `exports.ts` is the only place where [TransactionReceiptQuery](https://github.com/hashgraph/hedera-sdk-js/search?q=TransactionReceiptQuery) and [TransactionRecordQuery](https://github.com/hashgraph/hedera-sdk-js/search?q=TransactionRecordQuery) are imported.
2. Importing those has a side effect of monkey-patching `TransactionId.prototype.getReceipt` and `TransactionId.prototype.getRecord` on another file.

Merely removing them from `exports.ts` subtly breaks another export, i.e. `TransactionId`.

It should be easy to reorganize that code in a cleaner way.

e.g., `TransactionId` should import those if the object it exports depends on that.

That would likely introduce a circular import, but solving circular imports in this way only makes things worse and code more convoluted and prone to errors.

**Comment by mehcode** [comment]
I really appreciate the code review but note that `master` is only receiving bug fixes at this point with all of our development focus on the `develop` branch and v2.
