### ISSUE TITLE
Update token modifying transaction bodies for autoRenewPeriod, expiry and totalSupply

### ISSUE THREAD

**Issue by SimiHunjan** [hashgraph/hedera-sdk-js#288]
TokenCreateTransactionBody should return a Duration for AutoRenewPeriod, similar to ConsensusCreateTopic
TokenCreateTransactionBody should return a Timestamp for Expiry, similar to ConsensusCreateTopic
TokenMint, TokenBurn and TokenWipe should return the new totalSupply value post applying the transactions

Change dependent on protobuf update to include the above.

Hedera Services issue: https://github.com/hashgraph/hedera-services/issues/645

**Comment by danielakhterov** [comment]
I believe this issue is superseded by https://github.com/hashgraph/hedera-sdk-js/issues/319 The `Duration` and `Timestamp` types have already been updated on master.
