### ISSUE TITLE
(v2) Question: should signWithOperator overwrite prior signatures

### ISSUE THREAD

**Issue by gregscullard** [hashgraph/hedera-sdk-js#291]
Constructing a transaction (TokenCreate) and signing with an extra admin key (.sign) followed by .signWithOperator results in a single signature on the transaction.

Performing the opposite, operator first, then extra signature results in two signatures on the transaction.

Wondering if this is expected outcome or a bug.

**Comment by danielakhterov** [comment]
Can you elaborate your testing because I added a test for this and it seems to always produce 2 signatures if the `adminKey` is different than the operator key. If they were to be the same, then it is expected to have a single signature.

**Comment by gregscullard** [comment]
I don't appear to be able to reproduce this with v2.0.1. Closing.
