### ISSUE TITLE
FileAppendTransaction with large data results in DUPLICATE_TRANSACTION precheck

### ISSUE THREAD

**Issue by gregscullard** [hashgraph/hedera-sdk-js#309]
* SDK Version
2.0.3

* Problem
Trying to create a large file, using `FileAppendTransaction` to automatically append a large amount of data results in DUPLICATE_TRANSACTION precheck error

Tried the `file-append-chunked.js` example to ensure it wasn't my own code at fault and the problem can be reproduced here too.

* What should happen
FileAppendTransaction runs as many `append` transactions as required, ensuring the transaction id is unique for each transaction.

**Comment by danielakhterov** [comment]
I believe this is fixed on master right now, and will be released soon. We have a test on master for this which passes https://github.com/hashgraph/hedera-sdk-js/blob/master/test/integration/FileAppendIntegrationTest.js#L80
