### ISSUE TITLE
PublicKey length check error

### ISSUE THREAD

**Issue by cmdhema** [hashgraph/hedera-sdk-js#313]
sdk version: 2.0.9
node version: 12.14.0

`const pubKey = '302a300506032b6570032100e1a2f71c87c269d43f5790f4d01f62cd501373d99244334d10146faf5792c921';
    console.log(PublicKey.fromString(pubKey));`

Error log is
'(node:76979) UnhandledPromiseRejectionWarning: BadKeyError: invalid public key length: 44 bytes
    at Function.fromBytes (/Users/kjwook/Desktop/hello-hedera-js-sdk/node_modules/@hashgraph/cryptography/lib/PublicKey.cjs:68:11)
    at Function.fromString (/Users/kjwook/Desktop/hello-hedera-js-sdk/node_modules/@hashgraph/cryptography/lib/PublicKey.cjs:82:22)
    at main (/Users/kjwook/Desktop/hello-hedera-js-sdk/generate-mnemonic-key.js:21:27)'

When I check the 'Private.fromString' source code.
(/@hashgraph/cryptography/lib/PublicKey.cjs)

`

static fromBytes(data) {

    switch (data.length) {

      case 32:

        return new PublicKey(data);

      case 48:

        // eslint-disable-next-line @typescript-eslint/no-unsafe-call

        if ((0, _array.arrayStartsWith)(data, derPrefixBytes)) {

          return new PublicKey(data.subarray(12));

        }

        break;

      default:

    }

    throw new _BadKeyError.default(`invalid public key length: ${data.length} bytes`);

  }`
 

I think that String PublicKey is 44 bytes and PrivateKey is 48 bytes.

Isn't it correct to change case 48 to case 44?
When I change the code on my local environment. PublicKey.fromString('String PublicKey') working well.

**Comment by danielakhterov** [comment]
Where do you get your public key from?

**Comment by cmdhema** [comment]
@danielakhterov 

`

const {
    PrivateKey,
} = require("@hashgraph/sdk");
user1Key = await PrivateKey.generate();
console.log(`private key for user 1= ${user1Key}`);
console.log(`public key for user 1= ${user1Key.publicKey}`);
`

I get the codes.

**Comment by danielakhterov** [comment]
You're right, I can't believe we haven't found that bug in so long. I've since changed the case to be `44` from `48` and updated master. This should be fixed in the next release.

**Comment by prasannavenkatesh-colan** [comment]
node_modules/@hashgraph/cryptography/lib/PrivateKey.cjs:172
    throw new _BadKeyError.default(`invalid private key length: ${data.length} bytes`);
          ^

BadKeyError: invalid private key length: 47 bytes

**Comment by danielakhterov** [comment]
Not sure what to say, the error you're getting seems to be correct? 47 bytes is not a valid key length.
