### ISSUE TITLE
Cannot find namespace 'proto'.

### ISSUE THREAD

**Issue by benjiebob** [hashgraph/hedera-sdk-js#314]
I'm a bit new to npm so please be gentle if this turns out to be my fault!

I'm developing an Angular typescript app, and have run the install as suggested

```
npm install --save @hashgraph/sdk 
```

Unfortunately I receive the following error messages:

```
Error: node_modules/@hashgraph/sdk/lib/query/CostQuery.d.ts:24:14 - error TS2503: Cannot find namespace 'proto'.

24     _header: proto.IQueryHeader | null;
                ~~~~~
node_modules/@hashgraph/sdk/lib/topic/TopicId.d.ts:23:30 - error TS2503: Cannot find namespace 'proto'.

23     static _fromProtobuf(id: proto.ITopicID): TopicId;
```

I'd be grateful for any advice

**Comment by danielakhterov** [comment]
What version of Angular.js and @hashgraph/sdk are you running?

**Comment by danielakhterov** [comment]
Stale issue; closing.
