### ISSUE TITLE
Error: invalid private key: <pkey>

### ISSUE THREAD

**Issue by ilyakmet** [hashgraph/hedera-sdk-js#32]
When I use string type pkey:

```js
import {Client} from "@hashgraph/sdk";

const client = new Client({ 
    // this key defaults to this url, a public free proxy to the Hedera public testnet
    // generously hosted by MyHederaWallet.com
    url: "https://grpc-web.myhederawallet.com",
    operator: {
        // the account which signs transactions and query payments by default
        account: { shard: 0, realm: 0, account: ___ },
        // the private key used to sign the transactions, either encoded as a string
        // or as an `Ed25519PrivateKey` type 
        privateKey: "..."
    },
});
```

Error:
```bash
Error: invalid private key: <pkey>
```

How I can convert string type pkey to Ed25519 type ?

```js
/** If `privateKey` is a string it will be parsed as an `Ed25519PrivateKey` */
export type PrivateKey = { privateKey: Ed25519PrivateKey | string };
export type PubKeyAndSigner = {
    publicKey: Ed25519PublicKey;
    signer: Signer;
};
```

**Comment by mehcode** [comment]
```Ed25519PrivateKey.fromString("30....")```

should work

**Comment by abonander** [comment]
@ilyakmet your private key string must be one of the following character lengths, which is how the SDK infers its encoding type:

* 64: raw private key, 32 hexadecimal encoded bytes
* 128: 32 raw private key bytes + 32 public key bytes, hexadecimal encoding
* 96: DER encoded structure of private key as hexadecimal bytes

It's possible that your private key string is actually a hex(DER) encoded structure containing both a private key and a public key. Can you measure and report its length and where you got it from?

**Comment by 5atoshin** [comment]
Invalid private key encoding (code -5)
