### ISSUE TITLE
GetAccountBalance result - JSON Stringify doesn't include tokens

### ISSUE THREAD

**Issue by gregscullard** [hashgraph/hedera-sdk-js#323]
Getting account balance for an account associated with tokens, printing `JSON.Stringify(accountBalance)` outputs much of the information except tokens which aren't displayed.

Is the serialisation missing the tokens ?

**Comment by danielakhterov** [comment]
I believe this is because in JS the `Map` type doesn't properly serialize using `JSON.stringify()`. We should instead add a proper `AccountBalance.toString()` implementation.

**Comment by mehcode** [comment]
We should probably also add a `toJSON` (which `JSON.stringify` uses) to the custom object Map types.

**Comment by danielakhterov** [comment]
This is now implemented on `master` https://github.com/hashgraph/hedera-sdk-js/blob/0e4934525d90d580b8fb4ed2eccf392f0428f04a/src/account/AccountBalance.js#L97 and will be part of the next release.
