### ISSUE TITLE
Mirror Listener abruptly shuts down without any error if JSON parse/stringify is used on the message. Hashgraph SDK v2.0.14

### ISSUE THREAD

**Issue by itsdheerajbudhiraja** [hashgraph/hedera-sdk-js#324]
![image](https://user-images.githubusercontent.com/52557912/105454491-f7b41480-5ca7-11eb-94c5-883d58ac184a.png)

**Comment by danielakhterov** [comment]
The mirror shutting down does sound like an issue, but I think what you meant to write is
```js
console.log(JSON.parse(new TextEncoder("utf-8").decode(message.contents));`
```

**Comment by danielakhterov** [comment]
Can you confirm this is still an issue for you. Currently in our code we have ```                    try {
                        listener(topicMessage);
                    } catch (error) {
                        errorHandler(topicMessage, error);
                    }
``` which will catch all errors thrown by the callback supplied to `subscribe` and pass the error to the provided error handler. The `TopicMessageQuery` should not be shutting down, and I cannot seem to reproduce this.
