### ISSUE TITLE
[Question] how to transfer hbar for a HTS token?

### ISSUE THREAD

**Issue by Cooper-Kunz** [hashgraph/hedera-sdk-js#331]
Is there any way I can get an example of an HBAR to token atomic swap?

**Comment by gregscullard** [comment]
@Cooper-Kunz the HTS demo does that. Are you looking for a more "concise" example ?

**Comment by gregscullard** [comment]
rough outline

```
const tx = await new TransferTransaction();
tx.addTokenTransfer(token1, fromAccount, -tokenQuantity);
tx.addTokenTransfer(token1, toAccount, tokenQuantity);

tx.addHbarTransfer(fromAccount, new Hbar(hBars));
tx.addHbarTransfer(toAccount, new Hbar(-hBars));

tx.freezeWith(client);

await tx.sign(fromAccountKey);
await tx.sign(toAccountKey);

const result = await tx.execute(client);
const transactionReceipt = await result.getReceipt(client);

....
```

**Comment by gregscullard** [comment]
The example signs with both keys (one to pay tokens, the other to pay hbar). If the token was sent with hbar from the same account, only that account needs to sign.

**Comment by mul1sh** [comment]
> rough outline
> 
> ```
> const tx = await new TransferTransaction();
> tx.addTokenTransfer(token1, fromAccount, -tokenQuantity);
> tx.addTokenTransfer(token1, toAccount, tokenQuantity);
> 
> tx.addHbarTransfer(fromAccount, new Hbar(hBars));
> tx.addHbarTransfer(toAccount, new Hbar(-hBars));
> 
> tx.freezeWith(client);
> 
> await tx.sign(fromAccountKey);
> await tx.sign(toAccountKey);
> 
> const result = await tx.execute(client);
> const transactionReceipt = await result.getReceipt(client);
> 
> ....
> ```

@gregscullard so how does one know how many tokens to swap for hbars i.e. if I swap 2 tokens for 100hbars, what make these 2 tokens be worth 100 hbars?

**Comment by gregscullard** [comment]
There is no such function, it would be by agreement between the two parties, the same way it works on a centralised exchange except that on an exchange you transfer tokens to the exchange and state how much you want for them, someone comes along and accepts your price, the exchange transfers the tokens to them and credits you with the proceeds.

**Comment by mul1sh** [comment]
Ahh ok. So then I would need an order book of sorts before the swap showing the buy & sell prices of a token by other traders correct?

**Comment by gregscullard** [comment]
That's right.

**Comment by gregscullard** [comment]
Unless you have another use case where the trading value of the token is fixed and those trading would have no interest in selling above or below that price.

**Comment by gregscullard** [comment]
Note: The HTS demo sort of does this (order book) through a marketplace account (escrow / exchange).

**Comment by mul1sh** [comment]
Awesome thanks for explain

> Unless you have another use case where the trading value of the token is fixed and those trading would have no interest in selling above or below that price.

Awesome thanks for the swift reply, this will really help in my project. I appreciate the help 😃

**Comment by danielakhterov** [comment]
After reading this discussion it seems the issue has been resolved, so closing. Re-open if I'm misunderstanding or you're having further trouble.
