### ISSUE TITLE
[BUG] when throwing MaxQueryPaymentExceeded

### ISSUE THREAD

**Issue by kwkr** [hashgraph/hedera-sdk-js#334]
https://github.com/hashgraph/hedera-sdk-js/blob/330bb78e0cad7871cfb285aa00259d5a12c89830/src/query/Query.js#L218-L219

The lines above seem to be off. As the `cost` variable seems to represent the max cost and the `actualCost` the cost of the transaction, the direction of the operator is wrong which results in an error being thrown although it shouldn't.  Also the error's constructor arguments are in the wrong order which results in errors like this one `MaxQueryPaymentExceededError: query cost of 2 tℏ HBAR exceeds max set on client: 10 tℏ HBAR`.

**Comment by danielakhterov** [comment]
Thank you, and you're completely right @kwkr. We've fixed this since you posted the issue. https://github.com/hashgraph/hedera-sdk-js/blob/17f9864dc986f46f3316ed44c94892e3f375fb1e/src/query/Query.js#L222 The other mistake we had was comparing `Long` instead of `int`
