### ISSUE TITLE
NPM install should install the latest version not latest published.

### ISSUE THREAD

**Issue by SimiHunjan** [hashgraph/hedera-sdk-js#336]
https://www.npmjs.com/package/@hashgraph/sdk 

Current tag is v1.4.6

**Comment by danielakhterov** [comment]
Thank you for the issue. Unfortunately NPM doesn't allow us to chose to always keep any v2 as the latest version. So, instead all new v1 releases will be tagged with `@v1` to prevent this from happening again. https://www.npmjs.com/package/@hashgraph/sdk
