### ISSUE TITLE
TransactionId.toString incorrectly handles seconds

### ISSUE THREAD

**Issue by xin-hedera** [hashgraph/hedera-sdk-js#339]
`Transaction.toString` converts `validStart.seconds` to `Int`, so any value >= 2^32 will not show up properly.

https://github.com/hashgraph/hedera-sdk-js/blob/3c51bad20c1a10f028bcb2febde007d2fb7a7c16/src/transaction/TransactionId.js#L72

**Comment by danielakhterov** [comment]
Thanks for bringing this up. I believe we have fixed this issue: https://github.com/hashgraph/hedera-sdk-js/blob/1c02e00bc486a5fc6a4fcd44fbac5822565ad91f/src/transaction/TransactionId.js#L125
