### ISSUE TITLE
SDK v1.4.6 memo length

### ISSUE THREAD

**Issue by failfmi** [hashgraph/hedera-sdk-js#341]
Hello, I am trying to submit a CryptoTransfer using `MyHbarWallet` locally with a memo, which is almost close to 100 symbols. Unfortunately, when I submit the transfer an error appears, stating `memo may not be longer than 100 bytes`.
I saw there is a check in `TransactionBuilder.js` restricting this.
![image](https://user-images.githubusercontent.com/20928965/111748643-73da6b00-8899-11eb-8bc1-3d08bc1086e2.png)
Commenting this check allows successful submission.

**Comment by ivancsicsmarkus** [comment]
Based on the referenced code, the memo can not be longer than 50 characters.

**Comment by danielakhterov** [comment]
Yea, @ivancsicsmarkus is correct; since each character is 2 bytes the max length of a valid memo field in characters is 50.

**Comment by failfmi** [comment]
Is this check found in `>= v2.0.0`

**Comment by mehcode** [comment]
In v2 we re-encode a string memo in UTF-8 which alleviates the mentioned issue. You should be able to use 100 ASCII characters (or those with a single byte encoding in UTF-8).
