### ISSUE TITLE
Missing ScheduleID protobuf being used by hashgraph sdk

### ISSUE THREAD

**Issue by zbarbuto** [hashgraph/hedera-sdk-js#342]
`schedule.js` references `proto.ScheduleID`:

https://github.com/hashgraph/hedera-sdk-js/blob/master/src/schedule/ScheduleId.js#L57

The typings list this as being exported:

https://github.com/hashgraph/hedera-sdk-js/blob/master/packages/proto/src/index.d.ts#L57

However the actual package does not export ScheduleID

https://github.com/hashgraph/hedera-sdk-js/blob/master/packages/proto/src/index.js

This leads to build errors in webpack based applications as the import can not be found:

![image](https://user-images.githubusercontent.com/9100419/112400672-c49a0a00-8d58-11eb-9919-2ec7d3329160.png)

**Comment by andrix10** [comment]
Thanks for bringing this up, will be fixed very soon.

**Comment by danielakhterov** [comment]
Can confirm that this is now fixed on `master`; also released new `@hashgraph/proto` version v1.0.23 which contains this fix.
