### ISSUE TITLE
`keyListToProtobuf()` does not handle `KeyList` with a threshold

### ISSUE THREAD

**Issue by danielakhterov** [hashgraph/hedera-sdk-js#348]

**Comment by derdis14** [comment]
Would you assign me this issue? I would be happy to fix it!

**Comment by danielakhterov** [comment]
Heh, I should of closed this issue because I fixed it soon after I made this issue: https://github.com/hashgraph/hedera-sdk-js/commit/8314a8371835cbee14135d30ba0ab5bd7958dbff

However, there are other issues that can be worked on; if you'd like to take some issue please let me know and I will assign it to you.
