### ISSUE TITLE
Support for token memo missing in 2.0.19

### ISSUE THREAD

**Issue by gregscullard** [hashgraph/hedera-sdk-js#356]
It is not possible to set a memo on a new token, the protobufs support memos on tokens.

`TokenGetInfo` doesn't have a memo property

As per `TokenCreateTransaction`, `TokenUpdateTransaction` shows a setter for tokenMemo which is not available.

**Comment by danielakhterov** [comment]
@gregscullard can you elaborate?
Look at the `master` branch I can we have the following methods/fields.
`TokenInfo.tokenMemo`
`TokenCreateTransaction.setTokenMemo()`
`TokenCreateTransaction.tokenMemo`
`TokenUpdateTransaction.setTokenMemo()`
`TokenUpdateTransaction.tokenMemo`

**Comment by mehcode** [comment]
I can confirm this is supported: https://github.com/hashgraph/hedera-sdk-js/blob/master/src/token/TokenCreateTransaction.js#L561
