### ISSUE TITLE
Deprecate v1 Client

### ISSUE THREAD

**Issue by danielakhterov** [hashgraph/hedera-sdk-js#370]

**Comment by SimiHunjan** [comment]
I think for this one you can actually deprecate the entire package: https://docs.npmjs.com/deprecating-and-undeprecating-packages-or-package-versions

**Comment by danielakhterov** [comment]
Released and deprecated v1.4.9 https://github.com/hashgraph/hedera-sdk-js/releases/tag/v1.4.9%40v1 Tested example and I am now seeing ```warning @hashgraph/sdk@1.4.9: Please upgrade to version 2 of the SDK
``` when trying to use that version.
