### ISSUE TITLE
Latest @hashgraph/proto causes UnhandledPromiseRejection

### ISSUE THREAD

**Issue by rocketmay** [hashgraph/hedera-sdk-js#374]
The latest update to @hashgraph/proto from 1.0.25 to 1.1.0 causes the SDK to throw an error when trying to execute a query/transaction.

Deleting node_modules and updating package.lock to use version 1.0.25, then running "npm ci" fixes the issue.

I'm not sure what the issue is, but on fresh installs the update to 1.1.0 currently makes the SDK unusable.

Error:

(node:36840) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'encode' of undefined
    at _makePaymentTransaction (E:\PROJECTS\GITHUB\CRYPTO\hashgraph-bootstrap\node_modules\@hashgraph\sdk\lib\query\Query.cjs:420:54)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async AccountBalanceQuery._beforeExecute (E:\PROJECTS\GITHUB\CRYPTO\hashgraph-bootstrap\node_modules\@hashgraph\s    at async AccountBalanceQuery.execute (E:\PROJECTS\GITHUB\CRYPTO\hashgraph-bootstrap\node_modules\@hashgraph\sdk\lib\Executable.cjs:217:5)
    at async main (E:\PROJECTS\GITHUB\CRYPTO\hashgraph-bootstrap\main.js:42:23)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:36840) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:36840) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by danielakhterov** [comment]
I'm speechless, how was this not caught earlier? I've forgotten that we released 1.1.0 6 months ago, so all new releases were under the 1.0.X release. Either way, we'll release 1.1.1 to fix this issue.

**Comment by danielakhterov** [comment]
I've released `@hashgraph/proto` v1.1.2 and tried using the latest SDK version within examples and it seems to work now. Can you confirm this resolves your issue @rocketmay

**Comment by rocketmay** [comment]
Beautiful. The bug appears to be fixed!

Thank you.
