### ISSUE TITLE
String to entity conversion inconsistencies

### ISSUE THREAD

**Issue by gakz** [hashgraph/hedera-sdk-js#397]
Using v 2.03 of the SDK I experienced inconsistent handling of entities by the SDK. 

For instance, when importing an account ID from a `.env` file: 

`const myAccountId = process.env.MY_ACCOUNT_ID`

And then using `myAccountId` to configure the client:

`client.setOperator(myAccountId, myPrivateKey);`

`setOperator` seems to convert the string to an Account ID entity. 

However, when performing other calls, specifically `TopicMessageSubmitTransaction()` the SDK manages it differently; producing a type error when passing a string into the following: 

`const myTopicId = process.env.MY_TOPIC_ID`

```
const MessageSubmit = await new TopicMessageSubmitTransaction({
      topicId: myTopicId,
      message: "Hello there!",
    }).execute(client);
  }
```

This produces a type error while I anticipated the string to entity conversion being consistent across all SDK calls.

**Comment by danielakhterov** [comment]
Thanks for pointing this out, what you have should definitely work; we'll fix this with the next release.

**Comment by danielakhterov** [comment]
#400 was very close to being merged and released with https://github.com/hashgraph/hedera-sdk-js/milestone/2 However, there were some mirror issues within the PR which prevented it from being merged. Moving this issue to milestone https://github.com/hashgraph/hedera-sdk-js/milestone/3
