### ISSUE TITLE
Implement PEM encoding and decoding

### ISSUE THREAD

**Issue by abonander** [hashgraph/hedera-sdk-js#4]
Another feature recently implemented in the Java SDK: https://github.com/hashgraph/hedera-sdk-java/pull/209

**Comment by mehcode** [comment]
@danielakhterov PEM encoding is 

```
LINE OF TEXT HERE
BASE 64 DATA OF KEY
LINE OF TEXT HERE
```

1) Split by line
2) Grab `[1]` line
3) Optionally decrypt
4) Base64-decode
5) Pass to other methods

**Comment by abonander** [comment]
Closed by #204
