### ISSUE TITLE
Add more extensive tests for key derivations between all SDKs

### ISSUE THREAD

**Issue by danielakhterov** [hashgraph/hedera-sdk-js#425]
https://github.com/hashgraph/hedera-sdk-js/issues/417#issuecomment-868840497

**Comment by robkainz** [comment]
@danielakhterov As you probably saw from my comment on the closed defect (which needs to be reopened), the fix you suggested didn't work for me in a React Native environment - honestly not sure if it works in pure javascript. I'm mentioning it here in hopes it will be addressed sooner than later, as it's one of two main issues blocking me on getting token service support in Wallawallet. I tested this on versions 2.0.22 and 2.0.23 and they are both broken (likely previous versions as well.)

I modified my function to use the index -1 as you suggested, but I am still not getting the correct public key for this mnemonic phrase with either index 0 or -1.

```
export async function mnemonicToPublicKey(mnemonic, passphrase = "") {
    const m:Mnemonic = await Mnemonic.fromString(mnemonic);
    const pk:PrivateKey = await m.toPrivateKey(passphrase);
    const schemePk:PrivateKey = await pk.derive(-1);
    const rawPublicKey:string = Buffer.from(schemePk.publicKey.toBytes()).toString('hex');
    console.log('rawPublicKey: ', rawPublicKey)
    return rawPublicKey;
}

```

Here is the output I got for -1 index:

> [Mon Jun 28 2021 07:55:06.311] LOG rawPublicKey: 6ab342c5ef89b275477d99c56554076d1eb293605fb65b2b3d11fed02d48f047

The expected value for derive(0) is:

> f3aec5b29a666a80c42652bc8528e2e831ba54fa0053aa39e4d9bd242ef281fc

for the mnemonic:

> tray trust alert balance rubber seat own use critic protect crucial license

Please note that this expected value for derive(0) works as expected on the golang SDK (and most likely the Java SDK as well.)

**Comment by mehcode** [comment]
I'm running this script from a modified example file on master.

```js
    const m = await Mnemonic.fromString("tray trust alert balance rubber seat own use critic protect crucial license");
    const root = await m.toPrivateKey("");
    const pk0 = await root.derive(0);

    console.log(pk0.publicKey.toString().slice(24));
```

```
> f3aec5b29a666a80c42652bc8528e2e831ba54fa0053aa39e4d9bd242ef281fc
```

**Comment by mehcode** [comment]
I now tried running your script (nearly) verbatim.

```js
const { Mnemonic } = require("@hashgraph/sdk");

async function mnemonicToPublicKey(mnemonic, passphrase = "") {
    const m = await Mnemonic.fromString(mnemonic);
    const pk = await m.toPrivateKey(passphrase);
    const schemePk = await pk.derive(0);
    const rawPublicKey = Buffer.from(schemePk.publicKey.toBytes()).toString('hex');
    console.log('rawPublicKey: ', rawPublicKey)
    return rawPublicKey;
}

void mnemonicToPublicKey("tray trust alert balance rubber seat own use critic protect crucial license");
```

For derive index of `0`:

```
rawPublicKey:  f3aec5b29a666a80c42652bc8528e2e831ba54fa0053aa39e4d9bd242ef281fc
```

For derive index of `-1`:

```
rawPublicKey:  e1c10f40cdd95525d65d007fe5a2002ef263808838b45712d16c4e50cba6e25b
```

**Comment by mehcode** [comment]
If you get the incorrect behavior you're describing from, this seems to indicate that whatever cryptocurrency primitives are implemented differently in React Native there is a variation large enough to change the resultant key.

**Comment by mehcode** [comment]
@robkainz To help narrow this down for me.. Can you log the hex of the private keys for root, #0, and #-1?

```js
const { Mnemonic } = require("@hashgraph/sdk");

async function mnemonicToPublicKey(mnemonic, passphrase = "") {
    const m = await Mnemonic.fromString(mnemonic);
    const root = await m.toPrivateKey(passphrase);
    const pk0 = await root.derive(0);
    const pkN1 = await root.derive(-1);

    console.log("root secret:", Buffer.from(root.toBytes()).toString("hex"));
    console.log("root public:", Buffer.from(root.publicKey.toBytes()).toString("hex"));
    console.log("derive < 0> secret:", Buffer.from(pk0.toBytes()).toString("hex"));
    console.log("derive < 0> public:", Buffer.from(pk0.publicKey.toBytes()).toString("hex"));
    console.log("derive <-1> secret:", Buffer.from(pkN1.toBytes()).toString("hex"));
    console.log("derive <-1> public:", Buffer.from(pkN1.publicKey.toBytes()).toString("hex"));
}

void mnemonicToPublicKey("tray trust alert balance rubber seat own use critic protect crucial license");
```

My output is:

```
root secret: cae63bff6013a072a9b9c26f0c4184a3aaed600fd6434b4ced0621d3add4eafa
root public: 9839434ae9e88eedb24083757c9e4b25b7baea22300df51d0ab0d3ec2e3678fb
derive < 0> secret: b2bcda6691d2c9cdf0a0405b442d7174f8c4ab331f40f2ea3e640b2c5722c3a1
derive < 0> public: f3aec5b29a666a80c42652bc8528e2e831ba54fa0053aa39e4d9bd242ef281fc
derive <-1> secret: b5300af68795dd162567e38c2d81b38d13c30ef381fcc1bf63d2a8facfbc0ba2
derive <-1> public: e1c10f40cdd95525d65d007fe5a2002ef263808838b45712d16c4e50cba6e25b
```

I'm running this in nodejs v16.4.0 on Linux on the master branch. However, I did switch all the crypto implementations to point to the RN-specific ones instead of the node ones. They are pure JS rather than relying on node primitives so they work in node as well. It doesn't change the results.

**Comment by robkainz** [comment]
@mehcode Thanks Ryan for helping out.

Below is the output you have asked for, using my React Native environment (which, as I pointed out before, did work using the Ed25519PrivateKey/Ed25519PublicKey classes - V1 API in version 2.0.22, which was not completely suppressed, but is now in 2.0.23). 

> [Mon Jun 28 2021 16:18:11.730]  LOG      root secret: 22ab6adf40e2a854b9334c6481cf738e1dc27cf7775f70fefd4664f96ed59a02
> [Mon Jun 28 2021 16:18:11.735]  LOG      root public: 6e6e2db2833cc77afe17c533517a188fbd626eb55bc0769fb2660415a880d0a4
> [Mon Jun 28 2021 16:18:11.735]  LOG      derive < 0> secret: 9e45e5767c605b10b5af2b7e3fab36124744eb94d733a85b941e41a47c3ccd66
> [Mon Jun 28 2021 16:18:11.736]  LOG      derive < 0> public: 63f8ca3239d20b93e2c3ad212e966736636654d63ce136a4219f2a7016008104
> [Mon Jun 28 2021 16:18:11.736]  LOG      derive <-1> secret: aaae15316701d46798857de7c3087ecb19ef0c1f3395efbb7dea109f1b581ba7
> [Mon Jun 28 2021 16:18:11.736]  LOG      derive <-1> public: 6ab342c5ef89b275477d99c56554076d1eb293605fb65b2b3d11fed02d48f047

**Comment by mehcode** [comment]
That concerns me a bit. I flat guarantee that `Ed25519PublicKey` never worked, ever in the v2 sdk. This makes me think there is something going on with your environment. 

---

As another data point, I ran (a slightly modified version) of that script with the v1 SDK and it produced the same output (node, linux, etc.).

---

I'll see what I can do to test this in React Native today. I'm very curious what's going on. As it seems its not (just) the derive that's failing for you, but even something as simple as `toPrivateKey`.

**Comment by robkainz** [comment]
To get the Ed25519PrivateKey classes to work on v2.0.22 (and earlier) all I had to do was add this import:

import {Ed25519PrivateKey} from "@hashgraph/sdk/lib/crypto/Ed25519PrivateKey";

I'm working right now on getting the JS SDK examples/react-native example running with my code to see if it works or fails in the same way, will post the result.

**Comment by robkainz** [comment]
Confirmed that it still fails in the JS SDKs examples/react-native example code. Same results:

```
[Mon Jun 28 2021 17:02:31.760]  LOG      Running "main" with {"rootTag":11,"initialProps":{}}
[Mon Jun 28 2021 17:02:31.770]  LOG      root secret: 22ab6adf40e2a854b9334c6481cf738e1dc27cf7775f70fefd4664f96ed59a02
[Mon Jun 28 2021 17:02:31.770]  LOG      root public: 6e6e2db2833cc77afe17c533517a188fbd626eb55bc0769fb2660415a880d0a4
[Mon Jun 28 2021 17:02:31.780]  LOG      derive < 0> secret: 9e45e5767c605b10b5af2b7e3fab36124744eb94d733a85b941e41a47c3ccd66
[Mon Jun 28 2021 17:02:31.780]  LOG      derive < 0> public: 63f8ca3239d20b93e2c3ad212e966736636654d63ce136a4219f2a7016008104
[Mon Jun 28 2021 17:02:31.780]  LOG      derive <-1> secret: aaae15316701d46798857de7c3087ecb19ef0c1f3395efbb7dea109f1b581ba7
[Mon Jun 28 2021 17:02:31.790]  LOG      derive <-1> public: 6ab342c5ef89b275477d99c56554076d1eb293605fb65b2b3d11fed02d48f047
```

If you want to run the react-native example, just do the following:

Modify App.js to include call to the code you gave me to run.

```
import {Buffer} from 'buffer';  //add this import
...

//put this BEFORE "export default class App extends React.Component {"

const mnemonicToPublicKey = async (mnemonic, passphrase = "") => {
    const m = await Mnemonic.fromString(mnemonic);
    const root = await m.toPrivateKey(passphrase);
    const pk0 = await root.derive(0);
    const pkN1 = await root.derive(-1);

    console.log("root secret:", Buffer.from(root.toBytes()).toString("hex"));
    console.log("root public:", Buffer.from(root.publicKey.toBytes()).toString("hex"));
    console.log("derive < 0> secret:", Buffer.from(pk0.toBytes()).toString("hex"));
    console.log("derive < 0> public:", Buffer.from(pk0.publicKey.toBytes()).toString("hex"));
    console.log("derive <-1> secret:", Buffer.from(pkN1.toBytes()).toString("hex"));
    console.log("derive <-1> public:", Buffer.from(pkN1.publicKey.toBytes()).toString("hex"));
};

//Add call to mnemonicToPublicKey at start of componentDidMount():
    componentDidMount() {
        mnemonicToPublicKey("tray trust alert balance rubber seat own use critic protect crucial license");
   ...
```

Do the following to run it in a terminal:

```
cd examples/react-native
# Add dependency to package.json: "buffer": "~5.5.0",
yarn install
cd ios
pod install
cd ..
yarn ios  

```

**Comment by robkainz** [comment]
As to guaranteeing that Ed25519PublicKey never worked, if you really need me to prove that it did, all I need to do is pull Hedera JS SDK version 2.0.22 and follow the same steps above, except use this import:

`import {Ed25519PrivateKey} from "@hashgraph/sdk/lib/crypto/Ed25519PrivateKey";
`

and this method:

```
export async function mnemonicToPublicKey(mnemonic:string, passphrase = "") {
    const m:any = await Mnemonic.fromString(mnemonic);
    let pk:Ed25519PrivateKey = await Ed25519PrivateKey.fromMnemonic(m, passphrase);
    pk = await pk.derive2(0);
    const rawPublicKey:string = Buffer.from(schemePk.publicKey.toBytes()).toString('hex');
    return rawPublicKey;
}
```

Let me know if you want me to do that. It certainly worked for the JS SDK in the WW app, but I am quite certain it will also work in Daniel's react-native example.

**Comment by mehcode** [comment]
> Let me know if you want me to do that. It certainly worked for the JS SDK in the WW app, but I am quite certain it will also work in Daniel's react-native example.

So I now understand why this worked. Basically we had a release process that released v1, switched branches, then released v2. So v1 files were included in v2. That class has never been in v2 which was my confusion. As of the most recent release cycle, we've stopped the v1 releases (for the most part), which is why this didn't happen again.

**Comment by mehcode** [comment]
Happy to report this is fully fixed now. 🎉 The root issue was an erroneous implementation of UTF8 encoding on React Native in the `@hashgraph/cryptography` package. A `yarn upgrade` should fix it locally as this doesn't require an SDK update, just a patch update to `@hashgraph/cryptography`.
