### ISSUE TITLE
1.4.10-beta.1 missing methods

### ISSUE THREAD

**Issue by SimiHunjan** [hashgraph/hedera-sdk-js#453]
### Description

I was verifying the methods for creating fixed fees and fractional fees and it does not seem to provide the `.set...` methods as an option like the other SDKs. Please confirm

### Steps to reproduce

Try to build a custom fractional fee or fixed fee object.

### Additional context

![Screen Shot 2021-07-19 at 11 20 34 PM](https://user-images.githubusercontent.com/21989138/126271491-63f780c5-e496-4cf1-a467-9e49909cb349.png)

![Screen Shot 2021-07-19 at 11 20 19 PM](https://user-images.githubusercontent.com/21989138/126271460-42fe6c69-48e9-4d8b-b1c2-6c0c45969e28.png)

### Hedera network

other

### Version

1.4.10-beta.1

### Operating system

macOS

**Comment by danielakhterov** [comment]
Fixed: https://github.com/hashgraph/hedera-sdk-js/commit/a83f230d11b870eb00eb5b697af1dc95e0ce8335
