### ISSUE TITLE
Missing fee schedule key v1.4.10-beta.1

### ISSUE THREAD

**Issue by SimiHunjan** [hashgraph/hedera-sdk-js#459]
### Description

Missing ability to set fee schedule key during the creation of a token

Missing integration tests to validate this

https://github.com/hashgraph/hedera-sdk-js/blob/v1.4.10-beta.1/src/token/TokenCreateTransaction.ts

### Steps to reproduce

Try to create a token with a fee schedule key

### Hedera network

previewnet

### Version

1.4.10-beta.1

### Operating system

macOS

**Comment by danielakhterov** [comment]
Fixed: https://github.com/hashgraph/hedera-sdk-js/commit/6121683b072dd6754ad872e65374e16ce127c9e6
