### ISSUE TITLE
Missing addCustomFee()

### ISSUE THREAD

**Issue by SimiHunjan** [hashgraph/hedera-sdk-js#460]
### Description

Java SDK allows you to set a list of custom fees (`setCustomFees()`) or add individual fees (`addCustomFee()`) when creating a token with a fee schedule or updating a token fee schedule. v1.4.10- beta does not have the option to use `addCustomFee()` to add a single fee.

### Steps to reproduce

Try to `.addCustomFee()` when creating a token with a custom fee for version v1.4.10-beta.

### Hedera network

previewnet

### Version

v1.4.10- beta

### Operating system

macOS

**Comment by danielakhterov** [comment]
Closing since we determined it's best to not have `addCustomFee()` in the first place.

**Comment by SimiHunjan** [comment]
Thank you!
