### ISSUE TITLE
Add CI to run against the latest stable version of `master` for Hedera Services

### ISSUE THREAD

**Issue by danielakhterov** [hashgraph/hedera-sdk-js#470]
### Problem

Currently for any PR we have CI that runs only against `testnet`, but it would be useful to run it against the latest stable version of Hedera Services as well. This would allow us to have tests which use the genesis account and hence allows us to test transactions such as `System[Delete|Undelete]Transaction`. 

### Solution

Create a CI workflow which is run against the latest stable version of `master` on any PR

**Comment by yagop** [comment]
Can you please fix `CI against Hedera Services master branch` ?

Tests are failing on every run
https://github.com/hashgraph/hedera-sdk-js/runs/3326659286?check_suite_focus=true#step:10:1782

I want to test against a localnet but the client fails for the same reason
