### ISSUE TITLE
Implement `*[Query|Transaction].[to|from]Json()`

### ISSUE THREAD

**Issue by danielakhterov** [hashgraph/hedera-sdk-js#471]
### Problem

Users should be able to store requests in some human readable format such as JSON and construct requests directly from JSON to execute easily. If the user would to do this right now, they'd need to manually parse the JSON, check for nulls, and call the correct set methods for any fields which are not null.

Special case for JS is that the constructor already supports JSON being passed in. However, the issue is that it doesn't support all the fields on `Transaction` to be set; for instance this is the `AccountCreateTransaction` constructor params
```javascript
    /**
     * @param {object} [props]
     * @param {Key} [props.key]
     * @param {number | string | Long | BigNumber | Hbar} [props.initialBalance]
     * @param {boolean} [props.receiverSignatureRequired]
     * @param {AccountId} [props.proxyAccountId]
     * @param {Duration | Long | number} [props.autoRenewPeriod]
     * @param {string} [props.accountMemo]
     */
```

This doesn't support setting:
 - `transactionId`
 - `validDuration`
 - `transactionMemo`
 - `maxTransactionFee`
 - `nodeAccountIds`

For queries we should support setting:
 - `maxQueryPayment`
 - `queryPayment`
 - `paymentTransactionId`

### Solution

Add the aforementioned fields to all requests and implement `*[Query|Transaction].[to|from]Json()`

**Comment by SimiHunjan** [comment]
close for now
