### ISSUE TITLE
TokenMint transaction - support string[] as input

### ISSUE THREAD

**Issue by gregscullard** [hashgraph/hedera-sdk-js#582]
### Description

When creating a TokenMint transaction, the metadata has to be provided as an array of uint8Array. It would be useful/nice to offer an alternative input in the form of a string array and have the SDK perform the necessary conversion.

### Steps to reproduce

 TokenMintTransaction extends Transaction {
     * @param {object} [props]
     * @param {TokenId | string} [props.tokenId]
     * @param {Long | number} [props.amount]
     * **@param {Uint8Array[]}** <-- only Uint8Array[] allowed

### Additional context

 TokenMintTransaction extends Transaction {
     * @param {object} [props]
     * @param {TokenId | string} [props.tokenId]
     * @param {Long | number} [props.amount]
     * **@param {Uint8Array[] | string[]}** <-- add string[]

### Hedera network

mainnet, testnet, previewnet

### Version

v2.0.30

**Comment by gregscullard** [comment]
note `.addMetadata` and `.setMetadata` may be where this is best implemented.

**Comment by danielakhterov** [comment]
Heh, I actually deprecated this support recently. The reason I removed it is because if someone provides a `string` what encoding should we expect that string to be in? Originally, I expected the encoding to be in hex, but I've heard trying to use a regular string.
