### ISSUE TITLE
Error: 13 INTERNAL: Received RST_STREAM with code 0

### ISSUE THREAD

**Issue by schnouz** [hashgraph/hedera-sdk-js#622]
### Description

This error occurred randomly when making a transfer transaction or token association.
I tried to wrap the transaction in a retry loop with a delay of 6000 ms but still having the same result.
Should I override the behavior with .setNodeAccountIds() on retry when this error occurred ?

### Steps to reproduce

```
/* Retry the Associate Function 4 times with 6000 ms of delay between each */
   this.retryOperation(this.associate(accountId, tokenId, client, privateKey), 6000, 4)
```
   
```
/* Function to Associate a Token */
    async associate(accountId, tokenId, client, privateKey) {
        // Associate a token to an account
        const tx = new TokenAssociateTransaction()
            .setAccountId(accountId)
            .setTokenIds([tokenId])
            .freezeWith(client);

        // Sign with the private key of the account that is being associated to a token
        const signTx = await tx.sign(await PrivateKey.fromString(privateKey));

        // Submit the transaction to a Hedera network
        const txResponse = await signTx.execute(client);

        // Request the receipt of the transaction
        const receipt = await txResponse.getReceipt(client);

        // Get the transaction consensus status
        const transactionStatus = receipt.status;
    }
```

### Hedera network

mainnet

### Version

v2.0.30

### Operating system

Linux

**Comment by danielakhterov** [comment]
Can you capture the entire error being throw because I'm not able to reproduce it at the moment. Perhaps this only occurs occasionally. This is how I've been testing to see if any exception is thrown: https://github.com/hashgraph/hedera-sdk-js/pull/640/files#diff-e94ce93d4b27da34a565aa431a5d3179f5ea862641f33bfe2a0fd7b0a326bb37R247

**Comment by schnouz** [comment]
Hi, thanks for your answer. This is actually the entire error captured. This error is hard to reproduce because it occurs occasionally. But you need to try with TokenAssociateTransaction() instead because I never get that error with AccountBalanceQuery

**Comment by gregscullard** [comment]
Just tried
```        const pkey = PrivateKey.generate();
        await new AccountCreateTransaction()
            .setKey(pkey.publicKey)
            .setInitialBalance(Hbar.fromTinybars(1))
            .execute(client);
```

on mainnet against node 0.0.4 (35.186.191.247) 

got 

```
(node:64282) UnhandledPromiseRejectionWarning: Error: 13 INTERNAL: Received RST_STREAM with code 0 at Object.callErrorFromStatus (/Volumes/Samsung_X5/dev/github.com/hashgraph/hedera-sdk-js/node_modules/@grpc/grpc-js/build/src/call.js:31:26) at Object.onReceiveStatus (/Volumes/Samsung_X5/dev/github.com/hashgraph/hedera-sdk-js/node_modules/@grpc/grpc-js/build/src/client.js:179:52) at Object.onReceiveStatus (/Volumes/Samsung_X5/dev/github.com/hashgraph/hedera-sdk-js/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:336:141) at Object.onReceiveStatus (/Volumes/Samsung_X5/dev/github.com/hashgraph/hedera-sdk-js/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:299:181) at /Volumes/Samsung_X5/dev/github.com/hashgraph/hedera-sdk-js/node_modules/@grpc/grpc-js/build/src/call-stream.js:145:78 at processTicksAndRejections (internal/process/task_queues.js:75:11) (Use `node --trace-warnings ...` to show where the warning was created)
```

with latest SDK pulled from github.

**Comment by danielakhterov** [comment]
@gregscullard I added a test which checks the `shouldRetryExceptionally` is called twice meaning the query did retry on the first attempt when it received the error https://github.com/hashgraph/hedera-sdk-js/pull/689/files#diff-0dcd5935b81b021bc0d8b1f940c95746832e8a08f8fc8a634ad83a81853172eeR33

**Comment by danielakhterov** [comment]
@teacoat Are you running the latest version of the SDK?

**Comment by danielakhterov** [comment]
Another question worth asking is are you guys running this from a browser context or node?

**Comment by teacoat** [comment]
> @teacoat Are you running the latest version of the SDK?

I am running it in node, and it seems I haven't updated it from 2.0.13

**Comment by danielakhterov** [comment]
If you can, can you please update to the latest release. I know we recently fixed an issue with unpaid queries (`AccountBalanceQuery` and `TransactionReceiptQuery`) which retired using the same nodes instead of retrying on the next node which _might_ be the cause of this.

**Comment by topshef** [comment]
15 Oct Greg tested this on 2.1.1 and reproduced the RST_STREAM error https://discord.com/channels/373889138199494658/616725732650909710/898526564684296222

Issues re-occurred recently when node 0.0.25 was down.  Workaround remains to use custom node list `let client = Client.forNetwork(sdkNetwork);`

Any update or eta on this?

btw is there a way to read the list of operational nodes from status.hedera.com eg is this part of the webhook or feeds, any docs or tips welcome thanks!

**Comment by danielakhterov** [comment]
@topshef Have you tried using version 2.3.0 or 2.4.1? I believe this is when this issue was resolved. For any version before those you'd need to remove the nodes from the network manually.

> btw is there a way to read the list of operational nodes from status.hedera.com eg is this part of the webhook or feeds, any docs or tips welcome thanks!

Unfortunately, I this is not possible right now. However, we are currently working on implementing support for multiple IPs per node account ID which would then allow us to use the full network from Hedera instead of just one IP per node account ID. This would then allow us to _at the very least_ hard code the entire network from status.hedera.com

**Comment by derdis14** [comment]
@danielakhterov I'm using version 2.4.1 and consistently get this error when I run the [scheduled-transaction-multi-sig-threshold](https://github.com/hashgraph/hedera-sdk-js/blob/main/examples/scheduled-transaction-multi-sig-threshold.js) example on testnet.

If I set the nodeAccountID to "0.0.4" for all transactions, the error disappears.

**Comment by scalemaildev** [comment]
I am also regularly getting errors trying to do topic creation and message submission on Testnet using the .forTestnet() default nodes.

**Comment by tim-dewit** [comment]
I'm also on 2.4.1 and getting this error every time I try to make a transfer on the testnet.

**Comment by danielakhterov** [comment]
@derdis14 @scalemaildev @tim-dewit I believe the reason you hit those errors was because the network was down during the weekend.

**Comment by danielakhterov** [comment]
@hashaxis This is on the latest version? Is this being run on node or browser?

**Comment by hashaxis** [comment]
> @hashaxis This is on the latest version? Is this being run on node or browser?

This is occurring almost 100times per day on the official Hedera Mirror node for us.

**Comment by danielakhterov** [comment]
That's not really answering the question. Perhaps I should clarify, is your application running in Node JS or within a browser context? Also, are you using mainnet, testnet, or previewnet?

**Comment by hashaxis** [comment]
It's a Node js application connecting to mainnet through the standard SDK for selecting consensus nodes.

Issue is intermittent when fetching from mirror node: https://mainnet.mirrornode.hedera.com/
