### ISSUE TITLE
Request Support for BLS12 based signature verification

### ISSUE THREAD

**Issue by sudesh-supraoracles** [hashgraph/hedera-sdk-js#636]
Hi Team!

Since many protocols are putting BLS12 to use for digital signatures.
I want to verify BLS 12 based signature from Hedera smart contract.

Hoping for some positive inputs/response on this.

**Comment by danielakhterov** [comment]
I could be misunderstanding, but this sounds like something you'd want to add to https://github.com/hashgraph/hedera-improvement-proposal/ instead
