### ISSUE TITLE
AccountInfo class has incorrect definitions

### ISSUE THREAD

**Issue by teacoat** [hashgraph/hedera-sdk-js#712]
This line: https://github.com/hashgraph/hedera-sdk-js/blob/16005a679856b2ff2ce9e492faa7fb47633a46e7/src/account/AccountInfo.js#L22

Querying https://mainnet-public.mirrornode.hedera.com/api/v1/accounts/0.0.484746 returns the following data:
![image](https://user-images.githubusercontent.com/3913019/139179079-7a5df1ec-60a5-4076-97c1-baf7a5699e21.png)

As you can see, 'accountId' is actually being returned as 'account'

**Comment by valtyr-naut** [comment]
fix in prog: pr #626

**Comment by danielakhterov** [comment]
@teacoat There is no requirement for the SDKs to be consistent with the mirror node or vice versa. The current SDK API with returning `accountId` is the correct one, and it is what the other SDKs follow as well.
