### ISSUE TITLE
ContractExecuteTransaction.setFunctionParameters returns void

### ISSUE THREAD

**Issue by gregscullard** [hashgraph/hedera-sdk-js#728]
### Description

The `setFunctionParameters` of `ContractExecuteTransaction` returns void, thus preventing it from being used in a builder pattern.

### Steps to reproduce

```
let response = new ContractExecuteTransaction()
    .setMaxTransactionFee(new Hbar(15))
    .setContractId(ContractId.fromSolidityAddress(to.replace("0x", "")))
    .setFunctionParameters(Buffer.from(data, "hex"))
    .execute(client);
```
fails because `.setFunctionParameters` returns `void` and `.execute(client)` is run against `undefined`

There is a workaround which is to create the transaction object, then `.setFunctionParameters` on the object, then `.execute(client)` on the same object, however this isn't developer friendly and breaks the usual builder pattern.

### Hedera network

mainnet, testnet, previewnet

### Version

v2.4.0

### Operating system

macOS

**Comment by SimiHunjan** [comment]
I think you are supposed to use `setFunction()` instead of `setFunctionParameters()`?

```
const transaction = new ContractExecuteTransaction()
 .setContractId(newContractId)
 .setGas(100_000_000)
 .setFunction("set_message", new ContractFunctionParameters()
 .addString("hello from hedera again!"))
```

**Comment by valtyr-naut** [comment]
setFunction returns this which allows .execute to be chained like you want. Will double check with @danielakhterov

**Comment by SimiHunjan** [comment]
@gregscullard let us know if this resolves your issue

**Comment by danielakhterov** [comment]
@valtyr-naut Issue is correct. https://github.com/hashgraph/hedera-sdk-js/blob/55d93a160d29b67a5894b39c7ee62083e0d5df2d/src/contract/ContractExecuteTransaction.js#L209 Should `return this`
