### ISSUE TITLE
Getting "Not implemented" error when running Client.forTestnet() in Angular

### ISSUE THREAD

**Issue by tommueller** [hashgraph/hedera-sdk-js#735]
### Description

I am trying to use the js-sdk in an Angular application, but keep getting the error
 ```
ERROR Error: not implemented
    _createMirrorNetworkChannel Client.js:480
    Client Client.js:56
    WebClient WebClient.js:52
    forTestnet WebClient.js:134
    AppComponent app.component.ts:16
    AppComponent_Factory main.js:116
    Angular 18
core.js:6241:19
```
when running `Client.forTestnet()`.

### Steps to reproduce

1. Create fresh Angular project: `ng new hedera-test`
2. Edit app.component.ts to create the Hedera client:
```ts
import { Component } from '@angular/core';
import { Client } from '@hashgraph/sdk';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.sass']
})
export class AppComponent {
  constructor() {
    Client.forTestnet();
  }
}
```
3. Start the application `npm start`. The application builds fine, but when loading the page on localhost:4200 the error mentioned above show in the console and the application does not load.

### Additional context

I am using version 2.4.1 of the SDK. I did try it with all sorts of 2.x.x version, with no better luck.

<pre>
     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 13.0.1
Node: 14.17.0
Package Manager: npm 6.14.13
OS: linux x64

Angular: 13.0.0
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1300.1
@angular-devkit/build-angular   13.0.1
@angular-devkit/core            13.0.1
@angular-devkit/schematics      13.0.1
@angular/cli                    13.0.1
@schematics/angular             13.0.1
rxjs                            7.4.0
typescript                      4.4.4
</pre>

### Hedera network

testnet

### Version

2.4.1

### Operating system

Linux

**Comment by feri42** [comment]
I'm getting the same. The issue is that `_createMirrorNetworkChannel()` is missing in WebClient.

**Comment by danielakhterov** [comment]
This is definitely a bug with the SDK. Although the `WebClient` will still not support a `MirrorNetwork` it should not explode on client creation. We'll get on this asap.
