### ISSUE TITLE
TransferTransaction.addNftTransfer not working when NFT ID is provided

### ISSUE THREAD

**Issue by ed-marquez** [hashgraph/hedera-sdk-js#758]
### Description

Documentation currently shows that addNftTransfer(nftId, sender, receiver) should work. It doesn't work with these 3 inputs.

The nftId input is of [type NftId](https://docs.hedera.com/guides/docs/sdks/tokens/nft-id), which contains the token ID and NFT serial. However, for addNftTransfer to work, one has to pass (tokenId, serial, sender, receiver).

Should this method work with both? That would make sense. Thanks!

### Steps to reproduce

See line 206 here: https://github.com/ed-marquez/hedera-sdk-js/blob/main/examples/hts-nftP3-pause-freeze-wipe-delete.js

Then try: 
	let nft = new NftId(tokenId, 2);

	let tokenTransferTx2 = await new TransferTransaction()
		.addNftTransfer(nft, aliceId, bobId)
		.addHbarTransfer(aliceId, 100)
		.addHbarTransfer(bobId, -100)
		.freezeWith(client)
		.sign(aliceKey);
	tokenTransferTx2Sign = await tokenTransferTx2.sign(bobKey);
	let tokenTransferSubmit2 = await tokenTransferTx2Sign.execute(client);
	let tokenTransferRx2 = await tokenTransferSubmit2.getReceipt(client);
	console.log(`\n NFT transfer Alice -> Bob status: ${tokenTransferRx2.status} \n`);

See error: 
UnhandledPromiseRejectionWarning: TypeError: Cannot read property '_toProtobuf' of undefined

### Hedera network

testnet

### Version

v2.4

### Operating system

Windows

**Comment by SimiHunjan** [comment]
It looks like we can't support using the NFT ID object the way code snippet shows. Docs will be updated to show token ID and serial as the params for nftTokenTransfer and Java will need to add support for that. @danielakhterov @valtyr-naut feel free to add any additional context in terms of not being able to support the above.

**Comment by SimiHunjan** [comment]
adding NFT ID object support for `nftTokenTransfer()`

**Comment by SimiHunjan** [comment]
Reports the NFT ID does not work in transfers still. Please confirm @keirabee @danielakhterov .

**Comment by danielakhterov** [comment]
https://github.dev/hashgraph/hedera-sdk-js/blob/1f060ef1ea2170d4b13250797d98337e708f3259/test/unit/TransferTransaction.js#L162 is passing when an `NftId` object is passed as the first parameter.
