### ISSUE TITLE
Add .getTransactionId on queries

### ISSUE THREAD

**Issue by gregscullard** [hashgraph/hedera-sdk-js#777]
### Problem

When executing a query against Hedera, running the query may incur a cost which translates to a transaction on the network.
The query builder takes care of setting up the payment transaction, however the TransactionId for the cryptoTransfer is opaque to the developer.

It should be possible to consult the generated transaction id (or set it)

### Solution

Add a `.getTransactionId` and/or `setTransactionId` on queries

**Comment by danielakhterov** [comment]
I didn't realize this at the time, but this is already implemented as `get paymentTransactionId()` since `get transactionId()` would not work for `Transaction[Receipt|Record]Query`; I literally only realized this now as I was trying to implement `get transactionId()`
