### ISSUE TITLE
Test SDK retry enhancements do improve handling down nodes

### ISSUE THREAD

**Issue by SimiHunjan** [hashgraph/hedera-sdk-js#786]
### Problem

The following issues were added to increase the stability and performance of the SDKs when nodes are unavailable.

https://github.com/hashgraph/hedera-sdk-js/issues/769
https://github.com/hashgraph/hedera-sdk-js/issues/768
https://github.com/hashgraph/hedera-sdk-js/issues/766

After the enhancements are implemented, the SDK needs to be tested against an environment that has unavailable nodes in the network.

### Solution

- Add a few invalid node entries
- Set-up HAproxy that isn't routing

**Comment by bmgentile** [comment]
Could we prioritize this issue? Users are running into this error across testnet and mainnet; is critical to application functionality + perceived uptime of the [previewnet, testnet, mainnet] networks.

**Comment by HbarSuite** [comment]
agree with @bmgentile, very urgent one!

**Comment by ochikov** [comment]
We are currently researching on that. We've found a lot of potential problems across the JS, JAVA & GO SDKs.

**Comment by ochikov** [comment]
Hello @HbarSuite,
Actually, the new team that is working on the SDKs is reviewing all old and open issues. If you have any particular issue, please report it. Our goal is to make the SDKs more stable.
Thank you.

**Comment by shades2** [comment]
> Could we prioritize this issue? Users are running into this error across testnet and mainnet; is critical to application functionality + perceived uptime of the [previewnet, testnet, mainnet] networks.

Just curious if this one from July was actually dealt with, or was it re-prioritized?

**Comment by ochikov** [comment]
@shades2 If you open the three linked issues, they are fixed and closed. We are researching the whole handling nodes algorithm and improving it.

**Comment by shades2** [comment]
> @shades2 If you open the three linked issues, they are fixed and closed. We are researching the whole handling nodes algorithm and improving it.

Thanks for clarifying! I'll click through.
