### ISSUE TITLE
Regex never matches port

### ISSUE THREAD

**Issue by feri42** [hashgraph/hedera-sdk-js#793]
### Description

The regexp here: https://github.com/hashgraph/hedera-sdk-js/blob/628258026122ac189ed28c503221bb17799e5cee/src/ManagedNodeAddress.js#L8 never matches the port part. Because of this `isTransportSecurity()` always returns false: https://github.com/hashgraph/hedera-sdk-js/blob/628258026122ac189ed28c503221bb17799e5cee/src/ManagedNodeAddress.js#L109

### Steps to reproduce

Read the code

### Hedera network

mainnet

### Version

latest

**Comment by danielakhterov** [comment]
Can confirm this is a bug. I believe this was fixed in Java, but the fix was not ported to JS.

**Comment by danielakhterov** [comment]
Fixed directly on the `develop` branch with an accompanying test: https://github.com/hashgraph/hedera-sdk-js/blob/develop/test/unit/HostAndPort.js
