### ISSUE TITLE
HIP-21 Free network info query 

### ISSUE THREAD

**Issue by SimiHunjan** [hashgraph/hedera-sdk-js#810]
### Problem

Add support for a free address book query

HIP: https://hips.hedera.com/hip/hip-21

Depends on issue https://github.com/hashgraph/hedera-mirror-node/issues/3098

### Solution

See above

**Comment by SimiHunjan** [comment]
will only be supported by the mirror node at this time

**Comment by danielakhterov** [comment]
This already exists in `develop` https://github.com/hashgraph/hedera-sdk-js/blob/develop/src/network/AddressBookQuery.js
