### ISSUE TITLE
HIP-31 Add token transfer decimal information 

### ISSUE THREAD

**Issue by SimiHunjan** [hashgraph/hedera-sdk-js#811]
### Problem

HIP: https://hips.hedera.com/hip/hip-31

Hedera Protobuf: https://github.com/hashgraph/hedera-protobufs/pull/127

### Solution

Add token decimal support

### Task List

 - [x] `TransferTransaction`
    - [x] `addTokenTransferWithDecimals()`
    - [x] `getTokenIdDecimals()`
 - [x] `Status`
    - [x] `UNEXPECTED_TOKEN_DECIMALS`

**Comment by danielakhterov** [comment]
Resolved directly on main: https://github.com/hashgraph/hedera-sdk-js/commit/efb6b0079fda60e8a211d985867a090b06ee93f1
