### ISSUE TITLE
HIP-33 Add ledger ID field to info responses 

### ISSUE THREAD

**Issue by SimiHunjan** [hashgraph/hedera-sdk-js#812]
### Problem

HIP: https://hips.hedera.com/hip/hip-33

Hedera Protobufs: hashgraph/hedera-protobufs#128

### Solution

Add ledger ID field to info responses

### Task List

 - [x] `LedgerId`
    - [x] `fromString()`
    - [x] `fromBytes()`
    - [ ] `fromNetworkName()` (NA anymore since `NetworkName` was not a class before in the JS SDK)
    - [x] `isMainnet()`
    - [x] `isTestnet()`
    - [x] `isPreviewnet()`
    - [x] `toString()`
    - [x] `toBytes()`
    - [ ] `toNetworkName()` (NA anymore since `NetworkName` was not a class before in the JS SDK)
    - [x] `MAINNET`
    - [x] `TESTNET`
    - [x] `PREVIEWNET`
 - [x] `NetworkName`
    - [x] `OTHER`
    - [x] Deprecate
 - [x] `AccountInfo`
    - [x] `ledgerId`
 - [x] `ContractInfo`
    - [x] `ledgerId`
 - [x] `FileInfo`
    - [x] `ledgerId`
 - [x] `TokenInfo`
    - [x] `ledgerId`
 - [x] `TopicInfo`
    - [x] `ledgerId`
 - [x] `TokenNftInfo`
    - [x] `ledgerId`

**Comment by danielakhterov** [comment]
This seems to be still in progress.

**Comment by valtyr-naut** [comment]
- NetworkName removed from sdk [sdk uses LedgerId in all places NetworkName was used]
- NetworkName legacy checksum code migrated to LedgerId
- Local declaration for NetworkName reverted for Client
- LedgerId complete and pending review
