### ISSUE TITLE
Fetching balance giving incorrect result

### ISSUE THREAD

**Issue by danielakhterov** [hashgraph/hedera-sdk-js#813]
### Description

Not entirely sure why this is the case, but the result is `Long.MAX` even if the actual balance is not exactly `Long.MAX`. This might have something to do with us using v4 of `long`, but at this point I'm not entirely sure. 

### Steps to reproduce

Query account balance for `0.0.19139692` and look at token `0.0.19139694`. The balance should be `9223372036854775804`, but is being reported as `9223372036854775807`

https://v2.api.testnet.kabuto.sh/account/0.0.19139692/token

### Hedera network

mainnet, testnet, previewnet

### Version

v2.6.0

### Operating system

Linux

**Comment by lerpinglemur** [comment]
This issue is most likely relevant: https://github.com/protobufjs/protobuf.js/issues/1629

I wrote a patch below that forces the protobuf reader to re-initialize after Long has been loaded, but ideally vite, or js compiler should run a hook that injects the correct Long import into protobufjs.
Or protobufjs should be forked.

```/**
 * Patch protobuf race condition between loading protobuf and Long.js libraries.
 */
import Long from 'long';
import * as $protobuf from "protobufjs/minimal";

(() => {
  var $util = $protobuf.util;

  if ($util.Long == null) {

    console.log(`Patching Protobuf Long.js instance...`);
    $util.Long = Long;

    // @ts-ignore
    if ($protobuf.Reader._configure != null) {
      // @ts-ignore
      $protobuf.Reader._configure($protobuf.BufferReader);
    }

  }
})();
```

**Comment by gregscullard** [comment]
(in relation to setMaxSupply), tried the code below

```
    let maxSupply = new BigNumber("99999999999999999");
    resp = new TokenCreateTransaction()
        .setTokenName("ffff")
        .setTokenSymbol("F")
        .setDecimals(0)
        .setInitialSupply(Number(0))
        .setSupplyType(TokenSupplyType.Finite)
        .setMaxSupply(maxSupply)
        .setTreasuryAccountId(client.operatorAccountId);

    console.log(resp.maxSupply.toString());

    resp = await resp.execute(client);

    const tokenId = (await resp.getReceipt(client)).tokenId;
```

returns a precheck error: PrecheckStatusError: transaction 0.0.28534006@1642594229.163439701 failed precheck with status INVALID_TOKEN_MAX_SUPPLY

Yet the max supply specified is well below the max allowable by hedera (int64)

**Comment by danielakhterov** [comment]
What I didn't realize until now is that the `@hashgraph/proto` package doesn't depend on `long`. Yes, the package _can_ work with just `number`, but I don't see any issue with depending on `Long` and running the hook in `index.js` when the package is loaded.
