### ISSUE TITLE
Incorrect transaction ID reported in errors

### ISSUE THREAD

**Issue by gregscullard** [hashgraph/hedera-sdk-js#814]
### Description

I've noticed several users reporting errors which contain an invalid transaction id, for example:

```
receipt for transaction 0.0.0@1639643905.876389619 contained error status INVALID_TREASURY_ACCOUNT_FOR_TOKEN
```

note `0.0.0` for the account id part of the transaction id.

### Steps to reproduce

TBD

### Hedera network

mainnet, testnet, previewnet

### Version

v2.6.0

**Comment by danielakhterov** [comment]
I haven't seen that in JS for _awhile_. I'm definitely curious as to how to reproduce because when I ran tests today I consistently got the account ID in the receipt.

**Comment by SimiHunjan** [comment]
@gregscullard are you still experiencing this issue?

**Comment by SimiHunjan** [comment]
Closing for now. Please reopen if you encounter this again.
