### ISSUE TITLE
Unnecessary Promise usage for Signing

### ISSUE THREAD

**Issue by Daniel-K-Ivanov** [hashgraph/hedera-sdk-js#826]
### Problem

At the moment `signWith` is implemented by passing `pubKey` and a `transactionSigner` promise. Due to the fact that `signWith` is used for normal signing as-well (`.sign(privateKey)`) it enforces the usage of `Promises` unnecessarily. 

As an effect various functions must be defined as `async` and return `Promise` that otherwise do not need to. Example for such method is `getTransactionHash` on the `Transaction` object.,

### Solution

Remove the unnecessary need of enforcing `promises` where they are not needed.

- `Transaction.signWith`
- `Transaction.sign`
- `Transaction.signWithOperator`
- `Transaction.getTransactionHash`
- `Transaction.getTransactionHashPerNode()`
- `Transaction._signTranscation`

**Comment by danielakhterov** [comment]
- `Transaction.sign()`: 
    At the moment this is async because it uses `signWith` directly which requires this method to be async as you mentioned. We can make another variant such as `Transaction.signSync()`, but I feel that'll only add unnecessary complexity. There have been numerous times we had to create async variants of methods because we added support for something that required the use of await within the method such as `Transaction.toBytes()`.
- `Transaction.signWith()`:
    We support to code paths for this method at the moment. When `Client.signOnDemand` is set to `true` we only store the `PublicKey` and `TransactionSigner` and create the signatures when needed. The other code path is we sign the transaction on the stop which requires awaiting the `TransactionSigner` and hence requires the entire method to be async.
- `Transaction.signWithOperator()`:
    Much like `Transaction.sign()` we _can_ create alternatives, but I feel adding this complexity is unnecessary.
- `Transaction.getTransactionHash()`:
    I am not a fan that this method is async and does not end with `Async` in the name. However, this method is very much required to be async because of `Client.signOnDemand`. If sign on demand is enabled then we must create all the transactions, and sign them which again requires us to await promises.
- `Transaction.getTransactionHashPerNode()`:
    Same as `Transaction.getTransactionHash()`
- `Transaction._signTranscation()`:
    The method that does the actual signing so it is required to await the `TransactionSigner`, and hence requires the method to be async. Also, this method isn't part of the public API, so I'm not entirely sure if it should be part of this list.

That said, I'm wondering why the use of unnecessary promises is problematic. I understand there is a performance penalty, but this is JS after all. If you're looking for performance you should use one of our other SDKs.

**Comment by danielakhterov** [comment]
Stale issue, closing. Will re-open if needed.
