### ISSUE TITLE
Account alias example does not work

### ISSUE THREAD

**Issue by SimiHunjan** [hashgraph/hedera-sdk-js#827]
### Description

Tested the example in the SDK for creating an account via an alias because the code I wrote that was a copy for what I wrote in Java was failing. Using v2.7.0-beta.1

```
/Users/simihunjan/Desktop/hello-hedera-js-sdk2.0/accountcreatetest.js:36
    const publicKey = privateKey.getPublicKey();
                                 ^

TypeError: privateKey.getPublicKey is not a function
```

### Steps to reproduce

Run this example:

https://github.com/hashgraph/hedera-sdk-js/blob/v2.7.0-beta.1/examples/account-alias.js

### Hedera network

previewnet

### Version

2.7.0-beta.1

### Operating system

macOS

**Comment by danielakhterov** [comment]
In JS to access the public key you'd use `PrivatwKey.publicKey` this is intentional as it is a c'mon idiom for JS

**Comment by SimiHunjan** [comment]
That makes sense, but why does the example in the sdk repo use it? That's what I meant by the linked example in the repo does not work because it uses .getPublicKey() instead of what you suggested.

**Comment by SimiHunjan** [comment]
After I fix that in the example, it now errors hereL

**Comment by danielakhterov** [comment]
Sorry,, I shouldn't have responded at 4 in the mourning; didn't completely realize what was being talked about. This is my fault that the example is so broken. Will fix this asap.

**Comment by danielakhterov** [comment]
This has been resolved and merged last sprint.
