### ISSUE TITLE
Streamline contract creation flow

### ISSUE THREAD

**Issue by gregscullard** [hashgraph/hedera-sdk-js#850]
### Problem

Developers wanting to create smart contracts currently have to 
* Create a file (optionally using file append) with the contract's bytecode
* Create a contract from the resulting file

### Solution

Add a builder to the contractCreate transaction that accepts bytecode such that if specified, the createContractTransaction.execute does

* Create file (with admin key for append if necessary) from bytecode
* Appends n times to complete bytecode upload
* Creates the contract
* Upon querying for a receipt or record for the operation, the contractId should be returned. The information for any file append transactions or file create transactions will not be returned. If a user would like to have this information the user can submit the transactions individually. 
* to|from bytes will not be supported
* Return file ID in logs

Note: This should continue to support the specification of contract constructor parameters

### Alternatives

Continue to use current flow which is less than optimal for developer experience

**Comment by danielakhterov** [comment]
Implemented directly on `develop` https://github.com/hashgraph/hedera-sdk-js/blob/develop/src/contract/ContractCreateFlow.js
