### ISSUE TITLE
Fix broken methods 

### ISSUE THREAD

**Issue by SimiHunjan** [hashgraph/hedera-sdk-js#853]
### Description

Description
`Client.setRequestTimeout()`
`Executable.execute(client, timeout)`

These methods do not work.

Steps to reproduce
Use `Client.setRequestTimeout()` and `Executable.execute(client, timeout)`

Additional context
No response

Hedera network
other

Version
current

Operating system
No response

### Steps to reproduce

Use methods

### Hedera network

other

### Version

current

**Comment by danielakhterov** [comment]
JS Doesn't have these methods, only Java does.

**Comment by SimiHunjan** [comment]
ok thanks closing since we have https://github.com/hashgraph/hedera-sdk-js/issues/768
