### ISSUE TITLE
Integrate option to freeze a specific amount of custom tokens related to an associated accound ID.

### ISSUE THREAD

**Issue by ToMaciANura** [hashgraph/hedera-sdk-js#878]
### Problem

When "locking" or "freezing" liquidity related to an associated Account Id, There is no way to freeze a specific amount of tokens.

### Solution

Add .customTokenAmount for the freezing token functionality.

**Comment by danielakhterov** [comment]
You might want to create a [HIP](https://github.com/hashgraph/hedera-improvement-proposal/) for this. The functionality you're asking for is not supported by Hedera and hence not supported by the SDK.
