### ISSUE TITLE
deploying a smart contract

### ISSUE THREAD

**Issue by jigsnptel** [hashgraph/hedera-sdk-js#881]
### Description

I am trying to deploy the smart contract written in solidity on hashgraph testnet. i do not understand the meaning of "The contract bytecode **must** be hex encoded, it should notbe the actual data the hex represents". i used remix and got the bytecode of my contract. which is as follows:
'608060405234801561001057600080fd5b50611501806100206000396000f3fe608060405234801561001057600080fd5b50600436106100935760003560e01c80639613799f116100665780639613799f14610474578063b5b4aee2146104ba578063b8f4b31714610652578063c407670f1461084f578063dcfa88621461086d57610093565b806311b3b8271461009857806346a503be146101e8578063876876e81461033f578063902929f414610390575b600080fd5b610151600480360360208110156100ae57600080fd5b81019080803590602001906401000000008111156100cb57600080fd5b8201836020820111156100dd57600080fd5b803590602001918460018302840111640100000000831117156100ff57600080fd5b91908080601f016020809104026020016040519081016040528093929190818152602001838380828437600081840152601f19601f82011690508083019250505050505050919291929050505061095a565b6040518086815260200180602001858152602001848152602001838152602001828103825286818151815260200191508051906020019080838360005b838110156101a957808201518184015260208101905061018e565b50505050905090810190601f1680156101d65780820380516001836020036101000a031916815260200191505b50965050505050505060405180910390f35b6102a1600480360360208110156101fe57600080fd5b810190808035906020019064010000000081111561021b57600080fd5b82018360208201111561022d57600080fd5b8035906020019184600183028401116401000000008311171561024f57600080fd5b91908080601f016020809104026020016040519081016040528093929190818152602001838380828437600081840152601f19601f820116905080830192505050505050509192919290505050610a3e565b6040518087815260200186815260200180602001858152602001848152602001838152602001828103825286818151815260200191508051906020019080838360005b838110156102ff5780820151818401526020810190506102e4565b50505050905090810190601f16801561032c5780820380516001836020036101000a031916815260200191505b5097505050505050505060405180910390f35b61036b6004803603602081101561035557600080fd5b8101908080359060200190929190505050610b28565b6040518083151515158152602001821515151581526020019250505060405180910390f35b610449600480360360208110156103a657600080fd5b81019080803590602001906401000000008111156103c357600080fd5b8201836020820111156103d557600080fd5b803590602001918460018302840111640100000000831117156103f757600080fd5b91908080601f016020809104026020016040519081016040528093929190818152602001838380828437600081840152601f19601f820116905080830192505050505050509192919290505050610b7c565b6040518085815260200184815260200183815260200182815260200194505050505060405180910390f35b6104b86004803603606081101561048a57600080fd5b8101908080359060200190929190803515159060200190929190803515159060200190929190505050610d5b565b005b6104e6600480360360208110156104d057600080fd5b8101908080359060200190929190505050610ddf565b604051808060200180602001878152602001868152602001806020018515151515815260200184810384528a818151815260200191508051906020019080838360005b83811015610544578082015181840152602081019050610529565b50505050905090810190601f1680156105715780820380516001836020036101000a031916815260200191505b50848103835289818151815260200191508051906020019080838360005b838110156105aa57808201518184015260208101905061058f565b50505050905090810190601f1680156105d75780820380516001836020036101000a031916815260200191505b50848103825286818151815260200191508051906020019080838360005b838110156106105780820151818401526020810190506105f5565b50505050905090810190601f16801561063d5780820380516001836020036101000a031916815260200191505b50995050505050505050505060405180910390f35b61084d600480360360a081101561066857600080fd5b810190808035906020019064010000000081111561068557600080fd5b82018360208201111561069757600080fd5b803590602001918460018302840111640100000000831117156106b957600080fd5b91908080601f016020809104026020016040519081016040528093929190818152602001838380828437600081840152601f19601f8201169050808301925050505050505091929192908035906020019064010000000081111561071c57600080fd5b82018360208201111561072e57600080fd5b8035906020019184600183028401116401000000008311171561075057600080fd5b91908080601f016020809104026020016040519081016040528093929190818152602001838380828437600081840152601f19601f8201169050808301925050505050505091929192908035906020019092919080359060200190929190803590602001906401000000008111156107c757600080fd5b8201836020820111156107d957600080fd5b803590602001918460018302840111640100000000831117156107fb57600080fd5b91908080601f016020809104026020016040519081016040528093929190818152602001838380828437600081840152601f19601f82011690508083019250505050505050919291929050505061105d565b005b61085761115b565b6040518082815260200191505060405180910390f35b610958600480360360c081101561088357600080fd5b810190808035906020019092919080359060200190929190803590602001906401000000008111156108b457600080fd5b8201836020820111156108c657600080fd5b803590602001918460018302840111640100000000831117156108e857600080fd5b91908080601f016020809104026020016040519081016040528093929190818152602001838380828437600081840152601f19601f820116905080830192505050505050509192919290803590602001909291908035906020019092919080359060200190929190505050611161565b005b600181805160208101820180518482526020830160208501208183528095505050505050600091509050806000015490806001018054600181600116156101000203166002900480601f016020809104026020016040519081016040528092919081815260200182805460018160011615610100020316600290048015610a225780601f106109f757610100808354040283529160200191610a22565b820191906000526020600020905b815481529060010190602001808311610a0557829003601f168201915b5050505050908060020154908060030154908060040154905085565b600081805160208101820180518482526020830160208501208183528095505050505050600091509050806000015490806001015490806002018054600181600116156101000203166002900480601f016020809104026020016040519081016040528092919081815260200182805460018160011615610100020316600290048015610b0c5780601f10610ae157610100808354040283529160200191610b0c565b820191906000526020600020905b815481529060010190602001808311610aef57829003601f168201915b5050505050908060030154908060040154908060050154905086565b6000806004600084815260200190815260200160002060010160009054906101000a900460ff166004600085815260200190815260200160002060010160019054906101000a900460ff1691509150915091565b6000806000806000806000806001896040518082805190602001908083835b60208310610bbe5780518252602082019150602081019050602083039250610b9b565b6001836020036101000a03801982511681845116808217855250505050505090500191505090815260200160405180910390206000015493506001896040518082805190602001908083835b60208310610c2d5780518252602082019150602081019050602083039250610c0a565b6001836020036101000a03801982511681845116808217855250505050505090500191505090815260200160405180910390206002015492506001896040518082805190602001908083835b60208310610c9c5780518252602082019150602081019050602083039250610c79565b6001836020036101000a03801982511681845116808217855250505050505090500191505090815260200160405180910390206003015491506001896040518082805190602001908083835b60208310610d0b5780518252602082019150602081019050602083039250610ce8565b6001836020036101000a0380198251168184511680821785525050505050509050019150509081526020016040518091039020600401549050838383839750975097509750505050509193509193565b60405180606001604052808481526020018315158152602001821515815250600460008581526020019081526020016000206000820151816000015560208201518160010160006101000a81548160ff02191690831515021790555060408201518160010160016101000a81548160ff021916908315150217905550905050505050565b60608060008060606000600260008881526020019081526020016000206001018054600181600116156101000203166002900480601f016020809104026020016040519081016040528092919081815260200182805460018160011615610100020316600290048015610e935780601f10610e6857610100808354040283529160200191610e93565b820191906000526020600020905b815481529060010190602001808311610e7657829003601f168201915b50505050509550600260008881526020019081526020016000206002018054600181600116156101000203166002900480601f016020809104026020016040519081016040528092919081815260200182805460018160011615610100020316600290048015610f445780601f10610f1957610100808354040283529160200191610f44565b820191906000526020600020905b815481529060010190602001808311610f2757829003601f168201915b505050505094506002600088815260200190815260200160002060030154935060026000888152602001908152602001600020600401549250600260008881526020019081526020016000206005018054600181600116156101000203166002900480601f0160208091040260200160405190810160405280929190818152602001828054600181600116156101000203166002900480156110275780601f10610ffc57610100808354040283529160200191611027565b820191906000526020600020905b81548152906001019060200180831161100a57829003601f168201915b505050505091506002600088815260200190815260200160002060060160009054906101000a900460ff16905091939550919395565b6003600081548092919060010191905055506040518060e001604052806003548152602001868152602001858152602001848152602001838152602001828152602001600015158152506002600060035481526020019081526020016000206000820151816000015560208201518160010190805190602001906110e2929190611430565b5060408201518160020190805190602001906110ff929190611430565b50606082015181600301556080820151816004015560a0820151816005019080519060200190611130929190611430565b5060c08201518160060160006101000a81548160ff0219169083151502179055509050505050505050565b60035481565b6040518060c00160405280878152602001868152602001858152602001848152602001838152602001828152506000856040518082805190602001908083835b602083106111c457805182526020820191506020810190506020830392506111a1565b6001836020036101000a038019825116818451168082178552505050505050905001915050908152602001604051809103902060008201518160000155602082015181600101556040820151816002019080519060200190611227929190611430565b50606082015181600301556080820151816004015560a08201518160050155905050826001856040518082805190602001908083835b60208310611280578051825260208201915060208101905060208303925061125d565b6001836020036101000a038019825116818451168082178552505050505050905001915050908152602001604051809103902060020160008282540192505081905550816001856040518082805190602001908083835b602083106112fa57805182526020820191506020810190506020830392506112d7565b6001836020036101000a038019825116818451168082178552505050505050905001915050908152602001604051809103902060030160008282540192505081905550806001856040518082805190602001908083835b602083106113745780518252602082019150602081019050602083039250611351565b6001836020036101000a038019825116818451168082178552505050505050905001915050908152602001604051809103902060040160008282540192505081905550856001856040518082805190602001908083835b602083106113ee57805182526020820191506020810190506020830392506113cb565b6001836020036101000a038019825116818451168082178552505050505050905001915050908152602001604051809103902060000181905550505050505050565b828054600181600116156101000203166002900490600052602060002090601f016020900481019282601f1061147157805160ff191683800117855561149f565b8280016001018555821561149f579182015b8281111561149e578251825591602001919060010190611483565b5b5090506114ac91906114b0565b5090565b6114d291905b808211156114ce5760008160009055506001016114b6565b5090565b9056fea165627a7a72305820de60ac15c284a8f091edf749b88de117ed5bf768d4bb0a0f509d861e5b4dd12e0029'

i divided this bytecode into two parts and used file create and file append tranaction to create a contract file id. i used contract cretate trnasaction and tried to call the contract function "addDonor". but it says that "addDonor function is not there"

in the example here, helloworld.json was used. how do i get json file similar to helloworld.json for my contract ? 

pls help.

### Steps to reproduce

require("dotenv").config();

// import the 'Client' module from the Hedera JS SDK

const { Client,    PrivateKey,
    ContractCreateTransaction,
    FileCreateTransaction,FileAppendTransaction,    FileContentsQuery,
    ContractDeleteTransaction,
    ContractCallQuery,
    Hbar,
    AccountId
 } = require("@hashgraph/sdk");

async function main() {
    // Grab our account credentials
const operatorAccount = process.env.ACCOUNT_ID;
const operatorPrivateKey = process.env.PRIVATE_KEY;
const operatorPublicKey=process.env.PUBLIC_KEY;
console.log(operatorAccount)
console.log(operatorPrivateKey);
console.log(operatorPublicKey);
// Configure a testnet client with our Account ID & private key
const client = Client.forTestnet();
client.setOperator(operatorAccount, operatorPrivateKey);
// add the rest of your code here 
//import helloWorld from "./hello_world.json";
contractByteCode='0x608060405234801561001057600080fd5b50611501806100206000396000f3fe608060405234801561001057600080fd5b50600436106100935760003560e01c80639613799f116100665780639613799f14610474578063b5b4aee2146104ba578063b8f4b31714610652578063c407670f1461084f578063dcfa88621461086d57610093565b806311b3b8271461009857806346a503be146101e8578063876876e81461033f578063902929f414610390575b600080fd5b610151600480360360208110156100ae57600080fd5b81019080803590602001906401000000008111156100cb57600080fd5b8201836020820111156100dd57600080fd5b803590602001918460018302840111640100000000831117156100ff57600080fd5b91908080601f016020809104026020016040519081016040528093929190818152602001838380828437600081840152601f19601f82011690508083019250505050505050919291929050505061095a565b6040518086815260200180602001858152602001848152602001838152602001828103825286818151815260200191508051906020019080838360005b838110156101a957808201518184015260208101905061018e565b50505050905090810190601f1680156101d65780820380516001836020036101000a031916815260200191505b50965050505050505060405180910390f35b6102a1600480360360208110156101fe57600080fd5b810190808035906020019064010000000081111561021b57600080fd5b82018360208201111561022d57600080fd5b8035906020019184600183028401116401000000008311171561024f57600080fd5b91908080601f016020809104026020016040519081016040528093929190818152602001838380828437600081840152601f19601f820116905080830192505050505050509192919290505050610a3e565b6040518087815260200186815260200180602001858152602001848152602001838152602001828103825286818151815260200191508051906020019080838360005b838110156102ff5780820151818401526020810190506102e4565b50505050905090810190601f16801561032c5780820380516001836020036101000a031916815260200191505b5097505050505050505060405180910390f35b61036b6004803603602081101561035557600080fd5b8101908080359060200190929190505050610b28565b6040518083151515158152602001821515151581526020019250505060405180910390f35b610449600480360360208110156103a657600080fd5b81019080803590602001906401000000008111156103c357600080fd5b8201836020820111156103d557600080fd5b803590602001918460018302840111640100000000831117156103f757600080fd5b91908080601f016020809104026020016040519081016040528093929190818152602001838380828437600081840152601f19601f820116905080830192505050505050509192919290505050610b7c565b6040518085815260200184815260200183815260200182815260200194505050505060405180910390f35b6104b86004803603606081101561048a57600080fd5b8101908080359060200190929190803515159060200190929190803515159060200190929190505050610d5b565b005b6104e6600480360360208110156104d057600080fd5b8101908080359060200190929190505050610ddf565b604051808060200180602001878152602001868152602001806020018515151515815260200184810384528a818151815260200191508051906020019080838360005b83811015610544578082015181840152602081019050610529565b50505050905090810190601f1680156105715780820380516001836020036101000a031916815260200191505b50848103835289818151815260200191508051906020019080838360005b838110156105aa57808201518184015260208101905061058f565b50505050905090810190601f1680156105d75780820380516001836020036101000a031916815260200191505b50848103825286818151815260200191508051906020019080838360005b838110156106105780820151818401526020810190506105f5565b50505050905090810190601f16801561063d5780820380516001836020036101000a031916815260200191505b50995050505050505050505060405180910390f35b61084d600480360360a081101561066857600080fd5b810190808035906020019064010000000081111561068557600080fd5b82018360208201111561069757600080fd5b803590602001918460018302840111640100000000831117156106b957600080fd5b91908080601f016020809104026020016040519081016040528093929190818152602001838380828437600081840152601f19601f8201169050808301925050505050505091929192908035906020019064010000000081111561071c57600080fd5b82018360208201111561072e57600080fd5b8035906020019184600183028401116401000000008311171561075057600080fd5b91908080601f016020809104026020016040519081016040528093929190818152602001838380828437600081840152601f19601f8201169050808301925050505050505091929192908035906020019092919080359060200190929190803590602001906401000000008111156107c757600080fd5b8201836020820111156107d957600080fd5b803590602001918460018302840111640100000000831117156107fb57600080fd5b91908080601f016020809104026020016040519081016040528093929190818152602001838380828437600081840152601f19601f82011690508083019250505050505050919291929050505061105d565b005b61085761115b565b6040518082815260200191505060405180910390f35b610958600480360360c081101561088357600080fd5b810190808035906020019092919080359060200190929190803590602001906401000000008111156108b457600080fd5b8201836020820111156108c657600080fd5b803590602001918460018302840111640100000000831117156108e857600080fd5b91908080601f016020809104026020016040519081016040528093929190818152602001838380828437600081840152601f19601f820116905080830192505050505050509192919290803590602001909291908035906020019092919080359060200190929190505050611161565b005b600181805160208101820180518482526020830160208501208183528095505050505050600091509050806000015490806001018054600181600116156101000203166002900480601f016020809104026020016040519081016040528092919081815260200182805460018160011615610100020316600290048015610a225780601f106109f757610100808354040283529160200191610a22565b820191906000526020600020905b815481529060010190602001808311610a0557829003601f168201915b5050505050908060020154908060030154908060040154905085565b600081805160208101820180518482526020830160208501208183528095505050505050600091509050806000015490806001015490806002018054600181600116156101000203166002900480601f016020809104026020016040519081016040528092919081815260200182805460018160011615610100020316600290048015610b0c5780601f10610ae157610100808354040283529160200191610b0c565b820191906000526020600020905b815481529060010190602001808311610aef57829003601f168201915b50505050509080600301549080'
const fileTransactionResponse = await new FileCreateTransaction()
        .setKeys([client.operatorPublicKey])
        .setContents(contractByteCode)
        .execute(client);

    // Fetch the receipt for transaction that created the file
    const fileReceipt = await fileTransactionResponse.getReceipt(client);
    contractByteCode1='60040154908060050154905086565b6000806004600084815260200190815260200160002060010160009054906101000a900460ff166004600085815260200190815260200160002060010160019054906101000a900460ff1691509150915091565b6000806000806000806000806001896040518082805190602001908083835b60208310610bbe5780518252602082019150602081019050602083039250610b9b565b6001836020036101000a03801982511681845116808217855250505050505090500191505090815260200160405180910390206000015493506001896040518082805190602001908083835b60208310610c2d5780518252602082019150602081019050602083039250610c0a565b6001836020036101000a03801982511681845116808217855250505050505090500191505090815260200160405180910390206002015492506001896040518082805190602001908083835b60208310610c9c5780518252602082019150602081019050602083039250610c79565b6001836020036101000a03801982511681845116808217855250505050505090500191505090815260200160405180910390206003015491506001896040518082805190602001908083835b60208310610d0b5780518252602082019150602081019050602083039250610ce8565b6001836020036101000a0380198251168184511680821785525050505050509050019150509081526020016040518091039020600401549050838383839750975097509750505050509193509193565b60405180606001604052808481526020018315158152602001821515815250600460008581526020019081526020016000206000820151816000015560208201518160010160006101000a81548160ff02191690831515021790555060408201518160010160016101000a81548160ff021916908315150217905550905050505050565b60608060008060606000600260008881526020019081526020016000206001018054600181600116156101000203166002900480601f016020809104026020016040519081016040528092919081815260200182805460018160011615610100020316600290048015610e935780601f10610e6857610100808354040283529160200191610e93565b820191906000526020600020905b815481529060010190602001808311610e7657829003601f168201915b50505050509550600260008881526020019081526020016000206002018054600181600116156101000203166002900480601f016020809104026020016040519081016040528092919081815260200182805460018160011615610100020316600290048015610f445780601f10610f1957610100808354040283529160200191610f44565b820191906000526020600020905b815481529060010190602001808311610f2757829003601f168201915b505050505094506002600088815260200190815260200160002060030154935060026000888152602001908152602001600020600401549250600260008881526020019081526020016000206005018054600181600116156101000203166002900480601f0160208091040260200160405190810160405280929190818152602001828054600181600116156101000203166002900480156110275780601f10610ffc57610100808354040283529160200191611027565b820191906000526020600020905b81548152906001019060200180831161100a57829003601f168201915b505050505091506002600088815260200190815260200160002060060160009054906101000a900460ff16905091939550919395565b6003600081548092919060010191905055506040518060e001604052806003548152602001868152602001858152602001848152602001838152602001828152602001600015158152506002600060035481526020019081526020016000206000820151816000015560208201518160010190805190602001906110e2929190611430565b5060408201518160020190805190602001906110ff929190611430565b50606082015181600301556080820151816004015560a0820151816005019080519060200190611130929190611430565b5060c08201518160060160006101000a81548160ff0219169083151502179055509050505050505050565b60035481565b6040518060c00160405280878152602001868152602001858152602001848152602001838152602001828152506000856040518082805190602001908083835b602083106111c457805182526020820191506020810190506020830392506111a1565b6001836020036101000a038019825116818451168082178552505050505050905001915050908152602001604051809103902060008201518160000155602082015181600101556040820151816002019080519060200190611227929190611430565b50606082015181600301556080820151816004015560a08201518160050155905050826001856040518082805190602001908083835b60208310611280578051825260208201915060208101905060208303925061125d565b6001836020036101000a038019825116818451168082178552505050505050905001915050908152602001604051809103902060020160008282540192505081905550816001856040518082805190602001908083835b602083106112fa57805182526020820191506020810190506020830392506112d7565b6001836020036101000a038019825116818451168082178552505050505050905001915050908152602001604051809103902060030160008282540192505081905550806001856040518082805190602001908083835b602083106113745780518252602082019150602081019050602083039250611351565b6001836020036101000a038019825116818451168082178552505050505050905001915050908152602001604051809103902060040160008282540192505081905550856001856040518082805190602001908083835b602083106113ee57805182526020820191506020810190506020830392506113cb565b6001836020036101000a038019825116818451168082178552505050505050905001915050908152602001604051809103902060000181905550505050505050565b828054600181600116156101000203166002900490600052602060002090601f016020900481019282601f1061147157805160ff191683800117855561149f565b8280016001018555821561149f579182015b8281111561149e578251825591602001919060010190611483565b5b5090506114ac91906114b0565b5090565b6114d291905b808211156114ce5760008160009055506001016114b6565b5090565b9056fea165627a7a72305820de60ac15c284a8f091edf749b88de117ed5bf768d4bb0a0f509d861e5b4dd12e0029'
    // The file ID is located on the transaction receipt
    const fileId = fileReceipt.fileId;
    await (
        await new FileAppendTransaction()
            .setNodeAccountIds([fileTransactionResponse.nodeId])
            .setFileId(fileId)
            .setContents(contractByteCode1)
            .setMaxTransactionFee(new Hbar(5))
            .execute(client)
    ).getReceipt(client);

    const contents = await new FileContentsQuery()
        .setFileId(fileId)
        .execute(client);

    console.log(contents);
    const contractTransactionResponse = await new ContractCreateTransaction()
    // Set gas to create the contract
    .setGas(4700000)
    // The contract bytecode must be set to the file ID containing the contract bytecode
    .setBytecodeFileId(fileId)
    // Set the admin key on the contract in case the contract should be deleted or
    // updated in the future
    .setAdminKey(client.operatorPublicKey)
    .execute(client);

// Fetch the receipt for the transaction that created the contract
const contractReceipt = await contractTransactionResponse.getReceipt(client);

// The conract ID is located on the transaction receipt
const contractId = contractReceipt.contractId;
console.log('contract id is' + contractId);
const contractCallResult = await new ContractCallQuery()
// Set the gas to execute a contract call
.setGas(100000)
// Set which contract
.setContractId(contractId)
// Set the function to call on the contract
.addDonor("a","f",30,40,"a")
.setQueryPayment(new Hbar(2))
.execute(client);

if (contractCallResult.errorMessage != null && contractCallResult.errorMessage != "") {
console.log('error calling contract');
}

}

main();

### Additional context

C:\Program Files\nodejs\node.exe .\index.js
0.0.3498
302e020100300506032b657004220420f1dd384e8fbeb5ccb0009984fb94b4008106ef36a8303e9aa1bbf07bb3b13c1d
302a300506032b6570032100b153e8e8269b81ce8d65c1dac87ec03dfb59d981e4b6bcd898fa4aae368131d8
Buffer(10820) [48, 120, 54, 48, 56, 48, 54, 48, 52, 48, 53, 50, 51, 52, 56, 48, 49, 53, 54, 49, 48, 48, 49, 48, 53, 55, 54, 48, 48, 48, 56, 48, 102, 100, 53, 98, 53, 48, 54, 49, 49, 53, 48, 49, 56, 48, 54, 49, 48, 48, 50, 48, 54, 48, 48, 48, 51, 57, 54, 48, 48, 48, 102, 51, 102, 101, 54, 48, 56, 48, 54, 48, 52, 48, 53, 50, 51, 52, 56, 48, 49, 53, 54, 49, 48, 48, 49, 48, 53, 55, 54, 48, 48, 48, 56, 48, 102, 100, 53, 98, …]
contract id is0.0.29471292
(node:6064) UnhandledPromiseRejectionWarning: TypeError: (intermediate value).setGas(...).setContractId(...).addDonor is not a function
    at main (c:\Users\Vipul\hello-hedera-js\index.js:78:2)
    at processTicksAndRejections (internal/process/task_queues.js:86:5)
(node:6064) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:6064) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

kindly help. 

### Hedera network

testnet

### Version

v2.7.0

### Operating system

Windows

**Comment by jigsnptel** [comment]
got the json file for my contract. my bytecode file size is around 10 kb, but when i use create file transaction, it gives oversized transaction error. so i needed to split up the byte code file. pls can some one help ?

**Comment by SimiHunjan** [comment]
yes you would need to submit a `FileCreateTransaction()` and then a `FileAppendTransaction()` to add your bytecode to one file

**Comment by jigsnptel** [comment]
I got it. thank you for the help and guidance. A lot of help i got from the examples given here

**Comment by SimiHunjan** [comment]
np! Glad it is working!

**Comment by SimiHunjan** [comment]
np! Glad it is working!

**Comment by jigsnptel** [comment]
I got it. thank you for the help and guidance. A lot of help i got from the examples given here
