### ISSUE TITLE
Insufficient Payer Balance received for a lot of tx

### ISSUE THREAD

**Issue by publu** [hashgraph/hedera-sdk-js#89]
Currently smart contract deploy only works when account balance > 200 Hbars else we get “Insufficient Payer Balance”

**Comment by cody-l** [comment]
Are you still experiencing this issue? One possible culprit may be that you are accidentally sending too much gas. When the contract returns the extra gas is refunded, but it may be refusing to start unless there is sufficient balance for the requested gas.

**Comment by publu** [comment]
Would a refund be reflected in the transaction as a debit in hbar?

**Comment by cody-l** [comment]
It won't show up in the transfer list, the transfer list will only show the final amount paid. Under the hood the gas will be withdrawn and then credited back, but this isn't a detail recored in the ledger.

I just tried the contract on your domain lookup site using a wallet containing ~100hbar and it went through. Are you still experiencing the issue?

**Comment by publu** [comment]
The easiest way to replicate the issue is when doing a high-value hbar transaction. We had reports of users with 105 hbar being unable to purchase a domain (where the transaction would be ~102 hbar).

We have encountered similar issues when deploying contracts (this feature hasn't been released to the public yet on Composer) where we need >200hbar to deploy a contract even though the cost components (gascost, tx fee) were definitely lower.

**Comment by mehcode** [comment]
I don't think this is an issue with the SDK or one the SDK can help with. @gregscullard any ideas?

**Comment by mehcode** [comment]
Closing as there isn't something actionable for the SDK here
