### ISSUE TITLE
setMaxQueryPayment not honoring limit when specified for individual query

### ISSUE THREAD

**Issue by ed-marquez** [hashgraph/hedera-sdk-js#894]
### Description

This issue is the reverse of [issue 895](https://github.com/hashgraph/hedera-sdk-js/issues/895), but with setMaxQueryPayment.

**Setting the query payment to 1 tinybar for an individual query is not being honored in the JS SDK** (1tinybar is the smallest value possible):
`ContractCallQuery().setMaxQueryPayment(new Hbar(0.00000001))`

**When the limit is set for the client, the limit is honored.** 
`client.setMaxQueryPayment(new Hbar(0.00000001))`
The error message thrown in this case seems to be backwards and HBAR is not necessary in the text:
`MaxQueryPaymentExceededError: query cost of 1 tℏ HBAR exceeds max set on client: 0.00328579`
In the message, the cost is 0.00328579 and the max set on client is 1 tℏ. So, should they be reversed?

The limit should be honored in both cases.

### Steps to reproduce

1. Go to [this code Sandbox](https://codesandbox.io/s/hedera-example-contract-getter-setter-8whrs?file=/index.js) and enter your testnet credentials in .env (or download the .js, .sol, and .bin files if you wanna try locally) 
2. See line 63
3. Run index.js - notice that the limit is not honored. Can try also adding the query fee limit in line 92

4. then try adding the query limit to the client (line 21), run index.js
5. See error `MaxQueryPaymentExceededError: query cost of 1 tℏ HBAR exceeds max set on client: 0.00328579`

### Additional context

See repro steps

### Hedera network

testnet

### Version

v2.7.1

### Operating system

Windows

**Comment by danielakhterov** [comment]
Just want to note it here, this is a valid bug.

**Comment by danielakhterov** [comment]
Fixed: https://github.com/hashgraph/hedera-sdk-js/commit/9c8d19f08cfd8afeb2695633fbfea19df9508785
