### ISSUE TITLE
Hedera SDK for JS - HCS support

### ISSUE THREAD

**Issue by atul-hedera** [hashgraph/hedera-sdk-js#92]
Support HCS for Javascript SDK

**Comment by mehcode** [comment]
This isn't possible as currently defined. gRPC streaming doesn't work over gRPC-web.

**Comment by abonander** [comment]
We could support it on NodeJS as-is but would need a custom streaming protocol, probably built on Websockets, for web-based clients.

**Comment by mehcode** [comment]
This is done on the `hcs` branch.

```
yarn add @hashgraph/sdk#hcs
```
