### ISSUE TITLE
Creating Client.forNetwork with "undefined" value throws transaction must be frozen error

### ISSUE THREAD

**Issue by gregscullard** [hashgraph/hedera-sdk-js#933]
### Description

Created a Client with an undefined network (Client.forNetwork), when trying to execute a transaction, the SDK threw the following error which is misleading.

```
Error: transaction must have been frozen before calculating the hash will be stable, try calling `freeze`
```

Trying to freeze the transaction has no effect.

### Steps to reproduce

```
    client = Client.forNetwork(process.env.NETWORK1); // NETWORK1 has no value in .env
    const fileTransactionResponse = await new FileCreateTransaction()
        .setKeys([client.operatorPublicKey])
        .setContents(tokenJson.bytecode)
        .execute(client);
```

throws the error in the description

### Hedera network

mainnet, testnet, previewnet, other

### Version

v2.8.0

**Comment by danielakhterov** [comment]
I'm closing this as I don't think this is the responsibly of the JS SDK to check the parameters manually when the type signature requires an non-null object to be provided.
