### ISSUE TITLE
Record of TokenCreateTransaction shows total supply for the token as 0 - should show the initial supply, which is the correct total

### ISSUE THREAD

**Issue by ed-marquez** [hashgraph/hedera-sdk-js#937]
### Description

Record of TokenCreateTransaction shows total supply for the token as 0, which is incorrect. 
This record should show the initial supply, which is the correct total supply for a newly created token. 

### Steps to reproduce

1. see and run the main function in the _Additional Context_
2. Inspect the variables **supply** and **tokenCreateRec**
3. Notice **tokenCreateRec.receipt.totalSupply** shows as 0

### Additional context

async function main() {
	const tokenCreateTx = new TokenCreateTransaction()
		.setTokenName("dAppDayToken")
		.setTokenSymbol("DDT")
		.setTreasuryAccountId(operatorId)
		.setInitialSupply(100)
		.setDecimals(0)
		.setSupplyKey(operatorKey)
		.freezeWith(client);
	const tokenCreateSign = await tokenCreateTx.sign(operatorKey);
	const tokenCreateSubmit = await tokenCreateSign.execute(client);
	const tokenCreateRec = await tokenCreateSubmit.getRecord(client);
	const id = tokenCreateRec.receipt.tokenId;
	const supply = tokenCreateRec.receipt.totalSupply;
	console.log(`Created token with ID: ${id}`);
	console.log(`Supply: ${supply}`);
}

### Hedera network

testnet

### Version

v2.7.1

### Operating system

Windows

**Comment by danielakhterov** [comment]
I could be wrong, but I think the `TransactionReceipt.totalSupply` is only set for `Token[Min|Burn]Transaction`'s when the total supply changes. I did confirm that the SDK *decodes* the protobufs correctly for `TransactionReceipt` 30c3b74e3e5d9b47d9eb2e0a5f007b280cdf9a81 

Note: The commit provided did fix our *encoding* though; your example only uses *decoding*.
