### ISSUE TITLE
TLS issue with mirror node

### ISSUE THREAD

**Issue by steven-sheehy** [hashgraph/hedera-sdk-js#938]
### Description

See https://github.com/hashgraph/hedera-sdk-java/issues/855

### Steps to reproduce

See https://github.com/hashgraph/hedera-sdk-java/issues/855

### Hedera network

mainnet

### Version

latest

**Comment by danielakhterov** [comment]
Fixed: 98a95d64217894b5677e4333fc469974b2880587
