### ISSUE TITLE
HIP-336: Protobuf changes for Approve/Allowance

### ISSUE THREAD

**Issue by SimiHunjan** [hashgraph/hedera-sdk-js#961]
### Problem

Protobuf changes: https://github.com/hashgraph/hedera-protobufs/pull/160

### Solution

Add support

**Comment by danielakhterov** [comment]
Fixed on `develop` https://github.com/hashgraph/hedera-sdk-js/commit/e0e0071969ac46100486dd8fb2f938ae55a53730
