### ISSUE TITLE
ExchangeRate returns incorrect expirationTime

### ISSUE THREAD

**Issue by gregscullard** [hashgraph/hedera-sdk-js#966]
### Description

The `expirationTime` of the `exchangeRate` in a receipt is incorrect.

For example, the expiration time returned from a receipt is
`{
  "low": 1645714800,
  "high": 0,
  "unsigned": false
}`

which should resolve to `Thu Feb 24 2022 15:00:00`

is in fact `1970-01-20T01:08:34.800Z` in the receipt

### Steps to reproduce

Run a transaction, get a receipt, print the `receipt.exchangeRate.expirationTime`

### Hedera network

other

### Version

v2.9.1

**Comment by danielakhterov** [comment]
Fixed: here: https://github.com/hashgraph/hedera-sdk-js/commit/257b21e6590ffceb784378dd59b7adc238c9ff3d
