### ISSUE TITLE
Mark expo as an optional peer dependency

### ISSUE THREAD

**Issue by mehcode** [hashgraph/hedera-sdk-js#969]
https://docs.npmjs.com/cli/v7/configuring-npm/package-json#peerdependenciesmeta

---

This is only required in react native. The error in web is a bit distracting. 

```
 WARN  Issues with peer dependencies found
.
└─┬ @hashgraph/cryptography
  ├── ✕ missing peer expo@^44.0.5
  ├─┬ expo-crypto
  │ └── ✕ missing peer expo@"*"
  └─┬ expo-random
    └── ✕ missing peer expo@"*"
Peer dependencies that should be installed:
  expo@">=44.0.5 <45.0.0"
```

See https://github.com/hashgraph/hedera-sdk-js/blob/main/packages/cryptography/package.json#L85

**Comment by danielakhterov** [comment]
I believe this was fixed in #1010
