### ISSUE TITLE
Review default transaction fees for each Transaction and compare with the equivalent in the Java SDK 

### ISSUE THREAD

**Issue by mehcode** [hashgraph/hedera-sdk-js#970]
We're getting reports of the default fees not being high enough. 

Compare (for example)

- https://github.com/hashgraph/hedera-sdk-js/blob/fd24d5a6b5b2b5465fd3c3315ce4961a19524f0e/src/token/TokenAssociateTransaction.js#L49
- https://github.com/hashgraph/hedera-sdk-java/blob/main/sdk/src/main/java/com/hedera/hashgraph/sdk/TokenAssociateTransaction.java#L23

**Comment by danielakhterov** [comment]
I actually did this before the last release, but forgot to close. `develop` should be up to date with the same fees as Java.
