### ISSUE TITLE
Child transactions in scheduled transactions are failing in 2.9.1

### ISSUE THREAD

**Issue by ed-marquez** [hashgraph/hedera-sdk-js#974]
### Description

A user reported seeing strange behavior with scheduled transactions. We jumped on a call and during troubleshooting found that scheduled transactions (token and HBAR transfers) were not going through in v2.9.1 of the JS SDK. We tried this version with two separate examples and both failed. 

When we reverted to using v2.7.1, the scheduled transactions went through as expected. See repro steps for more details.

### Steps to reproduce

1. Copy and run this code from GitHub: https://github.com/ed-marquez/hedera-sdk-js/blob/main/examples/hts-nftP2-kyc-upate-schedule.js
2.  See lines 228-269 (Notice that the ScheduleInfoQuery even says that the schedule executed, but the child tx still didn't go through and no error is reported)
3. Run in v2.9.1 and v2.7.1 and notice that the transfer of NFT with serial 2 does not go through in 2.9.1 (see screenshots for console output confirmations
![v2 7 1](https://user-images.githubusercontent.com/72571340/156028740-e6c960fc-02b0-483a-99c5-49788df5f3e0.png)
![v2 9 1](https://user-images.githubusercontent.com/72571340/156028743-5b6c875a-74d7-46d6-b699-3343b579682f.png)
)

### Hedera network

testnet

### Version

v2.9.1

### Operating system

Windows

**Comment by hhe44** [comment]
Just wanted to corroborate with this - scheduled transactions seem to fail in v2.9.1 of the js-sdk. I had a difficult time tracking down the TX that gets fired off within the scheduled transaction, but I repeatedly found this INSUFFICIENT_TX_FEE error for a CRYPTOTRANSFER (the tx set inside the scheduled transaction)

It can be found here:
https://testnet.mirrornode.hedera.com/api/v1/transactions?account.id=0.0.12717560

Should be the transaction with consensus timestamp: 1646066846.427760590

I wasn't able to prevent those errors despite having HBARs in my test accounts, but if someone can offer more insight - I'd appreciate it.

**Comment by teacoat** [comment]
Could be related to https://github.com/hashgraph/hedera-sdk-js/issues/957

Notably one person brought up "It seems now one needs to set maximum fee for any transaction manually", haven't had a chance to test it myself but worth trying if you have a test rigged up already.

**Comment by danielakhterov** [comment]
As mentioned in #957 this might be solved in the latest beta release v2.11.0-beta.1. Ran our e2e tests suite which does not set max transaction fees, and 99% passed.

**Comment by danielakhterov** [comment]
I believe https://github.com/hashgraph/hedera-sdk-js/issues/957 supersedes this issue as it went into further detail, but it too has now been closed so this should also be marked closed.
