### ISSUE TITLE
Verify signature using key from `AccountInfoQuery`

### ISSUE THREAD

**Issue by SimiHunjan** [hashgraph/hedera-sdk-js#976]
### Problem

Title

- [ ]  Design
- [ ]  Implement

### Solution

Perhaps a Flow? Similar to https://github.com/hashgraph/hedera-sdk-java/issues/839 but for verification?

**Comment by danielakhterov** [comment]
Implemented here: https://github.com/hashgraph/hedera-sdk-js/commit/2a1dc942aa3e44f0f71181699c2b701db4a747c9
