### ISSUE TITLE
Signature provider updates

### ISSUE THREAD

**Issue by SimiHunjan** [hashgraph/hedera-sdk-js#985]
### Problem

- [x] Add signer example
- [ ] Update the .env file to include all parameters the wallet looks for

### Solution

See above

**Comment by danielakhterov** [comment]
We now have a signing example here: https://github.com/hashgraph/hedera-sdk-js/blob/develop/examples/local-wallet-sign-transaction.js Still need to update the env though.

**Comment by danielakhterov** [comment]
Updated env here: https://github.com/hashgraph/hedera-sdk-js/commit/cc881c4165f28a2377adeb30c7ffdda8cc8d297e
