### ISSUE TITLE
Issue with smart contract payableAmount/amount during to/from bytes

### ISSUE THREAD

**Issue by teacoat** [hashgraph/hedera-sdk-js#986]
### Description

Encountering some strange behaviour regarding the amount/payableAmount of a ContractExecute.

### Steps to reproduce

1. Follow the "[how to deploy smart contracts](https://hedera.com/blog/how-to-deploy-smart-contracts-on-hedera-part-1-a-simple-getter-and-setter-contract)" tutorial
2. Add a payable amount to the code in the tutorial:
![image](https://user-images.githubusercontent.com/3913019/157145086-987592c6-db32-419b-96c7-3e679dd28185.png)
3. Do toBytes() on it, and then do fromBytes()
4. you can see the difference here:
![image](https://user-images.githubusercontent.com/3913019/157145580-92caf248-65bb-4d5d-9ee2-b7ebb87bc240.png)

### Hedera network

testnet

### Version

2.7.1

**Comment by danielakhterov** [comment]
I believe this is now fixed: https://github.com/hashgraph/hedera-sdk-js/commit/4316bf9593510b88f06037e34cb0d27fd1deda0d
