### ISSUE TITLE
Transaction.executeWithSigner(LocalWallet) appears to be broken

### ISSUE THREAD

**Issue by 3Nigma** [hashgraph/hedera-sdk-js#987]
### Description

Created a new transaction and tried to send it through a `LocalWallet` via the `transaction.executeWithSigner(signer)` method call when.

Expected to execute successfully.

Actual result: 

Errored out with "`transactionId` must be set or `client` must be provided with `freezeWith`" message.

### Steps to reproduce

1. Create any type of `Transaction` (eg. `FileCreateTransaction`)
2. Obtain an instance of `LocalWallet`
3. call `transaction.executeWithSigner(wallet)`

### Additional context

At first glance, it looked like a missed operator setting in the [`Transaction.freezeWith` method](https://github.com/hashgraph/hedera-sdk-js/blob/a25a18577f8705b78102550b26af592283b76357/src/transaction/Transaction.js#L723) but updating that to 
```
this._operator = this._operator != null ? this._operator : 
    client != null ? client._operator : null;
```
now generates a `INVALID_SIGNATURE` response.

Freezing the transaction with `transaction.freezeWithSigner(signer)` method also does not seem to work. It errors out with "transaction must have been frozen before calculating the hash will be stable, try calling `freeze`", so I'm not sure what's happening there.

### Hedera network

testnet

### Version

2.11.0-beta.1

### Operating system

Linux

**Comment by 3Nigma** [comment]
Come to think of it, it might be that all `Transaction.executeWithSigner(Signer)` calls are affected by this.

**Comment by danielakhterov** [comment]
I believe you need to call `.freezeWithExecute()` first. I'm not sure it 'executeWithSigner()` should implicitly call `.freezeWithSigner()` since if this would go across the wire it would result in two calls instead of one.

**Comment by 3Nigma** [comment]
I'm not sure I follow. Could you, perhaps, give me a working example of how this might work?

**Comment by 3Nigma** [comment]
> I'm not sure I follow. Could you, perhaps, give me a working example of how this might work?

Nevermind. We [found this](https://github.com/hashgraph/hedera-sdk-js/blob/develop/examples/local-wallet-sign-transaction.js) and are looking into it.

**Comment by danielakhterov** [comment]
Closing as I think the above comment indicates this is resolved? Let me know if I've mistaken.

**Comment by DADADAVE80** [comment]
I just encountered this error trying to send HBAR on Hashpack
