### ISSUE TITLE
SubscriptionHandle not exposed via default export

### ISSUE THREAD

**Issue by KilianB** [hashgraph/hedera-sdk-js#989]
### Description

The `SubscriptionHandle` is not present in the `export.d.ts` file and thus it's type can not be imported.

### Steps to reproduce

Try to import SubscriptionHandle.  

````ts
import { SubscriptionHandle } from '@hashgraph/sdk';
````

> Module '"@hashgraph/sdk"' has no exported member 'SubscriptionHandle'.ts(2305)

### Hedera network

other

### Version

2.10.1

**Comment by danielakhterov** [comment]
Heh, kind of funny we haven't caught this for so long. Will fix asap.

**Comment by danielakhterov** [comment]
Fixed on `main`
