### ISSUE TITLE
Reorder TopicMessageQuery.subscribe method signature

### ISSUE THREAD

**Issue by KilianB** [hashgraph/hedera-sdk-js#990]
### Problem

````ts
const errorHandler = null;
const messageHandler = (message: TopicMessage) => {} 
new TopicMessageQuery(configObj).subscribe(client, errorHandler, messageHandler)
````

The `subscribe` method requires an error handler which at this time might already be supplied via the constructor or dedicated setter methods. 
In this case null has to explicitly be passed to the function. 

### Solution

Switch the position of the error and message handler and make the error handler optional.  This is a breaking change!

**Comment by danielakhterov** [comment]
As you said in the solution, it's a breaking change and it's not something we can do :( Especially since this API has been stable for _awhile_. If we were to do a v3 SDK then we'd definitely fix this.
