### ISSUE TITLE
TokenCreateTransaction.executeWithSigner(LocalWallet) throws INVALID_EXPIRATION_TIME

### ISSUE THREAD

**Issue by 3Nigma** [hashgraph/hedera-sdk-js#991]
### Description

Am not able to execute a `TokenCreateTransaction` via the `LocalWallet`.

Consistently getting
```
PrecheckStatusError: transaction 0.0.2908307@1647202410.942311042 failed precheck with status INVALID_EXPIRATION_TIME
```
exceptions.

> Note: We came across this issue while running [one of our Strato tests](https://github.com/buidler-labs/hedera-strato-js/blob/c8cb90d33d4df914e263bd05936006c45947a485/test/general/specs/LiveToken.spec.ts#L31) against the `develop`'s ([commit](https://github.com/hashgraph/hedera-sdk-js/commit/4316bf9593510b88f06037e34cb0d27fd1deda0d)) `LocalWallet` implementation.

### Steps to reproduce

Run a modified [`examples/local-wallet-sign-transaction.js` code](https://github.com/hashgraph/hedera-sdk-js/blob/4316bf9593510b88f06037e34cb0d27fd1deda0d/examples/local-wallet-sign-transaction.js) to use a `TokenCreateTransaction` instead:
```js
import { LocalWallet, TokenCreateTransaction } from "@hashgraph/sdk";

import dotenv from "dotenv";

dotenv.config();

async function main() {
    const wallet = new LocalWallet();

    let transaction = await new TokenCreateTransaction()
        .setTokenName("ffff")
        .setTokenSymbol("F")
        .setDecimals(3)
        .setInitialSupply(100)
        .setTreasuryAccountId(wallet.accountId)
        .setAdminKey(wallet.publicKey)
        .setFreezeKey(wallet.publicKey)
        .setWipeKey(wallet.publicKey)
        .setKycKey(wallet.publicKey)
        .setSupplyKey(wallet.publicKey)
        .setFreezeDefault(false)
        .freezeWithSigner(wallet);

    transaction = await transaction.signWithSigner(wallet);
    const response = await transaction.executeWithSigner(wallet);
    const receipt = await wallet.getProvider().waitForReceipt(response);

    console.log(`status: ${receipt.status.toString()}`);
}

void main();
```
via `node examples/local-wallet-sign-transaction.js` (with `.env` properly set)

### Additional context

Full thrown Error:
```
file:///home/vic/projects/js/hedera-sdk-js/src/PrecheckStatusError.js:15
        super(
        ^

PrecheckStatusError: transaction 0.0.2908307@1647202410.942311042 failed precheck with status INVALID_EXPIRATION_TIME
    at new PrecheckStatusError (file:///home/vic/projects/js/hedera-sdk-js/src/PrecheckStatusError.js:15:9)
    at TokenCreateTransaction._mapStatusError (file:///home/vic/projects/js/hedera-sdk-js/src/transaction/Transaction.js:1102:16)
    at TokenCreateTransaction.execute (file:///home/vic/projects/js/hedera-sdk-js/src/Executable.js:454:32)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async main (file:///home/vic/projects/js/hedera-sdk-js/examples/local-wallet-sign-transaction.js:25:22) {
  status: Status { _code: 45 },
  transactionId: TransactionId {
    accountId: AccountId {
      shard: Long { low: 0, high: 0, unsigned: false },
      realm: Long { low: 0, high: 0, unsigned: false },
      num: Long { low: 2908307, high: 0, unsigned: false },
      aliasKey: null,
      _checksum: null
    },
    validStart: Timestamp {
      seconds: Long { low: 1647202410, high: 0, unsigned: false },
      nanos: Long { low: 942311042, high: 0, unsigned: false }
    },
    scheduled: false,
    nonce: null
  }
}

Node.js v17.7.1
```

### Hedera network

previewnet

### Version

develop

### Operating system

Linux

**Comment by 3Nigma** [comment]
I want to add that [the original `examples/local-wallet-sign-transaction.js`](https://github.com/hashgraph/hedera-sdk-js/blob/4316bf9593510b88f06037e34cb0d27fd1deda0d/examples/local-wallet-sign-transaction.js) runs just fine.

**Comment by danielakhterov** [comment]
I found the issue, but I'm not sure if it's a bug or not. The issue is https://github.dev/hashgraph/hedera-sdk-js/blob/bfa87bf1b5f771cafd3fdf13f5c34a27841136e7/src/token/TokenCreateTransaction.js#L778 `TokenCreateTransaction` along with a few other transactions overwrite `freezeWith` to do extra work. We _can_ duplicate this code into https://github.dev/hashgraph/hedera-sdk-js/blob/bfa87bf1b5f771cafd3fdf13f5c34a27841136e7/src/Wallet.js#L228 but I don't like this idea. The only way we'd be able to get around this is if `client` were stored within `Wallet` or `Provider`, but that too is not reasonable because it eliminates the whole point of signature providers. For `TokenCreateTransaction` the way way around this is to simply set the auto renew account ID manually, but for `FileAppendTransaction` and `TopicMessageSubmitTransaction` I'm kind of stumped.

**Comment by danielakhterov** [comment]
Removing milestone from this issue as I think we need to first determine if it's a bug or not.

**Comment by danielakhterov** [comment]
After some thought, the `_freezeWithAccountId(accountId)` sounds like it should work well.
